### ISSUE TITLE
ensime-company too much of a lone wolf?

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1001]
I've been reading up on `company-mode` and it's pretty impressive how many backends there are.

I noticed that we reset the `company-mode-backends` to use just `ensime-company` to the exclusion of all other backends. But it would be really nice to be able to build on top of the existing hooks and add others.

I tried this:

```elisp
(set (make-local-variable 'company-backends) '(ensime-company company-dabbrev))
```

but it seems that the dabbrevs never come through. @aemoncannon are we doing something funky that stops other backends from working?

**Comment by fommil** [comment]
Ignore me! I was missing some parenthesis

```elisp
(set (make-local-variable 'company-backends) '(ensime-company company-dabbrev))
```

all the same, maybe we should add to the list instead of replacing it? Or are we assuming users can do that if they know about company-mode already?

**Comment by aemoncannon** [comment]
There was an issue, I recall, with the default list. It included emacs cap
function, which called our backend - so we ended up double calling in some
situations. Could be worked around I'm sure

**Comment by fommil** [comment]
I've been chatting on `#emacs` irc and it turns out that the way we're doing it is the right way. If you want to customise the backends for a mode, you should create a local variable (like above) because the standard logic is to go through the list of backends and ask (with the `prefix`) "are you responsible for completing this?". When one returns `t` it is used to the exclusion of the others. Groups can be used to aggregate results (like I'm doing above) but this is very much left to the user's preference.

It's weird because one would think that company-mode would keep going through the list if the "responsible" backend didn't return any results... but that's not the way it works.

**Comment by fommil** [comment]
Actually, there is one small thing to do here... so reopening.

Perhaps the `ensime-company` hook should return `nil` when given any prefix when the server is not up? Then we could add the defaults as the cdr of the list and fall through to them when using basic `scala-mode`.

**Comment by fommil** [comment]
ok, I'm clearly mad as a box of frogs... it seems that ensime-company does report `nil` if the server is not up.

**Comment by fommil** [comment]
my config was all messed up, `ensime-company` **does** try to hog the backends. Should be easy to fix.

**Comment by fommil** [comment]
ouch! I just accidentally pushed to upstream.

**Comment by fommil** [comment]
btw, with this patch it means that running

```elisp
            (set (make-local-variable 'company-backends)
                 '(ensime-company (company-keywords company-etags)))
```

after loading `(ensime-mode)` will mean that if the server is not available, `company-mode` will fall back to tags.
