### ISSUE TITLE
Provide a 2.10 build

### ISSUE THREAD

**Issue by huitseeker** [ensime/ensime-server#1002]
The project/Ensime.scala build file only provides a 2.11 build, it would be nice to have a 2.10 option.

**Comment by fommil** [comment]
we have a separate branch for 2.10

**Comment by fommil** [comment]
it's quite old though. Syncing 2.10 to master isn't that hard... but syncing 2.9 is a real PITA.

We've got a big refactor coming soon, so no point rebasing until after that.

**Comment by fommil** [comment]
wow, it really was ages ago... it was before we modularised. https://oss.sonatype.org/content/repositories/snapshots/org/ensime/ensime_2.10/0.9.10-SNAPSHOT/
