### ISSUE TITLE
FLX and CamelCase Completion

### ISSUE THREAD

**Issue by ChuckIrvine** [ensime/ensime-server#1003]
Hello. Ensime is looking pretty good. Thanks! Editing Java in Eclipse, I'm used to having camel case completion. I'm sure you know what I mean.... Is there a way to set that for use with Ensime?

**Comment by fommil** [comment]
That might actually be a feature request for company-mode which is the backend we're using. Although, it might need some work server side. We actually index camel cases and it should work in search.

Do you mean for classes or methods?

**Comment by ChuckIrvine** [comment]
Hi Sam, thanks for the reply. I haven't thought about it deeply enough. Classes, variables and methods at least I would think.

**Comment by fommil** [comment]
ok, they all use different mechanisms. Classes might be the easiest to start with. If you're interested in working on this, I could give you some pointers. We're all busy trying to work toward the 1.0 roadmap.

**Comment by fommil** [comment]
this needs some thought as to whether it is client side or server side supported. If we send the whole list of completions back from the server, then it is clearly a client side thing. If we're filtering and prioritising server side, then we definitely need to support flx matching there. It would be a useful feature to have in general as I'm sure search could reuse the flx code.

**Comment by slothspot** [comment]
@fommil any progress on this? If not, I would like to start hacking on this and would appreciate any input on where to start.

**Comment by fommil** [comment]
great! @slothspot it's probably best that you read and understand all the code/tests under the core module, in the "indexer" package. Good luck. SearchService is a bit messy, but you shouldn't need to get too deeply involved. I'm not sure how to implement flx with lucene, so you might want to do some investigation there.

**Comment by slothspot** [comment]
@fommil As I understand, entry point for me is searchClasses/searchClassesMethonds methods pair in SearchService, am I right? And I can't find any tests related to SearchService/IndexService. Are there any?

**Comment by slothspot** [comment]
@fommil have found SearchService tests in integration folder. And looks like that is answers my questions.

**Comment by slothspot** [comment]
Looks like that lucene itself works for CamelCase:
```scala
  it should "return results from J2SE (flx)" in withSearchService { implicit service =>
    searchesClasses("java.lang.StringIndexOutOfBoundsException", "StringInd",
        "SIO", "SI", "sio", "si")
  }
```
passes (with max = 100 in searchesClasses).

In the case of "StrIn" which I transform into "Str*In" I can't make WildcardQuery query work.
Another thing: I don't understand where completion options are filtered somehow. (I've seen scoring in CompletionControl).

So at this moment I have following plan:
0. Extend SearchServiceSpec with wild cards and CamelCase related tests
1. Make WildcardQuery work
2. Extend RichPresentationCompilerSpec with FLX and CamelCase related tests
3. Make these tests pass

**Comment by fommil** [comment]
That sounds like a good plan! Yes camelcase has specific support in our codebase. It's actually indexed, so it's super fast. I wouldn't be against holding things in memory to make flx work. In fact, having a fully in-memory lucene is something we've discussed.

**Comment by hzenginx** [comment]
Hello, This the feature I am missing most, is there any progress on this?
For Indexed methods and classes the solution should be easy as discussed above; also I know presentation compiler has this support too.

If there is no progress yet I can start hacking.

**Comment by fommil** [comment]
@hzenginx that'd be great! `ensime-search` only uses the indexer, not the PC. Completions use the PC and the client gets to apply FLX to the full set of valid completions... I think `company-mode` in emacs does that already (if it doesn't then support for that could be added there).

**Comment by fommil** [comment]
btw, there are some related tickets on improving search such as https://github.com/ensime/ensime-emacs/issues/186 and #1482 and #472 

Before doing any hacking on the indexer, I strongly recommend watching the latest video from scalasphere linked from the contributing page.

**Comment by hzenginx** [comment]
@fommil already watched, great talk BTW.

Because ensime is already indexing class and method names I think a simple wildcard query is enough, see: https://github.com/ensime/ensime-server/compare/2.0...hzenginx:2.0
It is passing the tests and working for me on emacs.

Looks like in `Completions` we are filtering some completions which brakes the support for partial CamelCase search for but I am not sure and investigate after work.

**Comment by fommil** [comment]
ok cool. I had a quick look, and I see you're adding a new `WildCardQuery`, nice. This is new to me, I'll need to read the lucene docs on it.

When I originally wrote the lucene support I'd come off a project that needed super-optimised lucene queries (it was for investment traders to find specialist products from a huge database) and I did as much index-side as possible... but I think ensime probably doesn't need to do it that way --- so adding richer query side support like you've done is probably the right way to go.

**Comment by fommil** [comment]
in fact, I wonder if perhaps we should just remove all our custom indexes and just use this. I still wonder if we even need Lucene.

**Comment by hzenginx** [comment]
`WildCardQuery`s are not fast as others of course but I don't think it will be a problem with the size of data ensime dealing with. They can become really slow when they start with a `*` so thats why my implementation is not adding one. 
see: https://lucene.apache.org/core/6_3_0/core/org/apache/lucene/search/WildcardQuery.html#WildcardQuery-org.apache.lucene.index.Term-int-

**Comment by hzenginx** [comment]
hi again @fommil, as I've guessed ensime were filtering output from PC with a prefix check, I added some tests and tweaked the filtering to accept camel case prefixes.
Can you check https://github.com/ensime/ensime-server/compare/2.0...hzenginx:2.0 again, I will open a PR if looks OK to you

**Comment by fommil** [comment]
Go for it!
