### ISSUE TITLE
Create a major-mode for all read-only ensime buffer.

### ISSUE THREAD

**Issue by reactormonk** [ensime/ensime-server#1005]
The major mode is so evil can pick it up and `(add-to-list 'evil-emacs-state-modes 'ensime-display-mode)` works.

**Comment by fommil** [comment]
is there anything else we can do to help out with evil mode? Like name buffers in a certain way or anything, or register with evil (if its loaded) when loading up the buffer?

**Comment by reactormonk** [comment]
A hook to execute `(evil-emacs-state)`.

**Comment by fommil** [comment]
Aah, so giving you some hooks would help. OK that sounds easier.

**Comment by fommil** [comment]
This issue was moved to ensime/ensime-emacs#151
