### ISSUE TITLE
ensime-sbt: 0.1.6 or 0.1.7?

### ISSUE THREAD

**Issue by gaydenko** [ensime/ensime-server#1007]
Hi! 

Documentation says about `0.1.6` while there is `0.1.7` tag already. Which to use?

**Comment by fommil** [comment]
0.1.7 and send a PR to update the docs.

**Comment by gaydenko** [comment]
I see, thanks.
Sorry, my brain isn't sufficiently power to understand PR necessity to change a single char :)

**Comment by fommil** [comment]
Just click edit on the page, thanks!

**Comment by gaydenko** [comment]
Clicked.

**Comment by fommil** [comment]
thanks!
