### ISSUE TITLE
DocURIAtPoint not working in Emacs

### ISSUE THREAD

**Issue by rorygraves** [ensime/ensime-server#1010]
@tbje @reactormonk reported

  ```
Synchronous RPC Aborted: Malformed swank:doc-uri-at-point call: (swank:doc-uri-at-point "/home/tbje/scalatrain/src/main/scala/misc/Queue.scala" 350)
```

I think this is due to one of the protocol refactors - OffsetRange used to accept

```(1 10)``` and ```10``` - I suspect that the parser now only accepts the first form (which emacs is not generating for a single point.  @fommil Was this lost in one of your refactors?

We either need to fix emacs to only send the range form or fix the server to accept the point form.

**Comment by fommil** [comment]
This is working for me. Are you definitely running latest client and server?

**Comment by tbje** [comment]
https://github.com/ensime/ensime-emacs/blob/master/ensime-client.el#L880-L882

(defun ensime-rpc-doc-uri-at-point (file point)
  (ensime-eval
   `(swank:doc-uri-at-point ,file (,point ,point))))

seems to work better.

**Comment by fommil** [comment]
This is supposed to work on the server (for SWANK, not for JERK)

https://github.com/ensime/ensime-server/blob/master/swank/src/main/scala/org/ensime/server/protocol/swank/SwankFormats.scala#L541

this is a test case that passes for me (put it in `SwankFormatSpec`)

```scala
    unmarshal(
      s"""(swank:doc-uri-at-point $file1_str 1))""",
      DocUriAtPointReq(file1, OffsetRange(1, 1)): RpcRequest
    )
```

Are you **sure** you're running against master?

**Comment by tbje** [comment]
Caused by dirty build. OK to close.
