### ISSUE TITLE
Errors displayed after adding dependencies to build.sbt

### ISSUE THREAD

**Issue by ale64bit** [ensime/ensime-server#1014]
I have a very simple project, which was working nicely with ensime. Then I added the following dependency to my `build.sbt`:
```
"org.scalatest" %% "scalatest" % "2.2.4" % "test",
```
And any class of this dependency is not recognized and reported as error. For example:
```
ERROR: object scalatest is not a member of package org : line 2
ERROR: not found: type WordSpecLike : line 4
```
Is there anything to do about this? Or I'm missing something?

**Comment by fommil** [comment]
you need to rebuild your `.ensime` file.

**Comment by ale64bit** [comment]
Thanks! is there any way to automate this? Let say, triggering the rebuild with some hotkey from inside emacs?

**Comment by fommil** [comment]
`C-h v ensime-auto-generate-config`

`M-x apropos RET ensime` to see everything like this.
