### ISSUE TITLE
Server seems to not reply to some requests

### ISSUE THREAD

**Issue by edani** [ensime/ensime-server#1015]
Possible regression from the Akka refactor.  The symptom is that the counter of pending messages in the Emacs modeline increases without bound. This seems to happen when I edit the buffer, so it's likely that one of the async calls triggered by keystrokes (typecheck, semantic highlight) isn't being acknowledged.

**Comment by fommil** [comment]
might be the init message? But we respond with an error. Hmm.

Should be relatively easy now in the server logs to relate requests to responses.

**Comment by edani** [comment]
The problem is that emacs sends two `SymbolDesignationReq`s in short succession (to make the visible part of the buffer update sooner). Only the first one is handled, the second one seems to be dropped.

**Comment by edani** [comment]
Fixed in #1061
