### ISSUE TITLE
Asynchronous RPC Aborted: Invalid rpc request after fresh project generation

### ISSUE THREAD

**Issue by ale64bit** [ensime/ensime-server#1017]
I get this error repeatedly after fresh generating with `gen-ensime`:
```
Asynchronous RPC Aborted: Invalid rpc request (swank:symbol-designations "/home/alex/myproject/src/main/scala/MyTestCode.scala" 0 11293 (var val varField valField functionCall implicitConversion implicitParams operator param class trait object package))
```
What does it means? And how to get rid of it?

**Comment by fommil** [comment]
You've not said, but I'm guessing this is a Scala 2.10 project? In which case, this is a know regression with the latest emacs client update. Follow https://github.com/ensime/ensime-emacs/pull/142 for the fix (merging very soon).

**Comment by ale64bit** [comment]
Actually, the Scala version is 2.11.5.

**Comment by fommil** [comment]
then your client/server versions are old, update everything. Open this ticket if it still happens.

**Comment by fommil** [comment]
also, looks like you're running a dev version of the client. Implicit conversions were only merged a few minutes ago.

**Comment by ale64bit** [comment]
Sorry: "update everything" means `ensime-update`?

**Comment by fommil** [comment]
no, it means update everything :wink: update ensime from MELPA and run `ensime-update` if the problem persists. A new version is disting to MELPA now so you might need to do this again in an hour.

Are you sure you're not using a local build of the client or server? Because that request is a dead giveaway.

**Comment by ale64bit** [comment]
Well, honestly I started using ensime+emacs a few days ago so I'm a bit lost. I just installed emacs and then used the instructions [here](https://github.com/ensime/ensime-server/wiki/Quick-Start-Guide).

How to know what client and/or server I'm using?

**Comment by edani** [comment]
@ale64bit  The quickstart guide really has two sets of instructions  1) how to install from repositories   2) How to install from source.   Do you think the guide needs to be clearer about which is which?

**Comment by ale64bit** [comment]
@edani I think the guide is very clear. Nonetheless, having a "smoother" workflow for installing and updating ensime and related components would please many not-so-terminal-oriented people :)
Btw, is there any place for contributions? I'm looking for an interesting project to work on.

**Comment by fommil** [comment]
You shouldn't need to install anything at all other than use MELPA to add the ensime emacs plugin. Of course, if you're new to emacs or something, that might be confusing. The server bootstarps itself, all you need is `sbt` installed.

Lots of room for contributions! :smile: Server or Emacs side, both... I recommend looking through the ticket tracker with an emphasis on anything tagged "low hanging fruit" or Milestone 1.0.
