### ISSUE TITLE
No declPos of symbolic methods

### ISSUE THREAD

**Issue by hedefalk** [ensime/ensime-server#1020]
_From @hedefalk on June 15, 2015 7:58_

This is due to the fact that there is no :pos in the answer from Ensime.

I guess I'm doing it wrong. I also think there is an issue that I'm asking the wrong thing. For instance:

```
def foo = 2
val bar = foo
```

Clicking on the call to foo will jump to scala.Int which is obviously wrong. I jump to the type of the expression and not to it's definition.

_Copied from original issue: ensime/ensime-atom#17_

**Comment by hedefalk** [comment]
_From @fommil on June 15, 2015 13:10_

there are a couple of outstanding problem with jump-to-source. https://github.com/ensime/ensime-server/issues/835 https://github.com/ensime/ensime-server/issues/775

Create tickets on the server repo if you have some reproducible cases.

**Comment by hedefalk** [comment]
@fommil Since I'm still using the swank protocol, is there any place other than: https://github.com/ensime/ensime-server/blob/master/swank/src/main/scala/org/ensime/server/protocol/swank/SwankProtocol.scala to browse? There used to be a little documentation there…

**Comment by hedefalk** [comment]
@fommil Reason I ask is I think I use "type-at-point" but should use "symbol-at-point". I used to look in that file to "browse" the api, but it's a bit harder now with just:
https://github.com/ensime/ensime-server/blob/master/swank/src/main/scala/org/ensime/server/protocol/swank/SwankProtocol.scala#L233

**Comment by hedefalk** [comment]
_From @fommil on June 15, 2015 13:53_

https://github.com/ensime/ensime-server/tree/master/api/src/main/scala/org/ensime <= these are the API docs

**Comment by hedefalk** [comment]
_From @fommil on June 15, 2015 13:55_

Btw, I have a PR soon that will remove `EnsimeApi` and put the docs on the `incoming.scala` messages. That should make it a lot easier for you, oh and JSON :wink:

**Comment by hedefalk** [comment]
_From @fommil on June 15, 2015 14:1_

here for examples of the S-Exp => https://github.com/ensime/ensime-server/tree/master/swank/src/test/scala/org/ensime/server/protocol/swank

**Comment by hedefalk** [comment]
Awesome, thanks!

**Comment by hedefalk** [comment]
@fommil I'll ask here. The tests seem to state just that both :pos and :decl-pos should be nil when using symbol-at-point or type-at-point. How am I supposed to get the declaration position of symbols or types? 

I think my code worked before, but now it is :nil and since the tests suggests that's correct, I guess I should use something different?

**Comment by hedefalk** [comment]
_From @fommil on June 15, 2015 19:50_

`symbol-at-point` is how emacs does it. If they come back `nil` then you're hitting a bug in the server. Does it ever work? It definitely works for me (mostly) because I use it all the time.

**Comment by hedefalk** [comment]
_From @fommil on June 15, 2015 19:52_

try running up the server against the server code itself, if you can give me some examples of where it fails that would be good (although there are a few known failure cases that should be easy to fix when I have the time...)

**Comment by hedefalk** [comment]
Never works on my current test project.

But I don't get it though, the test strings seems to suggest that this is the expected behaviour:

https://github.com/ensime/ensime-server/blob/master/swank/src/test/scala/org/ensime/server/protocol/swank/SwankTestData.scala#L22

Or does nil there just get interpreted somewhere to mean "we don't care about the value"?

**Comment by hedefalk** [comment]
I'll try it against ensime-server tomorrow! Need to get to bed :)

**Comment by hedefalk** [comment]
_From @fommil on June 15, 2015 19:56_

yeah, tests are just about checking the marshalling. Is your test project on github? I can have a look and see if it works for me.

**Comment by hedefalk** [comment]
I can put it up, it's just a couple of files I started typing. Be right back.

**Comment by hedefalk** [comment]
https://github.com/hedefalk/ensime-test-project

**Comment by hedefalk** [comment]
Sorry though, really got to hit the sack! Thanks for looking at it!

**Comment by hedefalk** [comment]
I left .ensime in there just so you could have a look at it if it was something going on there.

**Comment by hedefalk** [comment]
_From @fommil on June 15, 2015 20:10_

here's an example for you from the `ensime-server` code itself

```elisp
(:return (:ok (:name "sourceRoot" :local-name "sourceRoot" :decl-pos (:type offset :file "/home/fommil/Projects/ensime-server/server/src/it/scala/org/ensime/intg/BasicWorkflow.scala" :offset 755) :type (:arrow-type nil :name "<error>" :type-id 1 :decl-as nil :full-name "<none>.<none>" :type-args nil :members nil :pos nil :outer-type-id nil) :is-callable nil :owner-type-id nil)) 8)
```

and here's an example from your test project (`Foo.scala` `symbol-at-point` over `foo` in the definition of `def bar`)

```elisp
(:swank-rpc (swank:symbol-at-point "/home/fommil/Projects/ensime-test-project/src/main/scala/Foo.scala" 260) 6)

(:return (:ok (:name "foo" :local-name "foo" :decl-pos (:type offset :file "/home/fommil/Projects/ensime-test-project/src/main/scala/Foo.scala" :offset 149) :type (:arrow-type t :name "(asdf: Int, y: Int)Int" :type-id 2 :result-type (:arrow-type nil :name "Int" :type-id 1 :decl-as class :full-name "scala.Int" :type-args nil :members nil :pos nil :outer-type-id nil) :param-sections ((:params (("asdf" (:arrow-type nil :name "Int" :type-id 1 :decl-as class :full-name "scala.Int" :type-args nil :members nil :po...
```

(truncated in the logs... there is a way to get the full message from emacs, but I can't recall how)

I hope that helps!

**Comment by hedefalk** [comment]
Ah, sorry, that seems to work for me too! But not for any of the library things I tested, just my local stuff. For instance:

```
22:13:40.278 [Thread-10] INFO  o.e.s.protocol.swank.SwankProtocol - Received msg: (:swank-rpc (swank:symbol-at-point "/Users/viktor/dev/projects/ensime-test-project/src/main/scala/Foo.scala" 307) 57)
22:13:40.279 [Scala Presentation Compiler []] DEBUG o.e.core.RichPresentationCompiler - using symbol of class scala.reflect.internal.Trees$Select tree
22:13:40.287 [Scala Presentation Compiler []] DEBUG o.e.core.RichPresentationCompiler - search: scalaz.syntax.ApplyOps.|@| = None
22:13:40.291 [ENSIME-akka.actor.default-dispatcher-22] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:return (:ok (:name "|@|" :local-name "|@|" :decl-pos nil :type (:arrow-type t :name "[B](fb: F[B])scalaz.syntax.ApplicativeBuilder[F,A,B]" :type-id 25 :result-type (:arrow-type nil :name "<refinement>" :type-id 26 :decl-as class :full-name "scalaz.syntax.ApplyOps$<refinement>" :type-args nil :members nil :pos nil :outer-type-id 22) :param-sections ((:params (("fb" (:arrow-type nil :name "F" :type-id 24 :decl-as nil :full-name "scalaz.syntax.F" :type-args ((:arrow-type nil :name "B" :type-id 20 :decl-as ni...
```
and 
```
22:15:11.866 [Thread-10] INFO  o.e.s.protocol.swank.SwankProtocol - Received msg: (:swank-rpc (swank:symbol-at-point "/Users/viktor/dev/projects/ensime-test-project/src/main/scala/Foo.scala" 368) 59)
22:15:11.867 [Scala Presentation Compiler []] DEBUG o.e.core.RichPresentationCompiler - using symbol of class scala.reflect.internal.Trees$Select tree
22:15:11.869 [Scala Presentation Compiler []] DEBUG o.e.core.RichPresentationCompiler - search: net.liftweb.util.ToCssBindPromoter.#> = None
22:15:11.872 [ENSIME-akka.actor.default-dispatcher-23] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:return (:ok (:name "#>" :local-name "#>" :decl-pos nil :type (:arrow-type t :name "[T](it: => T)(implicit computer: net.liftweb.util.CanBind[T])net.liftweb.util.CssSel" :type-id 6 :result-type (:arrow-type nil :name "CssSel" :type-id 7 :decl-as trait :full-name "net.liftweb.util.CssSel" :type-args nil :members nil :pos nil :outer-type-id nil) :param-sections ((:params (("it" (:arrow-type nil :name "<byname>" :type-id 3 :decl-as class :full-name "scala.<byname>" :type-args ((:arrow-type nil :name "T" :type...
```
Maybe these are both cases of two short symbol names?

**Comment by hedefalk** [comment]
_From @rorygraves on June 15, 2015 20:36_

Well done @fommil for being so quick - I'm trying to debug similar issues on the sublime side, but I think that may be my ineptness rather than anything deeper so far.

**Comment by hedefalk** [comment]
I think after doing a TypecheckAll and using Symbol instead of type it seems to work most of the time, but I still do not get any declPos from things like scalaz ```|@|``` or lift's ```#>```.

Compare:

```
{
  "msg": {
    "name": "|@|",
    "localName": "|@|",
    "type": {
      "resultType": {
        "name": "<refinement>",
        "fullName": "scalaz.syntax.ApplyOps$<refinement>",
        "typehint": "BasicTypeInfo",
        "typeId": 9,
        "outerTypeId": 8,
        "typeArgs": [],
        "members": [],
        "declAs": {
          "typehint": "Class"
        }
      },
      "name": "[B](fb: F[B])scalaz.syntax.ApplicativeBuilder[F,A,B]",
      "paramSections": [
        {
          "params": [
            [
              "fb",
              {
                "name": "F",
                "fullName": "scalaz.syntax.F",
                "typehint": "BasicTypeInfo",
                "typeId": 5,
                "typeArgs": [
                  {
                    "name": "B",
                    "fullName": "scalaz.syntax.B",
                    "typehint": "BasicTypeInfo",
                    "typeId": 6,
                    "typeArgs": [],
                    "members": [],
                    "declAs": {
                      "typehint": "Nil"
                    }
                  }
                ],
                "members": [],
                "declAs": {
                  "typehint": "Nil"
                }
              }
            ]
          ],
          "isImplicit": false
        }
      ],
      "typehint": "ArrowTypeInfo",
      "typeId": 7
    },
    "isCallable": true,
    "ownerTypeId": 8
  },
  "callId": 31
}
```

with 

```
{
  "msg": {
    "name": "base64EncodeURLSafe",
    "localName": "base64EncodeURLSafe",
    "declPos": {
      "typehint": "OffsetSourcePosition",
      "file": "/Users/viktor/dev/projects/ensime-test-project/.ensime_cache/dep-src/source-jars/net/liftweb/util/SecurityHelpers.scala",
      "offset": 2391
    },
    "type": {
      "resultType": {
        "name": "String",
        "fullName": "java.lang.String",
        "typehint": "BasicTypeInfo",
        "typeId": 13,
        "typeArgs": [],
        "members": [],
        "declAs": {
          "typehint": "Class"
        }
      },
      "name": "(in: Array[Byte])String",
      "paramSections": [
        {
          "params": [
            [
              "in",
              {
                "name": "Array",
                "fullName": "scala.Array",
                "typehint": "BasicTypeInfo",
                "typeId": 10,
                "typeArgs": [
                  {
                    "name": "Byte",
                    "fullName": "scala.Byte",
                    "typehint": "BasicTypeInfo",
                    "typeId": 11,
                    "typeArgs": [],
                    "members": [],
                    "declAs": {
                      "typehint": "Class"
                    }
                  }
                ],
                "members": [],
                "declAs": {
                  "typehint": "Class"
                }
              }
            ]
          ],
          "isImplicit": false
        }
      ],
      "typehint": "ArrowTypeInfo",
      "typeId": 12
    },
    "isCallable": true,
    "ownerTypeId": 14
  },
  "callId": 32
}
``` 

The later has declPos.

I'll change title of this issue accordingly.

**Comment by hedefalk** [comment]
Also, if trying to navigate further by clicking on a link in a 3rd party lib I for instance get:


outgoing: 0000c3{"req": {"typehint":"SymbolAtPointReq","file":"/Users/viktor/dev/projects/ensime-test-project/.ensime_cache/dep-src/source-jars/net/liftweb/util/SecurityHelpers.scala","point":917}, "callId": 38}

client.coffee:16 incoming: {"msg":false,"callId":38}

**Comment by hedefalk** [comment]
I'll move this to server if you don't mind. Maybe just dup of https://github.com/ensime/ensime-server/issues/835

**Comment by hedefalk** [comment]
Ok, browsing the database I see I have:

net.liftweb.util.ToCssBindPromoter.$hash$greater

but I'm searching for:

net.liftweb.util.ToCssBindPromoter.#>


12:24:23.053 DEBUG None o.e.c.RichPresentationCompiler - using symbol of class scala.reflect.internal.Trees$Select tree
12:24:23.053 DEBUG None o.e.c.RichPresentationCompiler - search: net.liftweb.util.ToCssBindPromoter.#> = None


Don't know exactly where the fix should be though?

**Comment by hedefalk** [comment]
Is there any simple way to get the full map of scala class file escapings?

**Comment by fommil** [comment]
is this maybe a dupe of #635 ?

**Comment by fommil** [comment]
aah, no, you're right it's a dupe of #835

**Comment by hedefalk** [comment]
Definitely dupe of #835, but don't know about that one.
