### ISSUE TITLE
not semantic highlighting the first open file in a project

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1022]
It now seems repeatable that a save-file is needed to trigger semantic highlighting when the first file of a project is opened (it works for the second file). I would expect there to be an open-file hook that does this automatically.

To repeat:

* start ensime (await ready messages)
* open any scala file, not that it must be edited and saved for semantic highlighting to appear
* open second scala file, works automatically.
* close all scala buffers
* open any scala file, still not working.

Also, I don't think we should care about `(ensime-analyzer-ready)` --- the server will now simply schedule requests for when the analyser **is** ready.

**Comment by edani** [comment]
This may be related to #1015 , if the server swallows some semantic-highlighting requests.

**Comment by fommil** [comment]
This issue was moved to ensime/ensime-emacs#150
