### ISSUE TITLE
Asynchronous RPC Aborted:...

### ISSUE THREAD

**Issue by toddleo** [ensime/ensime-server#1026]
The mini-buffer reports: 

> Asynchronous RPC Aborted: Malformed swank:symbol-designations call: (swank:symbol-designations "/path/to/my/project/src/main/scala-2.10/tjack.scala" 0 34 (var val varField valField functionCall operator param class trait object package deprecated))

as I opened an empty `.scala` file, right after creating `.ensime` using `sbt gen-ensime` command. Annoyingly, this message prompts again everytime I hit any key to make it disappear.

**Comment by fommil** [comment]
This issue was moved to ensime/ensime-emacs#181
