### ISSUE TITLE
Indexing crashes silently on some spark dependency

### ISSUE THREAD

**Issue by koshelev** [ensime/ensime-server#1031]
Indexing never finishes on the project https://github.com/koshelev/hello-world. C-c C-v v and C-c C-r t does not work.

**Comment by fommil** [comment]
confirmed

**Comment by fommil** [comment]
@koshelev it might be a while before we get around to this, if you're interested in investigating further I'd recommend looking in `SearchService.scala` and putting in some `onFailure` handlers on the various `Future`s. That whole file needs a refactor to use `Actor`s.

**Comment by fommil** [comment]
It should also be relatively easy to add these three `jar`s to the integration tests for the search service. Just add them as `intransitive()` in the relevant testing project.

**Comment by koshelev** [comment]
Thanks for the info! Will try to figure it out this weekend.

**Comment by fommil** [comment]
@koshelev no need, we know what it is.

**Comment by fommil** [comment]
@koshelev but since you're fired up to help, have a look and see if there is anything else you could pick up instead :wink:

**Comment by fommil** [comment]
https://issues.apache.org/jira/browse/SPARK-8815
