### ISSUE TITLE
add additional nodes to the drone build farm

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1034]
i.e. rory, but also put out an open call for people to let us use their dockers.

**Comment by fommil** [comment]
@rorygraves I have generated the keys to go on your box, but it seems to have gone down.

note to self: http://readme.drone.io/setup/config/workers/

**Comment by rorygraves** [comment]
Don't have time this evening will check tomorrow.

**Comment by rorygraves** [comment]
Back now - have fun
