### ISSUE TITLE
new green dots and blue underline

### ISSUE THREAD

**Issue by ChuckIrvine** [ensime/ensime-server#1036]
In my emacs scala buffers, I notice green dots in the left hand margin and blue underlining under some of the text. I haven't been using Ensime very long, but I don't recall seeing these two things before. What are they for? I suppose its possible that they aren't coming form Ensime, but some other Emacs package.

**Comment by edani** [comment]
It's a new feature, they indicate where implicits are used. Hover over the blue underline  (not the green dot, hover isn't enabled) ; or type `C-c C-v e`  to see details about the implicits.

**Comment by ChuckIrvine** [comment]
I see. That sounds interesting. Do you think both forms of decoration are needed? If I had to pick one over the other, I would go with the green dots, and I would make them a little smaller. Personally, I find the underlining a bit too intrusive. Only my humble opinion. 

I’m really liking Ensime. Thanks

Chuck

**Comment by fommil** [comment]
@ChuckIrvine the faces are designed to be customised

**Comment by diego-alvarez-hs** [comment]
@fommil Can you point me in the right direction to customize/hide the green dot?

**Comment by fommil** [comment]
Look for the ENSIME overlays.

**Comment by aemoncannon** [comment]
+1 for not having both forms of deco by default.

**Comment by d1egoaz** [comment]
Tks @fommil 

I found the way to hide/change underline color of implicit parameters. It's in the wiki :smile: 
https://github.com/ensime/ensime-emacs/wiki/Editing#semantic-highlighting

but there's a issue with the example code, I fixed it in:
https://github.com/ensime/ensime-emacs/issues/260

So, if you want to change the underline color:

```elisp
  (setq ensime-sem-high-faces
        '((implicitConversion . (:underline (:style wave :color "cyan")))
          (implicitParams . (:underline (:style wave :color "cyan")))))
```

if you want to hide it:
``` elisp
  (setq ensime-sem-high-faces
        '((implicitConversion nil)
          (implicitParams nil)))
```

I don't know if we can override just those parameters or we have to pass again all parameters like:
``` elisp
 (setq ensime-sem-high-faces
  '((var . (:foreground "#ff2222"))
    (val . (:foreground "#dddddd"))
    (varField . (:foreground "#ff3333"))
    (valField . (:foreground "#dddddd"))
    (functionCall . (:foreground "#84BEE3"))
    (param . (:foreground "#ffffff"))
    (class . font-lock-type-face)
    (trait . (:foreground "#084EA8"))
    (object . (:foreground "#026DF7"))
    (package . font-lock-preprocessor-face)
    (implicitConversion . (:underline (:style wave :color "blue")))
    (implicitParams . (:underline (:style wave :color "blue")))
    (deprecated . (:strike-through "dark gray"))))
```

I still don't know how to make smaller and change the color of green dots :thought_balloon:

**Comment by fommil** [comment]
Yeah the sem faces require a full redefine

**Comment by SongWithoutWords** [comment]
I'm using ScalaTest, and nearly every line has an implicit conversion. Disabling the underline helped reduce the visual noise -  is there a way to remove the green dots as well?

**Comment by SongWithoutWords** [comment]
For posterity: the dots can be disabled with `(setq ensime-implicit-gutter-icons nil)` as described here: https://github.com/syl20bnr/spacemacs/issues/4746
