### ISSUE TITLE
Inspect type at point fails for all  nested types in a given file

### ISSUE THREAD

**Issue by adamchandra** [ensime/ensime-server#1040]
Given a file structure like so: 

    case class Foo(str: String)
    //          ^ point 1
    object someModule {
         val f0 = Foo("foo")
         //        ^ point 2

     }

When I try to inspect the type at point 1, I get the correct information regarding class Foo. If I try to inspect str, just past point 1, I still get the type information for Foo.

If I try to inspect at point 2, I get the type information for someModule. In fact if I try to inspect any type inside someModule, I get someModule's type info.

Not sure if this is an emacs integration issue, or related to another ensime subproject. Please let me know if I can provide any other helpful information.

**Comment by fommil** [comment]
I just tried this and it seems to work as expected. If you can reproduce this, please send us an example project and reopen.

**Comment by adamchandra** [comment]
My apologies for such a barebones complaint with no example project. I had this problem for a week or so, then changed a few things in my build.sbt and the problem disappeared. I will try to reproduce it if I can.
