### ISSUE TITLE
VFS filewatchers are really inefficient

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1042]
*sigh* seems an upstream bug in VFS that we might have to workaround.

Means that changes to H2 or Lucene and causing VFS to spin and use up all the CPU.

To trigger the extreme behaviour, wipe the cache and startup fresh.

**Comment by fommil** [comment]
@aemoncannon we could use this as a general catch all for the upstream bugs/perfomance problems against VFS2

**Comment by fommil** [comment]
* https://issues.apache.org/jira/browse/VFS-536
* https://issues.apache.org/jira/browse/VFS-537
* https://issues.apache.org/jira/browse/VFS-553

**Comment by fommil** [comment]
this one is really killing me at work too! Been thinking about making a Java 7 filewatcher as a dependency, and then using it if its available, otherwise falling back to the Java 6 implementation from VFS.

**Comment by fommil** [comment]
I'm working on some unit tests around the file watchers, including backporting the latest version of the file monitor (it still has these bugs)

but a massive improvement for the workaround dawned upon me... it seems to be able to detect the deletion of the root directory! So instead of watching the parent, I'll just watch for that instead and then recreate when that happens.

**Comment by fommil** [comment]
WIP https://github.com/fommil/ensime-server/tree/export-jars I should finish this off on Friday evening (going out tomorrow night)

**Comment by fommil** [comment]
@lxol you'll probably want to make use of these tests as well when I'm done

**Comment by lxol** [comment]
@fommil   I had to play with delays to pass some of your tests. Here the problems that I noticed.
-  I used `take` instead of `poll` for change monitoring. This is probably the reason why delay is so big. We can try to use `poll` on schedule if the delay is unacceptable.  I am not sure about performance impact though.
- I ignored tests that register files instead of directories for monitoring.  It looks like Java 7 WatchService can register only directories. I got an exception while trying to do that with a file.  I think as a workaround we can register a parent directory and use a selector equal to the file name. 

I submitted a PR to fommil/ensime-server with the successful test

**Comment by fommil** [comment]
just to be clear, this is closed as WontFix. We no longer need to have file watchers watching the file watchers, which is more efficient, but even if I use the new jar target support I'm still seeing ENSIME hang on startup due to all the filewatcher's time being spent in `getType`... so that operation is obviously extremely slow on windows and I don't really think I care to fix it since the JDK7 file watchers are just round the corner.

**Comment by fommil** [comment]
FYI (AFAIK, I only have `jar` files in the target directory)

```
"Back Traces - Method","Total Time [%]","Total Time","Total Time (CPU)","Samples",
" java.io.File.exists()","44.161507","8336849","8336849","88"
"  org.apache.commons.vfs2.provider.local.LocalFile.doGetType()","0.0","0","0","94"
"   org.apache.commons.vfs2.provider.AbstractFileObject.getType()","100.0","46313104","0","463"
"    org.apache.commons.vfs2.provider.AbstractFileObject.exists()","0.0","0","0","463"
"     org.ensime.indexer.DefaultFileMonitor$FileMonitorAgent.check()","0.0","0","0","913"
"      org.ensime.indexer.DefaultFileMonitor$FileMonitorAgent.access$200()","0.0","0","0","913"
"       org.ensime.indexer.DefaultFileMonitor.run()","0.0","0","0","82"
"        java.lang.Thread.run()","0.0","0","0","82"
```

**Comment by fommil** [comment]
actually might just reopen this to try and get to the bottom of that `getType` thing... no reason for it to be doing that and we might be able to offer a quick fix.

**Comment by fommil** [comment]
ok, I'm going to read the damn source code of `DefaultFileMonitor`...

**Comment by fommil** [comment]
couldn't see anything obviously wrong, except maybe we could turn down the frequency of polling

**Comment by fommil** [comment]
this should be replaced by #1217
