### ISSUE TITLE
Configuration not found, missing configuration 'compile'

### ISSUE THREAD

**Issue by richfwebb** [ensime/ensime-server#1044]
Hi, I'm getting the error below, does anyone have advice?

 configuration not found in org.ensime#ensime-sbt;0.1.5-SNAPSHOT; 'master(compile)'. Missing configuration: 'compile'. It was required from .... compile

[ivy:resolve] WARN: 	::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve] WARN: 	::          UNRESOLVED DEPENDENCIES         ::
[ivy:resolve] WARN: 	::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve] WARN: 	:: org.ensime#ensime-sbt;0.1.5-SNAPSHOT: configuration not found in org.ensime#ensime-sbt;0.1.5-SNAPSHOT: 'master(compile)'. Missing configuration: 'compile'. It was required from com.cortx#corenlp-utils_2.11;2.0.1 compile
[ivy:resolve] WARN: 	::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve] 	report for com.cortx#manti-corenlp_2.11;1.4.3-SNAPSHOT compile produced in /home/rich/.ivy2/cache/com.cortx-manti-corenlp_2.11-compile.xml
[ivy:resolve] 	report for com.cortx#manti-corenlp_2.11;1.4.3-SNAPSHOT runtime produced in /home/rich/.ivy2/cache/com.cortx-manti-corenlp_2.11-runtime.xml
[ivy:resolve] 	report for com.cortx#manti-corenlp_2.11;1.4.3-SNAPSHOT test produced in /home/rich/.ivy2/cache/com.cortx-manti-corenlp_2.11-test.xml
[ivy:resolve] 	report for com.cortx#manti-corenlp_2.11;1.4.3-SNAPSHOT provided produced in /home/rich/.ivy2/cache/com.cortx-manti-corenlp_2.11-provided.xml
[ivy:resolve] 	report for com.cortx#manti-corenlp_2.11;1.4.3-SNAPSHOT optional produced in /home/rich/.ivy2/cache/com.cortx-manti-corenlp_2.11-optional.xml
[ivy:resolve] 	report for com.cortx#manti-corenlp_2.11;1.4.3-SNAPSHOT sources produced in /home/rich/.ivy2/cache/com.cortx-manti-corenlp_2.11-sources.xml
[ivy:resolve] 	report for com.cortx#manti-corenlp_2.11;1.4.3-SNAPSHOT docs produced in /home/rich/.ivy2/cache/com.cortx-manti-corenlp_2.11-docs.xml
[ivy:resolve] 	report for com.cortx#manti-corenlp_2.11;1.4.3-SNAPSHOT pom produced in /home/rich/.ivy2/cache/com.cortx-manti-corenlp_2.11-pom.xml
[ivy:resolve] 	resolve done (938ms resolve - 15ms download)
[ivy:resolve] 
[ivy:resolve] :: problems summary ::
[ivy:resolve] :::: WARNINGS
[ivy:resolve] 		::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve] 		::          UNRESOLVED DEPENDENCIES         ::
[ivy:resolve] 		::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve] 		:: org.ensime#ensime-sbt;0.1.5-SNAPSHOT: configuration not found in org.ensime#ensime-sbt;0.1.5-SNAPSHOT: 'master(compile)'. Missing configuration: 'compile'. It was required from com.cortx#corenlp-utils_2.11;2.0.1 compile
[ivy:resolve] 		::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve] :::: ERRORS
[ivy:resolve] 	unknown resolver null
[ivy:resolve] 	unknown resolver null

**Comment by fommil** [comment]
you're using an ancient `ensime-sbt`

**Comment by richfwebb** [comment]
Thanks for your response. I inherited this project from a coworker and am not familiar with updating this plugin or resolving the dependency. Do you have any advice?

**Comment by fommil** [comment]
if you're not using ENSIME you can remove it. They should not have added it to the project plugin list anyway, it is a personal choice.

**Comment by richfwebb** [comment]
I removed the module from External Libraries, ran 'sbt publishLocal' to create a new ivy.xml, but after running ant with the new ivy file, I still receive the same configuration not found in org.ensime#ensime-sbt;0.1.5-SNAPSHOT ... how is that possible?

**Comment by fommil** [comment]
Maybe best ask in an SBT forum, sounds like you have ivy cache problems.

**Comment by richfwebb** [comment]
Thanks, I appreciate the help.
