### ISSUE TITLE
Rename JERK to DALEK

### ISSUE THREAD

**Issue by rorygraves** [ensime/ensime-server#1045]
Data Access Layer Ensime Koding - ala Scalawags @dickwall  - One for @fommil

**Comment by fommil** [comment]
:smile: or Joshy

**Comment by fommil** [comment]
or Jerky

**Comment by fommil** [comment]
@dickwall

**Comment by dickwall** [comment]
:-) :-) :-)

**Comment by fommil** [comment]
maybe we could use the DALEK name for the documentation server (we serve up all the scaladocs for the project and that feature currently doesn't have a name). Documents And Lesser ENSIME Knowledge. Or something.

**Comment by rorygraves** [comment]
lol, like it.

**Comment by fommil** [comment]
should probably have a generated splash page that lists all the javadocs for a project, ordered by name. that would be pretty handy actually.

**Comment by rorygraves** [comment]
I think there is a whole bunch of pages we could add to the webserver.
