### ISSUE TITLE
Scala 2.10 version of ensime being used for Scala 2.11 project

### ISSUE THREAD

**Issue by greenrd** [ensime/ensime-server#1048]
This is causing macros compiled for Scala 2.11 to crash the presentation compiler.

This was originally a 2.10 project. It appears that ensime-sbt has correctly generated the 2.11 deps in `.ensime`, but incorrectly left the version as 2.10.4.

Ah, actually, I guess what is happening is that it is a multi-project build with all the subprojects set to 2.11, but the main project / toplevel is defaulting to 2.10.

**Comment by greenrd** [comment]
Yes, that was it. I changed `build.sbt` to set it using `scalaVersion in ThisBuild := "2.11.7"` at the top level, and restarted ensime, and now the 2.11 version of ensime is being used.

**Comment by rorygraves** [comment]
Actually raises an intersting question - Ensime has a single presentation compiler, if somebody has a multi-module, multi-version build what do we do:
* Refuse to work
* Pick root one.... 
* Fix Ensime to spin up multiple PCs (one server, multiple child presentation compilers to handle it)

Not sure how common this usecase is - thoughts @greenrd @fommil ?

**Comment by fommil** [comment]
One version only, I don't think multi version projects make any sense. Sounds like maybe an SBT bug?

**Comment by greenrd** [comment]
I don't think it's an sbt bug - in theory different modules in the same build don't have to depend on each other in any way. But I've never seen that ability used.

I think it should just refuse to work - I've experienced presentation compiler instability for months and I'm hoping this mistake was the cause of at least some of those issues...

**Comment by rorygraves** [comment]
Agreed - I think rejecting the generation of the gen-ensime talk would make sense (we can't currently support it within Ensime (because of the single PC), rather than throwing spurious errors, outputing 'we don't support this because...' would be helpful.

@fommil Should I enable the sbt issue tracker and move it to there?

**Comment by fommil** [comment]
ok, sure. We have two open tickets for the sbt plugin so make sure to move them as well.
