### ISSUE TITLE
ycmd support

### ISSUE THREAD

**Issue by xanderdunn** [ensime/ensime-server#1049]
Almost exactly one year ago there was a [discussion](https://github.com/Valloric/YouCompleteMe/issues/1078) on adding ENSIME support in YouCompleteMe for vim.  I wonder if any progress has been made in that direction, or at the very least the refactoring you mentioned at the time that would be necessary for support?

**Comment by fommil** [comment]
Should be easy to add, we implemented JSON over websocket to make it easy. We just need someone the step up to the plate and do it... although offering only completions would significantly limit what ENSIME can do.

**Comment by xanderdunn** [comment]
@fommil

Thanks a lot. With luck, I'll be writing primarily Scala over the coming month, which will motivate me to do this.  ycmd/YouCompleteMe also supports file diagnostics (error/warnings), GoToDeclaration/Definition, so that information should also be usable.

**Comment by fommil** [comment]
Cool!!

**Comment by fommil** [comment]
If have any questions about the API, just ask. The gitter channel in pretty active.

**Comment by fommil** [comment]
closing because this is more discussion than bug... did you make any progress?
