### ISSUE TITLE
Spurious type errors are reported when trying to use dotty with Ensime

### ISSUE THREAD

**Issue by smarter** [ensime/ensime-server#1052]
I'd like to hack on [dotty](http://github.com/lampepfl/dotty) using Ensime, but it keeps hitting type errors even though the project compiles fine with `scalac`, here's how to reproduce what I'm seeing:
- Open `src/dotty/tools/dotc/core/Symbols.scala`
- Launch ENSIME with `M-x ensime` (after having followed the [Quick Start Guide](https://github.com/ensime/ensime-emacs/wiki/Quick-Start-Guide))
- Enter a single space, in the file, remove it, save the file
- Press `M-n` to find the first spurious type error, which will look like:
```scala
type mismatch;
found   : dotty.tools.dotc.core.Symbols.(some other)Symbol(in object Symbols){type ThisName = N}
required: dotty.tools.dotc.core.Symbols.Symbol(in object Symbols)
```
Notice that the types should match here, they don't because the found type is `(some other)Foo` instead of `Foo`, which makes me suspect that Ensime is keeping around stale symbols which confuses the presentation compiler.

Also note that this does not happen with scala-ide, so this does not seem to be a bug in the presentation compiler itself.

**Comment by fommil** [comment]
The first thing I'd like the understand is why Scala ide in OK. It's it suppressing the error or is it using the presentation compiler with an additional parameter that either gets it over this hump or never fires the warning.  @sshafer do you have any ideas on this?

**Comment by sschaef** [comment]
Beside from restarting the presentation compiler I don't know how to resolve such an error or why it appears. In Scala IDE we also had and still have problems with flaky tests (i.e. tests that sometimes fail) when we cache compiler instances. We never figured out what the problem really is, restarting the compiler completely or trying to reset as much state as possible were always the ways how we tackled the problem. I give the ball to @retronym, maybe he has an idea how to find out more about the roots of the problem.

**Comment by fommil** [comment]
@sschaef cool thanks. The confusing thing is that we're restarting entirely, so my our perspective it looks like we're doing exactly the same as `scala-ide` --- yet we're seeing type errors and scala-ide is apparently ok with it.

**Comment by sschaef** [comment]
Yes, that is exactly what we see in our test suite. The tests are always the same but sometimes they fail nevertheless. I saw similar errors that were reproducible, i.e. they always appeared. But they always occurred in complex type hierarchies, minimizing them would have taken hours. Therefore I never did it/succeeded with it.

**Comment by edani** [comment]
I've seen this type of errors before. Now, at least, we have a reproducible example. 

@smarter  if it helps, a workaround is to restart the presentation compiler with `C-c C-c r`, it clears up errors that have been accumulating.

**Comment by smarter** [comment]
I managed to find a hack that seems to solve the issue, see #1053, would be great if someone with some knowledge of the presentation compiler could take a look to figure out what's going on!

**Comment by fommil** [comment]
btw, can you please raise a separate ticket for having to "Enter a single space, in the file, remove it, save the file". This shouldn't be necessary.
