### ISSUE TITLE
Add architecture overview to CONTRIBUTING

### ISSUE THREAD

**Issue by markschaake** [ensime/ensime-server#1063]
Form a potential contributors perspective, it would be nice if there was an architecture overview to make it less intimidating to approach adding a feature. Specifically, why the SBT build is broken into subprojects and an example of how to thread a new feature through all the necessary layers. Here's an opinion:

Add to the root README a high-level overview of the build breakdown and the role of each subproject (one line per subproject).

Add a README to each of the subproject's root dir with more focused documentation.

**Comment by fommil** [comment]
the best place for this would be the CONTRIBUTING file. The project is not large enough to require a README per subcomponent. FYI, such an overview is here http://ensime.github.io/talks/scaladays15/#/3/1 with notes in the Architecture section here https://raw.githubusercontent.com/ensime/ensime.github.io/master/talks/scaladays15/scaladays-ensime.org
