### ISSUE TITLE
emacs frozen right after M-x ensime

### ISSUE THREAD

**Issue by betehess** [ensime/ensime-server#1065]
It is "Waiting for connection-info"...

I was having this issue from time to time. I would normally force kill emacs, go back into the project, restart ensime. With the latest update for ensime (today), it systematically freezes right away. I don't think I have anything special in my configuration. I am not sure where to look to provide a better feedback.

**Comment by betehess** [comment]
And Activity Monitor shows that Emacs is stuck at 100% CPU usage.

**Comment by rorygraves** [comment]
Hmm sorry about that!,

Can you let me know:

Platform (Windows/Mac etc)
Emacs version.
What is displayed in the inferior-ensime-buffer (assuming you can get to it)

Thanks

**Comment by fommil** [comment]
Also, if you can profile where that CPU is would be great. He you have an example project to point us at?

Workaround is the git clone and checkout a version that was working for you, publishLocal and delete the ENSIME classpath cache file in .emacs.d/ensime

**Comment by betehess** [comment]
Here are a few more information.

> Platform (Windows/Mac etc)

OS X Yosemite 10.10.5. I had installed emacs through homebrew as explained in http://www.emacswiki.org/emacs/EmacsForMacOS.

> Emacs version.

```
➜  ~  emacs -v
emacsclient 24.5
➜  ~  cat ~/.emacs
(custom-set-variables
 '(inhibit-startup-screen t))
(custom-set-faces
 )

;; http://www.rensselaer.org/dept/acs/rpinfo/common/Computing/Consulting/Software/Emacs/Hints/backup.html
(setq make-backup-files nil)

;; http://www.emacswiki.org/emacs/EmacsForMacOS#toc26
(when (eq system-type 'darwin)
  (setq ns-command-modifier 'meta)
  )

(tool-bar-mode -1)

(require 'package)
(add-to-list 'package-archives
	     '("melpa" . "http://melpa.milkbox.net/packages/") t)
(package-initialize)

(when (not package-archive-contents)
  (package-refresh-contents))

(require 'ensime)
(add-hook 'scala-mode-hook 'ensime-scala-mode-hook)

(setq scala-indent:use-javadoc-style t
      popup-complete-enabled-modes '(scala-mode)
      ensime-default-buffer-prefix "ENSIME-"
      scala-outline-popup-select 'closest)

;; flx and idof
;; https://github.com/lewang/flx
(require 'flx-ido)
(ido-mode 1)
(ido-everywhere 1)
(flx-ido-mode 1)
;; disable ido faces to see flx highlights.
(setq ido-enable-flex-matching t)
(setq ido-use-faces nil)
(global-set-key "\M-x" 'smex)

(require 'windmove)
(windmove-default-keybindings 'meta)

;; http://web-mode.org/
(require 'web-mode)
(add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))
(defun my-web-mode-hook ()
  "Hooks for Web mode."
  (setq web-mode-markup-indent-offset 2)
  (setq web-mode-css-indent-offset 2)
  (setq web-mode-code-indent-offset 2)
  (setq-default indent-tabs-mode nil)
  (setq-default tab-width 2)

)
(add-hook 'web-mode-hook 'my-web-mode-hook)

;; https://github.com/bbatsov/projectile
(projectile-global-mode)
(persp-mode)
(require 'persp-projectile)

;; https://raw.githubusercontent.com/magit/magit/next/Documentation/RelNotes/1.4.0.txt
;;(setq magit-last-seen-setup-instructions "1.4.0")
```
> What is displayed in the inferior-ensime-buffer (assuming you can get to it)

The last thing I can see is "Waiting for connection-info". I cannot do anything from there. Is there a place where I can find logs or anything?

> you have an example project to point us at?

Here is how I can systematically reproduce the problem on my machine:

```
➜  foobarbaz git:(master) ✗ tree
.
├── build.sbt
└── src
    └── main
        └── scala
            └── foobar
                └── Foo.scala

4 directories, 2 files
➜  foobarbaz git:(master) ✗ cat build.sbt
name in ThisBuild := "foobar"

organization in ThisBuild := "foooo"

version in ThisBuild := "0.1-SNAPSHOT"

scalaVersion in ThisBuild := "2.11.7"

scalacOptions in ThisBuild ++= Seq("-feature", "-deprecation", "-unchecked")

lazy val root = project.in(file("."))

➜  foobarbaz git:(master) ✗ cat src/main/scala/foobar/Foo.scala
package foobar

trait Foo
➜  foobarbaz git:(master) ✗ sbt gen-ensime
```

Then I open emacs on `src/main/scala/foobar/Foo.scala` (that's important), then `M-x ensime`, then it freezes. Apparently it works fine when I first launch ensime from `build.sbt` and only then open `Foo.scala`.

I hope this is not happening only on my machine :-/

**Comment by fommil** [comment]
which version of the emacs client are you using? Look in the `.emacs.d/elpa` folder. Update to the latest and try again.

**Comment by fommil** [comment]
btw, server logs are in the buffer called `*ensime-inferior-server*`. You can also cancel any emacs hanging by typing `C-g` (this is a standard "exit" command in emacs). If you enable `debug-on-error` and `debug-on-quit` then you'll get some lisp stack traces.

It's definitely not happening for me on Linux.

**Comment by fommil** [comment]
actually, the buffer will be called `ENSIME-server-...` for you (because you've copied some config from me :wink:)

I don't advise using `popup-complete-enabled-modes` because we have `company-mode` nowadays. Although I don't think that would be causing a conflict.

**Comment by fommil** [comment]
This issue was moved to ensime/ensime-emacs#220
