### ISSUE TITLE
Silent server connection fail

### ISSUE THREAD

**Issue by hedefalk** [ensime/ensime-server#1066]
_From @laughedelic on August 17, 2015 17:18_

I think I have this since the last update (no sure). 
When I do `Ensime: Start`, the panel appears, but then nothing happens. And in the console there are these error messages:

```
/Users/laughedelic/.atom/packages/Ensime/lib/client.coffee:53 client connected
client connected

/Users/laughedelic/.atom/packages/Ensime/lib/client.coffee:67 
Ensime server error event: Error: read ECONNRESET

/Users/laughedelic/.atom/packages/Ensime/lib/client.coffee:64 
Ensime server close event
```

**Comment by hedefalk** [comment]
Thanks for reporting!

1) Do you have an .ensime_cache/port file?
2) Is there a ensime-server process on this port?
3) If so, can you see any error message in the .ensime_cache/server.log under your project?

**Comment by hedefalk** [comment]
_From @rorygraves on August 17, 2015 19:52_

@hedefalk this could be related to the latest server changes.  Hopefully I haven't broken it!!!

**Comment by hedefalk** [comment]
Did cleanLocal and updated server from repo and now get the same:

```
22:30:14.859 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - ENSIME HTTP on /127.0.0.1
22:30:14.860 ERROR None Server - Shutdown requested due to internal error: http endpoint failed to initialise: An ENSIME server might be open already for this project. If you are sure this is not the case, please delete /Users/viktor/dev/projects/ensime-test-project/.ensime_cache/ht
```

**Comment by hedefalk** [comment]
Works for me after a `rm -r .ensime_cache`.

@rorygraves Can I take it a server update was made that needed a cleaning out of cache folder?

**Comment by hedefalk** [comment]
_From @rorygraves on August 17, 2015 20:51_

@hedefalk Hmm.  Interesting - it appears to believe there was a lock file (the http file showing the port for the websockets client).  You could have got away with removing ```/Users/viktor/dev/projects/ensime-test-project/.ensime_cache/http ```.

I have changed the logic round a bit, but I'm surprised that it stopped it working like that if it had previously shut down normally.   Will do a bit more digging.

If you shutdown and restart does the error reappear?

**Comment by hedefalk** [comment]
_From @rorygraves on August 17, 2015 21:6_

Btw @hedefalk  Are you using websockets now?

**Comment by hedefalk** [comment]
Hm, maybe I had a hard reboot the other day… @laughedelic How about you, can you get the connection up?

And sorry, no, we're still using jerk over swank here. Any cool reason to switch?

**Comment by hedefalk** [comment]
_From @rorygraves on August 17, 2015 21:28_

@hedefalk The reason I asked is the latest server changes are fairly strict on message framing - the length should be the number of bytes, not the number of utf-8 characters - see https://github.com/ensime/ensime-emacs/issues/216  Do double check, otherwise you may get wieird parse errors.  (e.g. try the unicode characters for ← and ⇒ in you match statements).   So format is xxxxxMMMMM where xxxx is a number describing the number of bytes following (i.e. some UTF-8 characters are multiple bytes).

**Comment by hedefalk** [comment]
_From @rorygraves on August 17, 2015 21:29_

Switching to websockets simply means that the message framing problem is handled by the underlying protocol.

**Comment by hedefalk** [comment]
@rorygraves Cool. I'll try to do it pretty soon, but the swank protocol seems to work just fine so not top prio for me.

**Comment by hedefalk** [comment]
_From @laughedelic on August 18, 2015 11:0_

Hi. I tried to remove `.ensime_cache`, regenerate `.ensime` and start it again. Doesn't help. Here is what I get in the console:
```
/Users/laughedelic/.atom/packages/Ensime/lib/client.coffee:53 client connected
/Users/laughedelic/.atom/packages/Ensime/lib/client.coffee:67 Ensime server error event: Error: read ECONNRESET
/Users/laughedelic/.atom/packages/Ensime/lib/client.coffee:64 Ensime server close event
/Users/laughedelic/.atom/packages/Ensime/lib/client.coffee:67 Ensime server error event: Error: This socket is closed.
```

Here is the content of my `.ensime` and `.ensime_cache/server.log`: [gist](https://gist.github.com/laughedelic/ecd168b4103520558331). And there are no other files in `.ensime_cache/`.

**Comment by hedefalk** [comment]
Looks like server chokes on some source-jar and dies?

Shortified stack:

org.ensime.core.Project.<init> -> ensime.indexer.SourceResolver -> ZipFileSystem.init -> org.apache.commons.vfs2.FileSystemException: Invalid relative file name.

**Comment by hedefalk** [comment]
@rorygraves I'll move this to server, but feel free to reopen if this is caused by something in Atom client.

**Comment by fommil** [comment]
weird "Invalid relative file name"

**Comment by fommil** [comment]
could be https://issues.apache.org/jira/browse/VFS-219 ?

**Comment by fommil** [comment]
@hedefalk can you please isolate which source jar is causing the trouble? Just do an `unzip -l` on them all and grep for a relative path beginning `../`

**Comment by hedefalk** [comment]
@fommil Gonna have to forward to @laughedelic. If the project is something you can share on github I can give it a try.

**Comment by hedefalk** [comment]
Ouch, that Apache-ticket is 7 years old :)

**Comment by laughedelic** [comment]
@hedefalk you won't believe me, but now it somehow works.. "_ 
I wanted to show you the project where it appeared, but then I couldn't reproduce it. I'm not sure what has changed, but if I encounter this problem again, I will let you know.

**Comment by hedefalk** [comment]
Great!
