### ISSUE TITLE
[vim] Cannot make bridge file on OS X

### ISSUE THREAD

**Issue by geowa4** [ensime/ensime-server#1081]
When running ensime-vim with either vim or neovim, I get the following error.

```
/usr/local/lib/ruby/gems/2.2.0/gems/ensime_bridge-0.0.4/lib/ensime_bridge.rb:11:in `read': No such file or directory @ rb_sysopen - .ensime_cache/bridge (Errno::ENOENT)
        from /usr/local/lib/ruby/gems/2.2.0/gems/ensime_bridge-0.0.4/lib/ensime_bridge.rb:11:in `get_socket'
        from /usr/local/lib/ruby/gems/2.2.0/gems/ensime_bridge-0.0.4/lib/ensime_bridge.rb:32:in `remote_stop'
        from /usr/local/lib/ruby/gems/2.2.0/gems/ensime_bridge-0.0.4/bin/ensime_bridge:11:in `<top (required)>'
        from /usr/local/bin/ensime_bridge:23:in `load'
        from /usr/local/bin/ensime_bridge:23:in `<main>'
```

Looking through the code, I'm not sure why it would do that. Let me know if you'd like me to do anything to help identify and fix the issue.

**Comment by fommil** [comment]
I think you meant the report this on the Vim tracker. I'm on a train now, so I can't easily move it. Can you recreate there?

**Comment by geowa4** [comment]
No, I wanted to do that, but I cannot create issues in ensime-vim. 
<img width="198" alt="screen shot 2015-09-01 at 08 35 00" src="https://cloud.githubusercontent.com/assets/136390/9604263/75050a1a-5084-11e5-9873-117facbcfc06.png">

**Comment by fommil** [comment]
aah, ok, enabled now. I don't know why that was disabled.
