### ISSUE TITLE
Organize imports refactoring removes a needed import

### ISSUE THREAD

**Issue by greenrd** [ensime/ensime-server#1097]
I had `import spray.routing.Route` as one of my import lines, and it was removed, even though there was a reference to `Route` in the code.

**Comment by fommil** [comment]
I think that is an upstream bug with scala-refactoring lib. It's notoriously bad, especially if you have macros and compiler plugins anywhere near. Let me know if you'd can't find their repo on github. Actually, we should see if it is possible to upgrade.

**Comment by aij** [comment]
Would scala-refactoring also cause ENSIME to warn an import is unused even though it is used?

I had Organize Imports remove a needed import, but when I manually added it back in it says "Unused import".

In this case it is needed to compile, although it is only used in a typedef, which might be what is confusing it.
