### ISSUE TITLE
publish only a "sumo jar"

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1101]
i.e. bundle all our module together into one jar, which should make the continuous release a lot faster for end users (and easier for corporates to on-board).

@dwijnand @non how does one do this? I can't find anything about this on google.

**Comment by dwijnand** [comment]
One project that I know does (or did) this is specs2 (specs2-all.jar I think), so I would look there, hopefully it's straightforward and not a bunch of dir/file path hacked together.

**Comment by fommil** [comment]
turns out these are mythical beasts. Shame, would have been awesome!

**Comment by dwijnand** [comment]
Fwiw I'll add it to my todo list. Perhaps one day it'll be a plugin.
