### ISSUE TITLE
SExpress parsing very very slow?

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-server#1102]
Would someone try to reproduce this experiment? 

* Modify the CompletionsReq rpc handler in Analyzer.scala so that it returns a trivial, empty result. 
* Modify ensime-idle-typecheck-function (in ensime-startup.el) to do nothing.
* Boot up ensime.
* Type a string of gibberish

I see the queue of rpcs grow rapidly, wait for several seconds then sloowwlly drain. Something is wacky.
My CPU spikes to 100% and a YourKit dump yields:
![image](https://cloud.githubusercontent.com/assets/7484/10119071/16d46af4-6451-11e5-9d35-7094ec563297.png)

**Comment by aemoncannon** [comment]
That image was sorted by 'Own Time'. Here's by time:
![image](https://cloud.githubusercontent.com/assets/7484/10119076/3d2e87c0-6451-11e5-8cb4-914526c386e0.png)

Are we Thread.sleeping somewhere?? I'm confused.

**Comment by aemoncannon** [comment]
Hotspots view:
![image](https://cloud.githubusercontent.com/assets/7484/10119149/72f8b630-6453-11e5-9545-48efe8d8043b.png)

**Comment by aemoncannon** [comment]
Server log. Note: nothing but Completion requests with empty results. Also note: many seconds passing

13:43:21.170 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/46 o.e.s.RequestHandler - CompletionsReq(SourceFileInfo(/Users/aemoncannon/projects/ensime-server/core/src/main/java/org/ensime/core/javac/TreeUtilities.java,Some(...),None),7815,1000000,false,true)
13:43:21.170 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message CompletionsReq(SourceFileInfo(/Users/aemoncannon/projects/ensime-server/core/src/main/java/org/ensime/core/javac/TreeUtilities.java,Some(...),None),7815,1000000,false,true)
13:43:21.170 DEBUG akka://ENSIME/user/ensime-main/project/analyzer o.e.c.Analyzer - received handled message CompletionsReq(SourceFileInfo(/Users/aemoncannon/projects/ensime-server/core/src/main/java/org/ensime/core/javac/TreeUtilities.java,Some(...),None),7815,1000000,false,true) in state ready
13:43:21.170 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/46 o.e.s.RequestHandler - received handled message CompletionInfoList(,List()) in state receive
13:43:23.159 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/47 o.e.s.RequestHandler - CompletionsReq(SourceFileInfo(/Users/aemoncannon/projects/ensime-server/core/src/main/java/org/ensime/core/javac/TreeUtilities.java,Some(...),None),7816,1000000,false,true)
13:43:23.159 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message CompletionsReq(SourceFileInfo(/Users/aemoncannon/projects/ensime-server/core/src/main/java/org/ensime/core/javac/TreeUtilities.java,Some(...),None),7816,1000000,false,true)
13:43:23.159 DEBUG akka://ENSIME/user/ensime-main/project/analyzer o.e.c.Analyzer - received handled message CompletionsReq(SourceFileInfo(/Users/aemoncannon/projects/ensime-server/core/src/main/java/org/ensime/core/javac/TreeUtilities.java,Some(...),None),7816,1000000,false,true) in state ready
13:43:23.160 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/47 o.e.s.RequestHandler - received handled message CompletionInfoList(,List()) in state receive
13:43:25.136 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/48 o.e.s.RequestHandler - CompletionsReq(SourceFileInfo(/Users/aemoncannon/projects/ensime-server/core/src/main/java/org/ensime/core/javac/TreeUtilities.java,Some(...),None),7817,1000000,false,true)
13:43:25.137 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message CompletionsReq(SourceFileInfo(/Users/aemoncannon/projects/ensime-server/core/src/main/java/org/ensime/core/javac/TreeUtilities.java,Some(...),None),7817,1000000,false,true)
13:43:25.137 DEBUG akka://ENSIME/user/ensime-main/project/analyzer o.e.c.Analyzer - received handled message CompletionsReq(SourceFileInfo(/Users/aemoncannon/projects/ensime-server/core/src/main/java/org/ensime/core/javac/TreeUtilities.java,Some(...),None),7817,1000000,false,true) in state ready
13:43:25.137 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/48 o.e.s.RequestHandler - received handled message CompletionInfoList(,List()) in state receive
13:43:27.129 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/49 o.e.s.RequestHandler - CompletionsReq(SourceFileInfo(/Users/aemoncannon/projects/ensime-server/core/src/main/java/org/ensime/core/javac/TreeUtilities.java,Some(...),None),7818,1000000,false,true)
13:43:27.130 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message CompletionsReq(SourceFileInfo(/Users/aemoncannon/projects/ensime-server/core/src/main/java/org/ensime/core/javac/TreeUtilities.java,Some(...),None),7818,1000000,false,true)
13:43:27.130 DEBUG akka://ENSIME/user/ensime-main/project/analyzer o.e.c.Analyzer - received handled message CompletionsReq(SourceFileInfo(/Users/aemoncannon/projects/ensime-server/core/src/main/java/org/ensime/core/javac/TreeUtilities.java,Some(...),None),7818,1000000,false,true) in state ready
13:43:27.130 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/49 o.e.s.RequestHandler - received handled message CompletionInfoList(,List()) in state receive
13:43:29.111 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/50 o.e.s.RequestHandler - CompletionsReq(SourceFileInfo(/Users/aemoncannon/projects/ensime-server/core/src/main/java/org/ensime/core/javac/TreeUtilities.java,Some(...),None),7819,1000000,false,true)
13:43:29.111 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message CompletionsReq(SourceFileInfo(/Users/aemoncannon/projects/ensime-server/core/src/main/java/org/ensime/core/javac/TreeUtilities.java,Some(...),None),7819,1000000,false,true)
13:43:29.112 DEBUG akka://ENSIME/user/ensime-main/project/analyzer o.e.c.Analyzer - received handled message CompletionsReq(SourceFileInfo(/Users/aemoncannon/projects/ensime-server/core/src/main/java/org/ensime/core/javac/TreeUtilities.java,Some(...),None),7819,1000000,false,true) in state ready
13:43:29.112 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/50 o.e.s.RequestHandler - received handled message CompletionInfoList(,List()) in state receive
13:43:31.076 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/51 o.e.s.RequestHandler - CompletionsReq(SourceFileInfo(/Users/aemoncannon/projects/ensime-server/core/src/main/java/org/ensime/core/javac/TreeUtilities.java,Some(...),None),7822,1000000,false,true)
13:43:31.077 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message CompletionsReq(SourceFileInfo(/Users/aemoncannon/projects/ensime-server/core/src/main/java/org/ensime/core/javac/TreeUtilities.java,Some(...),None),7822,1000000,false,true)
13:43:31.077 DEBUG akka://ENSIME/user/ensime-main/project/analyzer o.e.c.Analyzer - received handled message CompletionsReq(SourceFileInfo(/Users/aemoncannon/projects/ensime-server/core/src/main/java/org/ensime/core/javac/TreeUtilities.java,Some(...),None),7822,1000000,false,true) in state ready
13:43:31.077 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/51 o.e.s.RequestHandler - received handled message CompletionInfoList(,List()) in state receive

**Comment by aemoncannon** [comment]
Ohhhhhh. 
Duh.
I forgot were sending the *entire fucking file* in the request.
Still, this is way too slow.

**Comment by aemoncannon** [comment]
I'm going to try the 'write to temp file and read in server' strategy (which we already support) and see if it scales better for this source file. By the way, the file is only 1000 lines. The problem is that we're shoving 1000 lines through a parser that is carefully scrutinizing each character, looking for escapes and delimiters.

**Comment by aemoncannon** [comment]
Then again, the scala compiler has to do that, anyway. Hmm. Maybe parboiled is just really slow?

**Comment by rorygraves** [comment]
Cool analysis - we might be missing some parsing tuning in parboiled.

**Comment by aemoncannon** [comment]
Will ping back with result of experiment. Apologies for getting so worked up. Performance regressions make me sad : (

**Comment by rorygraves** [comment]
No need to apologise this is important stuff.

**Comment by fommil** [comment]
Uugg, that sucks. I have an open ticket under "loose ends" for sexpress that might capture this. That said, @sirthius did rewrite spray-json to be zero dependency AND were on the old version of parboiled. An upgrade to parboiled2 might be fruitful. If you could create a good test case, it'd make my job of tying up the loose ends a lot easier (this will be my priority after I manage to onboard ENSIME at my new job, oh and after my 3 week holiday as of Monday :smile:)

**Comment by fommil** [comment]
(Priority is because this is all related to my scalax talk in Dec. Actually for ENSIME, everything under the 1.0 milestone is what I'd rather work on)

**Comment by aemoncannon** [comment]
Enjoy your holiday!

I did the write-to-temp-file experiment and it did the trick. Queue doesn't grow at all (for no op requests) which is what we want. I'll probably push a PR to make that change for emacs, as it seems to be a nice 'feel' improvement for big files.

**Comment by fommil** [comment]
@rorygraves what are your thoughts on temp files for comms? I'm actually OK with it, and I'd like us to move towards a .diff approach for refactorings, which lends itself well to temp files.

**Comment by aemoncannon** [comment]
Couple random ideas:
* maybe have support for a fixed-length buffer syntax in reader.
* or, a 'channel' id, and we write the file to the channel socket concurrently, where the server will hold it until the id is requested. I think SLIME has something like this.

Honestly writing to temp file doesn't bother me so much.

**Comment by fommil** [comment]
:+1: for writing to files. I'll fix the perf issue for the wire protocol when I come back. How does jerky handle it? Good or merely better?

**Comment by rorygraves** [comment]
I'm ok with temp file writing as a quick fix, - esp as we already support it. 
We should fix the parser as asap.  Interesting about the channel concept.

**Comment by sirthias** [comment]
Without having looked any deeper into the source of the problem here I can say that a potential upgrade from parboiled 1 to parboiled 2 would give you a roughly 10-fold parsing performance increase.
How complex is the parser?

**Comment by rorygraves** [comment]
Parser is here - https://github.com/ensime/ensime-server/blob/master/sexpress/src/main/scala/org/ensime/sexp/SexpParser.scala

I don't think its complex - will try and update it to parboiled 2 in the next few days

**Comment by sirthias** [comment]
Yes, this looks very doable in parboiled 2.
You should see a very nice speedup from the migration.
Let me know if you need support with the migration!
Also, ping me when you are done. I'll have a quick look over your implementation and maybe suggest a few more perf tweaks...

**Comment by rorygraves** [comment]
@sirthias Thanks for the offer - I will be sure to take you up on it :smiley:

**Comment by rorygraves** [comment]
https://github.com/ensime/ensime-server/pull/1238

**Comment by rorygraves** [comment]
We are now fully on PB2 since #1253

**Comment by aemoncannon** [comment]
We should compare parsing time for bug file contents w.r.t above. I can do
tonight mayhaps..

**Comment by fommil** [comment]
I prefer insect files.
