### ISSUE TITLE
remove debug launcher, only attach

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1105]
@rorygraves I started some work on this in this branch https://github.com/fommil/ensime-server/tree/debug_attach it is very nearly ready to be used. Basically we're saying we only support attach mode debugging sessions. However, we still need a way to launch JVMs in the tests, so I've been trying to get the java `Process` stuff to work, but it is pretty flakey (no ephemeral ports, and I keep seeing duplicate messages when connecting to the "remote" JVM). Maybe you could take a look and build on this?

This might need some additional tweaks on OS X and Windows.

If the emacs tests fail, it's probably because we're using the `debug-start` for testing. That can probably be fixed quite easily, but feel free to wait for me to return from holidays to do it.

btw, this makes #1067 redundant.

**Comment by aemoncannon** [comment]
Do we need to remove the debug-start support entirely? It might be a nice
backdoor to have for people without build support for launching in debug
mode...

**Comment by fommil** [comment]
We could keep it if you think someone's going to use it, but I'm always keen to remove functionality that nobody is using. It probably just depends on how the future of the debugging support goes: I seen a few people chatting on the gitter channel about some ideas that had in that area.

**Comment by rorygraves** [comment]
Ok, I've been thinking about this - especially with respect to the ongoing stuff in the gitter channel as well - (I'm going to do a more detailed writeup there) - but I think we should actually support both modes (in the server side) but potentially disable the Ensime launch command within emacs.  There is at least one major bug with source mapping within the debugger at the moment that exists in both modes (back mapping of line numbers to source is calculated once on startup and never refreshed).
