### ISSUE TITLE
set up github autoresponder

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1115]
it would be good if we had a github auto responder that basically responded to all new tickets with a polite reminder of everything in `CONTRIBUTING.md`:

* check FAQ
* check latest tickets
* if this is a bug, provide reproducible test case in form of github project

no such (easily found) third party service exists, so this might mean coding up a small standalone spray or akka-http app to do the auto responding through the github API. We can host it on fommil.com.

**Comment by SethTisue** [comment]
you might take a look at https://github.com/scala/scabot and see what you can raid. it's a little Akka app that handles similar duties in the scala/scala repo. at minimum, the part of the code that talks to the GitHub API would be useful, I think.

lots of other projects, even within Typesafe & EPFL, have similar things — if there's been any unification effort on this, I'm unaware of it

**Comment by fommil** [comment]
great! Although I know zero play, so this might be impenetrable for me. I'll try to learn as much from it as I can.

**Comment by SethTisue** [comment]
you're unlikely to bump your head on any Play code; the Play stuff is late addition and is only there to support an experimental web UI that doesn't have much to do with the rest of the code. communication with GitHub is done with Spray.

**Comment by SethTisue** [comment]
(it makes only light use of Play API's, so you probably won't bump your head there)

**Comment by fommil** [comment]
closed in light of new github changes
