### ISSUE TITLE
ensime-update can't find org-netbeans-modules-java-source;RELEASE731

### ISSUE THREAD

**Issue by gempesaw** [ensime/ensime-server#1126]
Hullo, my `ensime-update` is having trouble, exiting with exit code `1` due to being unable to find some package

```
[info] Resolving jline#jline;2.12 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.netbeans.api#org-netbeans-api-java;RELEASE731: not found
[warn] 	:: org.netbeans.api#org-netbeans-modules-java-source;RELEASE731: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.netbeans.api:org-netbeans-api-java:RELEASE731
[warn] 		  +- org.ensime:core_2.11:0.9.10-SNAPSHOT
[warn] 		  +- org.ensime:server_2.11:0.9.10-SNAPSHOT
[warn] 		  +- org.ensime:ensime_2.11:0.9.10-SNAPSHOT (/private/var/folders/19/fy4zlkw13c160qyl6h5px_dh55vrly/T/ensime_update_51643GLw/build.sbt#L19-20)
[warn] 		  +- default:ensime_update_51643glw_2.11:0.1-SNAPSHOT
[warn] 		org.netbeans.api:org-netbeans-modules-java-source:RELEASE731
[warn] 		  +- org.ensime:core_2.11:0.9.10-SNAPSHOT
[warn] 		  +- org.ensime:server_2.11:0.9.10-SNAPSHOT
[warn] 		  +- org.ensime:ensime_2.11:0.9.10-SNAPSHOT (/private/var/folders/19/fy4zlkw13c160qyl6h5px_dh55vrly/T/ensime_update_51643GLw/build.sbt#L19-20)
[warn] 		  +- default:ensime_update_51643glw_2.11:0.1-SNAPSHOT
sbt.ResolveException: unresolved dependency: org.netbeans.api#org-netbeans-api-java;RELEASE731: not found
unresolved dependency: org.netbeans.api#org-netbeans-modules-java-source;RELEASE731: not found
```

My `~/.sbt/0.13/plugins/plugins.sbt` only contains

```
addSbtPlugin("org.ensime" % "ensime-sbt" % "0.2.1")
```

The project's `build.sbt` is

```
enablePlugins(GatlingPlugin)

scalaVersion := "2.11.5"

scalacOptions := Seq(
  "-encoding", "UTF-8", "-target:jvm-1.7", "-deprecation",
  "-feature", "-unchecked", "-language:implicitConversions", "-language:postfixOps")

libraryDependencies += "io.gatling.highcharts" % "gatling-charts-highcharts" % "2.1.7" % "test"
libraryDependencies += "io.gatling"            % "gatling-test-framework"    % "2.1.7" % "test"
```

So far in my flailing, I've deleted and re-created the `.ensime` file with `sbt gen-ensime`, deleted `.ensime_cache` in the project folder, I deleted `~/.ivy2/cache/org.ensime` and eventually the entire `~/.ivy2/cache` folder, all to no avail. 

Also, many thanks for ensime, I find it to be quite invaluable for my scala coding & I'm eagerly awaiting the Java branch as well!

**Comment by gempesaw** [comment]
err... okay, I guess for google's sake good thing I bothered to write it up. My `sbt` was installed via `homebrew` and was `0.13.8`; updating via `brew upgrade sbt` to `0.13.9` has done away with this error message.

**Comment by adamchandra** [comment]
I got this error even when using sbt 0.13.9. I hacked around it by adding the neatbeans libraries to my project dependencies (along with the appropriate netbeans repo), which fetched the libraries into my local .m2 directory. Once they were locally cached, ensime-update was able to resolve everything.

Here's what I used in my build.sbt:

resolvers += "Netbeans" at "http://bits.netbeans.org/nexus/content/groups"

libraryDependencies ++= Seq(
"org.netbeans.api" % "org-netbeans-api-java" % "RELEASE731",
"org.netbeans.api" % "org-netbeans-modules-java-source" % "RELEASE731"
)

**Comment by fommil** [comment]
@adamchandra sounds like you have some user-level config setup to use maven cache instead of ivy cache. It should be downloaded to `~/.ivy2`

**Comment by fommil** [comment]
@gempesaw interesting, we explicitly set the version of sbt to 0.13.9, your script version shouldn't matter. https://github.com/ensime/ensime-emacs/blob/master/ensime-startup.el#L231

**Comment by fommil** [comment]
@adamchandra actually, sounds like you haven't upgraded the client code yet. Are you using Emacs?

**Comment by adamchandra** [comment]
@fommil yes, I'm using emacs. I'll try updating the client code.

**Comment by fommil** [comment]
@adamchandra btw, you only need to update the emacs code. It automatically updates the server.

**Comment by adamchandra** [comment]
@fommil thank you, the root of my problem was updating the ensime server manually without updating the client code,  everything works properly now.

**Comment by jarandaf** [comment]
Not sure how this relates to `ensime-vim`, but I am also getting the same problem.

**Comment by fommil** [comment]
ensime-vim has its own issue tracker

**Comment by morgen-peschke** [comment]
I'm also having this issue. In my case the update was initiated by the emacs client.

Is there a workaround that does not involve adding to the project dependencies? I'm having this issue on a shared project. I doubt my collaborators would appreciate additional dependencies to accommodate my preference for Ensime over another IDE :)

**Comment by umhan35** [comment]
Uh... I'm having the same issue...
