### ISSUE TITLE
Show how two classes are related

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1128]
It'd be a great code exploration tool to be able to see the method calls and plumbing classes that are navigated to link two classes together. Extremely useful for large corporate codebases (many a week has been spent in such Archaeology)

**Comment by aemoncannon** [comment]
Cool idea. Likewise: paths between packages

**Comment by matanster** [comment]
I've [implemented this in scala](https://github.com/CANVE/extractor/blob/81143a1fa9025643d43d8d15b974387c98f474f3/compiler-plugin/src/test/scala/extractor/Instantiaion.scala#L71-L77) if it helps in any way, through a [special traverser] (https://github.com/CANVE/extractor/blob/master/simple-graph/src/main/scala/org/canve/simpleGraph/algo/impl/GetPathsBetween.scala). This is really simple once you settle on what types of relationships a path between object A and object B is allowed to be composed of. 

This is part of [simple-graph](https://github.com/CANVE/extractor/tree/master/simple-graph) which I have to clean up a little as I go.

**Comment by fommil** [comment]
cool, thanks. I think there are some `A*` implementations in the graph database that we're using.
