### ISSUE TITLE
Allow specifying bind address and a fixed port

### ISSUE THREAD

**Issue by lucasmundim** [ensime/ensime-server#1146]
It would be nice to be able to specify a bind address other than 127.0.0.1 and a fixed port instead of a random one.

It'll help running ensime server with docker.

**Comment by fommil** [comment]
This then becomes a security issue. I've made promises that ENSIME can only run out localhost the pass security reviews, but I see your usecase with docker. This is something we'd prefer to support with a server config file, not the .ensime file.

**Comment by fommil** [comment]
you should be able to specific a specific port now by writing out the files before starting the server, but we are never going to bind to anything other than `127.0.0.1` for security reasons. You can set up routing in your container if you wish to achieve that.
