### ISSUE TITLE
add the acyclic plugin

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1148]
improve the quality of things: https://github.com/lihaoyi/acyclic

**Comment by lukasz-golebiewski** [comment]
@fommil Do you want to add the `acyclic.file` import to all files/packages?

**Comment by fommil** [comment]
I don't really know how the plugin works but removing acyclic dependencies sounds like a good idea.

**Comment by fommil** [comment]
knowing what is acyclic would be a good first move.

**Comment by lukasz-golebiewski** [comment]
But this requires adding an explicit import to all classes / package objects :/
