### ISSUE TITLE
Analyzer per module

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1152]
I'm working on a project that has different `scalacOptions` per module, and some modules have compiler plugins and others don't. To fix this (and get limited scope contextual completions) it would be good if each module had its own analyzer.

However, some problems with this:
1. potentially huge drain on heap usage
2. how do we handle cross-module refactorings? Maybe each refactor needs its own throwaway presentation compiler which loads all necessary source files

**Comment by fommil** [comment]
scala-ide say they use a watchdog that closes presentation compilers if they have not been used for 20 seconds and it works well. That could work.

**Comment by balajisivaraman** [comment]
As discussed on Gitter with @fommil, I'll be happy to try and fix this issue once I'm comfortable enough with the Ensime Server codebase.

**Comment by fommil** [comment]
an interesting impact of fixing this would be that macros should be a lot better in ensime! Because macros don't work in the same presentation compiler that loads them.

**Comment by rorygraves** [comment]
Unless one of the PCs is doing full compilation to bytecode how is the second PC going to apply the macro?  Am I missing something?

**Comment by fommil** [comment]
Sbt does the compiling, second one picks it up

**Comment by fommil** [comment]
another thing that we could do as part of this refactor (perhaps we'll create a new ticket) would be to monitor PC actors with heartbeats and basically throw them away / kill them if they disappear for more than 30 seconds. We would need to keep a count of how many PCs are still "being killed" so that we don't blow up the heap. This could be accompanied with an async message to users to let them know that they maybe need to introduce some `cachedImplicit`s or something.
