### ISSUE TITLE
false positive error: "<artifact> is defined twice  conflicting both originated in..."

### ISSUE THREAD

**Issue by gaydenko** [ensime/ensime-server#1159]
After today updating of `ensime-emacs` to `ensime-20151117.2103` starting of editing of any file results in the error, where atifact can be a method, a val or even internal method as `$init$`. The issue doesn't depend on the code under editing. Say, this simple project https://github.com/gaydenko/temp01 is also affected by the issue. ensime-sbt 0.2.1 is in use as a global plugin. Java is Oracle one build 1.8.0_66-b17. Scala is 2.11.7.

Have tried without success:
- to clean ensime_cache
- to redownload the world by deleting ~/.ivy2

Few last commits are related to file manipulation, and it can be a reason of accounting the same file twice. Crazy idea is if developers use, say, Mac treating file manipulation different in comparison with, say, Linux.

**Comment by fommil** [comment]
asked reporter to repost to ensime-emacs
