### ISSUE TITLE
Google Summer of Code

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1161]
@aemoncannon you obviously know about these :smile:

  https://developers.google.com/open-source/gsoc/faq

how much work is it to put in an application? If we could find a willing student it might be really good. Doesn't have to be limited to the server, could even be a case of getting one of the other editors up to par with Emacs.

**Comment by aemoncannon** [comment]
Relavent timeline here:
8 February, 2016 19:00 UTC	Mentoring organizations can begin submitting applications to Google.
19 February 19:00 UTC	Mentoring organization application deadline.
20 February - 26 February	Google program administrators review organization applications.
29 February 19:00 UTC	List of accepted mentoring organizations published on the Google Summer of Code 2016 site.

**Comment by aemoncannon** [comment]
Looks like there's a place on mentor application for established orgs to mention up-and-comers. That would be helpful.

Also 'most important' part is the Idea List. That should be *no* problem.

**Comment by fommil** [comment]
I've put the feelers out on twitter. Let's see what comes back in terms of students.

**Comment by sugakandrey** [comment]
I'm very interested in participating. Currently in the third year pursuing my CS degree, long time emacs user and been using ensime to write scala for a year more or less. Would be glad to be of any help.

**Comment by fommil** [comment]
Sweet!

**Comment by fommil** [comment]
Apparently the deadlines are coming up soon https://developers.google.com/open-source/gsoc/timeline

We have until the 19 February to submit applications.

@sugakandrey you're basically the only person who has registered interest, so it's up to you to make some suggestions for the topic :smile: If you draw a blank, we can help out. I'd recommend thinking about what your dream feature or integration in ENSIME would be.

**Comment by sugakandrey** [comment]
Right now I'm a little bit busy with the upcoming exams, but will try to come up with something as soon as I get some spare time, which will hopefully be soon.

**Comment by ChavXO** [comment]
I'd be interested at well. Where can we post ideas for suggestions?

**Comment by fommil** [comment]
Here is good, or gitter / email

**Comment by fommil** [comment]
all ! ping

without project ideas, we can't submit anything

**Comment by sugakandrey** [comment]
I'm sorry for being inactive, but I have finally finished my exams and willing to move on with this. Any directions I should follow, when coming up with project idea? Pretty much every editor seems to have been integrated already (Emacs, Vim, ST,  Atom, etc), is there anything on the ensime-server side that needs improving? Also, what should the scale of the project be?

**Comment by fommil** [comment]
Actually only really Emacs is "fully functional".

@aemoncannon / @rorygraves ?

Probably there would need to be a theme, E.g. improved debugger or integration with coverage / style checkers. The graphpocaypse would have been a good one, but that should be finished before the summer. Maybe there could be some extra analysis we could do on top of that data.

**Comment by aemoncannon** [comment]
Isn't there a scala linting framework? Would be cool to see those pop up as warnings in the editor.

also simple, fast, local static analysis. like: hey you're not handling this null.

+1 for graph analysis on top of graph indexer. for example: if you could pop up a graphviz graph of the communities or connected components that'd be neat.

a good and v. practical end2end project:  surfacing doc excerpts in the editors.

a framework for suggestions. could go hand in hand with the linting above.

hoogle-style type search integration -- i'm not sure I think this is v. useful, but some people love it!

robust support for profiling in the wild and a privacy-sensitive way for us to aggregate and learn from that data.

decompiling!

**Comment by fommil** [comment]
doh! yes, actually search for the [OMG Ponies](https://github.com/ensime/ensime-server/issues?q=is%3Aopen+is%3Aissue+label%3A%22OMG%21+Ponies%21%22) tag for all our favourite ideas.

Definitely #848 and  #472 as Aemon suggests, would be brilliant (#1173 might be of wider interest too)

**Comment by fommil** [comment]
*sigh* I really need to get past all my firefighting with windows and write that damn graphpocalypse. I was sooo close when I got distracted.

**Comment by sugakandrey** [comment]
Alright, I'll take a closer look at those.

**Comment by sugakandrey** [comment]
#888 is perhaps the feature I miss the most in ensime, it is in my top 5 most used IntelliJ features too. 
#472 seems interesting too. Hoogle has been an immense timesaver, when writing haskell, and having something like that directly in your editor would be sweet.

**Comment by aemoncannon** [comment]
+1 for #888. This would benefit everyone and there are some fun problems in there like how to cleanly scrape the excerpt in a way that can be displayed in n editors, and how to scrape docs from source code when we don't have a doc jar.

**Comment by fommil** [comment]
OK, great! What do we do next @aemoncannon ? I'm happy to draft/edit any proposals that we have to write

**Comment by aemoncannon** [comment]
Applications don't open for another couple days but maybe we could think about:
* Who wants to be a mentor? http://en.flossmanuals.net/GSoCMentoring/what-makes-a-good-mentor/
     Sadly I don't think I can commit to the time investment right now. (Also I work at google which might be weird?)
* What projects can we ask to endorse us (previous years participating organizations) https://www.google-melange.com/gsoc/org/list/public/google/gsoc2015
(at the very least we could probably get scala team to speak for us)

**Comment by fommil** [comment]
if its just a couple of hours a week, I can do that. I very narrowly dodged a permanent career in management a few years ago, so I know how this works :-P

**Comment by aemoncannon** [comment]
It says to be prepared for 10* hours / week

* my mentor didn't spend that amount of time :-)

**Comment by fommil** [comment]
@sugakandrey please keep pestering me to do my part in writing the proposal.

**Comment by fommil** [comment]
@sugakandrey the only thing to be wary of is that I'm UK Timezone and I can only really talk in the evenings, which will be quite late for you in Russia :-/

**Comment by sugakandrey** [comment]
@fommil I tend to stay up late anyways, so that shouldn't be much of a problem.

**Comment by fommil** [comment]
yeah, so that might be like 11pm or midnight for you when I come online :-/

I might be able to get up early some days, and also weekends. I'll also be able to answer quick questions on my phone during the day (and probably reply on tickets in github)

**Comment by sugakandrey** [comment]
If you ask me, this should work out just fine.

**Comment by sugakandrey** [comment]
@fommil  So how is it going with the proposal?

**Comment by fommil** [comment]
Uuuh, not started yet sorry. I should download the templates.

**Comment by fommil** [comment]
we have to put together an organisation proposal first, which means creating an ideas page. @sugakandrey can you help out here by sending a PR to https://github.com/ensime/ensime.github.io/ with a new page under a "contributing" folder? No need to link it up to the main site, it can be a dangling page.

**Comment by fommil** [comment]
@sugakandrey (doesn't need to be a final document in any shape or form, just to get the ball rolling... we'll edit it to make it shiny)

**Comment by sugakandrey** [comment]
@fommil Sure, I'll get on it tomorrow, alright? Have to wake up early tomorrow, so gonna get some sleep now :)

**Comment by sugakandrey** [comment]
@fommil You wanted me to keep pestering you, so I just have to remind, that according to the [GSoC Timeline](https://developers.google.com/open-source/gsoc/timeline) we only have 5 days left to submit an application.

**Comment by fommil** [comment]
@sugakandrey actually it's 5 days to submit an organisation application, the idea proposal comes later. We are on it :smile: @rorygraves is going to finish off what I started.

**Comment by sugakandrey** [comment]
@fommil Alright then, my bad :)

**Comment by rorygraves** [comment]
Yep - its in progress.

**Comment by fommil** [comment]
"Housekeeping" is definitely the wrong milestone! :rocket: milestone...

**Comment by fommil** [comment]
@sugakandrey just a heads up that it looks like ensime submits to be an organisation, then you submit to google to be a student (if we're accepted)... so there are still many hurdles and I don't want you to get your hopes up too much.

**Comment by fommil** [comment]
we've really filled out the most strategic ideas here: http://ensime.github.io/contributing/ideas/

(There is an argument to drop the bottom two, as they sound quite weak next to the bigger proposals... what do you say @rorygraves ?).

We're going in under the banner of EPFL / Scala rather than ENSIME organisation. This should dramatically increase our chances of getting funded, but it also means that Java-specific features are unlikely to be of interest. It seems like a fair trade off.

@sugakandrey the process is much less in our hands now, so the best I can do is encourage you to apply through the official Google Summer of Code mechanism and wish you all the best of luck! :smile:
