### ISSUE TITLE
Search in javadocs 

### ISSUE THREAD

**Issue by ancane** [ensime/ensime-server#1173]
1. Create and implement an API endpoit that takes a search term and returns a list of javadoc URLs.
2. Implement the search bar in HTTP server. 

Related to #472

**Comment by fommil** [comment]
Excellent opportunity to write some code that targets the JavaScript engine :smile: (Racket!)

**Comment by fommil** [comment]
actually if we want search to work *inside* the docs, that will require a whole load of work in the server side. Supporting just the class / member search should be feasible though.
