### ISSUE TITLE
SWANKY (over WebSockets)

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1189]
can't believe we didn't have a ticket for this.

**Comment by fommil** [comment]
oh, we did have this: #834 but that is also a more general refactor of the actual protocol itself too.

**Comment by fommil** [comment]
this will involve deprecating the FamilyFormats and creating a spray-json-shapless style thing for s-express. Then well gradually migrate Emacs to SWANKY and Sublime to JERKY.

**Comment by fommil** [comment]
I've started working on this in https://github.com/fommil/ensime-server/tree/swanky

I debated in my head how general this should be: support for `nil`s and alists and so on, and I decided just to go for the principle of least power and support only a minimal set of features for `SexpData` style formats (not alists). If we decide that alists are definitely preferable on the client side and worth breaking the `.ensime` format for, then we can reassess.

**Comment by aemoncannon** [comment]
lgtm so far!  I'm indifferent about alists.
