### ISSUE TITLE
correctly index methods by FQN and Descriptor

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1190]
I'm currently working on this as part of the Graphpocalyse but it might make sense to split this out as a separate piece of work and support it in H2 first of all.

We can trivially get the FQN and Descriptor from the bytecode, but getting it from the scalac `Symbol` is tricky.

`Helpers.symbolIndexerName` and `DocFinding.javaFqn` should really be sharing the same logic, which could be implemented in the `FullyQualifiedName` domain model... and then translated into `Descriptor`s (logic exists) and `DocFqn`s.

In any case, my WIP is in this general area https://github.com/fommil/ensime-server/blob/graphpocalypse/core/src/main/scala/org/ensime/model/Helpers.scala#L128

And there are a bunch of other places in the code where we do something similar, so obviously there is a good opportunity for code reuse. I wonder how Scala IDE does this, if it does it at all. Surely `scalac` knows how to do this in the bytecode output layers.

**Comment by fommil** [comment]
@VlachJosef btw this is related to the problem with jumping to method sources, I think.

**Comment by fommil** [comment]
good old `scala.meta`
https://github.com/scalameta/scalameta/blob/master/scalahost/src/main/scala/scala/meta/internal/hosts/scalac/reflect/Platform.scala

**Comment by fommil** [comment]
my WIP is in https://github.com/fommil/ensime-server/tree/index_method_descriptors

which now really clarifies the distinct graphpocalypse changes (I'll come back to it after fixing this)

https://github.com/fommil/ensime-server/tree/graphpocalypse

**Comment by fommil** [comment]
and also https://github.com/lihaoyi/Metascala/blob/master/src/main/scala/metascala/imm/Type.scala#L48-L52

**Comment by fommil** [comment]
https://github.com/scala-ide/scala-ide/blob/master/org.scala-ide.sdt.core/src/org/scalaide/core/internal/jdt/model/ScalaStructureBuilder.scala

**Comment by fommil** [comment]
Jason says this is how to do it in 2.12

```scala
scala> val sym = typeOf[List[String]].member(TermName("foldLeft"))
sym: $r.intp.global.Symbol = method foldLeft

scala> exitingPostErasure(genBCode.bTypes.methodBTypeFromSymbol(sym).descriptor)
res5: String = (Ljava/lang/Object;Lscala/Function2;)Ljava/lang/Object;
```

**Comment by fommil** [comment]
@paulp apologies for pinging. We'd like to resolve FQNs for `scala.tools.scalap.scalax.rules.scalasig.Symbol` as well as `scala.reflect.internal.Symbols.Symbol`. It would be convenient to turn the latter into the former, to avoid duplicating the effort.

You probably know this code better than most https://github.com/scala/scala/blob/2.11.x/src/scalap/scala/tools/scalap/scalax/rules/scalasig/Symbol.scala so I thought it best to ask:

1. do you know how to turn a `Symbols.Symbol` into a `scalasig.Symbol`?
2. do you know how to get the Java FQN from the latter?

**Comment by fommil** [comment]
some progress (at least for `Symbols.Symbol`)

- https://github.com/fommil/ensime-server/blob/index_method_descriptors/core/src/main/scala/org/ensime/core/SymbolToFqn.scala
- https://github.com/fommil/ensime-server/blob/index_method_descriptors/core/src/it/scala/org/ensime/core/SymbolToFqnSpec.scala

I'm a bit confused about what to do for `scala.Boolean` and co vs their primitives. I wonder if those signatures ever actually appear in method signatures.

**Comment by sschaef** [comment]
What is the confusion regarding `scala.Boolean`?

**Comment by fommil** [comment]
I don't know when to resolve them and when not to. They aren't completly erased into primitives.

**Comment by paulp** [comment]
Other than to wonder if you've seen `def javaClassName` I can't comment except to say this code has been written a hundred times but never yet correctly.

`scala/Boolean` will never appear in a correct jvm-level descriptor or signature. It's `Z` in a position where a primitive type can appear (e.g. method parameter type or return type) and `java/lang/Object` where it can't - type argument.

**Comment by fommil** [comment]
@paulp no, I had not seen that, looking into it. I don't know how I missed that. It doesn't solve everything but it might save me a few lines of code (I think). Is `javaClassName` "broken"?

I was thinking along similar lines re: `Boolean`. But, there is also the case where the user really wants to see the methods on `Boolean` in which case we **do** want to see something like `scala.Boolean.&&` (ok, maybe not because they'd be pretty clueless users, but they might be interested in the docs. OK, so its a corner case... I'll just always resolve to `boolean`).

**Comment by paulp** [comment]
In principle `javaClassName` (which should just be `javaBinaryName.toString`) is as close to canonical as you will find, since it's the method used in bytecode generation. Probably you can still be burned by phase issues.

**Comment by fommil** [comment]
@paulp oh joy. And any ideas on the pickler side?

**Comment by paulp** [comment]
Not sure what you mean by the pickler side, but I think that even if I could help you on that point I wouldn't because I do not wish to be an enabler. My helpfulness streak sometimes gets the better of me, but only briefly.

**Comment by fommil** [comment]
@paulp cheers anyway, by pickler I meant `scala.tools.scalap.scalax.rules.scalasig.Symbol`

**Comment by paulp** [comment]
AFAIK that's just yet another re-encoding of the symbol structure. It might only exist to get around the nightmare of the global-internal path-dependent types. But all that code predates me and has barely been touched in maybe ten years.

**Comment by fommil** [comment]
indeed it is. And, of course, the only way to create an instance seems to be to enter the `Pickler` phase, create some `Array[Byte]`s, and then parse it again. Joy. Going the other way would appear to involve loading every symbol into a presentation compiler that has access to the bytes or sources, which would probably blow up the heap on any desktop machine for a big project.

**Comment by fommil** [comment]
int/boolean example `scala.Int.$plus(I)I` (the FQN of "plus" between two integers) Simple rule can be: always resolve to a primitive, unless its the base class name of a method.

**Comment by fommil** [comment]
wo0t! @aemoncannon check out this

- https://github.com/fommil/ensime-server/blob/index_method_descriptors/core/src/main/scala/org/ensime/core/SymbolToFqn.scala
- https://github.com/fommil/ensime-server/blob/index_method_descriptors/core/src/it/scala/org/ensime/core/SymbolToFqnSpec.scala

and I can now see why the logic can't be fully shared with the doc finding, because there are weird rules like going to the exact class's method, instead of where it is implemented. But there still might be some room for sharing.

I still need to finish this off for `Symbols.Symbol`, but it's coming along nicely. Then I'll have a go at doing something similar for `scalasig.Symbol`... which should be a lot easier to test.

**Comment by rorygraves** [comment]
Cool stuff

**Comment by aemoncannon** [comment]
Awesome! Will take a look soon. Will this format be public, e.g. exposed
via symbol-by-name at some point?

**Comment by fommil** [comment]
I think I've ended up fixing https://github.com/ensime/ensime-server/issues/635 while doing this. My branch is still WIP but I've got nice behaviours and tests around:

- Symbol => FQN
- Type => Symbol => FQN
- FQN => Symbol

where FQN is a structured ADT.

**Comment by rorygraves** [comment]
Nice!

**Comment by fommil** [comment]
at this point, either I "fix" the implementation to match what the tests expect (which I think are broken)  or update the tests to test the right thing. I'm going to do the latter. This is probably going to be a reasonably big change.

**Comment by rorygraves** [comment]
Never break the code to meet the test if the test is broken....
