### ISSUE TITLE
Bug in a rename function id  refactor request

### ISSUE THREAD

**Issue by lxol** [ensime/ensime-server#1194]
A refactor rename request produces a wrong result for a function id when param's opening and closing parentheses are on different lines.  
For example the snippets below is an attempt to rename `doIt` to `doItNow`
```` scala
package org.ensime.testing
trait Foo {
def doIt(
) = "foo"
}
````

```` scala
package org.ensime.testing
trait Foo {
def doItNow(
 = "foo"
}
````

I will submit a reproduction ignored test for the issue.

**Comment by fommil** [comment]
hmm, this is probably an upstream bug with scala-refactoring. Can you please re-raise with them, the failing test case is good!

**Comment by lxol** [comment]
done
https://github.com/scala-ide/scala-refactoring/issues/119

**Comment by lxol** [comment]
https://github.com/scala-ide/scala-refactoring/pull/121
