### ISSUE TITLE
Force downloading of javadocs?

### ISSUE THREAD

**Issue by fosskers** [ensime/ensime-server#1197]
I'm working on an application that needs access to Google's APIs. It does this via [Google APIs Client Library for Java](https://developers.google.com/api-client-library/java/).

I've added the following to the `libraryDependencies` list in my `build.sbt`:

```
  "com.google.api-client" % "google-api-client" % "1.20.0",
  "com.google.apis" % "google-api-services-compute" % "v1-rev88-1.21.0"
```

Now, in a source file, I import the following:
```scala
import com.google.api.client.googleapis.auth.oauth2.GoogleCredential
```
which compiles. The trouble is, the ensime typechecker tells me: `ERROR: object googleapis is not a member of package com.google.api.client`. It tells me this even if I remove my `.ensime_cache` and let it typecheck the whole project again. Could this be because `ensime` hasn't downloaded the docs for that library? (confirmed by checking `ensime-project-docs` in emacs) If so, is there a way to force said downloading?

I've been using ensime for a month or so over three projects and this is the first time this has happened to me.

EDIT: I just updated `ensime` through `list-packages`, and the problem persists.

**Comment by fommil** [comment]
The tool that generates your .ensime is responsible for doing this. ensime-sbt does it.

**Comment by fommil** [comment]
but, it just sounds like you need to regenerate your `.ensime` and then restart ensime. BTW, these kinds of tickets are best raised on the client that you're using, not the server.

**Comment by fosskers** [comment]
Thank you, I'll keep that in mind. I has assumed it was some problem with the underlying server, hence I opened it here.

**Comment by fommil** [comment]
thing is, if you report problems on the server, nobody knows which client you're using. ENSIME is not just about Emacs anymore... actually we have more Sublime and Atom users these days than Emacs users.

**Comment by fosskers** [comment]
Ok, it worked. I did `gen-ensime` within `sbt`, and that pulled down what I need. Thanks again.
