### ISSUE TITLE
Java completions shouldn't contain private functions

### ISSUE THREAD

**Issue by tanzoniteblack** [ensime/ensime-server#1198]
When using ensime to work on Java files (which I know is still in alpha), the completions list contain private functions for other objects.

This is not true when working with autocompletions for Java objects from within a scala file.

**Comment by fommil** [comment]
yeah, we should probably filter by ability to see the symbol. Does our scala mode handle this correctly?

**Comment by tanzoniteblack** [comment]
The scala mode handles it correctly.

**Comment by aemoncannon** [comment]
Good catch! Should be a pretty easy change

**Comment by aemoncannon** [comment]
@tanzoniteblack, want to take a crack at this?

**Comment by tanzoniteblack** [comment]
Sure. I'll take a look when I get a chance. Probably sometime tomorrow.

**Comment by tanzoniteblack** [comment]
@aemoncannon I have some tests sitting on a branch (https://github.com/ensime/ensime-server/compare/master...tanzoniteblack:java-private-completions?expand=1), but it's not immediately obvious to me how to actually filter out the privates.
