### ISSUE TITLE
Java symbol at point doesn't work at beginning of word

### ISSUE THREAD

**Issue by tanzoniteblack** [ensime/ensime-server#1199]
Using `|` to represent cursor position, running the ensime-emacs command `ensime-rpc-symbol-at-point` in java-mode at `|UserDetails` returns `nil`, while running it at `U|serDetails`, `UserDetails|`, or anywhere else inside the symbol, returns valid information. This works as I would expect in scala-mode.

I'm filing this bug against ensime-server, since it looks like this emacs function is just a thin wrapper around `swank:symbol-at-point`, which I think just calls the server directly.

**Comment by fommil** [comment]
OK cool, this sounds like the sort of thing that could be written up as a failing test in the server. Do you think you'd be able to do that if we help? Have you got paulp's sbt-extras installed? That's the only dependency, everything else bootstraps.

**Comment by tanzoniteblack** [comment]
If you point me in the right direction of where such a test would live, I could write something out. Honestly, if you point me in the right direction of where the code that does this kind of thing lives, I could probably also fix the issue. Only reason I haven't started working on bugs in this projects, like I have in ensime-maven and ensime-emacs, is that I haven't gotten around to exploring the much larger code base and unfamiliar project layout.

**Comment by fommil** [comment]
ok cool, some docs

https://github.com/ensime/ensime-emacs/wiki/Quick-Start-Guide#installing-the-server-from-assembly-builds-or-source

and the test for this would probably be somewhere like https://github.com/ensime/ensime-server/blob/master/core/src/it/scala/org/ensime/core/JavaCompilerSpec.scala

**Comment by aemoncannon** [comment]
Please do add test.

To fix, see TreeUtilities.java and look for pathFor, which creates
TreePaths given a compilation unit and an offset.
