### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1209]
Sorry all @ensime/server-panel @ensime/emacs-panel @smootoo I upgrade docker on our build machines yesterday (Ubuntu promised it was a security update) and now all the builds are hanging.

Looks like it might be this

  https://github.com/docker/docker/issues/18180

I'll fix as a priority tonight.

**Comment by fommil** [comment]
I downgraded `docker` and that seems to have fixed it. However, I need @rorygraves to hard restart his server as it took it down, then I'll need to add his box again as a node.

**Comment by fommil** [comment]
@smootoo it looks like you were allowed to log on to `fommil.com` so you should have been able to add your projects. I've flagged you as admin.

**Comment by fommil** [comment]
for future reference, this is the script to run to generate all the necessary crypto on the docker server https://gist.github.com/bradrydzewski/a6090115b3fecfc25280

**Comment by fommil** [comment]
and put this in `/etc/defaults/docker` (substitute IP address)

```
DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4 --tls --tlscacert=/etc/docker/ca.pem --tlscert=/etc/docker/server-cert.pem --tlskey=/etc/docker/server-key.pem -H=213.136.89.60:2376"
```

**Comment by fommil** [comment]
then you send the `key.pem` and `cert.pem` to me, and I put it in a folder and run something like

```
drone node create --docker-host=213.136.89.60:2376 --docker-tls-verify=false --docker-cert-path=/etc/drone/fieldmarkeng.co.uk
```

**Comment by fommil** [comment]
![everything's fine](https://media.giphy.com/media/3rgXBtMidPgPQb1is8/giphy.gif)

**Comment by chipsenkbeil** [comment]
@fommil, do you have a recommendation for restricting access to `fommil.com`? Looks like you can do something with iptables as described [here](https://forums.docker.com/t/restricting-external-container-access-with-iptables/2225/2).

**Comment by fommil** [comment]
I've not done it before but that looks sensible, I think you only want the one line for public access on the external interface.
