### ISSUE TITLE
use sbt-catalysts

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1222]
there is lots of stuff that could be ripped out or simplified from our build definitions because its now available in https://github.com/InTheNow/catalysts

**Comment by InTheNow** [comment]
And  https://github.com/InTheNow/sbt-catalysts

**Comment by fommil** [comment]
oh! I'm reading the wrong one.

**Comment by fommil** [comment]
If this is a prerequisite for the Typelevel community build then we need to do it. But it's really non trivial (not Low Hanging Fruit at all) because our build also preps the integration tests, and requires all our scala dependencies to be using sbt-catalysts, so that means we're blocked on spray-json-shapeless and #1398 

I also want to have minimal disruption to my own workflow, so that means SensibleSettings needs to become an AutoPlugin and all the bits that catalysts provides to be removed.

**Comment by fommil** [comment]
No longer exists.
