### ISSUE TITLE
Migrate to use Scala debugger api

### ISSUE THREAD

**Issue by chipsenkbeil** [ensime/ensime-server#1223]
Currently, the Ensime server uses the in-house debugging logic mixed with Akka message passing to handle debugging. Now that the [Scala debugger api](https://github.com/ensime/scala-debugger) is part of Ensime, we should look into migrating the server to using the api.

At this point, I don't know what the feature parity is between the debugger api and server; so, the debugger api might need a couple of updates along the way. Not sure how to break this one up, @fommil @rorygraves. Is there any way you can think of to tackle this in parts? Would make it more approachable for me and anyone else that wants to work on it.
###### Ensime Server Verifications
- [x] Achieve working integration tests based on old tests
- [ ] Add unit tests for all new classes/methods (*sob*)
- [x] Add new integration tests to cover other message types
- [ ] Manually test Ensime with Emacs/vim

###### Ensime Server Alterations
- [x] Create actor file that is purely geared towards processing input from the user (refactor existing actor) (DebugActor.scala)
- [x] Split off logic to create, use, and destroy virtual machine (VirtualMachineManager.scala)
- [x] Refactor logic transforming JDI information to Ensime-specific messages into separate class (StructureConverter.scala)
- [x] Clean up source manager, which currently uses raw source names rather than source paths
    - Still needs to allow looking up by source name rather than path to stay compatible
- [ ] Ensure proper refresh of source map (#1375)
- [ ] Fix duplicate breakpoints and traversal of sourcemap (#1330)
- [x] Start tests by starting a separate process and using attaching debugger instead of using launching debugger

###### Scala Debugger Improvements
- [ ] Even more issues, but I'm getting tired of listing them here...
- [x] https://github.com/ensime/scala-debugger/issues/235
- [x] https://github.com/ensime/scala-debugger/issues/233
- [x] https://github.com/ensime/scala-debugger/issues/231
- [x] https://github.com/ensime/scala-debugger/issues/229
- [x] https://github.com/ensime/scala-debugger/issues/219
- [x] https://github.com/ensime/scala-debugger/issues/218
- [x] https://github.com/ensime/scala-debugger/issues/217
- [x] https://github.com/ensime/scala-debugger/issues/213
- [ ] https://github.com/ensime/scala-debugger/issues/212
- [x] https://github.com/ensime/scala-debugger/issues/211
- [x] https://github.com/ensime/scala-debugger/issues/209
- [x] https://github.com/ensime/scala-debugger/issues/208
- [x] https://github.com/ensime/scala-debugger/issues/203
- [x] https://github.com/ensime/scala-debugger/issues/200
- [x] https://github.com/ensime/scala-debugger/issues/198
- [x] https://github.com/ensime/scala-debugger/issues/183
- [x] https://github.com/ensime/scala-debugger/issues/182
- [x] https://github.com/ensime/scala-debugger/issues/181
- [x] https://github.com/ensime/scala-debugger/issues/180
- [x] https://github.com/ensime/scala-debugger/issues/179
- [x] https://github.com/ensime/scala-debugger/issues/178
- [x] https://github.com/ensime/scala-debugger/issues/177
- [x] https://github.com/ensime/scala-debugger/issues/176
- [x] https://github.com/ensime/scala-debugger/issues/175
- [x] https://github.com/ensime/scala-debugger/issues/174
- [x] https://github.com/ensime/scala-debugger/issues/173
- [x] https://github.com/ensime/scala-debugger/issues/172
- [x] https://github.com/ensime/scala-debugger/issues/171
- [x] https://github.com/ensime/scala-debugger/issues/170
- [x] https://github.com/ensime/scala-debugger/issues/169
- [x] https://github.com/ensime/scala-debugger/issues/168
- [x] https://github.com/ensime/scala-debugger/issues/163
- [x] https://github.com/ensime/scala-debugger/issues/158
- [x] https://github.com/ensime/scala-debugger/issues/157
- [x] https://github.com/ensime/scala-debugger/issues/156
- [x] https://github.com/ensime/scala-debugger/issues/155
- [x] https://github.com/ensime/scala-debugger/issues/152
- [x] https://github.com/ensime/scala-debugger/issues/151
- [x] https://github.com/ensime/scala-debugger/issues/150
- [x] https://github.com/ensime/scala-debugger/issues/142
- [x] https://github.com/ensime/scala-debugger/issues/122

**Comment by fommil** [comment]
might make sense to have a milestone for this if you can break it up into lots of smaller tasks. Or use this ticket as an epic and use

- [ ] checkboxes
- [ ] like this

**Comment by chipsenkbeil** [comment]
So, went through Ensime's code for debugging. The only aspect that I think the debugger API is still lacking is variable management. So, I'm going to tackle that first by adding low-level variable management as well as a profile abstraction (pure only for now). After that, I should be able to knock the entire thing out in a [solid] day (so maybe 2-3 actual days) from what I've seen.

**Comment by rorygraves** [comment]
Awesome stuff!

**Comment by fommil** [comment]
wow, that sounds much faster than I expected :smile:

**Comment by fommil** [comment]
(we're going to finish TNG 2.0 before Stable 1.0 at this rate...)

**Comment by rorygraves** [comment]
same as normal then....

**Comment by chipsenkbeil** [comment]
So, started working on this last night. Wrote up quite a few TODOs that I'm going to tackle in the debugger API to a) get missing abstractions added and b) clean up the code such that it is fewer lines in Ensime.

Got a branch started here: https://github.com/chipsenkbeil/ensime-server/tree/RefactorDebugger

Main file of interest will be this one: https://github.com/chipsenkbeil/ensime-server/blob/RefactorDebugger/core/src/main/scala/org/ensime/core/debug/DebugActor.scala

Definitely does not compile right now as I've got some bits of "needs to look this way" and bobs of "this is what it currently looks like if possible." More status as I go along (potentially with questions). I'll open a WIP PR once this gets closer.

**Comment by fommil** [comment]
Nice! It would be really good if you got the tests attaching to an external process by tcp but nnot 100% necessary. Or even figuring out the current windows failure would be good.

**Comment by chipsenkbeil** [comment]
@fommil, you mean spinning up the process and using the socket attaching debugger versus the raw command line (launching) debugger? I've already got tools to do that (`JDITools.spawn(...)`), so I would think it would be possible, but not in the initial scope of this issue, right?

**Comment by chipsenkbeil** [comment]
Added all of the changes/missing features that I came up with to my issue list: https://github.com/ensime/scala-debugger/issues

Once again, lots of tiny issues, but not too many that wouldn't take an hour to implement and test. Once all of these are done, the Ensime server debug code that needs to be maintained shrinks by quite a lot (and becomes more readable).

**Comment by chipsenkbeil** [comment]
Old integration tests now pass. As I've mentioned on Gitter, these tests seem really flaky. I'm assuming I've introduced some sort of issue. The correct messages are received, but sometimes the integration tests just hang after zero, one, or two out of the three tests pass. It seems to be happening less often, but that isn't good enough.

Given how much of an overhaul this is, I'd like to add integration tests for all other message types, but I might need some help from @fommil or @rorygraves to understand the full setup process.

The branch hasn't been refactored yet, either, so there's too much code in the `DebugActor` class.

**Comment by chipsenkbeil** [comment]
PR is ready for review. Opened issues to address various potential concerns.
