### ISSUE TITLE
H2 read is a bottleneck

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1226]
this may well be completely replaced by the Graphpocalypse, but at least in the short term we would benefit from some low hanging fruit optimisations to the SearchService startup. This is particularly true for large projects.

e.g. maybe we don't need to always read before a write, and we certainly don't need to read the full list of everything twice during startup. We can assume the state does not change during the startup to keep things real simple.

**Comment by jschlather** [comment]
I think I can tackle this, but I need a little bit of context around what's happening on startup and which methods I'm safe to avoid on startup. So it seems like we have the following chain of things that are performed on startup for SearchService

```scala
   for {
      checks <- db.knownFiles()
      stale = findStaleFileChecks(checks)
      deletes <- deleteReferences(stale)
      bases = findBases()
      added <- indexBases(bases)
      _ <- commitIndex()
    } yield (deletes, added)
```

So we have a db.knownFiles which seems to scan the database and then indexBases() which hits the database and checks if each base is stale. It seems straightforward to me to add an isStartup flag to refresh and then during startup assume each base is fresh. Is this what you intended?

Regarding the other optimization, I can't find a place that's read before writing. Is there something higher or lower level than SearchService's persist that I'm missing?

```scala
  def persist(check: FileCheck, symbols: List[FqnSymbol]): Future[Option[Int]] = {
    val iwork = Future { blocking { index.persist(check, symbols) } }
    val dwork = db.persist(check, symbols)
    iwork.flatMap { _ => dwork }
  }
```

**Comment by fommil** [comment]
@jschlather great! `refresh()` is only called during startup so there is no need for a flag. But files can certainly be fresh on startup, so we definitely need to check them. But there is probably some double reading going on here in terms of asking the DB twice for files.

**Comment by fommil** [comment]
Also, we could probably benefit from upserts http://stackoverflow.com/questions/15286084/insert-into-h2-table-if-not-exists instead of read/write

**Comment by jschlather** [comment]
Okay, I don't think we can remove the initial table scan, since we use that for deleting references to stale files. In which case I'm not seeing anymore db reads during the startup procedure, can you point me to them?

Also, if I did this with merge it looks like we'd probably need to drop down to raw SQL. Because slick at best supports [insertOrUpdate](http://underscore.io/blog/posts/2015/07/14/upsert.html), which maybe is good enough, but it's still executing two queries as far as I can tell.

**Comment by jschlather** [comment]
@fommil Is there anything else to do here? Or should we close it?

**Comment by fommil** [comment]
I think you did a great job here! You could still improve the performance if this something you would like to look at, but given that we have the graphpocalypse incoming, I'd recommend you turn your attention to something else that suits your fancy :smile:
