### ISSUE TITLE
Project waiting for init...

### ISSUE THREAD

**Issue by rlvoyer** [ensime/ensime-server#1229]
I have started Scala development on a new machine and I am unable to get ensime up and running. The ensime server logs this line and then never does anything else:

```
14:49:10.134 [default-akka.actor.default-dispatcher-4] INFO  org.ensime.server.Project - \|    require(file.exists(), s"$name does not exist")
Project waiting for init...
```

I'm seeing this behavior when attempting to get it working for development on the ensime-server project, but I've confirmed that the behavior is consistent w/ other Scala projects on my machine. Here's what my environment looks like:

OS: OS X 10.11.2
Java: Java HotSpot(TM) 64-Bit Server VM 25.65-b01, Java(TM) SE Runtime Environment 1.8.0_65-b17
Scala: 2.11.7
Ensime: 0.9.10-SNAPSHOT
Emacs: 24.5

See the contents of the *inferior-ensime-server-ensime-server* buffer [in this gist](https://gist.github.com/rlvoyer/6676a2ea055fd5bcc8ab).

See the contents of my corresponding .ensime file [in this gist](https://gist.github.com/rlvoyer/0d0e6d8b9e9f59b0eb57). Let me know if there are any other details I can provide to help figure this out.

**Comment by fommil** [comment]
what exactly are the steps that you took... literally every command you type when starting Emacs.

Also, please reopen in ensime-emacs.
