### ISSUE TITLE
a slow indexer can dramatically slow down type-at-point

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1233]
I am experiencing serious performance problems with the indexer on a huge project.

When a fresh server starts up against a project, type-at-point is pretty snappy. However, after a while, it starts timing out.

I suspect we are querying the indexer and it is timing out, resulting in the type-at-point timing out. We should have aggressive timeouts for the indexer in these sorts of queries to get the answer back to the user.

**Comment by fommil** [comment]
(I'm just guessing, it might be totally unrelated to the indexer...)

**Comment by aemoncannon** [comment]
I have seen this too. Are there lucene queries that can realistically run
for multiple secs?

**Comment by fommil** [comment]
it's probably more a case of waiting for a connection or hitting a `synchronized` somewhere. I don't think lucene or h2 is ever that slow.

**Comment by aemoncannon** [comment]
that's what i figured. our index is just not *that* big.

**Comment by rorygraves** [comment]
Running the indexer on ensime-server creates ~80M temporary objects

**Comment by rorygraves** [comment]
So it basically comes down to replacing DescriptorParser with a parboiled2 parser

**Comment by aemoncannon** [comment]
Should we consider antlr? I assume parboiled2 is still going to have a lot
of the combinator overhead. Antlr parsers are near optimal.

**Comment by rorygraves** [comment]
To the best of my knowledge, parboiled2 is a complete reimplementation using a PEG parser and is much more efficient (orders of magnitude type)

**Comment by fommil** [comment]
That's during creation, this is all on lookup that I'm sung the slowdown.

**Comment by fommil** [comment]
Sung -> seeing *thanks*, Google

Do we have a separate ticket for the parboiled 2 implementation? Might need to create one because the previous ticket was for sexpparser

**Comment by rorygraves** [comment]
Ok, actually went ahead and re-implemented the DescriptorParser in PB2 - it saves about 30% of the indexing time - the slow one now is the pickling - it has its own parser for loading classfiles to get to the pickle sig, a bit of hacking would probably make that go away (reading the sig information directly)

PR coming shortly.

**Comment by fommil** [comment]
"a bit of hacking" **giggles uncontrollably** (once you see that code, you cannot "unsee" it...)

**Comment by rorygraves** [comment]
I mean - extract the symbols from the classfiles ourselves, its running an entire custom parser when we need at most 2 bits of info from each file.

**Comment by fommil** [comment]
*muahahahahahahaha!*

Actually we'll use all that information shortly, so don't count your chickens. That's the only way we can get the scala names for the symbols.

**Comment by aemoncannon** [comment]
Can we use ASM? Is much fast

**Comment by rorygraves** [comment]
I'm suggesting we extract the required value from the class and then pass just the name to their parser.  Right now it parses the entire classfile and then reads a single value out of it.
@aemoncannon Yeah, I think we can

**Comment by fommil** [comment]
The pickle data is in a binary blob in the classfile, when I last investigated there was no way to just go from that blob to a List of scala symbols. It'd be great if there was.

**Comment by fommil** [comment]
This really needs a reproduction.
