### ISSUE TITLE
conflicting Shapeless cross-version suffixes 

### ISSUE THREAD

**Issue by anakos** [ensime/ensime-server#1242]
I get the following error when trying to start up an ensime server in Emacs for a Scala 2.10 project (sbt version is 0.13.9):

```
...
[info] Done updating.
[error] Modules were resolved with conflicting cross-version suffixes in {file:/private/var/folders/0n/vdd8x_j942n6509ndrltqgdc2qdnn3/T/ensime_update_17990V5b/}ensime_update_17990v5b:
[error]    com.chuusai:shapeless _2.10.4, _2.10
java.lang.RuntimeException: Conflicting cross-version suffixes in: com.chuusai:shapeless
....
```

Unfortunately I cannot bump the scala version of the project to 2.11 and from what I can tell, nothing in the project has a dependency on Shapeless at all.  I am at a bit of a loss as to what the source of this error could be  - is there anything that can be done to fix this? These are the contents of my build.sbt file:

```
name := "abstract-core-articles-filter"

scalaVersion := "2.10.5"
 
ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }

val exclusionsForXmlAndSparkConflicts = Seq(
  ExclusionRule(organization = "com.fasterxml.jackson.core"),
  ExclusionRule(organization = "org.apache.spark"),
  ExclusionRule(organization = "com.fasterxml.jackson.core"),
  ExclusionRule(organization = "com.fasterxml.jackson.datatype")
)

libraryDependencies ++=
  Seq(
    "org.apache.spark" %% "spark-core" % "1.4.1" % Provided,
    "com.typesafe" % "config" % "1.3.0",
    "com.github.seratch" %% "awscala" % "0.5.3" excludeAll (exclusionsForXmlAndSparkConflicts: _*),
    "org.slf4j" % "slf4j-log4j12" % "1.7.12",
    "org.mockito" % "mockito-core" % "1.10.19" % Test,
    "org.scalatest" %% "scalatest" % "2.2.4" % Test
  )
```

I have additionally attached the project .ensime file (renamed to ensime.txt)
and the complete output from the ensime server startup (ensime_startup_error.txt) to this issue. Any help with this would be greatly appreciated! Thanks!

[ensime_startup_error.txt](https://github.com/ensime/ensime-server/files/101393/ensime_startup_error.txt)

[ensime.txt](https://github.com/ensime/ensime-server/files/101396/ensime.txt)

**Comment by rlvoyer** [comment]
I ran into this as well.

**Comment by rorygraves** [comment]
I may know what this is - @fommil, the server download/start script probably does not obey the intransitive marker in the build dependencies.  I guess we are going to have to roll back the Parboiled changes until we work out how to sort the client scripts (and update all the clients).

**Comment by fommil** [comment]
@sirthias you must have seen this before? I think ultimately you're going to have to release a parboiled2 that doesn't use cross versions for shapeless.

**Comment by fommil** [comment]
@anakos which client are you using?

**Comment by fommil** [comment]
@milessabin we have a direct dependency on shapeless from ensime-server, but parboiled2 has a dependency on cross build versions. Have you seen this problem before where downstream users end up with both? Seems to be a bug in ivy/maven unable to retain the intransitive information that we'll have to work around.

**Comment by fommil** [comment]
@rorygraves I suspect we could update the build scripts to exclude the exact cross build. But, yuck! I'd rather fix this server side instead of all clients having to be updated.

**Comment by fommil** [comment]
ok, we think we can fix this with a line like

```
excludeAll (ExclusionRule ( name = "shapeless", version = "..." ) )
```

in https://github.com/ensime/ensime-emacs/blob/master/ensime-startup.el#L54

and the other clients too.

(btw, please raise bugs against your editor in future :stuck_out_tongue: )

**Comment by fommil** [comment]
anyone with some sbt foo want to give that a go? I'm a bit busy right now with the file watchers.

**Comment by anakos** [comment]
@fommil - I am using Emacs 24.5.1

**Comment by fommil** [comment]
actually, http://www.scala-sbt.org/0.13/docs/Library-Management.html#Exclude+Transitive+Dependencies might be a server fix

**Comment by fommil** [comment]
anyone want to send us a PR with that fix to the server?

**Comment by anakos** [comment]
@fommil - I am more than happy to do it - how can I test locally to ensure that it's worked? Apologies in advance for all the Q?s but I am completely new to tinkering with emacs. Thanks!

**Comment by fommil** [comment]
actually it sounds like we can fix this server side in the `project/EnsimeBuild.scala` file... this is a server bug it would appear (but we do prefer tickets to be raised on `ensime-emacs` or equivalent first... ENSIME isn't just Emacs)

**Comment by fommil** [comment]
@anakos I think rory is working on it btw. Try hacking on a 2.11 project in the meantime, it's immune to the problem.

**Comment by anakos** [comment]
@fommil - ok, no

**Comment by anakos** [comment]
@fommil - ok no problem. Thanks for the swift reply to this!

**Comment by fommil** [comment]
got a fix, just testing locally

**Comment by fommil** [comment]
new artefacts will appear in ~30 mins with a fix

**Comment by milessabin** [comment]
I don't quite understand the problem. Is this with 2.10.x?

As of shapeless-2.2.0 cross builds are used for all Scala versions. Prior to 2.2.0 explicit Scala version dependencies were required for 2.10.x. By now I would expect pretty much everything non-ancient would be using cross builds everywhere.

**Comment by fommil** [comment]
@milessabin parboiled2's 2.10 build depends on `shapeless_2.10.4`, but ensime-server depends on `shapeless_2.10`. When published, maven isn't able to handle intransitives so one has to do something like https://github.com/ensime/ensime-server/commit/2a0f12b767fa11538e46d443bb79e6c990b43726

**Comment by milessabin** [comment]
Gotcha. Given that parboiled2 is on shapeless-2.2.3 I'd say that this is a bug in their build ... shapeless-2.2.x has only ever been cross built (see [here](https://github.com/milessabin/shapeless/commit/a7073a0a014246a1532118c0e85250fc14300e8c)) so I'm uncertain how the parboiled build is supposed to work.

**Comment by fommil** [comment]
@milessabin oh I think that's their `master` branch. The latest release is shapeless 2.1. We can remove our hack when we update.

**Comment by sirthias** [comment]
@fommil Sorry for coming in late on this.
Yes, pb2 is still on shapeless 2.1 and the Scala 2.10 version still has the cross build requirement, which we should remove now.

Is there anything you still need from my side at this point?
