### ISSUE TITLE
Failed to navigate to sources in src_managed

### ISSUE THREAD

**Issue by VlachJosef** [ensime/ensime-server#1244]
When trying to navigate to sources in `src_managed` no definition is found.

I've created [small project](https://github.com/VlachJosef/ensime-gen-sources) when issue can be reproduced.

When trying to navigate to `Foogen` [here](https://github.com/VlachJosef/ensime-gen-sources/blob/3eb498bb0da674819e020736bba3d8527f62d1d5/src/main/scala/com/tst/Server.scala#L10) or `Bargen` [here](https://github.com/VlachJosef/ensime-gen-sources/blob/3eb498bb0da674819e020736bba3d8527f62d1d5/src/main/scala/com/tst/Server.scala#L11) navigation fails althoug navigation to `Foo` [here](https://github.com/VlachJosef/ensime-gen-sources/blob/3eb498bb0da674819e020736bba3d8527f62d1d5/src/main/scala/com/tst/Server.scala#L13)  and `Bar` [here](https://github.com/VlachJosef/ensime-gen-sources/blob/3eb498bb0da674819e020736bba3d8527f62d1d5/src/main/scala/com/tst/Server.scala#L14) works normally.

`Foogen` and `Bargen` are defined in `/src_managed/main/scala/com/gen/Foogen.scala`
`Foo` and `Bar` are defined in `/src/main/scala/com/live/Foo.scala`

**Comment by fommil** [comment]
ok, I'll have a look and post my thoughts.

**Comment by fommil** [comment]
some relevant logging

```
18:45:41.514 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/2 o.e.c.RichPresentationCompiler - search: com.gen.Foogen = Some(FqnSymbol(Some(66),file:///home/fommil/Projects/ensime-gen-sources/target/scala-2.11/classes/com/gen/Foogen.class,file:///home/fommil/Projects/ensime-gen-sources/target/scala-2.11/classes/com/gen/Foogen.class,com.gen.Foo
18:45:41.515 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/2 o.e.c.RichPresentationCompiler - search object Foogen: Try Companion
18:45:41.518 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/4 o.e.s.RequestHandler - received handled message Some(SymbolInfo(com.gen.Foogen$,Foogen,None,BasicTypeInfo(Foogen$,1,Object,com.gen.Foogen$,List(),List(),None,None),false,Some(2))) in state receive
```

It looks like it is not able to find the source. I thought it might be a problem with finding the companion apply, so I added an explicit type to the `foogen: Foogen` and it still wasn't finding it.

Something worth looking into is that you're outputting into `target` and that's kind of unusual.

**Comment by fommil** [comment]
it does work if you navigate to `Foogen.scala`, so the presentation compiler can load it ok. It looks like this is a bug in the indexer.

**Comment by VlachJosef** [comment]
Ok, I wouldn't mind to investigate and try to fix it. I would like to get more familiar with Indexer and other parts of ensime-server.

**Comment by fommil** [comment]
I have a PR which touches a lot of this, should be merged tonight.

**Comment by VlachJosef** [comment]
Ok, than I will wait if it will get fixed by your PR.

**Comment by fommil** [comment]
Is merged.

**Comment by VlachJosef** [comment]
Hm, so your merged PR doesn't seems to solve it.

**Comment by fommil** [comment]
the way it works is that when we index the binaries, we use the SourceResolver to find the associated sources, and then we persist that. My guess is that it's failing at this point, not when you're making the query. 

- https://github.com/ensime/ensime-server/blob/master/core/src/main/scala/org/ensime/indexer/SourceResolver.scala
- https://github.com/ensime/ensime-server/blob/master/core/src/it/scala/org/ensime/indexer/SourceResolverSpec.scala

**Comment by VlachJosef** [comment]
Great, I will look into this.

**Comment by VlachJosef** [comment]
It turns out that this is not bug in indexer, not even in ensime-server. Issue is in generated `.ensime` file.

Record in `:source-roots` for `src_managed` looks like this:
```
/Users/pepa/develop-ensime/ensime-gen-sources/target/scala-2.11/src_managed/main
```
but it should look like this:
```
/Users/pepa/develop-ensime/ensime-gen-sources/target/scala-2.11/src_managed/main/scala
```
I will open issue in ensime-sbt.

**Comment by fommil** [comment]
heh, interesting. Should be really easy to write a test case for that! I can definitely help you fix that.

**Comment by fommil** [comment]
btw, are you sure that sbt doesn't think that the path is `src_managed/main` and that you're maybe putting the files in the wrong place? (I suspect sbt uses probably does cross version paths, but just checking)

**Comment by VlachJosef** [comment]
Actually I'm not sure what expected structure should be in `src_managed/main`. I've quickly check the internet and it looks like that generated sources should go directly into this folder no into subdirectory `scala`. So this must be issue with my configuration.

**Comment by fommil** [comment]
cool! Glad to get this one resolved

**Comment by VlachJosef** [comment]
I'm glad I got deeper insight into ensime-server

Btw. [this](https://github.com/sbt/sbt-scalabuff/blob/16aa7c0ed99348afe211f77a0149873a895f02cc/src/main/scala/ScalaBuffPlugin.scala#L59)  is the reason why I got trapped into this. Someone already [fix it](https://github.com/idecide/sbt-scalabuff/commit/2741732bddff1a05fbf8c967c0ffcee75ce74bee) in his fork of sbt-scalabuff plugin.

**Comment by fommil** [comment]
interesting, I use that plugin... I should check that I'm not susceptible as well
