### ISSUE TITLE
rewrite tests to use EnsimeSpec

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1245]
we have a preferred testing style, FlatSpec, which is abstracted in `EnsimeSpec`... which also saves a bunch of boilerplate when it is extended.

It would be good to refactor all our tests to use this style, including converting `assert` => matchers.

**Comment by fommil** [comment]
@noelmarkham you once showed some interest in doing this.

**Comment by ancane** [comment]
I'll take a look at this, if you don't mind ;)

**Comment by fommil** [comment]
@ancane :-) feel free to! You will also find that we have a bunch of unit tests that can use the EnsimeVFS fixture (I caught one in my dev branch) and that some integration tests can actually be moved into the `test` config.

BTW, still loving `M-i`... I use it a lot now.
