### ISSUE TITLE
file handles being kept open

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1250]
we are leaving file handlers open on jars during indexing, which means that windows can't delete the files (among other resource leakage goodness). Oh, Windows!

**Comment by fommil** [comment]
@jvican this is something you should also watch out for... never leave file handlers lying open because it is really bad on windows (jar files and classes could be marked as read-only by the OS until the locks are released)

**Comment by fommil** [comment]
not fixed :cry:

**Comment by fommil** [comment]
it's the interactive compiler :crying_cat_face:

**Comment by fommil** [comment]
the interactive compiler is holding open references to jar files in FileZipArchive which causes serious problems on Windows (a file handle will prevent the file from being deleted by other processes, say, the build tool...). I'm going to have to look into a workaround in ensime, but this will impact Scala IDE as well @sschaef

at this stage, getting a fix upstream is an extremely long term solution, so a workaround would be good

https://github.com/scala/scala/blob/2.12.x/src/reflect/scala/reflect/io/ZipArchive.scala

**Comment by fommil** [comment]
https://issues.scala-lang.org/browse/SI-9632

**Comment by fommil** [comment]
@retronym had an absolutely brilliant idea for this: we monkey patch! i.e. we create `ensime-monkeys` and make sure the clients put that jar before the other jars on the classpath. We could even coax `sbt-assembly` to prefer our versions over the standard implementations. It only requires a very small change to the clients to order the classpath that sbt / coursier generates.

We'd have to be careful though, we can't really test our monkey patches so we'll be sure to only do ABI-compatible bug / performance fixes with it (e.g. interning inside VFS2).

**Comment by fommil** [comment]
BTW, this also means we could potentially monkey patch anything we want inside the presentation compiler :open_mouth:

**Comment by jvican** [comment]
Great idea, like it! :+1:

**Comment by aemoncannon** [comment]
![image](https://cloud.githubusercontent.com/assets/7484/12689957/a5cad796-c6a5-11e5-8cf5-9c66a5025ea4.png)

**Comment by fommil** [comment]
hehehe, yeah, it's insane. But it might just be crazy enough to work. Jason already has a proposed fix in the compiler, and this seems like a way to let us backport whatever fix we need.

**Comment by sschaef** [comment]
In scala-ide we use AspectJ for such cases...
