### ISSUE TITLE
intern Strings in VFS

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1257]
I did a quick heapdump of ENSIME server in quiesscent state and found about GB of duplicated strings (thanks to YourKit). We could remove a lot of that by using `.intern`, but a bunch of it is internal to VFS so we'd have to hack their code.

If we catch every string going into `EnsimeVFS` it should help. Might slow down Java 6 a bit but this is generally a good move on modern JVMs.

* https://issues.apache.org/jira/browse/VFS-593

**Comment by fommil** [comment]
with ensime-monkeys we can probably do this

**Comment by fommil** [comment]
TODO: get the details of the hotspots from the heapdump.

**Comment by fommil** [comment]
Whilst creating a heap dump for `File` handler diagnosis, I also grabbed this

```
"Name","Objects","Retained Size","Dominators","Level"
"<All the objects>","15314","2327728","","1"
"org.apache.commons.vfs2.provider.local.WindowsFileName","15314","2327728","15313","2"
"<Retained from several objects simultaneously (don't have a dominator)>","3","456","","3"
"java.util.HashMap$Entry","","","","4"
"org.apache.commons.vfs2.cache.FileSystemAndNameKey","","","","4"
"org.apache.commons.vfs2.provider.FileSystemKey","","","","4"
"org.apache.commons.vfs2.provider.LayeredFileName","","","","4"
"org.apache.commons.vfs2.provider.local.LocalFile","","","","4"
"org.apache.commons.vfs2.provider.LayeredFileName","15311","2327272","15311","3"
"<Retained from several objects simultaneously (don't have a dominator)>","7655","1163560","","4"
"java.util.HashMap$Entry","","","","5"
"org.apache.commons.vfs2.cache.FileSystemAndNameKey","","","","5"
"org.apache.commons.vfs2.provider.jar.JarFileObject","","","","5"
"org.apache.commons.vfs2.FileName[]","7656","1163712","483","4"
"org.apache.commons.vfs2.provider.jar.JarFileObject","7656","1163712","483","5"
"<Retained from several objects simultaneously (don't have a dominator)>","7656","1163712","","6"
"java.lang.Object[]","","","","7"
"java.lang.ref.Finalizer","","","","7"
"java.lang.ref.SoftReference","","","","7"
```

**Comment by fommil** [comment]
and

```
"Name","Objects","Retained Size","Dominators","Level"
"<All the objects>","15313","1960064","","1"
"org.apache.commons.vfs2.provider.local.WindowsFileName","15313","1960064","15313","2"
"org.apache.commons.vfs2.provider.LayeredFileName","15311","1959808","15311","3"
"org.apache.commons.vfs2.FileName[]","7656","979968","483","4"
"org.apache.commons.vfs2.provider.jar.JarFileObject","7656","979968","483","5"
"<Retained from several objects simultaneously (don't have a dominator)>","7656","979968","","6"
"java.lang.Object[]","","","","7"
"java.lang.ref.Finalizer","","","","7"
"java.lang.ref.SoftReference","","","","7"
"<Retained from several objects simultaneously (don't have a dominator)>","7655","979840","","4"
"java.util.HashMap$Entry","","","","5"
"org.apache.commons.vfs2.cache.FileSystemAndNameKey","","","","5"
"org.apache.commons.vfs2.provider.jar.JarFileObject","","","","5"
"<Retained from several objects simultaneously (don't have a dominator)>","2","256","","3"
```

**Comment by jvican** [comment]
If I remember correctly, `String.intern` keeps strong references to the objects. In general, I'll use `WeakReference`s to do this. But, in case there's any chance that those strings appear again after being cleared from memory, I'll stick with `SoftReference`s. They'll be removed before an `OutOfMemoryError` is thrown even though the JVM will try to keep them in memory as long as possible.

**Comment by fommil** [comment]
It just means `.intern()` when constructing strings.

**Comment by fommil** [comment]
No need to consider strong or weak refs. Once you call .intern just forget the original. Are thinking about picking up this one? :-) happy to talk about it on gitter tomorrow

**Comment by jvican** [comment]
You have another issue in which you show worries about memory consumption. I think that interning should depend on the available memory and therefore I propose a reference-based implementation instead of using the default intern.‎ This will free up the memory if it's really necessary, and given the condition that ensime is probably running along another JVM (e.g. Sbt), I consider this a feasibe feature. Wdyt?

**Comment by fommil** [comment]
It would be a big help if the one or two places inside VFS that create highly repetitive strings had .intern called on these strings after creation. It should be a very surgical change in a monkey patch. Let's keep it simple and just do it with prejudice. I don't know where the objects are being created, although the memory dump shows where they remain. If you could do a memory allocation trace with yourkit, it should light up like a bonfire.

**Comment by fommil** [comment]
Btw, i don't really know why you're talking about references here. The intern pool is a fixed and configurable size orders of magnitude below the current usage

**Comment by jvican** [comment]
Oh, I missed the point that this is going to be a fix for VFS, I though it was server-related and therefore I proposed something more complex and efficient. I'm talking about using references as circuit breakers (for the GC). Obviously, `intern` will be way more efficient than the current state, I was just proposing to push this efficiency a little bit more.

**Comment by jvican** [comment]
How can I reproduce this to profile it?

**Comment by fommil** [comment]
Heh. Find a big project and take a heap dump :smile: we have some yourkit licences, we might be able to ask for more. The trial licence should work for a few weeks.

**Comment by jvican** [comment]
Okey, I'll do that. I'll stick with intern but do you understand now why I proposed references?

**Comment by fommil** [comment]
Ah yes. i see! :smile: yeah if it's domain objects one can be much more advanced with interning techniques. I've considered writing a smarter case class impl that does something similar

**Comment by fommil** [comment]
@jvican do you think you'll have any spare cycles to look at this?

**Comment by jvican** [comment]
Yes, I’ll have some time next w-e and I'll tackle this issue (hope so, at least).

**Comment by fommil** [comment]
Sweet! Another way we could do this is with a java agent. I'm not sure which is worse: monkey patch or Java agent.

**Comment by jvican** [comment]
I'm sorry @fommil, I won't be able to pick this in the short-term, I'm currently very busy.

**Comment by fommil** [comment]
no problem, thanks for letting us know. There is a hack day coming up soon so maybe somebody can grab it there.

**Comment by fommil** [comment]
the right answer here is to just remove VFS and use NIO, which is on the 2.0 roadmap.

**Comment by fommil** [comment]
https://github.com/apache/commons-vfs/pull/14
