### ISSUE TITLE
utf-8 characters not supported by descriptor parser (scalaz)

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1259]
oh scalaz, aren't you just so cute and smart with your fancy method names...

```
12:03:36.878 ERROR akka.dispatch.Dispatcher a.d.Dispatcher - Failed to parse descriptor type: Invalid input 'η', expected PackageNamePredicate, '/', ClassNameCharPredicate or ';' (line 1, column 57):
Lscalaz/syntax/ToApplicativeOps$ApplicativeIdV$$anonfun$η$1;
```

**Comment by fommil** [comment]
@noelmarkham want to have a look at this? I'm not terribly motivated to support scalaz :wink:

**Comment by isomarcte** [comment]
+1 for this bug! It killed my development session today.

**Comment by fommil** [comment]
@isomarcte should be an easy fix, want to submit it? Create a one-line failing test in `SexpParserSpec.scala` (please remember to include a snarky comment about scalaz being very clever :wink: ), and fix it in `SexpParser.scala`. Once merged, it's released.

**Comment by fommil** [comment]
btw, it shouldn't kill the development session. It should just spit out an exception in the server and continue on without search results for scalaz.

**Comment by rorygraves** [comment]
DescriptorParserSpec

**Comment by fommil** [comment]
doh! I'll update my comment.

**Comment by fommil** [comment]
@isomarcte @rorygraves is fixing it

**Comment by rorygraves** [comment]
@rorygraves has fixed it - just running tests and putting together the PR, - I had to go back and reread the jvm spec for what characters are allowed in classnames (at the jvm level), the short answer is 'all of them except / and ;'

**Comment by fommil** [comment]
omg, really? We **have** to use this as the namespace for our monkey patches http://www.fileformat.info/info/unicode/char/1f435/index.htm

**Comment by fommil** [comment]
oh, darn, by definition we have to use the same as the originals. Maybe we can have that just for fun.

**Comment by rorygraves** [comment]
PR raised - 
Which chars are allowed you ask?  All of them (minus delimiters)!!!
```val ClassNameCharPredicate = CharPredicate.All -- ";/ " ```  

Including 🐵

**Comment by isomarcte** [comment]
Thanks for the fast fix. 

@fommil hmm, I'm not sure what killed my connection between emacs and the server then. Although you are right, the server kept on running after the exception was thrown. My mistake.

**Comment by rorygraves** [comment]
No problem, I broke it - its probably fair I fix it ;)

**Comment by rorygraves** [comment]
Fixed
