### ISSUE TITLE
Re-enable file manager caching in JavaCompiler.scala

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-server#1262]
This is an order-of-magnitude speedup when there are lots of jars (jar caching is file managers job!). I measure 800ms -> 50ms when analyzing .java file with 600 jars on the classpath. Notably ensime is still usable at 800ms, but it is *awesome* at 50ms :-)

**Comment by aemoncannon** [comment]
Note: will have to selectively re-enable for java7+ probably.

**Comment by fommil** [comment]
Oh wow, due you have a PR in mind?

**Comment by aemoncannon** [comment]
Yeah. Just a simple fix.
