### ISSUE TITLE
Java generally having trouble jumping to method declarations from index.

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-server#1263]
Might just be feeding a bad query to the indexer?

**Comment by fommil** [comment]
Oh I know what that is. I'm trying to fix this in my dev branch but I've been firefighting windows performance problems

**Comment by fommil** [comment]
this is the branch, needs a rebase https://github.com/fommil/ensime-server/tree/index_method_descriptors and it'll be what I get to as soon as I get past these damn windows problems. I'm actually getting close to it working.

**Comment by fommil** [comment]
#1190
