### ISSUE TITLE
Open in github

### ISSUE THREAD

**Issue by hedefalk** [ensime/ensime-server#1265]
_From @d6y on January 29, 2016 12:58_

Imported from README:

> Someday it would be cool to not use exploded single tree for dep-src so that one have more control like "open on github" of ensime: 404: 

This link is dead, but was in the readme:

https://github.com/xebia/cakemix/blob/master/.ensime_cache/dep-src/source-jars/scala/concurrent/duration/package.scala#L17

_Copied from original issue: ensime/ensime-atom#132_

**Comment by hedefalk** [comment]
I think I want to move this to server. I'll explain:

In _modern_ editors like Atom :), you typically have commands like "Open on github" which is a pretty convenient way of getting an url to pin down a file or line of a file in a dependency that you can post in bug reports or IM. I guess it reads URL from .git if it's a first class project, but it would probably be possible to hook into this and provide info from sbt, pom.xml or ivy file in the case of Java deps. That of course would require that the sources isn't flattened out into one global classpath directory, but subdirs per jar-lib with individual meta data.

**Comment by fommil** [comment]
I don't understand. Btw there is a ticket to get rid of the dep-src altogether. Emacs can browse inside jars no problem.

**Comment by hedefalk** [comment]
Cool, then this is probably a dup of that. 

But well, I don't understand right back at you! :)

Currently, when "code surfing", server gives me file paths to an exploded directory dep-src. Here, there isn't enough meta data to do anything cool. If I instead could get path's to within the jars (I think Atom can browse zip's too), I could read meta-data from those jars like pom.xml, ivy or sbt to get a repo-url like:

`"repository": "https://github.com/hedefalk/ensime-atom",``

Then I could hook into functions of Atom, like "open on github" by relativizing the file to this url, like:

`https://github.com/hedefalk/ensime-atom/blob/master/lib/features/typechecking.coffee#L27``

which is super-nice-to-have when communicating on the internetz.

I'll try to find the dupe and close this one with ref…

**Comment by fommil** [comment]
OK, sounds like it's a dupe. Have a search for jar maybe? I'm on a phone so can't do it right now

**Comment by hedefalk** [comment]
Dup of #761
