### ISSUE TITLE
imenu hangs for big projects

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-server#1270]
@ancane 
I tried this the other day on a large project (600 jars on classpath) and it hung. Is it trying to get structure of everything?

**Comment by ancane** [comment]
@aemoncannon no, it's only building structure of observable file.

**Comment by fommil** [comment]
this sounds like it's a presentation compiler issue :sob:

**Comment by fommil** [comment]
good test case for huge files is always `Defaults.scala` in `sbt`
