### ISSUE TITLE
ClassCastException on HTTP-RPC Request TypeAtPointReq

### ISSUE THREAD

**Issue by msiegenthaler** [ensime/ensime-server#1272]
HTTP-RPC requests (no Websockets) for TypeAtPointReq throw
`java.lang.ClassCastException: Cannot cast scala.Some to org.ensime.api.EnsimeServerMessage
`

Related to #1267

**Comment by fommil** [comment]
I'm confused, what's the difference with the existing ticket?

**Comment by msiegenthaler** [comment]
Well, it's actually two separate code paths, in this case the Analyzer return Option[RpcResponse] while in the other its more complicated with the Analyzer returning Option[DocSigPair] and the Analyzer needs to be called a second time.

So for sake of tracebility I opened a second ticket. I don't like fixing bugs without a reference to a ticket.

**Comment by fommil** [comment]
is this still an issue?
