### ISSUE TITLE
use ports in the files, instead of bailing

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1277]
as discussed on gitter with @hedefalk and @rorygraves it would be advantageous if the ensime server could use the same port as in a previous session. For Atom, it sounds like they want to use this as the mechanism for restarting the server when the `.ensime` file changes (maybe emacs could do the same, although there is some old startup initialisation logic in there) but for Windows it is a good workaround to https://github.com/ensime/ensime-emacs/issues/338

I suppose the server, when it sees a port file (or websockets file) would attempt to use that port... and only if it fails to obtain the exclusive ownership of that port would it fail.

**Comment by fommil** [comment]
https://github.com/ensime/ensime-server/blob/cbacc3d37577be93e68a70c597442961d0e998c6/server/src/main/scala/org/ensime/server/PortUtil.scala

(which should probably `sys.exit` instead of throwing an exception in any case)

**Comment by fommil** [comment]
plus, as rory points out, we should re-introduce stopping the server on client disconnections. It was always a debugging feature to leave a persistent ensime-server connection anyway.

**Comment by fommil** [comment]
@hedefalk I'm stealing this one off you

**Comment by hedefalk** [comment]
Awesome!

**Comment by fommil** [comment]
ok, got a patch. But need to write a test for it.
