### ISSUE TITLE
Documentation lookup for cats.data.Xor$$Right

### ISSUE THREAD

**Issue by d6y** [ensime/ensime-server#1281]
I'm using Atom with ENSIME, and not having any joy getting `DocUriAtPointReq` to work with `Xor.Right` (from cats).  

Example project: https://github.com/d6y/xor-scaldoc-lookup

Code:

``` scala
import cats.data.Xor._

object O {

  val r = Right(1)

}
```

And if I try to lookup the doc for `Right` like this...

```
 "req": {
    "typehint":"DocUriAtPointReq",
    "file":"/Users/richard/Developer/tmp/xor-scaldoc-lookup/src/main/scala/example.scala",
    "point":{"from":61,"to":61}},
    "callId": 28
  }
```

...the result is:  `{"callId":28,"payload":{"typehint":"FalseResponse"}}`

Expecting to resolve `Right` to:

```
/docs/cats-core_2.11-0.4.1-javadoc.jar/index.html#cats.data.Xor$$Right
```

This via: https://github.com/ensime/ensime-atom/pull/152#issuecomment-181031838

**Comment by fommil** [comment]
ok, cool. It should be really easy to get an integration test case for this.

1. add whatever jars you want to the integration test project https://github.com/ensime/ensime-server/blob/e0ab76b8c8bbe09f33795d33f924f8ddfd9fc8d8/project/EnsimeBuild.scala#L264-L271
2. confirm what type is being inferred in https://github.com/ensime/ensime-server/blob/e0ab76b8c8bbe09f33795d33f924f8ddfd9fc8d8/core/src/it/scala/org/ensime/core/DocFindingSpec.scala (in my dev branch this is becoming a more general FQN discovery feature)
3. add a test to https://github.com/ensime/ensime-server/blob/e0ab76b8c8bbe09f33795d33f924f8ddfd9fc8d8/core/src/it/scala/org/ensime/core/DocResolverSpec.scala

**Comment by d6y** [comment]
Thanks - are there any pointers on how to run the integration test to see if I have step 2 right? `sbt it:test` runs but I'm missing something else running (presumably the server itself).

**Comment by fommil** [comment]
Check the .drone.yml for what the ci runs. You'd need to run gen-ensime and create the cache dir. We could probably handle the latter case the be honest.

**Comment by d6y** [comment]
Thank you - I've been able to progress.  The doc signature in step 2 seems to be: `DocSig(DocFqn("cats.data", "Xor$$Right$"), None)` - I don't know if that's correct or not, but the it:test passes with that value :-/

Regarding step 3, that is failing for me already without any change:

```
[info] DocResolverSpec:
[info] DocResolver
[info] - should support a wide range of queries *** FAILED ***
[info]   Some("docs/scala-reflect-2.11.7-javadoc.jar/index.html#scala.package@Exception=Exception") was not equal to Some("docs/scala-library-2.11.7-javadoc.jar/index.html#scala.package@Exception=Exception") (DocResolverSpec.scala:275)
[info]   org.scalatest.exceptions.TestFailedException:
```

I'll look into that tonight and check my set up against the travis config.  But if it rings any bells, let me know.

**Comment by fommil** [comment]
that's interesting. Try with JDK6 ? It sometimes affects the ordering of the search-like tests.

**Comment by d6y** [comment]
No joy yet using OpenJDK 6 on Ubuntu.  I'll try some more later in the week. I'll maybe study [the Docker image](https://github.com/ensime/ensime-docker/blob/v1.x/Dockerfile) to see if I can spot anything obvious from that.

**Comment by fommil** [comment]
that's interesting. This should just work. Are you coming on Saturday to Hack the Tower?

**Comment by d6y** [comment]
A little more progress...  The  `DocResolverSpec` now runs.  I hadn't run `gen-ensime` in the project.

`sbt it:test` now fails with different errors:

```
[error] Failed tests:
[error]         org.ensime.core.RichPresentationCompilerThatNeedsJavaLibsSpec
[error]         org.ensime.intg.BasicWorkflow
[error]         org.ensime.indexer.SourceResolverSpec
```

I'll try to look into those in more detail.

If i apply the changes I made (!) I get failures (which I expect):

```
[info]   None was not equal to Some("docs/cats-core_2.11.7-0.4.1-javadoc.jar/index.html#cats$
data.Xor$$Right") (DocResolverSpec.scala:315)
```

and 

```
[info]   DocSig(DocFqn(scala.util,Right$),Some(Right:util.Right.type)) was not equal to DocSi
g(DocFqn(cats.data,Xor$$Right$),None) (DocFindingSpec.scala:133)
```

This is progress :-)

I won't be around Saturday, but will kick on this some more later in the week.

**Comment by fommil** [comment]
Are you using sbt-extras?

**Comment by d6y** [comment]
Yes I am using paulp sbt-extras.

I'll work through each error in turn, see if I can get anywhere.

In case this suggets anything, the first is...

```
$ sbt  "it:testOnly org.ensime.core.RichPresentationCompilerThatNeedsJavaLibsSpec"

...

[info] RichPresentationCompilerThatNeedsJavaLibsSpec:
[info] RichPresentationCompiler
[info] - should locate source position of Java classes in import statements *** FAILED ***
[info]   sym.declPos.isDefined was false (RichPresentationCompilerSpec.scala:41)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:500)
[info]   at org.scalatest.WordSpec.newAssertionFailedException(WordSpec.scala:1881)
[info]   at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:466)
[info]   at org.ensime.core.RichPresentationCompilerThatNeedsJavaLibsSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$29$$anonfun$apply$1.apply(RichPresentationCompilerSpec.scala:41)
[info]   at org.ensime.core.RichPresentationCompilerThatNeedsJavaLibsSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$29$$anonfun$apply$1.apply(RichPresentationCompilerSpec.scala:39)
....
```

**Comment by fommil** [comment]
ah. Are you perhaps lacking the java source zip?

I really need to create a checklist.

**Comment by d6y** [comment]
> I really need to create a checklist.

I think we're doing it here :-)

I did do `apt-get install openjdk-6-source`, but maybe there's more to do.

**Comment by fommil** [comment]
that is totally weird. The best I can offer is to screen share or something on Saturday or next week. Everything seems to be in order.

Can you perhaps try to run in the CI environment? `go get github.com/drone/drone-go/drone` then `drone .` in `ensime-server`.

**Comment by fommil** [comment]
(you can speed it up a little by running `docker pull ensime/ensime:latest` beforehand)

**Comment by d6y** [comment]
Reporting in...  the drone build does work for me (the sbt part... I killed it after that).  I'll re-check my steps, and if I still can't see anything, I'll have a look at the tests that are failing for me for more clues.

Aside - Just for the record, the commands were slightly different for me:

- I followed the [drone-cli install instructions](https://github.com/drone/drone-cli)
- `rm -rf .ensime_cache`
- `drone exec .`
