### ISSUE TITLE
Add line, col for end position in ranges

### ISSUE THREAD

**Issue by hedefalk** [ensime/ensime-server#1286]
From discussion in gitter:

> To be super clear, server gives: {"beg":7429,"line":207,"col":57,"end":7435} which is col, line and offset for start pos but only offset for end pos. We can't know if error spans multiple lines without opening up the actual file. When having 100+ warnings or so it kind of sums up to a bit of work on each update of messages from server.

https://github.com/ensime/ensime-server/blob/master/core/src/main/scala/org/ensime/util/Reporter.scala#L55

for start pos we use the following:

```
def line: Int           = if (hasSource) source.offsetToLine(point) + 1 else 0
  def column: Int         = if (hasSource) calculateColumn() else 0
```

Maybe we can just use shift:

```
val end = pos.withShift(pos.end-pos.start)
end.line, end.col
```

to reuse those functions.

**Comment by hedefalk** [comment]
I can't add labels. Still can't edit labes / add new ones in ensime-atom either. ping @fommil.

**Comment by fommil** [comment]
The github perms are really weird. They changed everything recently. I'd like everybody in time org to me one to assign and edit labels. I might have to raise a support ticket.

**Comment by fommil** [comment]
@hedefalk do you have any spare cycles to implement this?

**Comment by hedefalk** [comment]
Yeah, would love to implement this. Maybe within a few weeks at least. Still have some client side stuff I want to do first and still have to get over that first server contribution threshold, but would be fun and game.
