### ISSUE TITLE
exact match classnames being trumped by (often noise) inner classes

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1287]
e.g. when I search for `Foo` if there are loads of inner classes, they'll dominate the search results for me.

**Comment by fommil** [comment]
should probably make each `$` have a penalty when lucene indexing, I also thought our search query had a boost for an exact match. I'll need to check that.

**Comment by rorygraves** [comment]
Notes:  This will be in the SearchService class (the lucene indexer).  It is possible to create an integration test expressing the behaviour.

**Comment by caoilte** [comment]
You would think https://github.com/ensime/ensime-server/commit/df0eb4a7ef9af07d14d79370dea9993574fa76a4 would demonstrate that this cannot happen, but there must be something coincidental about that naming which doesn't lead to the inner class coming top.

I was able to reproduce the exact problem with (and can be called in SearchServiceSpec conveniently)

`service.searchClasses("Matchers", 100)`

which returns the following with `org.scalatest.Matchers` right in the middle,

`List("org.scalatest.Matchers$ResultOfStartWithWordForCollectedString", "org.scalatest.Matchers$HavePropertyMatcherGenerator", "org.scalatest.Matchers$", "org.scalatest.Matchers$ExactlyCollected", "org.scalatest.Matchers$ValueWord", "org.scalatest.Matchers$ResultOfEvaluatingApplication", "org.scalatest.Matchers$ResultOfCollectedAny", "org.scalatest.Matchers$ResultOfIncludeWordForCollectedString", "org.scalatest.Matchers$NoCollected$", "org.scalatest.Matchers$ResultOfFullyMatchWordForCollectedString", "org.scalatest.Matchers$StringShouldWrapper", "org.scalatest.Matchers$BetweenCollected$", "org.scalatest.Matchers$ResultOfContainWordForCollectedAny", "org.scalatest.Matchers$ShouldMethodHelper$", "org.scalatest.Matchers$ResultOfBeWordForAny", "org.scalatest.Matchers$ResultOfProduceInvocation", "org.scalatest.Matchers$TheSameInstanceAsPhrase", "org.scalatest.Matchers", "org.scalatest.Matchers$ResultOfNotWordForCollectedAny", "org.scalatest.Matchers$AllCollected$", "org.scalatest.Matchers$EveryCollected$", "org.scalatest.Matchers$AnyShouldWrapper", "org.scalatest.Matchers$ExactlyCollected$", "org.scalatest.Matchers$ResultOfBeWordForCollectedArray", "org.scalatest.Matchers$ResultOfStartWithWordForString", "org.scalatest.Matchers$RegexWrapper", "org.scalatest.Matchers$AtLeastCollected", "org.scalatest.Matchers$AtLeastCollected$", "org.scalatest.Matchers$ResultOfBeWordForCollectedAny", "org.scalatest.Matchers$ResultOfFullyMatchWordForString", "org.scalatest.Matchers$ResultOfHaveWordForExtent", "org.scalatest.Matchers$Collected", "org.scalatest.Matchers$KeyWord", "org.scalatest.Matchers$AWord", "org.scalatest.Matchers$AtMostCollected", "org.scalatest.Matchers$ResultOfEndWithWordForString", "org.scalatest.Matchers$RegexWord", "org.scalatest.Matchers$ResultOfEndWithWordForCollectedString", "org.scalatest.Matchers$BetweenCollected", "org.scalatest.Matchers$ResultOfIncludeWordForString", "org.scalatest.Matchers$class", "org.scalatest.Matchers$AnWord", "org.scalatest.Matchers$ResultOfHaveWordForCollectedExtent", "org.scalatest.Matchers$AtMostCollected$", "org.scalatest.MatchersHelper$", "org.scalatest.MatchersHelper")`

**Comment by ChrisCoffey** [comment]
I'm interested in taking this on if nobody is active on it.

**Comment by ChrisCoffey** [comment]
I'm thinking a 10% score penalty for each non-trailing `$` in the fqn should address this. I'll obviously have to test it out, but that's the plan right now.

**Comment by fommil** [comment]
we might have to return to it later on, but for now I think that's a reasonable approach and it's more important that we create that link between the classfile indexer and lucene boosts.

**Comment by caoilte** [comment]
Was probably going to have a look at it at the hackday on Saturday - but if you're near to a fix then I'll happily look at something else.

**Comment by ChrisCoffey** [comment]
I have a candidate fix that I'm debugging locally. If you don't hear from my by Saturday feel free to take this though.

**Comment by fommil** [comment]
@caoilte I cleaned up the tracker, should be lots now. Have a look at updated /contributing page.

**Comment by ChrisCoffey** [comment]
I'll dust off the branch I was working on here in the next day or so.

**Comment by fommil** [comment]
Cool! This one bites me at work sometimes.

**Comment by fommil** [comment]
I think we disable indexing f anything with two dollar signs as a workaround.

**Comment by ChrisCoffey** [comment]
I've been swamped lately, and don't see myself having much time in the next few weeks, so feel free to hand this out at a hackathon!

**Comment by sugakandrey** [comment]
This one is pretty annoying, also I think I almost have a working fix for that. So I'll take this, if nobody is working on it.
