### ISSUE TITLE
remove the old refactor API

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1293]
@lxol is it time? :smile: start with a PR to the emacs client?

Then we'll need the thumbs up from @hedefalk  @jvican and @dickwall

**Comment by rorygraves** [comment]
This is not live in sublime yet.

**Comment by hedefalk** [comment]
:+1:

**Comment by lxol** [comment]
shall we keep the old refactoring as a not-default option or get rid of it all together?

**Comment by fommil** [comment]
remove it completely. This was always an opt-in beta test period since it was such a big change, but I'm really happy with it. We can even remove all the old emacs code for showing the preview of the refactor. Might be a big PR of deletions!

**Comment by lxol** [comment]
ok, I will do that next week

**Comment by aemoncannon** [comment]
+1 and that will be a nice chunk of elisp we can purge...

**Comment by Valdaer** [comment]
This will be blocked until removal of old api in all clients, right?

**Comment by fommil** [comment]
@dickwall any ETAs on the refactor move over?

**Comment by hedefalk** [comment]
It has been removed in Atom just to clarify.

**Comment by jvican** [comment]
We didn't even use it. So it's ok :smile:

**Comment by rorygraves** [comment]
Sublime now users new ractoring api - so this is unblocked and good to go.

**Comment by rorygraves** [comment]
PR already open - waiting for rebase.
