### ISSUE TITLE
print tree at point

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1298]
would be very useful for debugging and working around presentation compiler issues

**Comment by aemoncannon** [comment]
+1

I was thinking it'd be cool to have a namespace for experimental rpcs --
XGetTree or whatever.

**Comment by rorygraves** [comment]
To add details - 
Add an API call which defers down to ```showRaw``` on the compiler API.
This would need a companion ticket on emacs/etc to implement the client side rendering.

Thought from @fommil  'There is another way of visualising too, which shows the pseudo scala code'

**Comment by sugakandrey** [comment]
This seems easy enough, going to give it a shot. Also, could someone provide a simple use case example for this?

**Comment by fommil** [comment]
Use case: a macro developer, wanting to print out the AST of the code at point.

or, ENSIME developer wanting to see what the AST looks like in the presentation compiler wanting to do the same.
