### ISSUE TITLE
upgrade to scala-refactoring nightlies / next release

### ISSUE THREAD

**Issue by sschaef** [ensime/ensime-server#1305]
The moment when the dependency to scala-refactoring is updated one will get compilation errors because `PimpedTrees` does no longer exist. For now the change is not yet necessary since ensime-server doesn't depend on the nightlies of scala-refactoring.

The scala-refactoring change responsible for this issue can be found here: https://github.com/scala-ide/scala-refactoring/pull/135

**Comment by sschaef** [comment]
Do you want to depend on the nightlies of scala-refactoring? They are now published to sonatype.

**Comment by fommil** [comment]
cool, we might do that soon.
