### ISSUE TITLE
log trimming is too short

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1314]
the sbt build info from @dwijnand is not appearing in the default output logs because we trim log lines to 250 chars https://github.com/ensime/ensime-server/blob/master/core/src/main/resources/logback.xml#L10

Might be worth thinking about increasing the limit to 500. The point of the trimming is to avoid log bombs when something goes epically wrong and we end up with multi-MB long log lines (e.g. for source files or huge compile `Tree`s)

**Comment by dwijnand** [comment]
(*grumble* *grumble* I wanted to write a test for this *grumble* *grumble*)

What if `Enviornment.info` returned a seq of strings to log instead?

**Comment by rorygraves** [comment]
@dwijnand  I think your suggestion is the right one
