### ISSUE TITLE
RequestHandler FIXME: Find and eliminate all the Option responses legacy

### ISSUE THREAD

**Issue by ancane** [ensime/ensime-server#1316]
Eliminate Option responses according to [FIXME](https://github.com/ensime/ensime-server/blob/cbacc3d37577be93e68a70c597442961d0e998c6/server/src/main/scala/org/ensime/server/RequestHandler.scala#L49)

**Comment by fommil** [comment]
cool! This looks sensible. There might be another handler in the WebSockets side, I seem to recall it being added recently.

Tests failing, can you see the error?
