### ISSUE TITLE
GC on idle

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1318]
We could GC / runFinalizers when no messages have been received in a few minutes. Will keep our heap size down whilst also helping with that annoying file handler issue on windows which won't go away: I'm pretty sure it's VFS and/or #1322.

We should also run GC / finalizers when we restart the presentation compiler (either intentional restarts or actor restart)

**Comment by dwijnand** [comment]
I could have a crack at this at Hack The Tower.

Could you provide some more detail please?

* Where are messages received? An Actor?
* How can we test this behaviour? I think one can inspect runtime heap usage in code, so something around that perhaps.

**Comment by fommil** [comment]
- the `Project.scala` actor, we already have a debounce style pattern that you could use for inspiration for restarting the `Analyzer` actor
- depends what you want to test. Do you just want to test that the message / GC occurs, or that JarFile references are really cleared up? That is really tricky, you might think you can use reflection here, but the JVM lies like a cheap watch. There is a mythical JDNI method for looking up all instances of a class in the JVM, but it apparently needs a native component to be written.

**Comment by fommil** [comment]
btw, I'm pretty sure that https://github.com/ensime/ensime-server/issues/1322 / https://issues.scala-lang.org/browse/SI-9682 is the culprit of some problems I'm seeing.

**Comment by dwijnand** [comment]
I think we can start with a GC occurred because the heap is less, on some threshold.

So perhaps we could:
* dial down the "no messages - let's GC" threshold to 1 second
* generate a bunch of heap, by sending a bunch of messages and doing something
* then stop and register the heap used
* then wait
* then validate that less heap is used, thus proving a GC occurred

I've used Google's Caliper once in a non-production codebase to validate that I'm managing memory.

WDYT?

**Comment by fommil** [comment]
yeah that sounds good! We can't be sure that GC / runFinalizers are doing what we want but I've evidence that in this particular case (unlike the sbt test runners) a GC does actually make a difference. We should also run GC after restarting the PC because that's the exact moment that jarfiles become stale.

**Comment by dwijnand** [comment]
Yeah the approach can get more sophisticated if we're unhappy with immediate results.

When does the PC get restarted? How do we simulate that to test for the GC occurring?

**Comment by dwijnand** [comment]
Do you mind updating the ticket otherwise I'll forget about the PC restart part too. Thanks.

**Comment by fommil** [comment]
the PC is restarted inside `Analyzer.scala`'s `restartCompiler` but also when the `Analyzer` actor itself restarts.

**Comment by dwijnand** [comment]
So how do I simulate either?

**Comment by fommil** [comment]
Just send a message to the analyser actor. The intended restart should be easy, the actor restart probably has some standard akka mechanism.

**Comment by rabbitonweb** [comment]
Hi,
both me & @lukasz-golebiewski met with @rorygraves  last Wednesday. Hack initial implantation. Today I've did some changes to it and it's on https://github.com/rabbitonweb/ensime-server/tree/gc_idle. 

It is not yet PR ready. It lacks: tests, running IdleScheduler actor & (optional) configration in .ensime to set idle time

**Comment by dwijnand** [comment]
ugh..

**Comment by rabbitonweb** [comment]
I want be able to finish it today and it's those are my first commits to Ensime (so they probably suck), maybe u can pick it up tomorrow?

**Comment by dwijnand** [comment]
It's all yours. I'll pick something else tomorrow.

**Comment by rabbitonweb** [comment]
here is PR: https://github.com/ensime/ensime-server/pull/1340
nothing really fancy

i'm sorry for taking it, i think we did not notice the conversation ...

**Comment by rabbitonweb** [comment]
Don't really know how to test that GC occurred. I could write abstraction over `System.gc` but that just seems like an overhead. Any ideas?

**Comment by rorygraves** [comment]
@dwijnand sorry, Mia culpa - didn't follow the discussion and was after a quick ticket - I think there aer actually two tickets in this  - GC on idle and restart the PC occasionally - I know @rabbitonweb 's ticket only addresses the first one.

**Comment by fommil** [comment]
#1322 suggested a remote GC
