### ISSUE TITLE
H2 delete is really inefficient

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1321]
Effectively reopening https://github.com/ensime/ensime-server/pull/1255

I'm noticing insane wait times on Windows for ENSIME to reindex a big jar.

@smootoo's fix is to add an index, but a quick hack didn't work due to performance reasons of creating the index (on a string column). Perhaps we can look at making the filenames foreign keys, which should also reduce the memory footprint.

This makes filewatching useless for me.

I was hoping the graphpocalypse would fix this, but its ages away.

**Comment by smootoo** [comment]
Is there a way for me to reproduce this? Maybe a test that exercises the problematic code paths?

**Comment by fommil** [comment]
Yup, I'll try to create one. For now manual test is the run ENSIME on a big compiled project and then `sbt clean`

**Comment by fommil** [comment]
@smootoo I'll try to make a reproducible test case for this today or tomorrow. If you don't see anything by the end of today, please pester me about it. Now descending into the last of imaginary things ... https://github.com/fommil/imaginary-friend

**Comment by fommil** [comment]
oh drat, I totally forgot to do this. I'll try to find this week as I managed to break the back of the imaginary friend stuff.

**Comment by smootoo** [comment]
I had a quick look at this on a running server and I think there might be some things that can be done to speed things up. Will need to play more.

**Comment by fommil** [comment]
fantastic! Do you still need me to put together an automated test case?

What I was going to do was to create an integration test for a project with loads of dependencies (maybe 100) and a module with loads of target classfiles (say 10,000). After indexing (which will take a couple of minutes), save the H2 for future use. Then we simulate removing the classes all at once.

The test should be more dramatic if run on Windows, or a slow hard drive. I have a Windows 7 VirtualBox image with sbt/java/emacs all preloaded if you'd like access to it?

I'm pretty sure a more judicious use of foreign keys, instead of using `String` keys everywhere, would be far better.

Automating this would hugely slow down and complicate our CI, so I'm not sure I'd want it to run all the time, but as a local test it could be ok (and also then normalising the timings of before / after any fixes are more reliable if restricted to one machine).

**Comment by fommil** [comment]
Hmm, I wonder if running ensime on `ensime-server` itself would generate a good enough example.  Then it should be a simple case of saving the `.ensime_cache` after everything is all committed for a fully compiled `ensime-server` and then firing off delete messages for every single `.class` file that is in the database, in a random order, to the `SearchService`.

**Comment by smootoo** [comment]
I've been playing with it on Slick. It's a monster project. I can see why it would be slow. Haven't had change to have a look at tweaking it yet. Got some interview prep to do. Is it ok if I look at it some time this week or is it more urgent than that?

**Comment by fommil** [comment]
That's fine! It's not super urgent. I flagged it as "priority" just so I knew what the next thing on my hit list should be, but I have a workaround.

**Comment by fommil** [comment]
@smootoo still slow :disappointed: your idea of selectively disabling MVCC sounds good. I'll try to do a hack along those lines.

**Comment by fommil** [comment]
`MVStore.freeUnusedChunks` is now the bottleneck for me according to YourKit. Deleting / resizing files on my Windows box is ridiculously slow, I wonder if this is related.

**Comment by fommil** [comment]
actually, it might still be really slow, but it is definitely faster than it was. If compile time is on par with H2 delete time, this might just about work.

**Comment by fommil** [comment]
hell, building an in-memory cache might make sense at this point.

**Comment by smootoo** [comment]
I don't have a windows box to reproduce the problem you are seeing, but I strongly suspect the filesystem is the problem. I do see the size of the db file growing and shrinking significantly during a clean/rebuild cycle. If that is slower on windows than on linux, that could be why it seems so bad for you. Try ;MVCC=FALSE maybe?

Without any evidence, I suspect an in-memory cache for local, transient class files and a persistent cache for jar based artefacts that don't disappear on a whim, and that could be shared between projects, might be the optimum configuration.

**Comment by fommil** [comment]
yeah, that'd be awesome. Probably a bit tricky to implement that so I'll try the MVCC config option and also consider an in-memory option and maybe bringing that index back now that its a foreign key and not a full String per row.

I didn't notice the file changing size on my windows box though. I see the problem on a **huge** jar file, about 2,000 source files all in (mixed java / scala). It was ok on smaller projects.

**Comment by fommil** [comment]
we could also try to mitigate the problem in the typical case by uses hashes of the classfiles, but that's just avoiding the real problem. If H2 had a real UPSERT option, that would also be good.

**Comment by ChrisCoffey** [comment]
FWIW, I'm pretty sure H2 supports "UPSERT" via MERGE or if you run it in MySql mode via the `insert ... on duplicate key update` clause.
