### ISSUE TITLE
REST endpoint to release JarFile references

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1322]
Another file handler bug in the scala-compiler, this time from `ScalaClassLoader` (the following on scala 2.10) might need another monkey patch // @retronym

#1318 is a potential workaround.

```
"Name","Retained Size","Shallow Size","Level"
"java.util.jar.JarFile name = ""D:\path\to\my\packageBin.jar""","792","64", "1"
"jar of sun.misc.URLClassPath$JarLoader","360","48", "2"
"[348] of java.lang.Object[549]","2216","2216", "3"
"elementData of java.util.ArrayList size = 432","2240","24", "4"
"loaders of sun.misc.URLClassPath","477176","40", "5"
"ucp of scala.tools.nsc.util.ScalaClassLoader$URLClassLoader","686248","88", "6"
"macroClassloader of scala.tools.nsc.Global$$anon$1","862176","328", "7"
"analyzer of org.ensime.core.RichPresentationCompiler [Stack Local]","317419832","1952", "8"
"compiler of scala.tools.nsc.interactive.PresentationCompilerThread [Thread, Stack Local ← this]  ""Scala Presentation Compiler []"" native ID: 0x8E0","1688","112", "9"
```

**Comment by fommil** [comment]
highly relevant https://github.com/sbt/junit-interface/issues/67

**Comment by fommil** [comment]
what the hell, github

**Comment by fommil** [comment]
raised as https://issues.scala-lang.org/browse/SI-9682

**Comment by fommil** [comment]
we might be able to do something with a monkey patch.

**Comment by fommil** [comment]
possibly even a REST API endpoint that sbt can hit to force a GC (and a prescompiler pause / restart) would be good.

**Comment by ChrisCoffey** [comment]
Is this in progress or can should pick this up?

**Comment by fommil** [comment]
might be better if you pick up something else, I'm working on a potentially much better solution to this, see https://github.com/fommil/class-monkey

**Comment by fommil** [comment]
Closing this because class monkey fixes it, w0000000t!
