### ISSUE TITLE
support custom deprecated annotations

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1331]
Some teams have their own deprecated annotations to work around the inability to disable deprecation warnings (and therefore get the benefit of fatal-warnings). It would be good to support user-defined deprecation annotations. e.g. anything called `deprecated` or `deprecating`

https://github.com/ensime/ensime-server/blob/5528de132e6b87682bb95e8ba93434f924c71dc3/core/src/main/scala/org/ensime/core/SemanticHighlighting.scala#L56

**Comment by rabbitonweb** [comment]
how should we distinguish which annotations are the 'deprectaing' ones? just by name ("e.g. anything called deprecated or deprecating") or some kind of project specific user configuration?

**Comment by fommil** [comment]
Just by name. This is a niche feature just to support my use at work, so no need to complexify my offering customisation.

**Comment by rabbitonweb** [comment]
Awesome, I think I will pick that as it seems good entry point

**Comment by fommil** [comment]
that'd be pretty cool! It might even be an idea to introduce our own `@deprecating` annotation too and use it in the public API. That way we can give hints to clients and ourselves, without failing the compile.

**Comment by rorygraves** [comment]
Cross reference - PR raised: 
https://github.com/ensime/ensime-server/pull/1334
