### ISSUE TITLE
why i have to download so many more package, even i already have them in my .ivy2?

### ISSUE THREAD

**Issue by zzguiji** [ensime/ensime-server#1335]
Every time I type-in `gen-ensime` when I make a small change in my `build.sbt`.

Ensime server will download as many as the project used packages again...

Now, I am update my `play framework` to `2.5.0` the `ensime` download almost the whole dependenses...

**Comment by fommil** [comment]
To post this ticket you bypassed the Getting Help page on ensiwe.org, choose the wrong issue tracker and explicitly ignored the github issue template and advice on how to get help. Please go back to the beginning.
