### ISSUE TITLE
Investigate a possible bug in WatchService on Linux

### ISSUE THREAD

**Issue by lxol** [ensime/ensime-server#1337]
As per this blog http://blog.omega-prime.co.uk/?p=161 it is possible that events can be discarded if we  are registering watches while simultaneously receiving events. 
We can add a property based test to verify that our implementation of the watcher is not affected by the bug.

**Comment by fommil** [comment]
@lxol did you look into this already?

**Comment by lxol** [comment]
When I run ensime-java7-watcher tests in parallel I saw random failures that look like what is described in the blog. Some events are either missing or detected by an unrelated watcher.

I think that to workaround the issue we can run a post registration function that finds all created and modified files in the last 1 second and resends  `ENTRY_CREATE` and `ENTRY_MODIFY` events. That could result in the duplicated events  but I think it is better than missing them completely.  `ENTRY_DELETE` will be lost with this approach.

Alternatively we can just do nothing about the bug. I think that in real life situation the chance of a clash between the registration and receiving event is very low.

**Comment by fommil** [comment]
When lots of events arrive, we debounce in the receiver so dupes are ok

**Comment by fommil** [comment]
you've got this one covered, right?
