### ISSUE TITLE
backpressure in the file indexing

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1341]
Currently, in the `SearchService`, we aggressively index the user's classfiles. However, this leads to memory usage explosions when the database write is too slow.

Make it use backpressure so we limit how many classes are being indexed at any one time. ensime server heap usage could be dramatically reduced.

**Comment by fommil** [comment]
#1351 would probably make this trivial

I say Low Hanging Fruit, but only for somebody with experience of doing this sort of thing.

**Comment by ChrisCoffey** [comment]
Is this any more complicated than using a bounded mailbox for the `IndexingQueueActor`?

**Comment by fommil** [comment]
Yup. We're not using actors for this code. But I'm OK with blocking a thread to achieve backpressure, especially since I want to rewrite all this code to use something more like clojure SCP channels (and replace akka everywhere else with SCP)

**Comment by fommil** [comment]
And also bounded queues don't achieve barkpressure, don't they just drop messages?

**Comment by fommil** [comment]
Are you interested in looking at this? It would really help keep memory under control. I don't think it's too hard to get something working.

**Comment by ChrisCoffey** [comment]
I believe you can make them block if you set the mailbox timeout to infinite. That being said, if the plan is to remove Akka anyways we're better off replacing the `IndexingQueueActor` entirely. 

From my reading of the code, I think we can get away with using a `java.util.concurrent.LinkedBlockingQueue` and drop the actor. I did something like this a few months ago at work.

**Comment by ChrisCoffey** [comment]
Sure, I'll take a stab at it this weekend.

**Comment by fommil** [comment]
That actor isnt the bit that needs the backpressure (well, it does, but it's not the priority), I don't think. It's the indexing during refresh.

**Comment by fommil** [comment]
I'm going to be out all day on Saturday but I'll be hacking on ensime all day sunday/monday.

**Comment by ChrisCoffey** [comment]
Cool, I'll be online then too, albeit EST.

**Comment by ChrisCoffey** [comment]
on #1436 @fommil said:

> @ChrisCoffey before I start teaching granny to suck eggs, how much of the reactive manifesto and sequential concurrent programming are you familiar with?

>There is so much buzzword bingo around the reactive manifesto that I wouldn't even consider sending you near it if you're new to it, but for SCP (and perhaps other paradigms that may be new to you) I strongly recommend Seven Concurrency Models in Seven Weeks by Paul Butcher. Clojure is used as the example but there is a scala implementation (not battle tested) in #1351 which could form the basis of a better model than akka going forward.

**Comment by ChrisCoffey** [comment]
Had to google *teaching granny to suck eggs*. Great phrase.

I read the reactive manifesto years ago and yes, it's buzzword soup. I'm also familiar with SCP, but mostly via Haskell's `MVar` and `Chan` (basically single cell or unbounded channels). I gave the chapter on SCP a re-read this morning & I can see how something like a `go` block would help with `refresh`. 

That being said, after playing with YourKit I have a much better picture of exactly where the allocations are taking place. I'll read through the code for pfn/scala-csp this afternoon when I have some time.

**Comment by fommil** [comment]
we don't need to be that fancy, I'd be fine with a mutex in the classfile indexing bit (yeah yeah) and something that releases it in the persistence side, maybe allowing something like 100 classfiles to be indexed at a time (which includes classfiles inside a jar).
