### ISSUE TITLE
project/server config as HOCON or JSON

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1346]
it would be good if we had a ServerConfig as well as an EnsimeConfig, and if both were in HOCON or JSON so that clients don't have to implement an s-expression parser.

**Comment by fommil** [comment]
and when we do this, perhaps we should change the `.ensime` structure so that each project configuration is explicitly listed (i.e. `compile`, `test`, `fun`, `it`)

**Comment by fommil** [comment]
@yyadavalli how about this one? :smile:

**Comment by fommil** [comment]
the `.ensime` format changes are already tracked in another ticket

**Comment by yyadavalli** [comment]
I was thinking of doing https://github.com/ensime/ensime-sbt/issues/217 first, but either one should be fine

I think finishing this before #1608 would be better, we can avoid rewriting `SexpParser.scala`

**Comment by yyadavalli** [comment]
I believe we can use https://github.com/typesafehub/config with HOCON

**Comment by fommil** [comment]
yeah that would be good! for the sbt one make sure to sync up with @sugakandrey so that you don't duplicate each others work. Maybe communicate on the gitter ensime-server channel? I think the sbt one would be more important than this.

The clients won't need to read the (new) server config files, but the clients will still need to read the `.ensime` files. There might be (or should be) a separate ticket to make the format of `.ensime` optional.

My hope with "server config files" (as opposed to "project config files") is that we can introduce a bunch of user preferences there, that are currently hard coded or hacked with system properties.

**Comment by yyadavalli** [comment]
Yup, agreed on everything.

The clients can determine whether to read a Sexp or HOCON `.ensime` with their own preferences. They will optionally communicate the format to ensime-server at startup, with the default formats based on protocol. 

I can think of a couple of system properties that can be moved to a `ServerConfig` object, I am sure we can provide more options as we move forward. `ServerConfig` does not involve the clients at all, we read it off and persist to project `:root-dir` for each instance of the server.

**Comment by yyadavalli** [comment]
Any thoughts on using typesafehub/config

**Comment by fommil** [comment]
yeah, it's a java library... I had assumed we'd use it :smile:

but we might want to write a little typeclass derivation thing using shapeless so we don't need to write custom parsers. might be fun... have you seen my shapeless for mortals workshop video? https://github.com/fommil/shapeless-for-mortals

I am aware of a few projects that do this, but they use their own macros and we're trying to reduce external dependencies.

**Comment by yyadavalli** [comment]
I don't think we'll need to write a custom parser, they have a parser packaged, I am not sure of its capabilities

But, yeah I'd be nice to write something with shapeless, a good learning experience for me. I have seen the workshop, it's really good. Haven't tried to do anything with that till now..

**Comment by fommil** [comment]
sorry, parser was the wrong word. I mean a way of converting from a `Config` object into any sealed family. If you want examples beyond the workshop, have a look in the graph branch and what we do for writing to orientdb.

**Comment by fommil** [comment]
you probably don't need to handle Coproduct, just products (HList)

**Comment by vil1** [comment]
FWIW there's https://github.com/kxbmap/configs that does a pretty good job at converting HOCON blobs into case classes instances. Might need 2.11.11 or typelevel compiler for things that bump into SI-7046 (namely hierarchies of sealed trait and case classes).
I'm afraid that comment comes a bit late though.

**Comment by fommil** [comment]
@vil1 yeah there are a few... but we have to aim for zero deps since we are tooling :expressionless:

**Comment by vil1** [comment]
fair enough ;)
