### ISSUE TITLE
transient debugger failure

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1347]
we've seen this a lot recently

```
[info] - should trigger/continue *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: expected DebugBreakEvent(DebugThreadId(1),main,/tmp/1457800313085-0/testing/debug/src/main/scala/breakpoints/Breakpoints.scala,32), found DebugThreadStartEvent(DebugThreadId(1))
```

e.g. http://fommil.com/ensime/ensime-server/268/2

**Comment by chipsenkbeil** [comment]
So it's not just me that's been seeing this error. I hadn't even touched the debug code yet when I encountered that error.

**Comment by scalanatortest** [comment]
No. Sees there is a second thread started message lucking about. We were not paying the errors proper attention

**Comment by rorygraves** [comment]
Lets  try that again - 
No. Sees there is a second thread started message lucking about. We were not paying the errors proper attention

**Comment by fommil** [comment]
I think the probability increased on well in my branch that spawned the process and attached.

**Comment by fommil** [comment]
FYI this is the branch I mean https://github.com/fommil/ensime-server/tree/debug_attach it's gone stale because it's not been a priority for me for some months, but hopefully there are some salvagable ideas in there.

**Comment by rorygraves** [comment]
Yep - two threads.....
```
[info] - should highlight varFields
460125476 - DebugThreadStartEvent: 348
460125476 - DebugThreadStartEvent: 1
[info] - should inspect variables *** FAILED ***
```

**Comment by rorygraves** [comment]
Just running more tests with the thread names as well

**Comment by fommil** [comment]
I think I've got to the bottom of this. It looks like even on Linux with an attach process we get the same thing. On startup we can listen for up to three messages and they will be

- `DebugBreakEvent`

and possibly none/either/both of

- duplicate `DebugBreakEvent`
- `DebugThreadStartEvent`

this probably points to a bug deep inside our debugging manager, but for now I'm considering this startup behaviour to be "expected" and writing the tests accordingly.

Did I mention how much I hate akka?
