### ISSUE TITLE
relative paths in .ensime

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1357]
as suggested by @soc and @dwijnand it would be good to have `HOME` and `root-dir` expansion in the `.ensime` file.

Will need editor support as well, but in terms of the server this could be implemented similarly to the `Canon` which is a filter on all `File`.

**Comment by fommil** [comment]
we could go one further in the indexer and support relative paths there, but let's restrict this to the reading of `File` off the wire / config file.

**Comment by dwijnand** [comment]
Depending on if we do ENSIME hacking at the next SLUG hack day or not, I might have a go at this (unless you were just about to take this one right now, if so don't stop on my account).

**Comment by dwijnand** [comment]
Tail-end of the Twitter conversation: https://twitter.com/fommil/status/712571272216059904
