### ISSUE TITLE
Add generics to RawClassfile

### ISSUE THREAD

**Issue by asznajder** [ensime/ensime-server#1362]
`RawClassfile` class represents a _.class_ file that's a result of Java/Scala code compilation. What's currently missing in its current representation is the generics part. It's implemented now as an `Option[String]` whereas it would be great to have a domain object instead.

**Comment by fommil** [comment]
Possibly related to #472

**Comment by fommil** [comment]
Needs some design work on what the domain objects would look like.

**Comment by asznajder** [comment]
I will be happy to work on this next week.

**Comment by fommil** [comment]
probably a `List[FullyQualifiedName]` would be my guess at something more sensible.

**Comment by asznajder** [comment]
Since `generics` field in `RawClassfile` has really the following grammar:

_**TypeSignature**: Z | C | B | S | I | F | J | D | FieldTypeSignature
**FieldTypeSignature**: ClassTypeSignature | [ TypeSignature | TypeVar
**ClassTypeSignature**: L Id ( / Id )* TypeArgs? ( . Id TypeArgs? )* ;
**TypeArgs**: < TypeArg+ >
**TypeArg**: * | ( + | - )? FieldTypeSignature
**TypeVar**: T Id ;_

I would like to suggest creating domain objects that are consistent with it. 

`sealed abstract class TypeSignature`
 `case class PrimitiveTypeWrapper(className: ClassName) extends TypeSignature`
 `sealed abstract class FieldTypeSignature extends TypeSignature`
 `case class ArraySignature(arrayType: TypeSignature) extends TypeSignature`
 `case class TypeVar(name: String) extends TypeSignature`
 `case class ClassTypeSignature(className: ClassName, typeArgs: List<TypeArg>) 
 `case class TypeArg(boundType: Option[Char], typeSignature: FieldTypeSignature)`

`ClassTypeSignature` doesn't handle inner types in this form and something might be wrong, but I wanted only to quickly give some insight.

Anyway, `generics` field in `RawClassfile` would be then of type: 

`case GenericClass(typeParams: Option[TypeParam], signatures: List[ClassTypeSignature])`

I know that, it looks a bit complicated, but current domain classes are not enough to handle all cases and properly change something like: `<A:Ljava/lang/Object;>Lscala/collection/AbstractSeq<TA;>;Lscala/collection/immutable/LinearSeq<TA;>;Lscala/Product;Lscala/collection/LinearSeqOptimized<TA;Lscala/collection/immutable/List<TA;>;>;Ljava/io/Serializable;` into domain objects. 

Are you ok with this approach?

**Comment by fommil** [comment]
It's in the right direction but try to reuse the existing domain objects as much as possible. Have a study of  the FullyQualifiedName trait.

**Comment by fommil** [comment]
Can we avoid using the word "type"? It has a more specific meaning in the context of Scala. I see you are using the ClassName trait. That's good.

**Comment by fommil** [comment]
Possibly use Generic instead of Type here.

**Comment by fommil** [comment]
BTW there is no reason why you can't add existing domain objects to a new type hierarchy in the same file. That might allow you to remove some of the encapsulation boilerplate.

**Comment by fommil** [comment]
@asznajder did you find any more time to look at this? :smile:

**Comment by asznajder** [comment]
Yes! Worked a bit on it last week. Looking for some free time slot to finish. Sorry that it takes so long but I have a lot of things on my head recently.

**Comment by fommil** [comment]
you might want to look at the date on tickets that I pick up, and the date (and **year**!) they eventually get merged, if you want to feel better :stuck_out_tongue:
