### ISSUE TITLE
Provide search context

### ISSUE THREAD

**Issue by asznajder** [ensime/ensime-server#1365]
It would be great to provide to `searchClasses` and `searchClassesMethods` methods in `SearchService` some kind of search context (user's module etc.). Without such data, it might be much harder to implement #1363.

**Comment by ChrisCoffey** [comment]
What's an example usecase for this? I can't think of a time when I knew the type and part of the method I wanted; i.e. isn't jumping directly to the type then a quick search/ browse w/in there enough?

**Comment by fommil** [comment]
The idea was that only things you could see from your current module would be visible. Perhaps more useful for import searches because I think most uses of search want to be global.

**Comment by ChrisCoffey** [comment]
Okay, I agree that import visibility makes sense.
