### ISSUE TITLE
Create requests / responses classes just for Java usage

### ISSUE THREAD

**Issue by asznajder** [ensime/ensime-server#1366]
`receive` method in `JavaAnalyzer` dispatches the requests from user depending their type. Create a sealed family of requests / responses just for Java usage. Currently for Java we use the same requests / responses classes as for Scala.

**Comment by rorygraves** [comment]
https://github.com/ensime/ensime-server/blob/master/core/src/main/scala/org/ensime/core/JavaAnalyzer.scala#L53

@aemoncannon  Not quite sure what you are after here, care to clarify - do you want to seperate out all of the Scala and Java calss?

**Comment by fommil** [comment]
I think that was me. It was a suggestion that we eventually have a dedicated protocol for Java. This is huge, it's not suitable for a one evening hack.
