### ISSUE TITLE
Create diffs for NewFile and DeleteFile edits in FileUtil.

### ISSUE THREAD

**Issue by asznajder** [ensime/ensime-server#1368]
`FileUtil` in `writeDiffChanges` method should be able to handle not only `TextEdit`s, but also changes that are of types `NewFile` and `DeleteFile`. Depending on the type of `FileEdit`, different `FileEditHelper.diffFrom*` method should be called. The missing ones are `FileEditHelper.diffFromNewFile` and `FileEditHelper.diffFromDeleteFile`. They are necessary to create diff files with proper contents.

**Comment by fommil** [comment]
This would be a good one! I think it might be a dupe as I remember @greenrd wanting to look at it.

**Comment by fommil** [comment]
dupe of #1283
