### ISSUE TITLE
Add nice stop method to MonitorOutput

### ISSUE THREAD

**Issue by asznajder** [ensime/ensime-server#1374]
`MonitorOutput` is a `Thread` that doesn't have any `stop` method.

**Comment by rorygraves** [comment]
So this class runs a thread (because of Java nastiness) - needs a clean way of shutting down - a stop method that does an appropriate interrupt and triggers a resource cleanup.

**Comment by rorygraves** [comment]
This is ```org.ensime.core.debug.MonitorOutput```
My personal preference as well is to not have that class extend Thread, but hide the thread within the class.

**Comment by rorygraves** [comment]
Also whilst we are here - can we add a threadName to the parameters (out/err) and add that to the log statement, otherwise you never know which thread has blown up.
