### ISSUE TITLE
BasicWorkflow ambiguous TODO

### ISSUE THREAD

**Issue by asznajder** [ensime/ensime-server#1382]
The TODO in `BasicWorkflow` is as follows:

_// TODO get the before content of the file_

It was between `PrepareRefactorReq` and `ExpandSelectionReq` result check.

Unfortunately, I couldn't figure out what should be done here. Probably more context needed.

**Comment by fommil** [comment]
Oh I think I know. It was about getting the file before the operation, as a String, then doing something, then checking the file changed. Maybe.
