### ISSUE TITLE
Workaround for Java 6 in UnsafeHelpers 

### ISSUE THREAD

**Issue by asznajder** [ensime/ensime-server#1383]
Unfortunately, I don't have enough context to explain this issue in `UnsafeHelpers`. The TODO is:

_TODO: Workaround for java 6
case t: JCMemberReference => Some(t.sym)_

**Comment by fommil** [comment]
Oh, I know that one. When raising your PR change the `TODO` to `JAVA6`.

**Comment by fommil** [comment]
(that class doesn't exist in Java 6, but the code was copied from a Java 7 version of Netbeans)
