### ISSUE TITLE
Move ScalariformFormat to org.ensime.server.protocol

### ISSUE THREAD

**Issue by asznajder** [ensime/ensime-server#1385]
`ScalariformFormat` is in `org.ensime.config` package. The original TODO is:

_TODO sexp formatting should live in server.protocol_

Actually, I think that it should be moved to `org.ensime.sexp.formats`. Please ack.

**Comment by fommil** [comment]
definitely not `org.ensime.sexp.formats` because that's a general S-Expression library whereas this is ensime protocol specific.

**Comment by fommil** [comment]
argh, but the problem is that it is used by the config, not in the protocol. Hmm. Let's just drop this one.
