### ISSUE TITLE
Don't change files on the server side in Refactoring

### ISSUE THREAD

**Issue by asznajder** [ensime/ensime-server#1386]
When we `execRefactor` we still apply the changes on the server side. It was said in #996 that it would be much better to move it to client. @rorygraves comment on this:

> The current refactor undo is very fragile if, between doing refactor and undo you make other non-refactor edits. The idea is by supplying the information to the client 'these 4 files need these changes', the client can insert them into its undo stack allowing IntelliJ style 'are you sure you want to undo 'refactor name' operation?' 2.0 feature as it requires a non-trivial amount of client side work otherwise we break the existing refactoring support.

**Comment by fommil** [comment]
oh this is closed by #1354
