### ISSUE TITLE
Highlighting constructors - ambiguous TODO

### ISSUE THREAD

**Issue by asznajder** [ensime/ensime-server#1387]
In `SemanticHighlightingSpec` highlighting constructors test we have the following TODO:

_TODO It would be better if the "new" was consistent._

What did you mean by this?

**Comment by rorygraves** [comment]
https://github.com/ensime/ensime-server/blob/master/core/src/it/scala/org/ensime/core/SemanticHighlightingSpec.scala#L79  - not sure who the original author is (this code was moved - probably worth working that out from git history and pinging them.

**Comment by fommil** [comment]
is it that `new` sometimes has `()` and sometimes doesn't?
