### ISSUE TITLE
Improve test case  generation of ArbitrarySexp

### ISSUE THREAD

**Issue by asznajder** [ensime/ensime-server#1388]
Improve ```ArbitrarySexp```

_// TODO: String/Char should be selected from a wider range
  // TODO: arbitrary[BigDecimal] but it freezes the tests
  // TODO: cons in SexpCons car, but it dramatically slows things_

**Comment by rorygraves** [comment]
https://github.com/ensime/ensime-server/blob/master/s-express/src/test/scala/org/ensime/sexp/SexpParserCheck.scala#L43

This might not all be low hanging fruit - but some investigation here should be informative
