### ISSUE TITLE
Finding classes in method signatures - ReferenceInClassHunter

### ISSUE THREAD

**Issue by asznajder** [ensime/ensime-server#1390]
TODO - _"we need a classesInSignature (which needs the ability to parse signature)"_

I might not have enough context but possible that this issue is outdated. We already have `classesInDescriptor` method. Wouldn't `classesInSignature` redundant in our use case?

**Comment by rorygraves** [comment]
https://github.com/ensime/ensime-server/blob/master/core/src/main/scala/org/ensime/indexer/ClassfileIndexer.scala#L111
