### ISSUE TITLE
FLX searching

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1397]
I'm so used to flx based searching in emacs now that I really miss it when using the searchservice because it only supports CamelCase. I wonder if the list of FQNs is perhaps small enough that we can apply the standard FLX algorithms, e.g. flx-ido.

**Comment by ChrisCoffey** [comment]
Looking at the server log for this project, we indexed ~320k fqns. We should be able to filter the full set down into manageable number by chopping the input into n-grams & searching for those in the index with a simple `DisjunctionMaxQuery`.

Selfishly, I would love to have this kind of fuzzy search exposed to the vim plugin.

**Comment by fommil** [comment]
I think this was closed by #1769
