### ISSUE TITLE
Refactoring: add import

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1401]
As @aemoncannon has noted, it would be good if adding an import was a server-side job.

Blocked on https://github.com/scala-ide/scala-refactoring/issues/154

**Comment by bomgar** [comment]
```

**Comment by bomgar** [comment]
I was surprised that the server actually supports adding an import. This code works:
```elisp
(ensime-refactor-diff
       'addImport
       `(file ,buffer-file-name qualifiedName ,qualified-name))))
```

But it only adds the import to the end of the import list. The elisp code does a much better job at the moment.

**Comment by fommil** [comment]
Also surprised :-) but at least that gives somewhere to start.

**Comment by fommil** [comment]
whatever we do it should agree with our organise import list e.g. in #1838 

I'm happy for a hack that doesn't use scala-refactoring
