### ISSUE TITLE
javacOptions for java analyser

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1405]
We currently ignore the user's `javacOptions` but we should really be passing them to the java analyser.

Will require an extra field added to the `EnsimeConfig` and support in ensime-sbt to add the flag.

**Comment by mwielocha** [comment]
Hi, requested pull for sbt part of this, also I have the server part but don't really have an idea how to test it. Plus while experimenting with common javac options like -source 1.6, I'm getting NPE from com.sun.tools.javac.util.ClientCodeException. Might need some help on this.

**Comment by fommil** [comment]
Cool! I'll have a detailed look in the next day or too.

**Comment by mwielocha** [comment]
All you need to do to replicate the NPE is to add -source 1.6 in JavaCompiler line 65: 
```scala
compiler.getTask(null, fileManager, listener, List(
      "-cp", cp, "-Xlint:" + lint, "-proc:none", "-source", "1.6"
    ).asJava, null, files).asInstanceOf[JavacTask]
```
And run JavaCompilerSpec.

**Comment by fommil** [comment]
This might have something to do with us using a version of netbeans libraries that targets the Java 7 api, but still runs on Java 6. Thanks for the repro. Please ping me if I forget to look at this, I'm under a lot of stuff right now.

**Comment by mwielocha** [comment]
Seems that removing netbeans didn't help on this one. I did some digging and I think this might have something to do with [https://blogs.oracle.com/darcy/entry/bootclasspath_older_source](url), anyway adding `-bootclasspath` as na options partially fixes the problem (still throws an exception on `JavaCompilerSpec` - unfortunately). Don't know where to go from here.

**Comment by jozi-k** [comment]
I think this is already solved.

**Comment by fommil** [comment]
No it's not implemented yet.
