### ISSUE TITLE
Ensime loses its mind with minimally sophisticated use of Shapeless + Slickless.

### ISSUE THREAD

**Issue by johanatan** [ensime/ensime-server#1415]
### Steps to reproduce

1. Add Slick & Slickless as dependencies to your project.
2. Implement a Slick table.
3. Implement a query based on the table that returns an HList.

### Expected behaviour
Everything compiles fine and Ensime doesn't lose its mind.
...

### Actual behaviour
Ensime loses its mind.
...

**Comment by fommil** [comment]
Can you please follow the steps at http://ensime.org/getting_help

I'll close this until you've confirmed that it is a bug by giving us a detailed reproduction.

**Comment by johanatan** [comment]
After following that guide (reinstalling sbt-ensime and ensime for emacs) I am still getting the following errors:

```
ERROR: not enough arguments for method map: (implicit shape: slick.lifted.Shape[_ <: slick.lifted.FlatShapeLevel, Nothing, T, G])slick.lifted.Query[G,T,Seq]. Unspecified value parameter shape. : line 35
ERROR: diverging implicit expansion for type slick.lifted.Shape[_ <: slick.lifted.FlatShapeLevel, Nothing, T, G] starting with method repColumnShape in trait RepShapeImplicits : line 35
ERROR: value ->> is not a member of String : line 36
ERROR: exception during macro expansion:  java.lang.IllegalArgumentException: argument type mismatch  : line 36
```

but I don't have time to create a minimal reproduction. If you try following my steps to reproduce, you should see simliar errors.

**Comment by fommil** [comment]
This isn't even nearly a reproduction.

**Comment by johanatan** [comment]
Did I claim it was?

**Comment by fommil** [comment]
You didn't follow the Getting Help or Troubleshooting guides: we're aggressively closing tickets which don't follow that process to improve the quality of our tracker and to make it easier for people to contribute to the remaining open bugs. If you want assistance with fixing this bug, you need to provide a reproduction.

As requested many times in the documentation,  please don't raise any more tickets without the details that we have kindly requested, and please read the documentation that we have spent a lot of time working on. This ticket in particular is almost certainly one of the FAQ tickets that is discussed several times in the docs.

**Comment by johanatan** [comment]
You're right. My apologies. I skipped steps #4 & #5 since they were not actionable and forgot to go back and check them after completing step 6 without success.

**Comment by johanatan** [comment]
FYI for anyone following along-- problems with Shapeless can go direct here (rather than "following 'getting help' or 'troubleshooting guides' and bothering with re-installing the world):

https://github.com/ensime/ensime-server/issues/673

**Comment by fommil** [comment]
I certainly wouldn't say you're out of luck, there are projects you can get involved in to help out. They are referenced in the ticket.
