### ISSUE TITLE
use java.nio instead of java.io, VFS and File

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1437]
as part of the "move to Java 7" effort.

Will negate the need to do #1257 so we can just close that ticket if it doesn't make it into 1.0.

**Comment by fommil** [comment]
https://github.com/fommil/ensime-server/blob/jar-urls/util/src/main/scala/org/ensime/util/ensimefile.scala

**Comment by rumoku** [comment]
i'm picking it up.

**Comment by fommil** [comment]
@rumoku hi, I added the utils to the 2.0 branch so you should be able to rebase and avoid conflicts now :smile: let me know if you need any help. I also forgot to give you some ENSIME stickers on Saturday, I'll do that next time.

**Comment by fommil** [comment]
we're susceptible to this known JDK issue until we move over to NIO https://bugs.openjdk.java.net/browse/JDK-8024496

**Comment by arigoldx** [comment]
@fommil is this that ticket you were talking about on gitter?

(Asking 'cause it mentions java.io vfs not apache vfs.)

**Comment by fommil** [comment]
This is the one. There is a comma missing between java.io and vfs

**Comment by arigoldx** [comment]
Woohoo! Thanks!

(:eyes:)
