### ISSUE TITLE
use scalafmt

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1439]
We encouraged Eugene to find a student strong enough to do this https://github.com/olafurpg/scalafmt
 I suppose we should use it :-D

1. they need to get regression parity with scalariform (pre and post trailing newlines "fix")
2. we need `ensime-sbt` support to reference a config file (lets not try to marshall the settings again)

so probably 2.0+.

**Comment by jodersky** [comment]
> lets not try to marshall the settings again

+1 on that

**Comment by fommil** [comment]
until scala.meta can support scala 2.10, we can't do this :sob: 

https://github.com/scalameta/scalameta/issues/295

**Comment by kozikow** [comment]
Not sure if this is a right place to post this comment, but prior to enabling scalafmt on a project it is probably required to have a good support in Emacs, as it's popular among ensime developers.

There is no Emacs library for it, but I briefly looked into it and it's relatively easy to
repurpose https://github.com/paetzke/py-autopep8.el and use scalafmt CLI to enable
scalafmt on save in Emacs.

**Comment by fommil** [comment]
@kozikow the support you're asking for would be provided via the sbt plugin. No need for Emacs support.

**Comment by fommil** [comment]
we are very close to having scalariform via sbt, scalafmt will be the same and won't be supported server side (no need!).
