### ISSUE TITLE
DocResolver creating incorrect URLs for java8 standard library functions

### ISSUE THREAD

**Issue by halcyon** [ensime/ensime-server#1440]
### Steps to reproduce

Attempt to look up documentation at point for any java 8 standard library function e.g. [static IntStream range(int startInclusive, int endExclusive)](http://docs.oracle.com/javase/8/docs/api/java/util/stream/IntStream.html#range-int-int-)

### Expected behaviour
It should open the documentation for the range function http://docs.oracle.com/javase/8/docs/api/java/util/stream/IntStream.html#range-int-int-

### Actual behaviour
It does not fully transform the anchor part of the URL, and leaves a comma between the arguments - causing the page to not open at the function being looked up.
e.g. http://docs.oracle.com/javase/8/docs/api/java/util/stream/IntStream.html#range-int,int-

**Comment by fommil** [comment]
Cool, would you like to look at this? I have a branch doing similar things for method FQNs

**Comment by fommil** [comment]
Ha, awesome, you already have.
