### ISSUE TITLE
build index and exit

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1445]
An enabler for #1208 it would be good (and easy) to be able to index a project from the CLI.

Use cases include:

- part of an automated workspace setup (I do this a lot at work) so that initial ENSIME indexing (and CTAG building etc) can all be triggered from a single command.
- simplifying our emacs integration tests

and could possibly even be used as a way to cache and speed up our own `it:test` configuration runs.

**Comment by yyadavalli** [comment]
Hi, I'm trying to get started on this
If my understanding is correct we need something that's sort of a client (similar to vim client) that will start the ensime server, wait till the index is built/updated and then close it.
Please correct me if this approach is wrong

**Comment by fommil** [comment]
no, even simpler. It can just be a main method that we invoke directly, waits for the index refresh to finish, then exits cleanly. In fact, no reason we can't just pass a flag to the existing main.

I **did** say Low Hanging Fruit :grinning:

**Comment by yyadavalli** [comment]
Hmm, so something like

```
val ensimeFlag = propOrNone("ensime.flag").getOrElse("")

val mainActor = system.actorOf(Props(new ServerActor(config, protocol)), "ensime-main")

val indexingComplete = // check if indexing is completed

if(ensimeFlag == "indexOnly" && indexingComplete)
  mainActor ! ShutdownRequest("Completed indexing", isError = false)
```

in the following location

https://github.com/ensime/ensime-server/blob/master/server/src/main/scala/org/ensime/server/Server.scala#L136

Then, I need to figure out how to check indexing is complete

**Comment by fommil** [comment]
Probably even simpler than that, just stick a cleanup/shutdown hook onto the Future returned by refresh.
