### ISSUE TITLE
Graph DBs performance characteristics analysis

### ISSUE THREAD

**Issue by sugakandrey** [ensime/ensime-server#1460]
As some of you may know, I'm participating in GSoC 2016 as part of the ENSIME team, trying to make Graphpocalypse come true. This will include swapping H2 database for a graph solution. This ticket is therefore dedicated to testing performance of various graph DBs and deciding which one should be used. As  some solutions are Java 8 only, the choice will also dictate if Graphpocalypse (if successfully implemented :smile:) will make it to 1.0 release or later versions of ENSIME.

Current plan:

- [x] Form a list of candidates for testing. Currently we have:
       - OrientDB
       - Neo4j 
       - Titan
- [x] Benchmark how much time does it take to index a fairly big project

- [ ] Test their performance on Windows (@fommil request)

- [ ] Pick the best candidate

**Comment by sugakandrey** [comment]
A paper from 2013 on basically the same subject: [An empirical comparison of graph databases](http://www.datascienceassn.org/sites/default/files/Empirical%20Comparison%20of%20Graph%20Databases.pdf)

**Comment by rorygraves** [comment]
A few thoughts on thinking about solutions:
- We don't need distribution or sharing - this is a single process owning a dataset
- The size of the graph is quite large (probably bigger than memory)
- Our querying requirements are relatively simple, altough when a file gets updated we may get a large number of updates.

It may be the fact that we end up with a custom implementation sacrificing the bits we don't care about.

**Comment by sugakandrey** [comment]
**Preface**: the following results **do not** necessarily represent real life performance and are only good for comparison with each other. All of the following benchmarks were run locally on my MacBook Air 2013, Intel Core i5 1,3 GHz, 4 GB DDR4, 256GB SSD. All the data was loaded into the database from the file, so there probably is significant IO overhead hidden here.


With that said, I've used excellent [sbt-jmh](https://github.com/ktoso/sbt-jmh) plugin to measure the insertion performance of some graph database solutions. The databases used were mostly untuned (i.e. I only tried to disable transactions if possible). Data inserted follows the model of `org.ensime.indexer.database.FqnSymbol` domain object. To understand what an average `FqnSymbol` looks like, I simply indexed a scala project using ENSIME and ran a couple of Slick queries to determine properties like average size of fields in `FqnSymbol`. 

The databases used are: 

- Neo4j 2.3.3 

- OrientDB 2.2.0 

- TitanDB 1.0.0 with embedded Cassandra backend

So here are the results (size is the amount of fqns inserted):
```
[info] Benchmark                  (size)  Mode  Cnt   Score    Error  Units
[info] Neo4jBatch.batchInsert         10  avgt    3   0.131 ±  0.037   s/op
[info] Neo4jBatch.batchInsert        100  avgt    3   0.143 ±  0.294   s/op
[info] Neo4jBatch.batchInsert       1000  avgt    3   0.177 ±  0.049   s/op
[info] Neo4jBatch.batchInsert      10000  avgt    3   0.474 ±  1.021   s/op
[info] Neo4jBatch.batchInsert     100000  avgt    3   3.018 ±  1.495   s/op
[info] Neo4jBatch.batchInsert     300000  avgt    3   8.318 ±  3.729   s/op
[info] Neo4jBatch.batchInsert     500000  avgt    3  14.377 ± 10.955   s/op
[info] Neo4jBatch.batchInsert    1000000  avgt    3  27.074 ± 15.596   s/op

[info] Neo4jSimple.txInsert           10  avgt    3   0.028 ±  0.071   s/op
[info] Neo4jSimple.txInsert          100  avgt    3   0.051 ±  0.160   s/op
[info] Neo4jSimple.txInsert         1000  avgt    3   0.224 ±  1.858   s/op
[info] Neo4jSimple.txInsert        10000  avgt    3   0.918 ±  3.223   s/op
[info] Neo4jSimple.txInsert       100000  avgt    3   9.288 ±  4.207   s/op
[info] Neo4jSimple.txInsert       300000  avgt    3  25.556 ± 10.558   s/op
[info] Neo4jSimple.txInsert       500000  avgt    3  41.835 ± 13.873   s/op
[info] Neo4jSimple.txInsert      1000000  avgt    3  84.248 ± 58.274   s/op

[info] Orient.noTxInsert              10  avgt    3   0.013 ±  0.064   s/op
[info] Orient.noTxInsert             100  avgt    3   0.046 ±  0.535   s/op
[info] Orient.noTxInsert            1000  avgt    3   0.210 ±  0.480   s/op
[info] Orient.noTxInsert           10000  avgt    3   0.990 ±  5.374   s/op
[info] Orient.noTxInsert          100000  avgt    3   6.977 ±  2.779   s/op
[info] Orient.noTxInsert          300000  avgt    3  21.142 ±  6.566   s/op
[info] Orient.noTxInsert          500000  avgt    3  33.999 ±  7.694   s/op
[info] Orient.noTxInsert         1000000  avgt    3  69.772 ± 49.413   s/op

[info] Orient.txInsert                10  avgt    3    0.047 ±  0.181   s/op
[info] Orient.txInsert               100  avgt    3    0.141 ±  0.427   s/op
[info] Orient.txInsert              1000  avgt    3    0.702 ±  2.008   s/op
[info] Orient.txInsert             10000  avgt    3    5.103 ±  0.955   s/op
[info] Orient.txInsert            100000  avgt    3   14.708 ± 17.663   s/op
[info] Orient.txInsert            300000  avgt    3   36.811 ± 10.844   s/op
[info] Orient.txInsert            500000  avgt    3   56.380 ± 34.937   s/op
[info] Orient.txInsert           1000000  avgt    3  110.344 ± 67.590   s/op

[info] TitanJava8.txInsert            10  avgt    3    3.906 ±  6.777   s/op
[info] TitanJava8.txInsert           100  avgt    3    6.196 ± 12.222   s/op
[info] TitanJava8.txInsert          1000  avgt    3    6.388 ± 12.391   s/op
[info] TitanJava8.txInsert         10000  avgt    3    6.581 ± 21.594   s/op
[info] TitanJava8.txInsert        100000  avgt    3   22.533 ± 14.786   s/op
[info] TitanJava8.txInsert        300000  avgt    3   53.489 ± 49.307   s/op
[info] TitanJava8.txInsert        500000  avgt    3   83.037 ± 90.941   s/op
[info] TitanJava8.txInsert       1000000  avgt    3  158.813 ± 82.302   s/op
```
or the plot ![plot](http://i.imgur.com/wnKAG9a.png). 
To clarify the plot legend: `orient`, `neo4j` and `titan` means the respective database with transactions **on** was used. `orient-no-tx` stands for OrientDB with transactions disabled and `neo4j-batch` is Neo4j using `org.neo4j.unsafe.batchinsert.BatchInserter`. Batching support does exist in Orient too, but is limited only to vertex creation and disallows any properties to be set. I can't quite make sense of high initial delay when using titan (see figure 1 of the plot) but it probably has to do with proper Cassandra configuration. 

It's too late right now to make meaningful conclusions out of this, so I'll leave this part for tomorrow. What do you guys think about it? @fommil @rorygraves

**Comment by fommil** [comment]
Cool, this gives us confidence that orientdb in not terrible and neo4j is fastest. How much more testing do you want to do?
