### ISSUE TITLE
change .ensime format to include named scopes and per-project settings

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1470]
if the `.ensime` format had per-project settings we could enable compiler plugins per-project #1152 and separate out the main / test configurations for better completions and build tool support (in clients).

**Comment by fommil** [comment]
as a migration path, we could make ensime-sbt (and other build tool plugins) generate the new format alongside the old, then swap the server to use the new format, followed by the clients, then remove the generation in the build tool plugins.

Best that we coordinate all changes that we want to make into one go.

**Comment by gyfarkas** [comment]
Hi, Im looking into this now.
