### ISSUE TITLE
replace akka-http with java-only lib

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1471]
to remove a dependency on the huge akka-http/streams framework, we would like to move to a java-only HTTP/WebSockets library.

It must be lightweight, probably based on netty.

complementary and a dependency of #1351

**Comment by ktonga** [comment]
Hey @pascr have you made any progress? If you're not able to work on it right now I'd like to give it a shot, since it's blocking other work. Cheers.

**Comment by pascr** [comment]
Hi @ktonga, nothing substantial yet so feel free to assign it to you.  (Worth having a look at #1351 as several alternatives have been mentionned)

**Comment by fommil** [comment]
It'd be really nice to get rid of this. It doesn't need a reactive platform, just nio... consider that we only have one client connection and user generated requests. We can easily throw a thread or two at this.

**Comment by ktonga** [comment]
Hey @fommil I have a couple of questions before I start with this.

I was thinking on going really minimalist with this and just use [Project Tyrus](https://tyrus.java.net) which is JSR 356 (Java API for WebSocket) reference implementation. It looks like a good fit for the requirements you mentioned:

- Java lib, supporting 1.7+
- Just a few dependencies
- Exactly what we need, nothing more

But to be sure I need to know:

- Are we OK with its __licence__?
- Do we have to support only __WebSocket__? or __HTTP__ as well?
- Do we have to receive/response __JSON__ as well as __S-Expression__?

I think that's it by now, I'm sure I'll have more questions when I start working on it.

**Comment by fommil** [comment]
They use the classpath exception, but that could still be a problem for us in our assembly jar. Are there any other impls?

**Comment by fommil** [comment]
Re: json/sexp we have the facility to convert into String with both so you just need a way of wrapping up a String payload into a message.

We do have http, for serving javadocs, sorry.

**Comment by ktonga** [comment]
What a pity. I guess I could take a look at [Atmosphere](https://github.com/Atmosphere/atmosphere), or [Nettosphere](http://atmosphere.github.io/nettosphere/) more precisely. It also supports HTTP.

I have to ask. Is __http4s__ totally discarded here?

* `+` It's FP and well typed
* `+` It's a Typelevel Incubator project
* `+` It supports both WebSocket & HTTP
* `-` We should use a really old version to support Java 1.7
* `-` Not available for Scala 2.12 yet (http4s/http4s#613)
* `-` Has a few dependencies

**Comment by fommil** [comment]
I'd love to use it but we really should move away from scala libs. We're in a unique position and we need to be able to move swiftly in future to support new versions of scala, so java libs are always preferred.

**Comment by fommil** [comment]
Atmosphere has license problems

**Comment by fommil** [comment]
Jetty uses epl/apache 2.0 which if we are free to choose apache 2.0 is good for us.

Wow. I never realised how messy all these "new world java" licenses are. So much for Apache 2.0 winning the license wars.

**Comment by fommil** [comment]
my goodness, even jetty has polluted components https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/NOTICE.txt

When it comes to JSR API jars, I think we're ok. But when it comes to implementations then we're in a spot of bother.

Maybe http4s isn't so bad after all... but I don't know why they've gone for Java 8. That's such an annoying decision.

**Comment by fommil** [comment]
maybe we should seek clarification from the FSF on the use of GPLv2+CPE in an assembly jar. The problem is that GPLv2 is incompatible with GPLv3.

**Comment by fommil** [comment]
Here is the classpath exception:

> As a special exception, the copyright holders of this library give you permission to link this library with independent modules to produce an executable, regardless of the license terms of these independent modules, and to copy and distribute the resulting executable under terms of your choice, provided that you also meet, for each linked independent module, the terms and conditions of the license of that module. An independent module is a module which is not derived from or based on this library. If you modify this library, you may extend this exception to your version of the library, but you are not obligated to do so. If you do not wish to do so, delete this exception statement from your version.

So we are perhaps ok using GPLv2+CPE so long as we have a justification for saying that we are an "independent module". We're not derived from, but it's hard to know what "based on" means here.

**Comment by ktonga** [comment]
Re http4s, I can ask why java 8, and maybe help them bringing java 7 support back. I guess it was 'cause they have a hell of a dependencies matrix already. Scala is a nightmare in that regard.

And we have the JDK version and licensing issues. We are running out of options.

Newbie question, sorry if you already answered it many times, Why it's that we can't isolate Ensime space from user project space? Why I can run Idea on Java 8 and build my project with Java 7? It's all about being lightweight?

**Comment by fommil** [comment]
ENSIME uses the same version of Java and Scala as your project, as does IDEA use the correct version of Java to compile your project. The analogy with IDEA falls down here because IDEA is written in Java whereas ENSIME (client) is written in emacs-lisp and python.

I've asked the FSF to clarify their position on GPLv2+CPE in a GPLv3 assembly jar. They've previously clarified that it is ok to distribute LGPL code in an Apache 2.0 assembly jar, so I'm hoping the same reasoning applies (i.e. that this is about classpath and not linking concerns). The more concerning thing is that the JSR itself is GPLv2+CPE because that means we most certainly **are** "based on".

**Comment by fommil** [comment]
but regarding "based on", then the same argument would apply for Java itself. So I think the classpath exception is just confused.

**Comment by fommil** [comment]
https://www.gnu.org/software/classpath/faq/faq.html#faq2_3 says

> you can use and distribute GNU Classpath as is in your program without changing the license of your software.

**Comment by fommil** [comment]
bah, worst case scenario is we create an assembly jar with all the GPLv2+CPE bits and add it to the classpath. Let's go ahead with Tyrus.

**Comment by ktonga** [comment]
But Tyrus can't serve the http bit. Maybe I could take a look at serve both
endpoints with jetty.

Presentation compiler must run embedded? Cannot be run in a separate JVM as
I guess IDEA does?

**Comment by fommil** [comment]
well ensime **is** a separate JVM :stuck_out_tongue:

IDEA doesn't use the presentation compiler. They wrote their type checker from scratch, which is why it gets it wrong so much.

Be careful with jetty because parts of it are EPL and we definitely can't use those.

**Comment by ktonga** [comment]
Yeah I know ensime is a separate JVM :) and I was aware of IDEA having its own compiler, I just used it as example since they clearly were able to separate their runtime from the user's project needs, as well as SBT does it so.
Maybe at some point, when SBT client/server gets stable, Ensime can just forward/relay on SBT compilation capabilities.
Will think better what to do with the http docs endpoint to avoid using jetty. I could use different tools and bind them to different port within the same JVM. It is static files from the extracted jar? Or it has some logic for serving the docs from within the jar without extracting it?

**Comment by ktonga** [comment]
I think I will use a combination of Tyrus and [this](http://docs.oracle.com/javase/8/docs/jre/api/net/httpserver/spec/com/sun/net/httpserver/package-summary.html)

**Comment by fommil** [comment]
The http and websockets endpoint need to be on the same port sorry or it'll mean client changes.

Ensime already just passes off to sbt for compilation and so on. It definitely makes sense for ensime to use the same java/scala version as the project so it gives the most collect and compatible experience.

The main reason we care about Java 7 is because both myself and Aemon use it at work :-) once our respective teams upgrade to java 8 then we'd probably be tempted to upgrade, but that looks unlikely right now.

**Comment by fommil** [comment]
Oh yeah, the net server. Heh, I wrote a blog post about that many moons ago. Is it possible to share the port with websockets?

**Comment by ktonga** [comment]
I thought that the client only opens docs URLs provided by the WS messages, why it can't be served on a different port? Does the ensime plugin generate the URLs itself using the same port it connects to the WS endpoint?
And we are talking about server 2.0, I thought some incompatibility would be expected.
Obviously I'll try to avoid the port change, but there are SOOO many restrictions that I feel surrounded before starting :)

**Comment by fommil** [comment]
Hehe, yeah. There is a splash page that clients can connect to and that reads the `http` file. I'm very confused why these java clients don't allow www and websockets on the same port. Ideally we'd like to move the just one port and drop the `swank` tcp connection.

If an extra port is required then as extra port is required. I'll mean creating another portfile, which is nasty.

**Comment by fommil** [comment]
Btw minimising port usage is important in corporate environments where this kind of thing is audited.

**Comment by fommil** [comment]
Are you sure Tyrus doesn't allow normal www? It would appear that in the examples, websockets are activated on a per-path basis https://tyrus.java.net/documentation/1.8/user-guide.html#d0e34 so we could have plain old REST endpoints too. Might be worth asking on their forum for some examples.

**Comment by fommil** [comment]
I'm trying desperately to remember how all this stuff works (I did this sort of thing in java before scala). I seem to recall that one sets up a servlet container and then it's possible to have various different handlers on that port, and of which word be this websockets thing and others would be REST, and of course it has a JSR and impls too so we just pick the smallest with the cleanest license.

**Comment by ktonga** [comment]
You're right, I totally forgot bout how the things were with containers, I'm so used to launch web servers ala spray or play right now.
I can embed a tomcat8 witch runs on Java 7 and later and supports both protocols. I'm also almost sure I'll be able to server both endpoints on the same port.
Now the $1M question.... How about Tomcat license?

**Comment by fommil** [comment]
I'm pretty sure there are much lighter weight solutions that tomcat. Doesn't Netty do this?
Maybe jetty is the right solution after all.

**Comment by fommil** [comment]
Tomcat is Apache 2.0 so definitely OK. But swapping out akka-streams for tomcat feels like getting rid of an oversized saloon to be replaced by a tractor.

**Comment by ktonga** [comment]
Ok. No Tomcat. I always found Netty too low-level for app code, I think it's targeted to lib devs. But I'll check it out.

**Comment by ktonga** [comment]
Looks like it is posible to [start a server](https://github.com/netty/netty/tree/4.0/example/src/main/java/io/netty/example/http/websocketx/server) with Netty to handle both protocols on the same port. Doesn't seem simple but it is possible.

**Comment by fommil** [comment]
we don't need SSL
