### ISSUE TITLE
make use of Java 7 Tree API for Java support

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1491]
We had some hacks because we were running on Java 6, but now we have access to the full Java 7 Tree API so we should revisit our Java support and make sure we support the "new" language features.

**Comment by fommil** [comment]
@mwielocha is this something you'd be interested in doing? You know those APIs better than most!

**Comment by mwielocha** [comment]
Sure, I'll give it a go on the weekend. Been trying to get back to ensime for some time now :)

**Comment by mwielocha** [comment]
This one is kinda blocked by #1494, so I'm got go there first.

**Comment by fommil** [comment]
Interesting. How come it's blocked? I think #1494 is probably more important anyway.

**Comment by mwielocha** [comment]
Only in the way that java support is basically not working atm. I'm gonna look at #1494 and hopefully that will make QA testing a bit easier with this one.

**Comment by fommil** [comment]
Add. Yeah maybe that one should go into 1.0.

**Comment by mwielocha** [comment]
Ok, so I went through the codebase in javac and I couldn't really find anything this task might be referring to, except maybe for the reusable compiler which actually works fine in 7 but I'm not sure if we want to drop support for 6 completely...? Anyway I can create a PR for this.
I think most of the 'hacks' where removed with netbeans deps, but maybe there is something I'm missing.
Regarding the tree api I looked briefly at this doc: http://www.oracle.com/technetwork/java/javase/jdk7-relnotes-418459.html and it seems that there is nothing there that we could benefit from.
I could add tests for all the new syntax features in 7 and that I think that would be it.

**Comment by aemoncannon** [comment]
sounds right to me

**Comment by mwielocha** [comment]
@fommil are we dropping java 6? Cause if so I have PR. Then again if not I also have a PR but a much smaller one 😄

**Comment by fommil** [comment]
we already dropped Java 6! :smile:

**Comment by mwielocha** [comment]
goodbye’s too good a word, gal So I’ll just say fare thee well

**Comment by rorygraves** [comment]
lol
