### ISSUE TITLE
incrementally update the sources map in SourceResolver

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1492]
the comment https://github.com/ensime/ensime-server/blob/2.0/core/src/main/scala/org/ensime/indexer/SourceResolver.scala#L22

```
  // it's not worth doing incremental updates - this is cheap
  // (but it would be nice to have a "debounce" throttler)
```

is hilarious if you have lots of sources, especially if they are huge.

We should we doing this incrementally and with a debounce to avoid duplicating work.

Workaround if this affects you is to disable source watching, which is advised for large projects anyway, which will reduce the number of times this is called.

**Comment by chiangqiqi** [comment]
trying to work on this

**Comment by jozi-k** [comment]
Hi, I am looking for some low-hanging-fruit issue and got here, but it has been probably already solved.

**Comment by fommil** [comment]
Nope, this is still open! Do you need any help getting started? The contributing page is the best plate to start and we're happy to answer questions on gitter or here

**Comment by jozi-k** [comment]
I am greenhorn here, but let me explain why I assumed it had been resolved:
1) Comment from issue description does not exist anymore.
2) PR #1633 mentions this issue as resolved. 
If that is not correct, can you explain in more detail what is this issue about?

**Comment by fommil** [comment]
Ah right, I'm thinking of a different sourcemap ticket... there is a ticket to reuse the source resolver in the debug actor.
