### ISSUE TITLE
symbol at point is inconsistent for java methods

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1494]
symbol at point is currently returning a weird BasicTypeInfo that doesn't make sense for java methods, e.g. see `JavaCompilerSpec.scala` for anything on a method, e.g. 

```
          case "3" =>
            info.name shouldBe "java.io.PrintStream.println(java.lang.Object)"
            info.localName shouldBe "println"
            info.`type`.name shouldBe "(java.lang.Object)void"
```

the `info.type` should be returning a sensible `ArrowTypeInfo` instead of a fake `BasicTypeInfo`.

**Comment by fommil** [comment]
Moving to 1.0 as this breaks java support.

**Comment by fommil** [comment]
just checked, not as bad as I thought. It still works but we don't get a nice template (but I don't think we ever did)

**Comment by mwielocha** [comment]
So if this is not breaking java support then what is?

**Comment by aemoncannon** [comment]
@fommil Completion templates? Those work (or have been) for me.

**Comment by fommil** [comment]
@aemoncannon they don't work so well as the scala method completions because we're returning the info as a blob in `BasicTypeInfo` instead of `ArrowTypeInfo`. But, yeah, it pretty much works right now for all practical purposes.

@mwielocha yeah, I'm not sure. It might just be on your machine... can you try to reproduce on the ensime-server project itself? We've got a couple of java files, mostly in the monkeys module.

**Comment by mwielocha** [comment]
Not sure what the hell happen but it started working again, sorry for the confusion.

**Comment by mwielocha** [comment]
Do we want this to be the same as in `scalaName` with the `=>` operator? Or more like Java for example `(java.lang.Object): java.lang.String` or something?

**Comment by fommil** [comment]
let's use Java syntax. We probably shouldn't be using the scala API to return Java Compiler objects anyway, maybe give them their own protocol.

**Comment by fommil** [comment]
(remember the user gets these responses back only when querying from a `.java` file)

**Comment by mwielocha** [comment]
Yeah that was my thought as well. Oh well, At least I got a first bite on this one :)

**Comment by mwielocha** [comment]
You think its a good time to re-implement both java incoming and outgoing?
Just found this:
```scala
    // HACK: to expedite initial dev, Java requests use the Scala API
    case m @ TypecheckFileReq(sfi) if sfi.file.isJava => javac forward m
    case m @ CompletionsReq(sfi, _, _, _, _) if sfi.file.isJava => javac forward m
    case m @ DocUriAtPointReq(sfi, _) if sfi.file.isJava => javac forward m
    case m @ TypeAtPointReq(sfi, _) if sfi.file.isJava => javac forward m
    case m @ SymbolDesignationsReq(sfi, _, _, _) if sfi.file.isJava => javac forward m
    case m @ SymbolAtPointReq(sfi, _) if sfi.file.isJava => javac forward m
```

**Comment by fommil** [comment]
that'll be #1366 :smile:

**Comment by mwielocha** [comment]
Right, feels a bit like some kind of an infinite ticket reference loop 😩 
Maybe we should merge those two tickets, after all giving `SymbolAtPoint` its own little protocol would make it a bit inconsistent with the rest of 'Java using Scala' api, right?

Plus it doesn't really seem that huge since we right now only support 6 message for `JavaAnalyzer` as stated above. Although I'm assuming this will require updating clients as well, right?

**Comment by fommil** [comment]
it's huge client side. Probably best to do this ticket first, then do the java one when we can coordinate somebody to update the client side.

**Comment by mwielocha** [comment]
I think we can close this one now, if something pops up we can open a different ticket for it.
