### ISSUE TITLE
ArrowTypeInfo should have a list of type parameters

### ISSUE THREAD

**Issue by ktonga** [ensime/ensime-server#1504]
Currently it's not possible to regenerate the list of type params for a generic method based on `typeInfo` content.

**Comment by fommil** [comment]
This is a server bug.

**Comment by fommil** [comment]
https://github.com/ensime/ensime-server/issues/1494

**Comment by ktonga** [comment]
Hi @fommil, I don't think this problems is related to #1494. It's related to the `completions` endpoint not to `symbol at cursor`, and in this case the server is returning `ArrowTypeInfo` which is the proper type for methods.

The problem here is that `ArrowTypeInfo` does not have a field for listing the type params defined for the method.

So for instance, if you have `def genericMethod[A, B](a: A)(f: A => B): B` you have no way to figure out the `[A, B]` part of the signatures from the method `typeInfo`.

Hope it clarifies the problem better.

**Comment by fommil** [comment]
Yes it's definitely that ticket. Happy to talk you through in more detail. Can you have a look at the referenced source files and also some example payloads for Scala (equiv Scala tests will do). All the information you want should be in TypeInfo.

**Comment by fommil** [comment]
(i.e. we either need to add type parameters to arrow types or we need to specialise for java)

**Comment by fommil** [comment]
incidentally, why do you need the type parameter list in particular? Isn't it enough that the types are on the parameters? We've never needed this for scala.

**Comment by fommil** [comment]
oh, you're using "generic" method when you're talking about scala methods. That's typically only reserved for talking about java methods since it's an implementation detail. For scala methods, we'd say "method with type parameters".

What's your usecase? We'd prefer not to increase the size of these payloads unless absolutely necessary, as it can impact performance.

**Comment by ktonga** [comment]
@fommil  Sorry if it sounded confusing, I referred all the time to them as 'type params', didn't realize about the 'generic' word connotation. I'm talking just about Scala.

To see my use case please take a look at [this comment](https://github.com/ensime/ensime-vim/issues/273#issuecomment-224019333) and to the issue in general.

Here you have a couple of comments I put in the gitter channel that better illustrate my problem:

> Hi. I'm trying to improve completions formatting in ensime-vim but I can't find an easy way to regenerate the type params list for a method from the typeInfo. Type params are embedded inside the paramSections, I could find them all and get the unique list but I won't be able to know in which order they were defined. Am I missing something? Thanks.

> I'm thinking in something like def foo\[A, B\](b: B)(f: A => B): B

> if I iterate the params sections to get the types I'll get [B, A]

> it would be nice to have a typeParams: [{name: "A"}, {name: "B"}] in typeInfo

I think it is important to show the type params list since Scala more than often forces you to explicitly put them due to its poor type inference.

Hope it makes sense.
Cheers.

**Comment by fommil** [comment]
Hmm, I'm not sure about how much this is actually needed, but it is adding to the API not regressing so it's not a big deal so long as the payloads don't get too big. I'd expect if somebody implements this in Emacs that it should be configurable as I wouldn't want to be distracted by having to fill out the type parameters all the time.

To be honest I've not got any spare cycles to do this, and I'm going to actively encourage people to work on the NIO-related 2.0 milestone, but I don't think this is particularly difficult to do and I'd be happy to help you or anybody you could rope into doing it.

**Comment by ktonga** [comment]
I want the type params as a separate list in the `ArrowTypeInfo` I don't want them added to the `name` and `fullName` string fields, this way each editor can use it optionally.

And to be clear, I don't want to fill type params always either. I just want to show them in the method signatures as a reference, just as IDEs and the REPL do. I would never add them to the completion template, as a tabstop I mean.

I can give it a try, I really love Ensime and I want to start contributing. Something that only I seems to want fills like a good start 😉

**Comment by aemoncannon** [comment]
Sounds great!

**Comment by fommil** [comment]
OK cool, well give to contributing guide a rod and then ping me back. If timezones work out I can give you a code walkthrough of this relevant part of the code on meet.jit.si 

We also hack a hack day all day on Saturday in London which you are welcome to join remotely. The gitter rooms should be chattier then normal and you'll get fast / detailed answers to questions.

**Comment by fommil** [comment]
Best place to start is with the tests, try looking at symboltoscalanamespec and around there.
