### ISSUE TITLE
toSymbol fails to resolve classnames with special characters

### ISSUE THREAD

**Issue by sugakandrey** [ensime/ensime-server#1507]
[This](https://github.com/ensime/ensime-server/blob/2.0/core/src/main/scala/org/ensime/core/FqnToSymbol.scala#L49-L58) will fail to produce a symbol for the `fqn` of a class with special characters in its name (e.g. `Predef.<:<` `ClassName(PackageName(List("Predef")), "$less$colon$less")`)

**Comment by fommil** [comment]
ah, well spotted. I believe it works in the other direction though. Should be easy to add a unit test.

**Comment by sugakandrey** [comment]
I added the test in my `scalap-converter` branch (15c03fc), will try to fix that.

**Comment by sugakandrey** [comment]
Fixed in 7f8406f, I'll leave this open until `scalap-converter` is ready to be merged.
