### ISSUE TITLE
Merge Graphpocalypse into 2.0

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1509]
there are some TODO comments in the code, which is against our coding standard. I temporarily disabled the detector in the `2.0-graph` branch but it would be good to add this back https://github.com/ensime/ensime-server/commit/d062758399ad2d9da0b22979b0cdc64fe8bb190e

TODOs either rot or deserve a ticket, they are more hassle than they are worth. It's good for CI to remind you after a PR that there are TODOs so you can do the cull after a work-in-progress branch.

**Comment by sugakandrey** [comment]
Alright, so to do anything with `2.0-graph` we would need #1572 and this ticket at the very least. Also, I had some ideas on how to optimise orient insertion during indexing by grouping `FqnSymbols` by their class. I guess, I'll track the progress here.

- [ ] remove TODOs
- [ ] fix emacs integration tests
- [ ] group `FqnSymbols` by class in `db.persist`

**Comment by fommil** [comment]
let's do the optimisation after, create a separate ticket for it and add it to your backlog column. I just want to get it in the 2.0 :wink: the perf is tolerable for now
