### ISSUE TITLE
Server dies when attempting to inspect value

### ISSUE THREAD

**Issue by greenrd** [ensime/ensime-server#1510]
### Steps to reproduce

1.  Run two instances of ensime - one on another project, and one on ensime itself. The one that's on ensime itself should have the additional java flags `-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044` so that ensime can be debugged.
2. Set a breakpoint in core/src/main/scala/org/ensime/core/Refactor.scala line 54 and attach the ensime debugger to port 1044.
3. Run an organise imports in a scala file in the other project (obviously a scala file which has some imports in it!)
4. Move point to the letter `c` in `modifications` on line 54 and do `C-c C-d i`.

### Expected behaviour
Should display some representation of the value of `modifications` in another buffer.

### Actual behaviour
Server shuts down.

[inferior.txt](https://github.com/ensime/ensime-server/files/310327/inferior.txt)

**Comment by greenrd** [comment]
[dot-ensime.txt](https://github.com/ensime/ensime-server/files/310330/dot-ensime.txt)

**Comment by fommil** [comment]
This looks like an Emacs bug, it shouldn't be sending a debug request for nil.

**Comment by fommil** [comment]
Could be that are old question of how we tolerate badly formatted queries @rorygraves

**Comment by fommil** [comment]
if this is about the latter, I suggest closing in favour of #1189 and #1471

**Comment by chipsenkbeil** [comment]
So, is this something that the `DebugActor` class can/should protect against? Or should I leave this one alone?

**Comment by fommil** [comment]
I don't think it even gets that far looking at the logs.

**Comment by rorygraves** [comment]
This is one of those parsing edge cases - the message we received is well formed (valid sexp) but not parseable to the expected message type.  So technically the protocl could stay open (its not out of sync).

**Comment by fommil** [comment]
Agreed. We shouldn't bail but I'm not interested in fixing it here because this code will be rewritten in the two referenced tickets and i'd rather a contributor put their time there instead.
Of course if you have a pr it would be accepted against 1.0 if it has tests.

**Comment by fommil** [comment]
@greenrd do you think food be able to find the time to fix the Emacs client the not send this broken message?

Historically the reason I wanted the server to bail was to force users into paying attention and fixing it, instead of sweeping it under the carpet in the server logs. I think that's served us well and now we're seeing a lot more general stability across all clients.
