### ISSUE TITLE
Replace SourceMap with SearchService implementation.

### ISSUE THREAD

**Issue by hardmettle** [ensime/ensime-server#1511]
When investigating #761 we discovered that `SourceMap` is reimplementing features that should be provided by the indexer.

This may explain why Ensime can't find the sources of external dependencies when debugging. 
@chipsenkbeil

**Comment by chipsenkbeil** [comment]
Were you or someone else planning to tackle this? Or did you want me to handle it eventually? Or maybe some form of pair programming exercise?

**Comment by fommil** [comment]
It's just something we spotted at the hack day. No expectations on who does it but it fits well with the 2.0 tech debt cleanup goal.
