### ISSUE TITLE
Symbols in scope

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1513]
It would be really good if the method completion templates could include suggestions of values to pass, effectively write the code for you. To do this, we'd need an API query that provides all the symbols of a given type that are currently in scope.

I'm not even sure if Emacs' yasnippet is powerful enough to support this idea, since it could involve completions within completions and dynamically changing the template.

**Comment by aemoncannon** [comment]
Neat. FYI I looked into use a theorem prover for this at one point. So you
could fill in non-trivial expressions. See 'insynth' - they seemed eager to
help integrate. Not sure if would actually be a good idea in practice....
(might be annoying).

**Comment by fommil** [comment]
hehe, yeah it's one of those ideas that seems like it might be annoying otherwise everybody would be doing it already. That's cool that EPFL have looked into this http://lara.epfl.ch/w/insynth but to be honest I thought the harder problem would be the UI! :smile:

Shouldn't you be sleeping or something?
