### ISSUE TITLE
SignatureParser fails when type parameter's bound is also a type parameter

### ISSUE THREAD

**Issue by mwielocha** [ensime/ensime-server#1515]
```
public class Java8Sig<U extends A, A> { }
```
Signature for this class is `<U:TA;A:Ljava/lang/Object;>Ljava/lang/Object;` which is currently not supported by `SignatureParser`.
This breaks java support in 2.0 on Java 8.

**Comment by fommil** [comment]
@asznajder FYI

**Comment by asznajder** [comment]
Oops, I will fix this!

**Comment by mwielocha** [comment]
Btw, maybe we should consider not throwing an exception when parsing fails? This way we cant just not support something rather than breaking indexing...?

**Comment by fommil** [comment]
@mwielocha let's keep the exceptions. This is a dev branch and this is the only way anybody cares enough to fix the bugs. Otherwise they will be exceptions in the logs for years with bizarre side effects.
