### ISSUE TITLE
Project actor init should happen on creation, not on connection info request

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1551]
We're delaying indexing until the connection is made, but this means we can't make use of the `ensime.exitAfterIndex` feature.

@rorygraves thoughts? Any reason you can think of why we only init on a connection?

**Comment by rorygraves** [comment]
Oh, I know why this was that way - originally the config was sent in one of the opening messages to the server. (the .ensime file went over the wire).  No reason for it now - it should bootstrap immediately.

**Comment by rorygraves** [comment]
Should be trivial to fix

**Comment by rorygraves** [comment]
Ah, reviewing the code I remember why this was left the nasty way round, needs a bigger refactor.
The client needs to see an 'IndexerReadyEvent' which comes from the end of indexing.  So we trigger it when the client sends the 'ConnectionInfoEvent' (which every client sends as a first message).

**Comment by rorygraves** [comment]
I blieve the answer is 'because otherwise emacs gets upset' ;)

**Comment by fommil** [comment]
in the meantime, couldn't we just make the project actor stash these messages until it sees the expected message?

Now that we have 2.0 we are free to write it the way we want to. I suggest removing the connection info request.

**Comment by rorygraves** [comment]
Rereading I don't think we need to we already have the stuff in the Broadcaster - I'm pushing a PR now.

**Comment by fommil** [comment]
w00t!

I tried to write a test for the indexer, but we lack a launcher. At work I'm just hardcoding it... probably we should have an emacs script for doing this then we could trigger it as the first thing in the tests.

**Comment by rorygraves** [comment]
I think rather than being a 'kill yourself flag' it should be a seperate main method that listens to the broadcaster and shuts down.

**Comment by rorygraves** [comment]
That logic should not exist in Project IMHO

**Comment by fommil** [comment]
yeah, I agree. It was a first time contributor.

**Comment by fommil** [comment]
it's not entirely clear but there is an open PR on this but it got delayed because of client integration problems, so more work is needed to retain the backwards compatible API https://github.com/ensime/ensime-server/pull/1552
