### ISSUE TITLE
async connection info

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1553]
as discussed in https://github.com/ensime/ensime-server/pull/1552 the first message that clients receive when connecting should be an _async_ connection info, with information about the protocol etc.

This is breaking, because right now it's a sync message in response to a request.

We can then remove the connection info request message.

This simplifies the client side logic.

**Comment by fommil** [comment]
We can keep the sync message for backwards compat and deprecate it, for removal later.

**Comment by jan0sch** [comment]
Is anyone working on this? I'm tempted to give it a shot when there is time.

Would this just involve removing the stashing and waiting stuff from the server?

**Comment by fommil** [comment]
you can't break the current protocols, but you could add an async message that the clients could move to. Then we can remove the old request/response message in 3.0

**Comment by jan0sch** [comment]
Ok, I'll try to give it a shot.
