### ISSUE TITLE
SWANKY: prefix or not to prefix?

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1559]
a question for @aemoncannon --- should we add `ensime-api-` or `ensime-` or `swanky-` to the start of all the type names in the new SWANKY protocol?

It's easy enough to do it, but I was concerned about littering the API with repetition.

From an Emacs Lisp point of view, it might make sense to add the prefixes since we're supposed to use prefixes as an alternative to namespaces.

**Comment by aemoncannon** [comment]
yeah that's basically where i stand. top-level symbols in elisp should be
namespaced with a prefix. It sucks but we'll regret it if we don't

**Comment by fommil** [comment]
ok, cool. I'll add `ensime-api-` unless you have any strong preferences otherwise (because it makes sense to call the file `ensime-api.el` where we define the api)

**Comment by aemoncannon** [comment]
sgtm
