### ISSUE TITLE
Semantic highlighting for comprehensions

### ISSUE THREAD

**Issue by marcsaegesser** [ensime/ensime-server#1577]
There are two annoying issues with semantic highlighting of `for` comprehensions:
1. The first generator sometimes gets highlighted incorrectly. Sometimes this results in a symbol highlighted partly as one type and partly a different type (e.g. it starts as an object and ends as a function call).
2. The subsequent generators do not get highlighted at all.

Both problems are related to the fact that for comprehensions are de-sugared into nested calls to flatMap and map. 

Problem one happens because we're highlighting both the symbol from the source code and the flatMap generated by the compiler. Depending on the lengths of the symbols and the order the overlays get created the highlighting can be incorrect.

Problem two happens because the remaining generators get turned into lambdas that are passed to the generated flatMap/map calls. The ASTs for these lambdas are flagged as Transparent and the semantic highlighter ignores transparent trees.

I've been hacking on some solutions to this. Before I get too far I wanted to double check that this isn't something that the graphpocalypse magic will help solve. If not then I'll try to finalize what I have and create a PR.

**Comment by fommil** [comment]
this sounds like something we should fix in the compiler, or do you have some workaround in mind?

**Comment by fommil** [comment]
btw, the compiler doesn't really support `for` comprehensions, it dusugars them at the **parsing** phase (yes, its insane)

**Comment by marcsaegesser** [comment]
I had in mind two possible approaches. 

The first is to simply detect places where we've received overlapping `SymbolDesignation`s and apply some heuristic to select the most appropriate one. Any approach that tries to go from `scala.reflect` ASTs back to code is going to require heuristics and guesses because of all the desugaring that the compiler has done. This approach will never be perfect; I'd settle for it just being less wrong.

The second approach is to use scala.meta for semantic highlighting. I have no idea about the feasibility of this, yet. I think ultimately it will be the only real solution. We need ASTs based on the actual code as written not on the desugared code.

**Comment by fommil** [comment]
you know this is basically what our second GSoC was? :stuck_out_tongue_winking_eye: http://ensime.github.io/contributing/gsoc2016/#source-code-preserving-ast it's turned out to be much much harder than expected... so I recommend going for simple heuristic at this stage.

**Comment by rorygraves** [comment]
Yeah, do you really want to be parsing the code to work out the location of the for comprehension?
Check out https://github.com/scalameta/scalameta/pull/457   Basically it allows transforms to keep the formatting/whitespace etc.

**Comment by fommil** [comment]
@rorygraves but that's a strategic solution, we can't really use it anytime soon. We can't realistically depend on `scala.meta` until ensime 3.0 when we (potentially) drop scala 2.10 support.

**Comment by rorygraves** [comment]
Yeah, fair enough, one thought - the scala-refactoring library might have some interesting hacks to deal with stuff in this area (the  munging of for loops is one of things it has to handle)

**Comment by xeno-by** [comment]
@fommil What's the timeline of ensime 3.0?

**Comment by fommil** [comment]
3.0 becomes the dev branch when we finish 2.0. i honestly have no idea because everything is on a volunteer basis. Well see how contributions pick up when the winter weather comes.

**Comment by xeno-by** [comment]
Allright that's another motivation for me to look into 2.10 support.

**Comment by fommil** [comment]
I don't know... we're seeing a lot of traction in our 2.0 roadmap. It'd probably be more efficient if you just helped us out to release 2.0 to be honest! :smile:

We only care about 2.10 for sbt. And sbt 1.0 is going to use scala 2.11.

**Comment by fommil** [comment]
@marcsaegesser did you ever get anywhere with this branch? If you even have a snippet to reproduce the problem, might be interesting to share here?

**Comment by marcsaegesser** [comment]
@fommil Sorry, I've made no progress on this at all. Right after I started looking at this I hurt my hand (the left pinky is kind of important in Emacs) and my recreational typing dropped to zero. I was just too damned frustrated after a day of work typing to deal with anything else. I'm (mostly) healed at this point but I haven't worked up the ambition to get back into this.

I'll try to submit a specific example of the problem, but essentially, syntax highlighting of *every* ```for``` comprehension is messed up because the parser has already de-sugared the comprehension into flatMap/map calls. The specific highlighting results vary based on the specifics of the ```for``` comprehension. Things like the lengths of the various generators will cause different parts of the expression to be highlighting in various different colors.

**Comment by fommil** [comment]
hmm, it works fine for me... I wonder if it's maybe a macro or compiler plugin you have that causes problems. Or an encoding issue?

**Comment by marcsaegesser** [comment]
[Here's](https://photos.app.goo.gl/BOoGUPbKEYRl805C3) a screen shot showing an example of what the syntax highlighting looks like. The code is from [here](https://github.com/marcsaegesser/scala-dbus/blob/master/src/main/scala/dbus/Marshal.scala) and looks something like this:

```scala
for {
  s <- get[UnmarshalState]
  p = padding(s.offset.toLong, align)
  b = s.bits.drop(p * 8)
  _ <- put(s.copy(offset = s.offset + p.toInt, bits=b))
} yield ()
```
What you see in the image is that the first line of the ```for``` comprehension is highlighted *almost* correctly. The ```get``` is highlighted as a functionCall (using what-cursor-position with a prefix-arg shows the the overlay is ensime-sym-type functionCall). The ```UnmarshalState``` starts being highlighted as a class (ensime-sym-type class) but the last two characters are highlighted as a function call. That's because there's probably a call to flatMap in the de-sugared code. The next line doesn't get any highlighting at all even though ```padding``` should be a functionCall. The expression ```p * 8``` somehow got highlighted as a functionCall.

As I recall, and it's been ages, the problem was partly due to ```SymDesigsTraverser``` in ```SemanticHighlighting``` generating overlapping overlays because the de-sugared code in the ```Tree``` didn't match up with the actual text in the source code. Also, I think it didn't properly traverse all the nested flatMap calls in the de-sugared code which is why only the first line of the ```for``` comprehension got highlighted. I think I had some very kludgy code that sort of made things better but ended up causing failures in several existing unit tests and basically just replaced old bad behavior with new bad behavior. After becoming "finger challenged" I just gave up on it.
