### ISSUE TITLE
import of objects not appearing in import type at point

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1582]
I can create a test project if you're unable to reproduce.

I've noticed a regression in the 2.0-graph version of ensime-server that when I write something like

``` scala
import Foo.thing
```

where `Foo` is an object that hasn't been imported yet, then `Foo` is not in the list of types to import. I'm pretty sure this used to work.

**Comment by jozi-k** [comment]
Is this duplicate of #1771? Can you reproduce it now?

**Comment by fommil** [comment]
Half the bug tracker is me reporting duplicates.
