### ISSUE TITLE
Cleanup WebSocket subprotocol negotiation implementation

### ISSUE THREAD

**Issue by ktonga** [ensime/ensime-server#1594]
All the hacky code in `WebSocketFrameHandler`, related to how we setup the handler after a handshake, was put there to sort out a Netty limitation. It can be easily removed once netty/netty#5734 get released

**Comment by ktonga** [comment]
My PR netty/netty#5751 to fix  netty/netty#5734 has been merged and will be released as part of [4.1.6](https://github.com/netty/netty/milestone/153)

**Comment by fommil** [comment]
woohoo!
