### ISSUE TITLE
documentation server no longer works

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1595]
looks like https://github.com/ensime/ensime-server/pull/1573 broke the documentation server. @ktonga 

Slightly concerning that this isn't covered even by the emacs tests :-/

I did a `C-c C-v d` over the use of a `@scala.inline` and got this but it can be reproduced easier by clicking on any of the jars listed under the `/docs` REST endpoint.

```
java.io.IOException: Error when getting information for file '/home/fommil/Projects/ensime-server/.ensime_cache/index.html': No such file or directory
	at sun.nio.fs.GnomeFileTypeDetector.probeUsingGio(Native Method)
	at sun.nio.fs.GnomeFileTypeDetector.implProbeContentType(GnomeFileTypeDetector.java:72)
	at sun.nio.fs.AbstractFileTypeDetector.probeContentType(AbstractFileTypeDetector.java:52)
	at java.nio.file.Files.probeContentType(Files.java:1576)
	at org.ensime.server.DocsHandler$$anonfun$channelRead0$2.apply(DocsHandler.scala:47)
	at org.ensime.server.DocsHandler$$anonfun$channelRead0$2.apply(DocsHandler.scala:46)
	at scala.Option.fold(Option.scala:158)
	at org.ensime.server.DocsHandler.channelRead0(DocsHandler.scala:45)
	at org.ensime.server.DocsHandler.channelRead0(DocsHandler.scala:20)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
```

**Comment by ktonga** [comment]
That's all the stack? I would like to know why the server ended up looking for the type of this missing file.
Do you have any server logs showing the request for the doc URI and the response for the server? I sounds like a relative path is asked to the server so it thinks it's in the working dir

**Comment by ktonga** [comment]
Everything is working for me and the tests do cover the docs service. Could you provide a sample link from the jars list?

**Comment by fommil** [comment]
I just tried with the `2.0` branch, cleaned everything, started up a fresh ensime server 2.0.0-SNAPSHOT against it, waiting for indexing, then went to the `/docs` page and clicked on the h2 jar. Also reproduces with `scala-library`. I don't know how the logs work now for netty, is there a package I could increase the logging for to see more information?

I use GNU/Linux (ArchLinux) if that helps.

**Comment by fommil** [comment]
btw, if I `touch .ensime_cache/index.html` then I do get responses back but they seem to have the wrong meta information because the raw HTML is rendered as text.

**Comment by ktonga** [comment]
The problem seems to be the way I'm using now to get the MIME-Type for the file entry. It uses a class from the JDK which relies on platform specific mechanism and is kind of buggy in Java 7. In my case it works perfect just mapping the file extension to the proper MIME-Type but in your case it seems it's trying to read the file header (probably b/c it doesn't have the mapping info) to determine the type based on the file content, and it obviously fails since the file doesn't exist, it was never intended to be open.

When I was researching the subject I found project [Tika](https://tika.apache.org/) but it's a bit of an overkill for our use case. I'm tempted to create a simple map `extension -> MIME` supporting only the file types we expect to have in a doc jar.

What do you reckon?

**Comment by fommil** [comment]
sounds good! I guess javadocs might also have JPGs, PNGs or SVGs in them so supporting them would be good as well as `.html`

**Comment by ktonga** [comment]
Sure. I was going to inspect a few jars and take a look at what kind of files I find

**Comment by ktonga** [comment]
If you run this in a Scala REPL for your Java version:

```
scala> new javax.activation.MimetypesFileTypeMap().getContentType("lalala.html")
res1: String = text/html
```

What you get? This should work since 1.6

**Comment by fommil** [comment]
```
scala> new javax.activation.MimetypesFileTypeMap().getContentType("lalala.html")
res0: String = text/html
```

**Comment by ktonga** [comment]
Hmmm... seems to be a little bit more reliable than ` Files.probeContentType`. I will give it a try.

Do you think I should add some logging lines to docs service?

**Comment by ktonga** [comment]
Can we use it (LICENSE)?
https://raw.githubusercontent.com/spring-projects/spring-framework/master/spring-context-support/src/main/resources/org/springframework/mail/javamail/mime.types

**Comment by fommil** [comment]
Yeah we can definitely use apache2, or bsd3 or mit.

**Comment by ktonga** [comment]
Yep, I figured out already. Included in the PR I've just opened.
