### ISSUE TITLE
add API for "remove file from presentation compiler"

### ISSUE THREAD

**Issue by dragos** [ensime/ensime-server#1603]
The Scala presentation compiler works by type-checking a set of files in the background. Files are added to the set of "managed" files by `askReload`.  During type-checking errors are reported _only_ for these files.

Usually, files are added to the "managed" set when they are open in a tab and removed when the tab is closed. The smaller the set of files that are managed, the faster the round-trip and the more responsive the PC is. Other than that, there is no harm in keeping files around.

The corresponding method for removing a file is [removeUnitOf](https://github.com/scala/scala/blob/2.12.x/src/interactive/scala/tools/nsc/interactive/CompilerControl.scala#L21). Currently Ensime does not offer an API for this call, only "removeAll". In the Eclipse implementation, this is surrounded by `ask`, so that's probably a good idea.

**Comment by fommil** [comment]
Hmm, yeah this probably shows up when we delete files. I thought we did this when we closed buffers in emacs.

**Comment by diesalbla** [comment]
I am currently working on this issue.

**Comment by dragos** [comment]
Cool, let me know if I can help. I know the presentation compiler fairly well.

**Comment by dragos** [comment]
This is what the Eclipse plugin is doing, and what I think Ensime should support: https://github.com/scala-ide/scala-ide/blob/master/org.scala-ide.sdt.core/src/org/scalaide/core/internal/compiler/ScalaPresentationCompiler.scala#L297-L300

**Comment by fommil** [comment]
we really need to resync with the scala-ide codebase in this area

**Comment by fommil** [comment]
Hi @diesalbla did you get anywhere with this? If you'd like to pick up another one after, the #1556 might be just up your alley! Especially now you have some experience with the API and internals of the PC actor.

**Comment by sugakandrey** [comment]
Is anyone against me taking this? I almost got it done before the hackday anyways.

**Comment by diesalbla** [comment]
@sugakandrey No problem. I am afraid I did not get too far on this.

**Comment by fommil** [comment]
@diesalbla there is always next time :-D
