### ISSUE TITLE
Ensime notes should not remove newlines

### ISSUE THREAD

**Issue by dragos** [ensime/ensime-server#1604]
Eclipse is notorious for not handling multi-line error messages, but it shouldn't force everyone else to follow the same limitation.

Ensime removes newlines from Scala errors, even though some clients (like VS Code) would render them just fine. This is particularly annoying for "type mismatch" errors.

If this is a problem in existing clients, maybe a new field could be added, "rawMessage".

**Comment by fommil** [comment]
+1

**Comment by fommil** [comment]
Sounds trivial, pr then we can beta test any problems?
