### ISSUE TITLE
Remove scalariform

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1606]
If we create a small sbt Task to format a single file we can remove the formatting api calls. The emacs commands could be transparently changed to send the relevant sbt command instead. We could provide the task under ensime-sbt until upstream take it.

**Comment by yyadavalli** [comment]
Once https://github.com/ensime/ensime-sbt/pull/230 is merged and the clients updated, we should be able to remove `FormatOneSourceReq` and `FormatSourceReq`, scalariform still stays on for `ExpandSelectionReq`.

But I think the bigger issue is we are removing a feature from ensime and putting in a sbt plugin. Users of other build tools will no longer have access to it, are we okay with that.

**Comment by yyadavalli** [comment]
Also, I'm not sure if we could remove the `formattingPrefs` from `EnsimeConfig`

**Comment by fommil** [comment]
Yeah, they aren't going to be able to use ensime 2.0 until they update the build plugin anyway.
