### ISSUE TITLE
Rewrite expand region without scalariform

### ISSUE THREAD

**Issue by yyadavalli** [ensime/ensime-server#1622]
With #1619  done, the only functionality using scalariform is expand region. Rewriting that would enable us to completely remove scalariform from the server and place it in the build tool plugins.

**Comment by dragos** [comment]
From the Gitter channel, regarding parse trees via the presentation compiler:

>The parser is (surprisingly) thread safe. And that’s pretty cheap, so we just parse when we need. No way to ask the compiler to give you a parse tree though. Here’s how we do that in Eclipse:
https://github.com/scala-ide/scala-ide/blob/master/org.scala-ide.sdt.core/src/org/scalaide/core/compiler/CompilerApiExtensions.scala
short and sweet
https://github.com/scala-ide/scala-ide/blob/master/org.scala-ide.sdt.core/src/org/scalaide/core/compiler/CompilerApiExtensions.scala#L34
You could modify the scala.tools.nsc.interactive.Global.Locator class to collect all nodes it traverses, instead of returning only the last one.

**Comment by fommil** [comment]
You know the other option might be @lihaoyi's fastparse and scala parser, which is used by scala meta, I think. Isn't any case, we plan to add it as a dep anyway. Haoyi, does that report back position info?

**Comment by dragos** [comment]
You just removed a dependency providing this functionality, and still have a perfectly working parser that's 100% correct (by definition ;-)). I'm not saying the library is bad, it's probably great, but I found Scala dependencies to carry a significant cost when used in such tools. Why would you add one more (with it's own dependencies)?

**Comment by fommil** [comment]
@dragos in this case it is ok because `scala.meta` depends on `fastparse` and is therefore going to be "blessed" in future versions of scala. Also, moving from parboiled2 => fastparse was on the cards too, so we're still reducing our dependency list.

**Comment by fommil** [comment]
this might be exactly what Iulian was saying, but I learnt that it may be possible to manually invoke the scalac parser and get back a tree... which is going to be a lot more reliable than either fastparse or scalariform.

**Comment by fommil** [comment]
I'm also thinking that we should do more with the inferred curly brackets... perhaps send the info back asyncronously when available and use it in emacs to add transparent faces to enable super fast semantic navigation (go to start/end of block, kill block, etc... a subset of smart-parens)

**Comment by dragos** [comment]
Yeah, that's what I was trying to say  :)
