### ISSUE TITLE
Limit source watching to creation and deletion of files

### ISSUE THREAD

**Issue by yyadavalli** [ensime/ensime-server#1625]
Source resolver needs an update only when files are added or deleted

Comments  in #1624 
> I'll need to look at this one in some detail because my description of it in the ticket might not have been top quality. We still want to watch sources for when they are created or deleted, to update the source resolver. But we no longer want to watch sources to cause re-typechecking or updates to the source resolver unless the existence of the files has changed.

**Comment by fommil** [comment]
yeah, as you noted, I think this is best fixed in #1492 which is why we introduced the workaround in the first place.
