### ISSUE TITLE
remove commons-io, commons-lang and guava

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1643]
there is no reason to use these utils since much of the functionality is now rolled into java 7 or 8 (especially on the IO side) and these are poor substitutes.

We may still wish to use them in the testing projects for assertions on using them from client code, but we shouldn't use them directly in our runtime or test code.

**Comment by fommil** [comment]
the use of the `unescapeHtml` could probably handle a much smaller subset of html things.

**Comment by pascr** [comment]
Will be happy to give that a go

**Comment by fommil** [comment]
cool! starting here is a good place http://ensime.github.io//contributing/

**Comment by fommil** [comment]
btw if you can move us to use `Path` instead of `File` that's always good but be careful about conflicting too much with #1637

**Comment by pascr** [comment]
Starting with commons-lang first.

**Comment by fommil** [comment]
@pascr I completely forgot about the stickers I had in my bag at the hack day. Be sure to ask for some at the next hack day, or email/gitter me your mail address and I'll post some.

**Comment by fommil** [comment]
I've made this a lot easier with my latest PR. We now have a lot of functionality around nio `Path` objects that previously was coming from Guava.

**Comment by strobe** [comment]
@pascr Could you create pull request with your commons-lang and HtmlUtil changes? 
I tried to do same things for #1740, but after I found that your code was updated recently, therefore I don't wish to repeat your work.

**Comment by pascr** [comment]
@strobe sure, will do it later today

**Comment by fommil** [comment]
Awesome

**Comment by jozi-k** [comment]
I was going through "low hanging fruit" issues and this one seems to be already resolved.
