### ISSUE TITLE
CanonSpec and EnsimeFileSpec fail if JAVA_HOME does not exist

### ISSUE THREAD

**Issue by tonylotts** [ensime/ensime-server#1650]
### Steps to reproduce

1. Remove the JAVA_HOME environment variable:
```shell
unset JAVA_HOME
```
2. Run all tests, or just CanonSpec and EnsimeFileSpec:
```shell
cd ensime-server
sbt test
``` 

### Expected behaviour
CanonSpec and EnsimeFileSpec pass.

### Actual behaviour
CanonSpec and EnsimeFileSpec use the path to the JDK source archive, "src.zip", which is located within the java home directory.
The Path is built from the string returned from ```scala 
scala.util.Properties.jdkHome```.
If JAVA_HOME is set, then jdkHome returns the java home directory. If JAVA_HOME is not set (such as the default on some systems like macOS), jdkHome returns '.<java home directoyr>/jre' which is a sibling to 'src.zip'

**Comment by fommil** [comment]
sorry, not a bug. See comments in PR.
