### ISSUE TITLE
Allow empty source dirs

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1652]
The java 6 filewatcher couldn't handle empty source dirs, maybe it can now @lxol ?

In which case we nhould allow them, and remove unpleasantness in the sbt plugin.

**Comment by lxol** [comment]
The new watcher should handle that. This is from FileWatcherSpec:
 
 it should "detect added / changed files"
 it should "detect added / removed files"
 it should "detect removed base directory"
 it should "detect removed parent base directory"
 it should "survive deletion of the watched directory"
 it should "be able to start up from a non-existent directory"
 it should "survive removed parent base directory and recreated base"
 it should "detect changes to a file base"
 it should "detect removal of a file base"
 it should "be able to start up from a non-existent base file"
 it should "survive removal of a file base"

**Comment by fommil** [comment]
meh, it's kinda simpler to not have to handle empty dirs
