### ISSUE TITLE
Debugging server hang in complex project

### ISSUE THREAD

**Issue by nicklan** [ensime/ensime-server#1655]
I'm working on getting ensime to run a complex project.  The project builds using bazel, so I've written some a basic bazel aspect to try and figure out the config for ensime.  Currently however, ensime simply hangs when I try to use any functionality. 

I'm fairly sure this is an error in my config file, but I'm having trouble debugging what the error might be.  I've configured logback to debug everything, but the only message output after I do something like inspect-type-at-point is:

```
10:25:36.591 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/3 o.e.s.RequestHandler - InspectTypeAtPointReq(Left([snip]/Class.scala),OffsetRange(357,357))
10:25:36.592 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message InspectTypeAtPointReq(Left[snip]Class.scala),OffsetRange(357,357)) from Actor[akka://ENSIME/user/ensime-main/tcp-server/con1/3#2105767425] in state hand
```

Then emacs/ensime simply hangs.  If I C-g then I get:
```
10:25:36.593 INFO  akka://ENSIME/deadLetters a.a.DeadLetterActorRef - Message [org.ensime.api.InspectTypeAtPointReq] from Actor[akka://ENSIME/user/ensime-main/tcp-server/con1/3#2105767425] to Actor[akka://ENSIME/deadLetters] was not delivered. [2] dead letters encountered. This logging can be turned off or adjusted wit
```

*Backtrace* has the following:
```elisp
Debugger entered--Lisp error: (quit)
  accept-process-output(nil 1 0)
  ensime-eval((swank:inspect-type-at-point "[snip]Class.scala" (357 357)))
  ensime-rpc-inspect-type-at-range()
  ensime-type-inspect-info-at-point()
  ensime-inspect-type-at-point()
  funcall-interactively(ensime-inspect-type-at-point)
  call-interactively(ensime-inspect-type-at-point nil nil)
  command-execute(ensime-inspect-type-at-point)
```

Obviously I'm not asking for a solution here since I can't give you the project to debug, but I would love some suggestions on where I could start looking to figure out what errors I might have in my generated config file.

Thanks!

**Comment by fommil** [comment]
How can we help you to implement this? We have some very detailed documentation to get you started at http://ensime.org/contributing/
Can you please give a reproduction in the form of a unit or integration test? A github repository with exact instructions for somebody to follow, like a script, is also a good starting point. We are more than happy to help you turn it into an automated test, and discuss ideas on how to fix it. Read the http://ensime.org/contributing guide for more information.

We close tickets that look like a known issue or don't provide the details requested by the template, but it's not the end of the conversation and we will open it up again when there is enough information to go on. This is to improve the quality of our issue tracker and to make it easier for contributors to help.

We will reopen this ticket if you can confirm it is a bug by giving us a **detailed** reproduction. Please read the http://ensime.org/getting_help guide to understand the steps that are required prior to submitting a bug report.

**Comment by grouzen** [comment]
I can confirm the same issue on both my gentoo boxes (I thought I'm the only one with the issue ;))
