### ISSUE TITLE
refactoring support for java

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1667]
@arichiardi better to start a fresh ticket for a new discussion

You want to implement stub methods for clasess that implement an interface.

This would be considered a refactoring, which we currently don't have any support for in java. But there is precedent for this in scala, which means the protocols and client support are all in place. The idea would be to send a diff back to the client.

Have a look at the java compiler files and the scala refactoring files, and the tests for each. That should give you a good idea of where to start.

Personally I'd love to see "add type at point" in java! i.e. convert

```java
foo = Foo.bar(baz, "bap")
```

to

```java
String foo = Foo.bar(baz, "bap")
```

**Comment by arichiardi** [comment]
Thanks for the ticket, I am not a big Scala dev (I took the Coursera  course but then switched to Clojure) but I'll try my best. The idea is to have the classic completion that all the IDEs have when you implement and interface.
