### ISSUE TITLE
Failed to connect ensime server from emacs

### ISSUE THREAD

**Issue by hypeboyz** [ensime/ensime-server#1672]
### Steps to reproduce

1. Start emacs
2. M-x ensime
3. Get the server error

### Expected behaviour

Connected to the server and loaded the project, then returning a sentence
...

### Actual behaviour

Failed to connect: server process exited
...

Everything worked well days ago until Dec. 3. The project I was working on suddenly lost connection and I can no longer connect it. Tried clear .ensime_case and .ensime many times without luck. The error messages can be found in attachment.
My emacs-ensime version is 1.0 from maple-stable and my sbt-ensime version is 1.12.3

[ensime-server-log.txt](https://github.com/ensime/ensime-server/files/630776/ensime-server-log.txt)

**Comment by fommil** [comment]
Can you please give a reproduction in the form of a unit or integration test? A github repository with exact instructions for somebody to follow, like a script, is also a good starting point. We are more than happy to help you turn it into an automated test, and discuss ideas on how to fix it. Read the http://ensime.org/contributing guide for more information.

We close tickets that look like a known issue or don't provide the details requested by the template, but it's not the end of the conversation and we will open it up again when there is enough information to go on. This is to improve the quality of our issue tracker and to make it easier for contributors to help.

We will reopen this ticket if you can confirm it is a bug by giving us a **detailed** reproduction. Please read the http://ensime.org/getting_help guide to understand the steps that are required prior to submitting a bug report.
