### ISSUE TITLE
Do not underline implicit conversions on multi-line expressions

### ISSUE THREAD

**Issue by mikaelv** [ensime/ensime-server#1680]
This kind of string is underlined to highlight an implicit conversion:

```
"""Multiline pimped strings
|are underlined
""".stripMargin
```

This does not look great and is not particularly useful when conversion happens on Strings.

**Comment by fommil** [comment]
:+1: we should have an exclusion rule

**Comment by fommil** [comment]
maybe we should do what intellij does, and underline the method that is called (but not it's parameters) instead of the thing that is implicitly converted.
