### ISSUE TITLE
dead letters encountered in InspectTypeByNameReq

### ISSUE THREAD

**Issue by Winiex** [ensime/ensime-server#1691]
I'm trying to run ensime server in terminal using command below:

`java -Xmx2048m -cp tools.jar:scala-compiler-2.11.8.jar:scala-library-2.11.8.jar:scala-reflect-2.11.8.jar:scalap-2.11.8.jar:ensime_2.11-1.0.0-assembly.jar -Densime.protocol=jerk -Densime.config=/Users/winiex/repository/code/hadoop-lab/.ensime org.ensime.server.Server`

All the jars are copied into the same directory. The hadoop-lab is a java project based on hadoop library jars.

And then I write a simple python websocket client to send request to the server, such as `InspectTypeByNameReq` request:

```python
from websocket import create_connection

def req_ConnectionInfoReq(conn):
      data = {
            'callId': 1,
            'req': {
                  'typehint':'ConnectionInfoReq'
            }
      }

      conn.send(json.dumps(data))
      print_response(conn.recv_data())

def req_InspectTypeByNameReq(conn, name):
      data = {
            'callId': 2,
            'req': {
                  'typehint': 'InspectTypeByNameReq',
                  'name': name,
            }
      }

      conn.send(json.dumps(data))
      print_response(conn.recv_data())

conn = create_connection('ws://127.0.0.1:57256/jerky')
req_ConnectionInfoReq(conn)
req_InspectTypeByNameReq(conn, 'java.lang.String')
```

The result is `req_ConnectionInfoReq` works just fine, but `req_InspectTypeByNameReq` encounters a `dead letters encountered` error, with no response returned from the server. Here is the log ensime server shows:

> 01:53:23.470 INFO  None a.e.s.Slf4jLogger - Slf4jLogger started
> 01:53:23.481 DEBUG EventStream(akka://ENSIME) a.e.EventStream - logger log1-Slf4jLogger started
> 01:53:23.485 DEBUG EventStream(akka://ENSIME) a.e.EventStream - Default Loggers started
> 01:53:23.531 INFO  None o.a.c.v.i.StandardFileSystemManager - Using "/var/folders/qc/c169c6j957gbcg2fm08d1jz80000gn/T/vfs_cache" as temporary files store.
> 01:53:23.613 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.TcpListener - Successfully bound to /127.0.0.1:57255
> 01:53:23.618 INFO  akka://ENSIME/user/ensime-main/tcp-server o.e.s.t.TCPServer - Bound server on port 57255
> 01:53:23.626 INFO  None o.e.s.PortUtil$ - creating port file: /Users/winiex/repository/code/hadoop-lab/.ensime_cache/port
> 01:53:24.590 DEBUG None o.e.f.FileWatchService - init watcher
> 01:53:24.592 DEBUG None o.e.f.FileWatchService - start a background monitoring thread
> 01:53:24.593 DEBUG None o.e.f.FileWatchService - start monitoring WatchService events
> 01:53:24.648 DEBUG None o.e.f.FileWatchService - init watcher
> 01:53:24.648 DEBUG None o.e.f.FileWatchService - start a background monitoring thread
> 01:53:24.648 DEBUG None o.e.f.FileWatchService - start monitoring WatchService events
> 01:53:24.649 DEBUG None o.e.f.FileWatchService - init watcher
> 01:53:24.649 DEBUG None o.e.f.FileWatchService - start a background monitoring thread
> 01:53:24.650 DEBUG None o.e.f.FileWatchService - start monitoring WatchService events
> 01:53:24.976 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.TcpListener - Successfully bound to /127.0.0.1:57256
> 01:53:24.988 INFO  None o.e.s.PortUtil$ - creating port file: /Users/winiex/repository/code/hadoop-lab/.ensime_cache/http
> 01:53:24.988 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - ENSIME HTTP on /127.0.0.1
> 01:53:24.990 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - Environment:
> 01:53:24.991 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   OS : Mac OS X
> 01:53:24.991 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Java : Java HotSpot(TM) 64-Bit Server VM 25.111-b14, Java(TM) SE Runtime Environment 1.8.0_111-b14
> 01:53:24.991 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Scala version: version 2.11.8
> 01:53:24.992 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Ensime : 1.0.0
> 01:53:24.992 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Built with Scala version: 2.11.8
> 01:53:24.992 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Built with sbt version: 0.13.11
> 01:53:24.993 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Built from git sha: cf6a0453d3a7890b3a711769cee081b497f535b6
> 01:53:24.993 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Built on: 2016-06-25 12:25:39.832
> 01:53:46.451 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.TcpListener - New connection accepted
> 01:53:47.141 DEBUG akka://ENSIME/user/$a/32706 o.e.s.RequestHandler - ConnectionInfoReq
> 01:53:47.143 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message ConnectionInfoReq in state awaitingConnectionInfoReq
> 01:53:47.146 DEBUG akka://ENSIME/user/$a/32706 o.e.s.RequestHandler - received handled message ConnectionInfo(None,EnsimeImplementation(ENSIME),1.0) in state receive
> 01:53:47.298 DEBUG akka://ENSIME/user/$a/5078 o.e.s.RequestHandler - InspectTypeAtPointReq(Left(/Users/winiex/repository/code/hadoop-lab/src/main/java/com/bachiscoding/hadoop/lab/ipc/IPCClient.java),OffsetRange(369,385))
> 01:53:47.483 WARN  akka://ENSIME/user/ensime-main/project o.e.c.Project - Detected a pure Java project. Scala queries are not available.
> 01:53:47.484 INFO  None c.z.h.HikariDataSource - HikariCP pool HikariPool-0 is starting.
> 01:53:47.508 DEBUG akka://ENSIME/user/$a o.e.s.ConnectionHandler - received handled message AnalyzerReadyEvent
> 01:53:47.577 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message InspectTypeAtPointReq(Left(/Users/winiex/repository/code/hadoop-lab/src/main/java/com/bachiscoding/hadoop/lab/ipc/IPCClient.java),OffsetRange(369,385)) in state handleRequests
> 01:53:47.578 INFO  akka://ENSIME/deadLetters a.a.DeadLetterActorRef - Message [org.ensime.api.InspectTypeAtPointReq] from Actor[akka://ENSIME/user/$a/5078#-871394335] to Actor[akka://ENSIME/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settin
> 01:53:47.954 DEBUG None o.e.i.SearchService - findStaleFileChecks
> 01:53:47.970 DEBUG None o.e.i.SearchService - removing 0 stale files from the index
> 01:53:47.982 DEBUG None o.e.i.SearchService - Indexing bases...
> 01:53:47.992 DEBUG None o.e.i.SearchService - indexing file:///Users/winiex/.m2/repository/com/sun/jersey/jersey-json/1.9/jersey-json-1.9.jar
> 01:53:47.993 DEBUG None o.e.i.SearchService - indexing file:///Users/winiex/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.jar
> 01:53:47.994 DEBUG None o.e.i.SearchService - indexing file:///Users/winiex/.m2/repository/com/sun/jersey/jersey-server/1.9/jersey-server-1.9.jar
> 01:53:48.130 DEBUG None o.e.i.SearchService - committing index to disk...
> 01:53:48.131 DEBUG None o.e.i.SearchService - ...done committing index
> 01:53:48.134 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - created 0 and removed 0 searchable rows
> 01:53:48.134 DEBUG akka://ENSIME/user/$a o.e.s.ConnectionHandler - received handled message IndexerReadyEvent
> 01:56:34.693 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.TcpListener - New connection accepted
> 01:56:34.719 DEBUG akka://ENSIME/user/$b o.e.s.ConnectionHandler - received handled message IndexerReadyEvent
> 01:56:34.720 DEBUG akka://ENSIME/user/$b o.e.s.ConnectionHandler - received handled message AnalyzerReadyEvent
> 01:56:34.720 DEBUG akka://ENSIME/user/ensime-main/StreamSupervisor-0/flow-14-0-actorRefSource a.s.i.ActorRefSourceActor - Dropping element because there is no downstream demand: [RpcResponseEnvelope(None,IndexerReadyEvent)]
> 01:56:34.720 DEBUG akka://ENSIME/user/ensime-main/StreamSupervisor-0/flow-14-0-actorRefSource a.s.i.ActorRefSourceActor - Dropping element because there is no downstream demand: [RpcResponseEnvelope(None,AnalyzerReadyEvent)]
> 01:56:34.751 DEBUG akka://ENSIME/user/$b/84334 o.e.s.RequestHandler - ConnectionInfoReq
> 01:56:34.751 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message ConnectionInfoReq in state handleRequests
> 01:56:34.755 DEBUG akka://ENSIME/user/$b/84334 o.e.s.RequestHandler - received handled message ConnectionInfo(None,EnsimeImplementation(ENSIME),1.0) in state receive
> 01:56:34.769 DEBUG akka://ENSIME/user/$b/485 o.e.s.RequestHandler - InspectTypeByNameReq(org.apache.hadoop.ipc.RPC)
> 01:56:34.770 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message InspectTypeByNameReq(org.apache.hadoop.ipc.RPC) in state handleRequests
> 01:56:34.770 INFO  akka://ENSIME/deadLetters a.a.DeadLetterActorRef - Message [org.ensime.api.InspectTypeByNameReq] from Actor[akka://ENSIME/user/$b/485#-217539582] to Actor[akka://ENSIME/deadLetters] was not delivered. [2] dead letters encountered. This logging can be turned off or adjusted with configuration settings

My assembly jar is downloaded from `ensime.typelevel.org`, and the information about my system is below:

> java -version
> java version "1.8.0_111"
> Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
> Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
> 
> uname -a
> Darwin GLaDOS-Air 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64

Could you tell me what's wrong with my trying? Thanks a lot. :)

**Comment by fommil** [comment]
Best use the troubleshooting guide and gitter channels. We don't use the issue tracker for support.

**Comment by Winiex** [comment]
Okay, sorry for the mistake. Thanks for you reply.
