### ISSUE TITLE
alternative find usages query using only the indexer

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1753]
the current impl of find usages (with the graph) loads all files into the PC. It would be good to have a variant that just returns the files and lines for displaying in the client like a grep query.

**Comment by fommil** [comment]
(some discussion in linked / closed tickets)

**Comment by VC1995** [comment]
@fommil Hey, I was out of scala work so wanted to pick this up. Just needed to clear a few things :)

Currently we use the `GraphService` to get an Iterable of `FqnSymbol`. We then use the filename(uri) information to load the file in compiler and then later, using `usesOfSym(pos, files)` we return `ERangePosition`s which have `filename` and also the `offset`. Am I right?

If we already have the `source` and `line`, why are we loading the files in the compiler and then using `usesOfSym(pos, files)` ?

Now, do we simply want to return the `source` and `line` to the user t?(which I think is actually enough to open and scroll to that location in the editor as we can convert (row,col=1) to offset after we have loaded file in the editor)

**Comment by fommil** [comment]
yes exactly. We just want to return a list of source and lines to the client.

**Comment by VC1995** [comment]
Okay :+1:
