### ISSUE TITLE
show implementing classes

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1754]
we kind of have it with the structure view in the graph, but it would be good (like in #1753) to have a version that returns something that can be rendered like grep search results.

**Comment by fommil** [comment]
#1131

**Comment by fommil** [comment]
it would be nice if the response payload contained a list of `ancestors` and `inheritors` so that clients could choose which to show. Or maybe not, there would be advantages to keeping it simple. If we could return a tree structure that retains what inherits from what, then maybe that would be better and would allow clients to render it, e.g. in `dot`

**Comment by VC1995** [comment]
Does this boil down to using `getTypeHierarchy(fqn: String, hierarchyType: Hierarchy.Direction)` with `Hierarchy.Direction` as `SuperTypes` and `SubTypes` for `ancestors` and `inheritors` and packing it with the response as well to get something like
`SymbolInformation(refs: List[SourcePositions], ancestors: Option[TypeHierarchy], inheritors: Option[TypeHierarchy])`

**Comment by fommil** [comment]
probably, but the sourcepositions need to be on each type, not as as separate field.

**Comment by VC1995** [comment]
Oh, okay. It'll be like a separate query? I was mixing it in with response payload of "find usages".

**Comment by fommil** [comment]
yeah, separate query/response.
