### ISSUE TITLE
backpressure in the indexer

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1756]
now that writing to the index (the graph) is really slow, we need something like #1351 because I'm loathe to reintroduce the #1739

to put some numbers on this, it means we need 4g to run ensime on ensime-server, but it used to be perfectly fine with 1g... and after initial index it's fine with a few hundred MB.

Workarounds are:

in `global.sbt`

```
import org.ensime.EnsimeKeys._

// to give more RAM
ensimeJavaFlags ++= Seq("-Xmx4g")

// point to a ram disk if you're on HDD
ensimeCachePrefix in ThisBuild := Some(file("/tmp/fommil-ensime"))
```

in `.ensime-server.conf`

```
akka.search-service-dispatcher.thread-pool-executor.core-pool-size-max = 1
```

to slow down the indexer.

Personally I don't really care because I have 64GB RAM so although this is a pretty important ticket, I am not going to be picking it up :stuck_out_tongue:

**Comment by iravid** [comment]
so are we open to depending on fs2?

**Comment by fommil** [comment]
@iravid absolutely, although that might need to wait until we cut ensime 2.0 because of scala 2.10 support. What we could do is trim down the 2.0 milestone with all breaking API changes, then cut it and then add purely new features and improvements in 3.0 (2.12 only, possibly 2.11).

**Comment by iravid** [comment]
Right. So how about modeling something simple with a `BlockingQueue` in there for now?

**Comment by fommil** [comment]
@iravid I don't see how that would make it easier to reason about than the semaphore approach we did before... which got past the tests for almost a year. Do you have something specific in mind? We only really need to backpressure on startup, no need to do it for incremental indexing. That said, if we modelled this with fs2, the two would be the same thing... it'd just be a big Stream of io events.

**Comment by iravid** [comment]
Exactly as you said - it's conceptually very similar to just handling a stream of IO events. Simpler in my mind than counting semaphore acquires :-)

I'll give it a try after I'm done with #1751.

**Comment by jvican** [comment]
It would be awesome if this is one of the first tickets to be tackled in 2.0. In my opinion, it would make Ensime's potential available to all those devs working with RAM-limited laptops. :smile:

**Comment by fommil** [comment]
2.0 has been going for over a year now.

It's in the sponsorship programme but we are unlikely to get to it because it is backed up behind language server, vscode and atom... and the money runs out around about that time. Those people with RAM limited laptops are going to have to step up their game, it doesn't impact me because I have 64GB RAM on my desktop.

**Comment by jvican** [comment]
I don't have time. I'll be offering 30$ to reward whomever gets this ticket done. Procedure? @fommil

**Comment by fommil** [comment]
:smile: well I doubt $30 will attract anybody (we tried it before, for even $500 on bigger tickets) but you are certainly more than welcome to add ticket-specific bounties on bountysource. I would, however, recommend putting it towards the sponsorship programme instead as it is in more dire need of this and if we hit the target we can certainly do this after vscode and atom.

**Comment by fommil** [comment]
(probably I will cut 2.0 when this is done)

**Comment by MasseGuillaume** [comment]
I'm offering a 1.5M $ bounty to the first one to implement this.

... runs

**Comment by fommil** [comment]
those Swiss francs really convert very well these days...

**Comment by rberenguel** [comment]
If I knew how to do it I'd do it for that price @MasseGuillaume :P

**Comment by fommil** [comment]
@iravid do you think it's realistic to be able to do this before fs2 now you've had a chance to look at the code?

**Comment by iravid** [comment]
My gut feeling is that it isn't worth it :-) Here's why:
- I don't think it'll be that much faster. The only advantage a queue-based solution would have on our current approach is that it'll keep the indexing pipeline saturated. Meaning, at all times (assuming the filesystem keeps up) there will be `batchSize` bases being indexed. Is that very gainful? Not sure
- The memory usage would be the same (higher, probably, as it will be keeping more things in memory concurrently)
- We'll be ripping that code out pretty soon after adopting fs2

What do you think?

**Comment by fommil** [comment]
It's not so much about performance as putting a cap on the memory usage. If it was reasonably possible to do that for 2.0, I'd be pretty keen on it since this is going to be the stable release for a few years and that tends to be attractive to a lot of people. That said... we've survived this long on hacks an workarounds, so maybe it's not necessary.

**Comment by iravid** [comment]
I see your point. If it's memory usage we're optimizing for, maybe we could just lower the default batch size and document that as an option for speeding up the indexing process for impatient devs.

**Comment by fommil** [comment]
but it's still not a guaranteed memory limit. Maybe we shouldn't bother.

Hmm, yeah I've been meaning to change the website a little. Maybe the Contributing page should become a subpage of a new Server page and we could try to centralise Troubleshooting advice there, as well as documenting the server configuration.

**Comment by fommil** [comment]
this does now mean that 2.0 is dangerously close to being completed :wink:

**Comment by iravid** [comment]
That's awesome. Scala IDEs of the world, beware ;)

**Comment by fommil** [comment]
@iravid now that 3.0 is 2.10 free, you are welcome to implement this in fs2 :smile:

**Comment by iravid** [comment]
🎉🎉 happily!

________________________________

**Comment by fommil** [comment]
relevant https://github.com/ensime/ensime-server/issues/1902
