### ISSUE TITLE
faster deletion in the indexer

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1758]
if we do a clean / compile cycle, it takes a *long* time for the indexer to catch up and it's sat at 100% CPU while it does it.

@sugakandrey I remember benchmarking this a while ago and it was quicker than H2... did something change?

**Comment by sugakandrey** [comment]
I don't think it was faster than H2 ever. When I looked at it, Orient didn't have a way to delete a whole subgraph, so I had to manually traverse all the linked nodes to delete them.

**Comment by fommil** [comment]
I thought that was still faster than H2 though. Maybe it was faster when everything was in the same jar? But not so good when it's `.class` files.

**Comment by iravid** [comment]
I noticed that when deleting files, we're using the transactional graph. Is it possible to switch to the `NoTx` variant when doing a clean/compile cycle?

**Comment by iravid** [comment]
Also, it looks like the SQL API for Orient supports batching deletes: http://orientdb.com/docs/last/SQL-Delete-Vertex.html

Perhaps we could traverse the graph, fetch the vertices to be removed, and then perform batch deletions (by ID? not yet familiar with how vertices are identified in orient) using SQL?

**Comment by fommil** [comment]
if I was going to write the indexer from scratch I think I'd have a file format that had a file for every jar containing everything it contains and references, perhaps even beside the jar (or in a global location versioned by the ensime schema), so that there would be no need to re-index dependencies between projects. Then the "ensime cache" could be the super optimised version of that for a given project (if a cache is even needed... it might be enough to scan the files on startup)

**Comment by iravid** [comment]
Sounds quite similar to scalameta's semanticdb.

**Comment by fommil** [comment]
I wonder why :smile: (I spent a lot of time talking about that with Eugene at Scala Sphere over the last few years)

**Comment by iravid** [comment]
Sam "Puppet Master" Halliday

**Comment by iravid** [comment]
:-)

**Comment by timcharper** [comment]
Sadly, the Orientdb version of ensime-server is currently unusable for me with larger projects. I mean this in the kindest way, I'm not trying to be hyperbolic. It takes 5 minutes to populate the database, initially, and it's crazy how much space it takes up, too! For the project I work on it weighs in at 1.5GB. I think with H2, it took about 300MB or so.

I did not have any blocker performance issues when using the H2 backend. If I do a clean compile, it takes sometimes as long as 30 minutes just to delete the stale nodes.

What would be the difficulty of switching back to H2?

I've been looking as I have time to start to understand the storage backend of ensime-server. Hopefully a batch delete is possible and ensime can become usable again. But, I think, long term, @fommil , the approach of creating a index of JARs is the most sensible.

Could such a datastructure reasonable fit in memory? Or, some subset of the data?

**Comment by fommil** [comment]
moving back to h2 won't solve the problem... it's just as slow if not worse at deletions. And reverting to 1.0 would mean losing reverse lookups.

My workaround is to `ensimeSnapshot` on a version of my project before compiling. Then when I get stuck I kill the server, `ensimeRestore`, and restart the server.

Yeah, it sucks, but I don't have the time or energy to fix it properly. I really wish I did, as this impacts me in a big way.

We don't need to store everything in memory... everything could live on disk and then be indexed. I think it would take me a couple of weeks working fulltime to be able to pull it off so I couldn't expect anybody to dedicate that amount of work. It would take months doing it as a hobby. It took a whole GSoC and several months of sponsorship to get to the point where we are... we're crippled by tech debt to be honest. That's why I don't think it would even be a good use of the month we have left of Vladimir who is wrapping up LSP work.

**Comment by timcharper** [comment]
Cool, updated to ensime-sbt 2.1.0 and I see the task now. Thanks, @fommil ! This will help me to limp by so I at least don't have to switch to a different editor for now :)

**Comment by fommil** [comment]
Once I ship `scalaz-deriving` and get back into a good stride on my book, I might write up a tech spec of what I think the indexer *should* look like.

Starting to wish I'd chosen a rewrite of ENSIME as the example project in my book, then I could do two birds with one stone :smile: Who knows... maybe this could be a bonus chapter.

**Comment by vovapolu** [comment]
@sugakandrey Hi! Could we discuss this issue somewhere? I'm going to try to fix it, but can't find your contacts...

**Comment by fommil** [comment]
relevant https://github.com/ensime/ensime-server/issues/1902

**Comment by fommil** [comment]
closing in favour of #1902
