### ISSUE TITLE
Your build tool has downloaded the stable version of ENSIME but you are using the Developer Emacs install

### ISSUE THREAD

**Issue by ambjlon** [ensime/ensime-server#1762]
system environment: 
emacs24.5
maven-ensime-1.1.1 
scala 2.12.1
And, I installed ensime throught melpa.

when I typed M-x ensime, I got  an error:
**Your build tool has downloaded the stable version of ENSIME but you are using the Developer Emacs install**

**Comment by fommil** [comment]
Troubleshooting

**Comment by ambjlon** [comment]
Sorry, I cannot solve this problem with getting_help.
Is a higher version maven-ensime-plugin needed?

**Comment by fommil** [comment]
Use stable ensime for Emacs, and/or get involved with ensime-maven development. Please re-read the Emacs install page.

**Comment by ambjlon** [comment]
I installed this version through melpa @_@
![image](https://cloud.githubusercontent.com/assets/4489822/25219534/672d6fd4-25e1-11e7-8fce-eb50c9097621.png)

**Comment by fommil** [comment]
@ambjlon you need to read our docs

**Comment by ambjlon** [comment]
I have read your docs carefully.  But it still failed.
I suspect that emacs24.5+maven cannot work well.

**Comment by fommil** [comment]
@ambjlon http://ensime.org/editors/emacs/install/#installing <= this is not what you did

**Comment by ambjlon** [comment]
I did it as "Unstable / Developer Edition" Section.

**Comment by fommil** [comment]
http://ensime.org/build_tools/maven/

**Comment by amanjpro** [comment]
Ensime maven plugin does not care about the text editor and it's plugin. All it cares about is the pom file

**Comment by fommil** [comment]
@amanjpro the webpage probably needs a section to set the server version. In sbt we just default to 2.0.0-SNAPSHOT because the stable emacs client doesn't read this information.

**Comment by amanjpro** [comment]
The maven one too just defaults to the snapshot.

**Comment by ambjlon** [comment]
Sigh. I cannot solve it ~. 
![image](https://cloud.githubusercontent.com/assets/4489822/25230173/9d8e91c4-2605-11e7-8af4-dff199fed7b2.png)

**Comment by amanjpro** [comment]
Can you share your pom file?

**Comment by amanjpro** [comment]
Or at least the portion which interests the ensime maven plugin

**Comment by ambjlon** [comment]
I send it to your email sherwany (dot) amanj at gmail dot com, ok?

**Comment by fommil** [comment]
perhaps you could move this to the ensime-maven issue tracker?

**Comment by ambjlon** [comment]
ok~

**Comment by ambjlon** [comment]
@amanjpro  Have you received my email?
