### ISSUE TITLE
Drop 2.10

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1766]
As per https://mobile.twitter.com/fommil/status/856271274619875329

We are blocked to use cats/fs2/scala.meta and we have 1.0.1 2.0.0-M1 out there. Sbt 1.0 is around the corner with 2.12 in it. I propose the 2.0 milestone continue without 2.10 crossbuild support.

**Comment by iravid** [comment]
Off with its head

**Comment by fommil** [comment]
overwhelming support (90%+ on twitter). 2.0 will ship without 2.10 support.

**Comment by leandrob13** [comment]
@fommil that means we could not use ensime for sbt plugin development in v2.0.0?

**Comment by fommil** [comment]
@leandrob13 not for sbt 0.13 plugin development. But 1.0 is around the corner.

**Comment by fommil** [comment]
we'll keep 2.10 support until there is a PR that can't support 2.10. At that point, we'll cut the final milestone for `_2.10` and drop it. No reason to drop it now, it's not causing too much of a burden.

**Comment by fommil** [comment]
the 3.0 branch no longer cross builds for scala 2.10
