### ISSUE TITLE
erroneous whitespace in generated docstring

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1775]
when reviewing #1773 I noticed that a doc-at-point call to `compareAndSet` produced this (broken) URL

`http://docs.oracle.com/javase/8/docs/api/java/util/concurrent/atomic/AtomicBoolean.html#compareAndSet-boolean- boolean-`

note the space between `boolean-` and `boolean-`. Removing this space fixes the issue.

**Comment by jozi-k** [comment]
Hi @fommil, I wanted to write failing test for this issue, but realized there is one already in [DocResolverSpecs](https://github.com/ensime/ensime-server/blob/893196d7931b8e54c4a83555c80175c95e07654a/core/src/it/scala/org/ensime/core/DocResolverSpec.scala#L424). The question is if this test is written correctly. I mean, in reality, `member` in `DocSig` is created with space, i.e. `Some("max(int, int)")`. There are 2 options how to proceed:
- Leave the test as is, correct creation of `DocSig#member`
- Change the test to contain space and make it pass.

I would vote for the second option, but I want to hear more opinions.

**Comment by fommil** [comment]
you're right... this test is wrong. Please update it to include whitespace and then the fix should be clear from there.
