### ISSUE TITLE
improve the sublime plugin

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1778]
Added to ensime-server because github doesn't support cross-repo Projects and we want this in the sponsorship backlog.

Things that could be done:

- SWANK => JERKY
- share code with ensime-vim, maybe a shared lib?
- write a test suite
- implement new protocol requests that have been added over the last few years
- general bugfixes

**Comment by fommil** [comment]
@dickwall @rorygraves @djspiewak would you guys be able to help out our sponsored developer @VC1995 when he works on this, probably in a few weeks?

**Comment by djspiewak** [comment]
I'd be happy to assist if I can.  It's unlikely that I'll have anything useful to help with though, given that I've only worked on the syntax highlighting.

**Comment by fommil** [comment]
Ah ok, I somehow thought you were involved in writing the early version of the plugin. In any case, your knowledge of the sublime may be invaluable.
