### ISSUE TITLE
use github releases instead of FTP

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1779]
I have no need for SNAPSHOT assembly jars anymore, let's just use the github Releases for distributing `-assembly.jar` files.

I don't know why we've not done this before.

**Comment by larsrh** [comment]
Is this still an issue? I'm about to decomission the server hosting ensime.typelevel.org.

**Comment by fommil** [comment]
done

**Comment by fommil** [comment]
umm, technically you can claim my Lambda World ticket :smile: https://twitter.com/fommil/status/887022235294236674

**Comment by larsrh** [comment]
Thanks for the offer; would've loved to. But no time this year!
