### ISSUE TITLE
exclusion list for completions

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1785]
very much the dual of #354 and mentioned in https://github.com/ensime/ensime-emacs/pull/623 by @yangwen0228

**Comment by yangwen0228** [comment]
So, as you mentioned, where to do this? 😃

**Comment by fommil** [comment]
The best place to start is the contributing page on the website. There are two videos there that explain the architecture of the server.

Then have a look for Analyzer and beneath that *Completion*. You should be able to find where to apply a regex filter easily enough. We can apply the $ exclusion for now but when the config PR is ready we can allow users to provide their own. I'm not sure if it applies to FQN symbols or relative.

**Comment by yangwen0228** [comment]
Ok, thank you! Then, let me watch the videos first...
