### ISSUE TITLE
Graphpocalypse browser

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1787]
The current implementation of the RPC calls used by the emacs inspector require use of the analyzer. We should rethink / redesign / rewrite the Emacs inspector to make use of the graphdb only, with appropriate and simpler API calls.

Using the global (all-seeing) Analyzer poses significant problems for #1152 which brings huge benefits for macros and compiler plugin usage.

**Comment by fommil** [comment]
@timcharper said he uses the Inspector... which may be a reason not to remove this. Would you be interested in implementing an all-new set of endpoints that could be easily implemented in Emacs (and other clients)?

My problem with the Emacs Inspector is that it's just so complicated and no other client has bothered to implement it.

On the server side, it is using the PC rather than the graph. I should imagine that anything in this area would be the super-set of https://github.com/ensime/ensime-server/issues/1754 and #1753 and #1742

**Comment by fommil** [comment]
@timcharper my recommended alternative to your usecase is to use `C-c C-v d` to get the documentation for the type at point, which is usually a far superior way to browse the methods of a class (`sbt myproject/doc` if it's in one of your own to generate the docs). Can you please try that out this week because it would be a *huge* win if we could remove these unreliable old queries... and then longer term move to Graphpocalypse-based features.

**Comment by fommil** [comment]
sorry I meant @mpollmeier ^^^

**Comment by mpollmeier** [comment]
I know `ensime-show-doc-for-symbol-at-point` and occasionally use it (however I'd prefer not to leave emacs for this). My main use case for the inspector is actually much simper: I just want to know the compiler-inferred type at point. If it doesn't list all available functions and inheritance, that's fine. 

Is there something simpler that achieves that? If not, what's a good place to start reading/investigating what's necessary to rebuild the inspector from the graph?

**Comment by fommil** [comment]
LOL you've been using it for that? You'll kick yourself... just use `C-c C-v t` use `T` for full path and prefix with the universal argument `C-u` to add to the kill ring.

**Comment by fommil** [comment]
To build a better inspector, start by watching my Scala Sphere thank (contributing page) about the Graphpocalypse, it introduces all the apis and let's you know what's there.

**Comment by mpollmeier** [comment]
Hehe, well I'm not really kicking myself now, the inspector was pretty fast for me. 
And you shouldn't have pointed me to `ensime-type-at-point`, now I have little to no incentive to rebuild the inspector :) Maybe it's actually best to be dropped.
