### ISSUE TITLE
config should use RawFile, not File

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1791]
Pretty simple refactor, will touch lots of code.

It would be good to take the opportunity to push for more nio / `Path` usage instead of legacy IO as per #1437

**Comment by fommil** [comment]
and while at it, removing `javaLibs` from the `EnsimeConfig` would be good.

**Comment by zaynetro** [comment]
I'd like to work on this one. First, I'll submit a pull request with `javaLibs` removed and then take a look at using `RawFile`.

**Comment by zaynetro** [comment]
When I start using `RawFile` from `api/common.scala` this part breaks immediately:

```
[error] ensime-server/core/src/main/scala/org/ensime/config/EnsimeConfigProtocol.scala:26: Cannot find SexpFormat for org.ensime.api.EnsimeConfig
[error]   private implicit val configFormat: SexpFormat[EnsimeConfig] = cachedImplicit
```

I suspect that `cachedImplicit` that is coming from shapeless can find implicit value for java's `File` class but doesn't know about `RawFile` class. Shall I implement `SexpFormat` for `RawFile`?

Implicit values are always a pain to me. Please, provide some guidance about this issue.

**Comment by fommil** [comment]
yes that's correct. In fact the problem is that there is no `Path` like there is for `File` in `StandardFormats.scala`, but that would break binary compatibility.

What you could do is something like what we do in `SwankyFormats.scala` but just for `RawFile`

```scala
  object Protocol extends DefaultSexpProtocol
    with OptionAltFormat
    with CamelCaseToDashes {
        implicit object EnsimeFileFormat extends SexpFormat[RawFile] {
    def write(f: RawFile): Sexp = SexpString(path.toString)
    def read(sexp: Sexp): RawFile = sexp match {
      case SexpString(file) => RawFile(file)
      case got => deserializationError(got)
    }
  }
  }
```

You may need to create a `Path` out of the `file`

**Comment by zaynetro** [comment]
Thanks for the answer. I will have time on the weekend to work on this issue again.
