### ISSUE TITLE
AppVeyor CI Broken: Windows is not unloading files

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1793]
in https://github.com/ensime/ensime-server/pull/1792 we had a weird error that we just worked around.

To reproduce, remove the hack in `ProjectFixture.scala` that ignores `Predef.scala` scala notes. Then run `BasicWorkflow` on a windows box. If you don't have access to a Windows box, edit appveyor.yml to only run this one test.

Some debugging to output the loaded file list after each stage of the test would be useful, or to print out which messages are causing which files to be loaded. e.g. add `logger.debug` info to `askReloadFiles`

**Comment by fommil** [comment]
still seeing problems, e.g. now at the end of BasicWorkflow we are getting spurious NewScalaNotesEvent from a file that's been unloaded. There is something funky going on.

**Comment by fommil** [comment]
@VC1995 if you could take a look at this one that would be good, as a break when the python and rebasing gets too much for you :smile:

**Comment by VC1995** [comment]
@fommil Yes, I was looking already. I got the that `NewScalaNotesEvent` on my linux machine as well at somepoint so this caught my eye. We also get these due the `SymbolAtPontReq` in the `BasicWorkflow` test but those are filtered out using `asyncHelper.fishForMessage`. I am going to try fixing this today :)

**Comment by fommil** [comment]
Removing fishForMessage would be a good first step.
