### ISSUE TITLE
Stable 2.0-like release?

### ISSUE THREAD

**Issue by dragos** [ensime/ensime-server#1798]
It would be very helpful for me to have a stable 2.0 release. It can be a milestone, of course. Right now the VS Code plugin is using 2.0 snapshot, downloaded via Coursier on first run. This means that some people (but not all) will see binary incompatibilities like dragos/dragos-vscode-scala#45.

I know you don't guarantee binary compatibility for library use, but any form of stable release would help tremendously.

**Comment by fommil** [comment]
I can cut an M2 this weekend if that helps

**Comment by dragos** [comment]
That would be great!

**Comment by fommil** [comment]
@dragos doing this now

**Comment by fommil** [comment]
on its way to maven central, enjoy!

**Comment by fommil** [comment]
you'll miss the new "analyzer per project" feature about to be merged.
