### ISSUE TITLE
file watchers should only restart relevant analyzers

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1802]
Once #1152 is merged, we should make our file watchers smarter. Source watchers should only restart the one module with the source in it, and classfile watchers should restart only the analyzer and its downstream dependencies.

**Comment by fommil** [comment]
@VC1995 something to work on alongside the sublime work, so you don't run of Scala coding entirely? :smile:

**Comment by VC1995** [comment]
Yep, okay :)
