### ISSUE TITLE
create javadoc from /**

### ISSUE THREAD

**Issue by albfan** [ensime/ensime-server#1810]
Is it possible that after type `/**`<Enter> on top of a class or method, ENSIME populate with a javadoc based on return, parameters and exceptions throwed?

**Comment by albfan** [comment]
Any hint of where should I ask this or why is it closed?

**Comment by fommil** [comment]
ask on the gitter room for the client you are using

**Comment by albfan** [comment]
Thanks!. Hope to contrib to this awesome project in short
