### ISSUE TITLE
build info hack

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1818]
add this https://github.com/sbt/sbt-buildinfo/issues/96#issuecomment-311155622

**Comment by fommil** [comment]
or even better, use https://github.com/dwijnand/sbt-dynver/blob/master/src/main/scala/sbtdynver/DynVerPlugin.scala#L13-L14

**Comment by arigoldx** [comment]
say @fommil -- i like double checking that i'm groking things right: the problem is that a new `.scala` file is created on every compile or test run, yah?

**Comment by fommil** [comment]
yup

**Comment by arigoldx** [comment]
well i gave it a sec and couldn't reproduce.. maybe 'cause i only ever compile in `sbt` itself (in a shell, that is).

can i please be a PITA and ask for reproduction steps?

**Comment by arigoldx** [comment]
heck, maybe i'll learning something -- i'd sure love to spend more time in emacs (than the shell) :)

**Comment by fommil** [comment]
Type compile, type compile again.

**Comment by fommil** [comment]
(this is in sbt, the need for Emacs)

**Comment by fommil** [comment]
errrr... @arigoldx I can't reproduce this. It may be the case that by using `buildInfoKeys` it doesn't redo the work whereas the standard `BuildTime` option does it everytime.

sorry for wasting your time.... (runs away very very quickly)....

**Comment by arigoldx** [comment]
aaaah ain't no biggie.

actually, thanks for double-checking. much easier when someone :100: with the problem domain gives it the ol' reproduction-test :bow:
