### ISSUE TITLE
internal fork of spray-json and spray-json-shapeless

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1821]
- to generally reduce external dependencies, part of strategic #1398 
- to avoid the ScalaJSON clusterfuck https://github.com/spray/spray-json/issues/232

**Comment by mdedetrich** [comment]
If you want to spend your time forking spray-json I can't really stop you here, just a couple of points to prevent misconceptions

- The test dependencies of ScalaJSON are exactly the same as SprayJSON (see https://github.com/spray/spray-json/issues/232#issuecomment-312285322). Note I am talking about JVM artifacts here (Scala.js artifacts are irrelevant to this issue)
- Referring to https://github.com/ensime/ensime-server/issues/1398, typelevel projects also use the same test dependencies (scalacheck, scalatest) all over the place. So even if your base dependencies are just typelevel projects, you will need these same test dependencies

At least from my PoV, this looks like an inconsistent knee jerk reaction
