### ISSUE TITLE
UsesOfSymbolAtPointReq should not try to solve symbols from classfiles

### ISSUE THREAD

**Issue by hzenginx** [ensime/ensime-server#1827]
When using UsesOfSymbolAtPoint feature on any symbol defined in classfile ensime hangs with NPE.

an example project can be any project using external libraries, including test projects in ensime.

Reproduction instructions:
 - Try to find uses of a function from standart libraries, example `"SomeString".length`
 - Kill ensime process from outside(`kill $PID`)
 - Check logs for a NPE 

Reason: Ensime is using `Symbol.sourceFile` to get source code, which returns `null` if symbol is defined in a classfile.

- [x] I have read http://ensime.org/getting_help/
- [x] I have followed the troubleshooting guide for my text editor
- [x] I have asked in http://gitter.im/ensime/ensime-server
- [x] I have included a link to an example project
- [x] I have included exact bug reproduction instructions

**Comment by fommil** [comment]
the real problem is that this API is pretty rubbish and should be replaced by https://github.com/ensime/ensime-server/issues/1753
