### ISSUE TITLE
C-c C-c a -> Server connection closed unexpectedly: connection broken by remote peer

### ISSUE THREAD

**Issue by anildigital** [ensime/ensime-server#1841]
Leave this list and include an `x` in the relevant boxes:

ENSIME ready. Let's flatMap this thing and go home!
Initializing Analyzer. Please wait... [2 times]
Mark set [2 times]
Checking entire project...
Server connection closed unexpectedly: connection broken by remote peer

Scala 2.12.3, Latest stable Ensime

- [x] I have read http://ensime.org/getting_help/
- [x] I have followed the troubleshooting guide for my text editor
- [x] I have asked in http://gitter.im/ensime/ensime-server
- [x] I have included a link to an example project
- [x] I have included exact bug reproduction instructions

**Comment by fommil** [comment]
If you're not going to do what is asked when you tick those boxes, your ticket gets closed.

**Comment by anildigital** [comment]
okay.
