### ISSUE TITLE
bugfixes for reverse lookup

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1843]
- exclude noise of self references (e.g. find usages of `SearchService` should not include usages within `SearchService`'s methods)
- include one line summary
- should work for methods

**Comment by ktonga** [comment]
Hey guys, any chance to include the column of the usage along with the line?

**Comment by fommil** [comment]
unfortunately not, it's not in the class files. See https://github.com/scalacenter/advisoryboard/pull/21 for some info. And https://github.com/lampepfl/dotty/issues/1523#issuecomment-255862771 and several discussions with the scalameta folks about putting this in the semanticdb.

**Comment by ktonga** [comment]
Ok, thank you for the references.

**Comment by VC1995** [comment]
Should we close this?

**Comment by ktonga** [comment]
Last time I tried it wasn't working for methods. Should it be working already?

**Comment by fommil** [comment]
Probably what you've done is looked for the uses of a method in an implementation of a trait or something... it will only find usages of that exact FQN. Look for usages of the trait method.
