### ISSUE TITLE
CompletionInfoList returns an empty list on failed compilation

### ISSUE THREAD

**Issue by MasseGuillaume** [ensime/ensime-server#1850]
/cc @dimart @rorygraves

to reproduce:

send a CompletionsReq with the following setup to ensime server:

```scala
object A {
  er.
//  ^autocomplete
}
```

result:

`CompletionInfoList` with empty prefix/completions

expected:

autocompletion almost always returns a result. When I see an empty list I can infer something went wrong. I think a more appropriate response could be `FalseResponse`

**Comment by fommil** [comment]
yeah, fair
