### ISSUE TITLE
Wrong response for type at point on values of type aliases

### ISSUE THREAD

**Issue by iravid** [ensime/ensime-server#1858]
Given the following (already with clues for the tests):
```
object TypeAliases {
  trait State[S, A]
  type IntState[A] = State[Int, A]
  val intInt@intintstate@State: IntState[Int] = ???
  type IntList = List[Int]
  val int@intlist@List: IntList = ???
}
```

The returned name for `intintstate` would be `State[Int]` and `List` for `intlist`. This happens because `tpe.typeSymbol` is used for constructing the name, which normalizes the typeSymbol and dealiases it. 

This has been annoying me, so PR with a fix coming up.

**Comment by fommil** [comment]
disabling dealiasing might break something else

**Comment by iravid** [comment]
Yes, it broke the display name for `java.lang.String` - it now shows `scala.Predef.String`. We can discuss in the PR :-)
