### ISSUE TITLE
`type`.class - URISyntaxException, indexing doesn't finish

### ISSUE THREAD

**Issue by jc776** [ensime/ensime-server#1869]
- [x] I have read http://ensime.org/getting_help/
- [x] I have followed the troubleshooting guide for my text editor
- [ ] I have asked in http://gitter.im/ensime/ensime-server
- [x] I have included a link to an example project
- [x] I have included exact bug reproduction instructions

- I'm on Windows 10.
- `ensime-server`: 2.0.0-M4
- `ensime-sublime`: Added the repository, "v2017.08.02.11.46.13".

[shadaj/slinky](https://github.com/shadaj/slinky)'s JAR contains a generated file \`type\`.class. When `ensime-server` tries to index it, the following effects happen:
- There's a `URISyntaxException`.
- `sbt ensimeServerIndex` never completes and doesn't exit, turning 'suspended' after 5 minutes.
- `ensime-sublime` won't give completions in this project, but still outputs compiler errors/warnings. Completions work in other projects that don't have the library.
```
$ sbt
> ensimeServerIndex
[info] Running org.ensime.server.Server
[info] ...
[info] 18:05:11.581 WARN  akka://ENSIME/user/ensime-main/project o.e.c.Project - Refresh failed: java.lang.IllegalArgumentException: Illegal character in opaque part at index 180: jar:file:///C:/Users/Jack/.coursier/cache/v1/https/repo1.maven.org/maven2/me/shadaj/slinky-web_sjs0.6_2.12/0.1.1/slinky-web_sjs0.6_2.12-0.1.1-sources.j
[info] 18:05:11.597 ERROR akka.dispatch.Dispatcher a.d.Dispatcher - Illegal character in opaque part at index 180: jar:file:///C:/Users/Jack/.coursier/cache/v1/https/repo1.maven.org/maven2/me/shadaj/slinky-web_sjs0.6_2.12/0.1.1/slinky-web_sjs0.6_2.12-0.1.1-sources.jar!/me/shadaj/slinky/web/svg/`type`.scala
[info] java.lang.IllegalArgumentException: Illegal character in opaque part at index 180: jar:file:///C:/Users/Jack/.coursier/cache/v1/https/repo1.maven.org/maven2/me/shadaj/slinky-web_sjs0.6_2.12/0.1.1/slinky-web_sjs0.6_2.12-0.1.1-sources.jar!/me/shadaj/slinky/web/svg/`type`.scala
[info] ...
[info] Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 180: jar:file:///C:/Users/Jack/.coursier/cache/v1/https/repo1.maven.org/maven2/me/shadaj/slinky-web_sjs0.6_2.12/0.1.1/slinky-web_sjs0.6_2.12-0.1.1-sources.jar!/me/shadaj/slinky/web/svg/`type`.scala
```
Example project in [jc776/ensime-url-error](https://github.com/jc776/ensime-url-error).
- Includes `.ensime` and `sbt-ensime` setup
- Includes an `sbt` log, `indexer-error.log`
- `sbt ensimeServerIndex` (after `sbt ensimeConfig`) causes the exception, and the command doesn't complete.

**Comment by fommil** [comment]
interesting, looks like a bug. I think we've had similar things in the past. Would you be interested in fixing this? It's probably a one liner somewhere in `EnsimeVFS.scala`, but you should add a test if you don't want it to regress (there is a PR with big changes in this area)

**Comment by jc776** [comment]
Alright - I'll have a go at it some time tomorrow, then.
