### ISSUE TITLE
WARNING: MaxDirectMemorySize JVM option is not set or has invalid value

### ISSUE THREAD

**Issue by dragos** [ensime/ensime-server#1879]
We get this in our VS Code integration. See dragos/dragos-vscode-scala#69.

What value should we use?

**Comment by jvican** [comment]
I've been trying to set this version everywhere and it doesn't work. Unfortunately I cannot use ensime until I know how to set this flag since I get lots of OOMs.

**Comment by kiviok** [comment]
same thing
