### ISSUE TITLE
Add the remaining methods from LSP

### ISSUE THREAD

**Issue by vovapolu** [ensime/ensime-server#1892]
Current LSP implementation supports only subset of LSP. Although this is enough for go-to-definitions, hover requests and errors/warnings highlights.

**Comment by aramesh117** [comment]
Just wondering, is your implementation of LSP in ensime-server going to replace the implementation of https://github.com/dragos/dragos-vscode-scala? I'd love to contribute but was wondering which project is going to be officially supported by ensime. Thanks!

**Comment by rorygraves** [comment]
@aramesh117 Yes, the plan is this will become the LSP implementation, meaning it can be shared among all the editors that support LSP.
