### ISSUE TITLE
rewrite indexer to use metacp

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1902]
If I have any time to work on ensime 3.0 in 2018 I would like to move more in the direction of the semanticdb. This would involve designing a spec for `semanticdb-bronze` (class files only, including scalap for scala output) and `semanticdb-silver` (reconciled with source jars).

The analysis we could perform would be the same as ensime 2.0, but major advantages include:

- indexing / reconciling once for shared binaries, instead of per-project
- a much smaller per-project db/index created that can survive rebuilds (currently the weakest part of ensime 2.0)
- make way for supporting semanticdb-gold (i.e. semanticdb as created by the scalac plugin)

// @xeno-by @olafurpg

**Comment by fommil** [comment]
Brain dump

Thanks for all the info folks. Got lots to go on.
As a side note, @fommil, I'd love to know what those top 10 commands are :wink:

Sam Halliday Dec 23 2017 19:59
heh, I honestly couldn't tell you... they are like a second language to me
I even need to think about it when I'm wondering "how do I create a new file?"

Andrew Valencik Dec 23 2017 20:00
mmmm, that's a good point. I'd have to think a fair amount about what I do most frequently in vim. Does emacs have a history file?

Salar Rahmanian Dec 25 2017 19:59
How does the ensime LSP support compare to the new sbt server provided with sbt version 1.1.0-RCx ?

Edmund Noble Dec 25 2017 21:17
It doesn't support completions or type-at-cursor
The new one, that is

Salar Rahmanian Dec 25 2017 21:27
ensime does I assume?
does ensime work with sbt 1.x now?
@edmundnoble ^^

Edmund Noble Dec 25 2017 21:30
Ensime does
I am not sure
Probably?

Sam Halliday Dec 25 2017 21:56
@dwijnand get that facepalm glove out

Andrew Valencik Jan 03 16:10
@fommil I have to admit, after looking into yasnippets I think you're right, remember that command is a lot more bang for your buck than ensime-create-test

Sam Halliday Jan 03 16:13
you could script it... e.g. if creating a file ending with Test.scala it could run the yasnippet automatically. That'd be cool, I'd probably use that.
although a lot of my projects use different testing styles, one of the worst things about the testing landscape in scala
so many ways to do it, all wrong.

Andrew Valencik Jan 03 16:15
Hah... yeah.

Andrew Valencik Jan 03 16:16
Are there "hooks" or something in place to attach that functionality to? In other words, when I currently create a file in emacs does ensime know about it at all?
Or would this script be entirely outside of ensime and just be some auto-yasnippets
(which appears to already be a package)

Sam Halliday Jan 03 16:17
outside ensime

Martin McNulty Jan 05 12:49
Hi everyone, I'm getting a lot of freezes using jump to definition, and I'm seeing future timeout exceptions in the server logs
seems like the GraphService thread has been maxing out one of my cores for c. 1 hr
(so far)
is this normal behaviour/a known issue? I've seen some issues about rewriting the indexer, so I'm wondering if this is related

Tim Spence Jan 09 11:40
Hi, do I need to do something for ensime-inf-switch to apply compiler settings from build.sbt? If I run sbt console and then :settings I see that my compiler settings are applied, but if I run ensime-inf-switch then they are not

Yash Yadavalli Jan 10 01:12
Hey @TimWSpence, ensime-inf-switch is not working, it is outdated and missing a lot of features. sbt console is the suggested workaround
We can continue this discussion in the emacs channel if you need more info

Chip Senkbeil Jan 13 21:22
@/all build server will be down while I reimage the machine. Could be a couple of days to a couple of weeks. Doesn't look like anyone has used it in nearly a month according to drone.senkbeil.org, so going to assume no one will miss it in that time.

vito-c Jan 16 19:30
what version of the server does ensime-sbt 2.2.0 use? I'm trying to make sure I have language support

Yash Yadavalli Jan 16 19:43
2.0
It should be selected automatically for you

vito-c Jan 16 20:27
looks like lsp was added in ensime-server 3.0 ensime/ensime-server#1888
so how does one specify the server version?

Yash Yadavalli Jan 16 20:41
Set ensimeServerVersion in your build files

Yash Yadavalli Jan 16 20:53
ensimeServerVersion in ThisBuild := 3.0.0-SNAPSHOT should do the trick
Note, it is not compatible with current emacs client

vito-c Jan 16 21:27
ok thanks

Tim Harper Jan 17 06:15
@martinmcnulty yeah, that is a known issue. See the ensimeSnapshot and ensimeRestore commands. Suggestion: Run ensimeConfig, then clean, then ensimeServerIndex. This will cause the server to just index your dependencies. Then, run ensimeSnapshot to save that state. When you rebuild and lots of files change then it takes a really long time for ensime to come back and be response. So you just need to re-run ensimeRestore and relaunch ensime. It totally sucks, but it is a workaround to limp by until the graphdb stuff can be optimized (or replaced by the semanticdb dream).

Tim Harper Jan 17 06:23
@fommil wrt #1902 where would be the best place to start this spec? A Google doc?

Sam Halliday Jan 17 10:22
It's all in my head at the moment, but if anybody wants to start drawing out a spec please do so. Just use the ticket.
I'm thinking we might get a month of Vladimir to work on this, so a good spec would be excellent.
I'm a bit indisposed at the moment. As with all things, 90% will need to be vervet out on the fly so the main principle is that everything should write out to an intermediate format on disk (per jar or per folder) and then there is a reconciliation stage, that also writes on to disk. Use of the index would be totally separate, with perhaps an index of the index in memory and built up from scratch every time.
For the persistence format and code, a typeclass convertor like our json or s-express thing would be a awesome
And using scalaz fundamentals as much as possible throughout. i.e. finally tagless style all the way.
fs2 for backpressure, but that can come in a follow-up.
I think we might be able to move this into a standalone subproject, out of core.

**Comment by olafurpg** [comment]
FWIW I found this related clang talk on "Index-While-Building" to be interesting https://www.youtube.com/watch?v=jGJhnIT-D2M&t=726s

**Comment by fommil** [comment]
@olafurpg I'd assume that when we move to a model of using the semanticdb, we'd just require the user to use it and then we'd get indexing for "free". For now, we watch the binary files and delete / parse them when they change.

**Comment by olafurpg** [comment]
we are employing a similar strategy for indexing with semanticdb as they explain in that video, it's actually interesting how we came to a similar architecture independently. clang is still quite a bit ahead of us, they're already using this in xcode 9 while our story is still evolving a bit.

**Comment by fommil** [comment]
I am really annoyed at myself for not doing it this way in the first place.

Flat files were an option prior to the graphpocalypse GSoC but we had no idea how bad OrientDB would be. We even did speed tests, but (despite talking about it) neglected to include flat files in the perf tests and then got pigeon holed into comparing neo4j / orientdb / etc etc.

The rewrite won't even require us to change **how** or **when** we index, it just changes the peristence format.

**Comment by olafurpg** [comment]
I'm still not convinced flat files are a better option than sql. semanticdb fits nicely into relational schema and "Goto definition" can be implemented as simple as `select * from occurrences o where o.symbol = {} and o.is_definition"`

**Comment by olafurpg** [comment]
The performance numbers in https://github.com/scalameta/scalameta/pull/1174 are promising for on-disk sqlite, with in-memory h2 I suspect we won't encounter problems with write-heavy loads

**Comment by fommil** [comment]
@olafurpg remember, we're not talking about the same data as you. We have a lot more information than you are storing. Also, saving to flat files means that indexing a jar file will share that index with all projects. A SQL database (ensime 1.0) or OrientDB (ensime 2.0) is per-project. Flat files are much faster to delete (addressing a performance issue with both SQL and GraphDB). Writing and deleting, e.g. full rebuilds, are the bottleneck in an interactive app. And redoing work, e.g. reindexing `scala-library.jar`.

**Comment by olafurpg** [comment]
> We have a lot more information than you are storing.

What information are you storing that we don't?


> A SQL database (ensime 1.0) or OrientDB (ensime 2.0) is per-project.

In Metals (old scalameta/language-server) we store all indices globally per-computer. We currently only use in-memory indices however and they consume lots of memory for large projects.

> And redoing work, e.g. reindexing scala-library.jar

These indices are shared globally in Metals and we only index the same jar once.


Either way, we will soon be publishing a lot more docs about semanticdb and its motivation. I'll send you a link once it's up 😄  We still don't have a canonical solution for "indexing", just a lot of experiments since the data is quite simple to play around with. In the long term we want to provide some standard "index" library.

**Comment by fommil** [comment]
@olafurpg http://ensime.github.io/talks/scalasphere17/

reverse lookup information, for a start.

**Comment by fommil** [comment]
@olafurpg a lib to read the semanticdb would be pretty cool, hopefully we could just swap it in for scalap. There is an old ticket for this... #1136

**Comment by olafurpg** [comment]
We support find all references in metals, but don't yet model stuff like abstract method implementations.

**Comment by olafurpg** [comment]
Reading raw semanticdb can already be done with a single method, but that just gives you the raw data without indexing. We are experimenting with APIs in metals how incremental updates and interactivity plays into the mix.

**Comment by fommil** [comment]
the data format that I seen is actually simple enough that a fastparse / adt approach would be high in my list because it gives us greatest control over I/O and minimises binary dependencies (a strategic goal).

**Comment by xeno-by** [comment]
@olafurpg and I have written down an initial version of the SemanticDB specification: https://github.com/scalameta/scalameta/pull/1220. There is still some work to do, but I feel that the document can already be useful.

**Comment by fommil** [comment]
@xeno-by @olafurpg ok, I think pulling all our efforts into metacp is the way to go, making indexing a job of the build tool and semanticdb-scalac a necessary part of using ensime 3.0.

We can figure out what is missing from the bronze db at scalasphere and make plans for a silver (which has access to sources, but not a semanticdb).

**Comment by olafurpg** [comment]
With sources alone it's possible to index global symbols. In metals we have a syntactic indexer for both Scala and Java

* https://github.com/scalameta/metals/blob/977c902b73468092def43b70ab54b3007f32951d/metals/src/main/scala/scala/meta/metals/mtags/JavaMtags.scala indexes ~450k loc/s
* https://github.com/scalameta/metals/blob/977c902b73468092def43b70ab54b3007f32951d/metals/src/main/scala/scala/meta/metals/mtags/ScalaMtags.scala indexes ~30-50k loc/s

It should be possible to get comparable indexing speed for Scala sources if someone is interested in helping out with optimizations.

For dependencies without sources, this is totally hypothetical but it should be possible to use metacp to replace scalap and get nice features such as browsing between classfiles. Our informal benchmarks for metacp indicate it can process ~20-30mb/s of classfiles, I haven't compared Scala vs. Java classpaths. No work has gone so far into optimizing metacp. Scalafix will soon require dependencies to be analyzed with metacp in order to support features like explicit result types with short names.

**Comment by olafurpg** [comment]
Note, it's only necessary to index global symbols in dependencies because those are the only symbols that are accessible from project sources. Once you goto definition in a dependency, you'll need further analysis on the open dependency source buffer to support browsing to other dependency sources.

**Comment by fommil** [comment]
yeah this all comes back to the bronze/silver/gold mental model I'm using

- bronze == metacp (i.e. ASM + scalap)
- silver == bronze + scalacemeta source parse
- gold == semanticdb

with the persistent format for bronze/silver/gold potentially being the same.

**Comment by olafurpg** [comment]
Just to clarify, both bronze and silver produce semanticdbs but only parts of the spec. In particular, 

* metacp produces only [SymbolInformation](https://github.com/scalameta/scalameta/blob/97e1e8af7ba75b7508bc47e25c766c5f83c96e1c/semanticdb/semanticdb3/semanticdb3.md#symbolinformation)
* scalameta source indexing (ScalaMtags and JavaMtags) produces [SymbolOccurrence](https://github.com/scalameta/scalameta/blob/97e1e8af7ba75b7508bc47e25c766c5f83c96e1c/semanticdb/semanticdb3/semanticdb3.md#symboloccurrence) for [global symbols](https://github.com/scalameta/scalameta/blob/97e1e8af7ba75b7508bc47e25c766c5f83c96e1c/semanticdb/semanticdb3/semanticdb3.md#symbol)
* semanticdb-scalac produces all currently supported features of semanticdb

**Comment by fommil** [comment]
yeah, that sounds like a really good starting point. Next step is figuring out what ensime needs that isn't produced by metacp.
