### ISSUE TITLE
ClassfileIndexer fails to index Java 9 multi-release classfile 

### ISSUE THREAD

**Issue by coreyoconnor** [ensime/ensime-server#1906]
Leave this list and include an `x` in the relevant boxes:

- [x ] I have read http://ensime.org/getting_help/
- [ x] I have followed the troubleshooting guide for my text editor
- [ x] I have asked in http://gitter.im/ensime/ensime-server
- [ x] I have included a link to an example project
- [x ] I have included exact bug reproduction instructions

Given a project that depends on log4j-api of at least 2.9.1 (Or another jar that uses multi-release versions under META-INF). When ensime-server attempts to index the log4j-api jar:

~~~
 DEBUG None o.e.i.ClassfileIndexer - indexing jar:file:///home/coconnor/.ivy2/cache/org.apache.logging.log4j/log4j-api/jars/log4j-api-2.9.1.jar!/META-INF/versions/9/org/apache/logging/log4j/util/ProcessIdUtil.class                                                                                                                   
 DEBUG None o.e.i.SearchService - finished indexing file:///home/coconnor/.ivy2/cache/org.apache.logging.log4j/log4j-api/jars/log4j-api-2.9.1.jar           
 WARN  akka://ENSIME/user/ensime-main/project o.e.c.Project - Refresh failed: java.lang.IllegalArgumentException                                               
 ERROR akka.dispatch.Dispatcher a.d.Dispatcher -                                                                                                               
 java.lang.IllegalArgumentException: null                                                                                                                                   
     at org.objectweb.asm.ClassReader.<init>(Unknown Source)                                                                                                                
     at org.objectweb.asm.ClassReader.<init>(Unknown Source)                                                                                                                
     at org.objectweb.asm.ClassReader.<init>(Unknown Source)                                                                                                                
     at org.ensime.indexer.ClassfileIndexer.indexClassfile(ClassfileIndexer.scala:26)                                                                                       
~~~

(Additional logging was added to ClassfileIndexer for clarity.)

Note the classfile being indexed is a multi-release classfile intended for Java 9: The classfile is under `META-INF/versions/9`. This classfile is being loaded by org.objectweb.asm and failing with `java.lang.IllegalArgumentException`.

Presuming ASM can read classfiles of the current JDK, then multi-release classfiles for later JDKs should not be indexed. In this case the JDK 8 is being used.

**Comment by coreyoconnor** [comment]
The commit:

* https://github.com/coreyoconnor/ensime-server/commit/6fa372a1301b1bb032789869d2f68f44d9484c89

avoids indexing any classfile under META-INF. Which seems fine to me. Tho  a proper solution should consider the current runtime version and filter only versions > that current.

**Comment by steven-collins-omega** [comment]
Retroactively adding a bit more context here (this bug is affecting my team as well) --

### Steps to reproduce

1. Assumption: `sbt` and `sbt-ensime` are installed (I have installed sbt 1.0.2 and sbt-ensime 2.1.0) 
1. Clone `https://github.com/steven-collins-omega/ensime-issue-1906.git`
1. As a control, `git checkout this-works` (this commit has the dependency on `log4j` commented out)
1. Run `sbt`, and at the `sbt` prompt run:
    ```
    ensimeConfig
    clean
    ensimeServerIndex
    ```
1. Note `ensimeServerIndex` completes successfully
1. Now run `git checkout master && rm -rf .ensime*`
1. Repeat Step 4
1. Note `ensimeServerIndex` logs the exception referenced in this issue and hangs
1. (Optional) Kill the hung process and repeat Step 4 again to see more clearly that it tries to index `log4j-api-2.9.1.jar` first thing and immediately fails
