### ISSUE TITLE
JsParserSpec doesn't verify test results

### ISSUE THREAD

**Issue by zainab-ali** [ensime/ensime-server#1909]
The equality checks in the `spray.json.JsParserSpec` aren't verifying any test results  as there are no matchers or `assert` statements to check them.

For example, the following test, in the current format, succeeds:
```scala
    "foobar" in {
      val foo = JsString("foo")
      val bar = JsString("bar")
      JsParser(PrettyPrinter(foo).getBytes("UTF-8")) === bar
    }
```

It fails with a matcher:
```scala
    "not foobar" in {
      val foo = JsString("foo")
      val bar = JsString("bar")
      JsParser(PrettyPrinter(foo).getBytes("UTF-8")) should ===(bar)
    }
```

I haven't yet checked other tests, but this could well be the case elsewhere.

(the list below doesn't apply to this kind of issue)
Leave this list and include an `x` in the relevant boxes:

- [ ] I have read http://ensime.org/getting_help/
- [ ] I have followed the troubleshooting guide for my text editor
- [ ] I have asked in http://gitter.im/ensime/ensime-server
- [ ] I have included a link to an example project
- [ ] I have included exact bug reproduction instructions

**Comment by rorygraves** [comment]
Ouch, thanks for the ticket - good observation - I suspect that you are right that a number of tests suffer from the same problem.

**Comment by fommil** [comment]
Oops

**Comment by fommil** [comment]
I translated them from spray-json and probably messed up the regex.

**Comment by zainab-ali** [comment]
They all passed when I fixed them anyway, so no harm done!
