### ISSUE TITLE
LSP notification json objects are incorrectly decoded into requests

### ISSUE THREAD

**Issue by zainab-ali** [ensime/ensime-server#1911]
LSP notification json objects get incorrectly decoded into requests with a null id:

For example:
```scala
JsObject(Map(
  jsonrpc -> JsString(2.0),
  method -> JsString("textDocument/didOpen"),
  params -> JsObject(Map(
    "textDocument" -> JsObject(Map(
      "uri" -> JsString("file:///path/to/file.scala"),
      "languageId" -> JsString("scala-yay"),
      "version" -> JsNumber(0),
      "text" -> JsString("someFileText")))))))
```
Is decoded into:
```scala
JsonRpcRequestMessage(
  2.0,
  "textDocument/didOpen",
  Some(ObjectParams(JsObject(Map(
    "textDocument" ->
      JsObject(Map(
        "uri" -> JsString("file:///path/to/file.scala"),
        "languageId" -> JsString("scala-yay"),
        "version" -> JsNumber(0),
        "text" -> JsString("someFileText")
      )))))),NullId)
```
This uses the `JsReader[JsonRpcMessage].read(json)` for decoding.  The `Connection` uses this decoder for attempting to decode notifications.

**Comment by zainab-ali** [comment]
A quick glance at the [LSP spec](https://microsoft.github.io/language-server-protocol/specification) indicates that requests should always have a non-null `id` parameter.  This isn't enforced within the `JsonRpcMessage` decoder, although an attempt is made to do this in the `JsonRpcRequestOrNotificationMessage` decoder.

I'll put in a PR to make the `JsonRpcRequestMessage` decoder fail on null ids.

**Comment by vovapolu** [comment]
`NullId` means both absence of `id` and `id: null`. Sometimes (`shutdown` request if I remember correctly) LSP sends `id: null` and  it means something...

**Comment by vovapolu** [comment]
So if decoder fails on requests with `NullId` it fails on `shutdown` also.

**Comment by zainab-ali** [comment]
That makes things more complicated.  I've had a look at a few other clients, notably [rust](https://github.com/rust-lang-nursery/rls/blob/55b1981909f4c14940072f0dead982b3c68f91de/src/server.rs) and [haskell](https://github.com/alanz/haskell-lsp/blob/master/src/Language/Haskell/LSP/TH/DataTypesJSON.hs).  These decode based on the method name.  I think that makes more sense than what we're doing here.  

I'd propose decoding to a general`LSPMessage` class as follows:
```scala
case class LspMessage(
id: ConnectionId,
method: Method,
params ...
)
```
And then converting that into a specific `JsonRpcRequestMessage` or `JsonRpcNotificationMessage` based on the method name.

What do you think of that approach?

**Comment by fommil** [comment]
I wasn't aware we had a choice... :+1: to anything that doesn't require 3 possible concepts of null.

**Comment by fommil** [comment]
@zainab-ali if you're getting into LSP, you might want to come to scalasphere. Will be much discussed.

**Comment by zainab-ali** [comment]
@fommil I probably can't attend this year, but I'll definitely keep an eye on the talks.  I have haskell connected up with LSP, and want to do the same for Scala.

**Comment by fommil** [comment]
anything you can do is appreciated. I am not maintaining ensime anymore but I can give you merge rights if you find that your PRs are being ignored.

**Comment by zainab-ali** [comment]
I've looked at the code in a bit more detail and am about to start an implementation.  

The haskell and rust implementations are simpler, but they don't give as much detail when it comes to parsing failures.  The current code enumerates `method not found` and `invalid params` as different errors.  I want to keep that. 

Unfortunately we're probably stuck with several different kinds of null - it's in the lsp spec after all.  I'll add some docs around this area, if nothing else.

What do you think of the following pseudocode?
```
Try and parse json
  failed => respond with error: cannot parse json
  succeeded =>
    is there a method field?
      yes => find the method in a list of methods
        is there a matching method?
          yes => 
            This is a request or notification.  Try and parse the params
              failed => respond with error: invalid params
              succeeded =>  return request or notification
          no => respond with error: method not found
      no => this must be a response 
        is there an error field?
          yes => this is a response with an error
          no => is there a result field?
            yes => this is a successful response with a result
            no => this is a successful response without a result
```

I'll implement the above and open up a PR soon.

**Comment by fommil** [comment]
I don't know the LSP code sorry, @vovapolu is the expert there... I'm still a fan of SWANK and I'd prefer to move to SWANKY than LSP :smile: 

which editor are you using?

**Comment by zainab-ali** [comment]
emacs, of course 😄

**Comment by fommil** [comment]
if you get it working, I'd be interesting in hearing about your setup. I heard the emacs lsp clients block on the main thread... whereas swank / swanky can be async (via buffers, so it doesn't block the main thread). LSP doesn't seem to allow out of band messages, which concerned me. e.g. inline warnings.

there is an initiative to rewrite the ensime-emacs client, but it sounds like that is not your thing :smile:

**Comment by zainab-ali** [comment]
I've got back on fixing this as part of #1935.  Could we possibly restore the issue?

**Comment by fommil** [comment]
with regards to JSON in general, something I've done in work projects is to have the json form of some things in the resources directory and then assert we serialise / deserialise to that exact string. If it fails, then mutable the file on disk so it is tracked along with git (which is much better than the scalatest differ), which can be backed out easily if it was an accident.

From my reading of the tests in the lsp module, we seem to be testing a lot of things that we don't need to be testing (i.e. testing the json library itself) and the json format we want to support can probably be supported with a much cleaner ADT.
