### ISSUE TITLE
SearchService.extractSymbols should recover when indexing a class throws certain exceptions

### ISSUE THREAD

**Issue by steven-collins-omega** [ensime/ensime-server#1912]
#1906 is essentially a special case of this. One could imagine many reasons (perhaps especially ones related to a new JDK version being out in the wild, which is the specific problem in #1906) why indexing a particular class would throw an exception but the overall indexing process _could_ recover. That is not what happens today -- indexing just gets "stuck" on the "bad" class.

All of the below was done for #1906 which, in a sense, is a specific manifestation of this issue.

Leave this list and include an `x` in the relevant boxes:

- [ ] I have read http://ensime.org/getting_help/
- [ ] I have followed the troubleshooting guide for my text editor
- [ ] I have asked in http://gitter.im/ensime/ensime-server
- [ ] I have included a link to an example project
- [ ] I have included exact bug reproduction instructions

**Comment by steven-collins-omega** [comment]
I'm working on a PR for this.

**Comment by fommil** [comment]
FYI this was by design, to encourage people to fix problems instead of dust them under the cover. The preferred approach would be to exclude the file locally until a fix can be found. There have been many flamewars, especially in other parts of the code like indexing sources, and I am 100% sure the code is better for it. I'm no longer maintainer, so I won't won't push for that approach here. But this leads to a messy hallway...

**Comment by steven-collins-omega** [comment]
> The preferred approach would be to exclude the file locally

@fommil Could you please expand on what you mean by this? (I'm obviously a n00b when it comes to ensime internals.) Is there some build setting that lets one exclude certain jars from indexing? Or do you just mean doing a local build of ensime where the jar is blacklisted in code? Or something else? Thanks.

**Comment by fommil** [comment]
Say you catch exceptions, and have no ops when encountering classfiles we didn't expect to see... How long do you think it will take to figure out why "jump to source" doesn't work sometimes? Or maybe it'll manifest as "find all references" missing a few references. Tech debt is all about deferring today's problems to tomorrow...

**Comment by fommil** [comment]
Oh you mean just the excluding? Have a read of the sbt-ensime docs. You can filter it whatever way you want.

**Comment by steven-collins-omega** [comment]
Overall, on reflection, I think I'm inclined to agree with you. Closing this issue and associated PR.
