### ISSUE TITLE
use gitlab ci for gnu/linux tests

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1922]
we no longer have the debugger, which dramatically reduces our CI requirements.

We can probably go back to using Travis for GNU/Linux as well as OSX tests now, without relying drone.

**Comment by fommil** [comment]
@nafg showed me that it is now possible to use gitlab ci for GitHub projects, this is a much better alternative! We can also have people contribute hardware easily.

**Comment by nafg** [comment]
Yeah, being able to stick runners anywhere and use them in various
combinations is a great ability of gitlab.

**Comment by fommil** [comment]
an example gitlab ci config file, for inspiration https://gitlab.com/fommil/scalaz-deriving/blob/master/.gitlab-ci.yml

@gabro ! ping

**Comment by gabro** [comment]
I'm a bit behind this, and I've definitely overpromised on the times, but I'll carve some time off my next weekend to look into this

**Comment by fommil** [comment]
I've created a connection, so it should pick up any files that are added. https://gitlab.com/ensime/ensime-server/
