### ISSUE TITLE
ensime.org should quickly point to the installation page

### ISSUE THREAD

**Issue by frgomes** [ensime/ensime-server#1944]
I've installed ensime-emacs several times, I even have an installation script which automagically installs ensime-sbt onto my box... still... I always get lost when I visit ensime.org.

It should be pretty clear and evident how ensime should be installed.
Instead, it's burried inside http://ensime.github.io/build_tools/sbt/

I underestand that several people make some mistakes and this is probably the reason for a number of warnings and several double-checkings on this and double-checkings on that. However, it's really frustrating to take 2 minutes to find where the installation instructions are. After you know that... well... this is pretty obvious where they are. No surprises here: everything is trivial and obvious after you know it. The really problem is how long it may take to find something when you don't know where it is.

**Comment by jozi-k** [comment]
I would argue that homepage should not say anything about sbt. If yes, then I would ask why maven/gradle/etc. instructions are not there. And what about editors? Should they not be on the homepage also?
So flow like `homepage -> getting started -> build tool / editor` sounds reasonably for me.

**Comment by frgomes** [comment]
@jozi-k :: When I click on "Getting Started" (not specifically on ensime.org, but everywhere!) I expect to find a big "Installation" topic, explaining how I should quickly install something.

I myself adopted such expedient on almost all my projects hosted on Github and other places: there's always something like "For the impatient" which contains a small shell script which automagically does whatever needs to be done.

OK, ok... maybe I'm asking too much... but a big "Installation" should be there under "Getting Started". Instead, there's a lot of text which talks about several useful things (I admit), leading to several other places... but a quick, obvious and evident "Installation" is not there.

A small shell script is not only documentation, but also runnable documentation. It just works. Just run it and magic happens. Simple, quick, obvious and evident.

Notice that there's no "Installation" either on the left side menu.
So, what happens in practice is that a visitor spends a lot of time trying to understand what it's all about.

For the benefit of visitors landing here, this is a snippet of one of my automagic scripts which installs ``ensime-sbt`` plugin:

```bash
function install_scala_sbt_ensime {
  # support for SBT 0.13 is now dropped; only version 1.0 now.
  local version=1.0

  mkdir -p ~/.sbt/${version}/plugins

cat << EOD > ~/.sbt/${version}/plugins/ensime.sbt
addSbtPlugin("org.ensime" % "sbt-ensime" % "2.5.1")
EOD

cat << EOD >> ~/.sbt/${version}/global.sbt
import org.ensime.EnsimeKeys._
ensimeIgnoreMissingDirectories := true
EOD
}
```

**Comment by fommil** [comment]
![2018-04-26-102707_1918x1078_scrot](https://user-images.githubusercontent.com/1914041/39297825-6ece0670-493c-11e8-821c-16b5a3705a80.png)

Also, no.

**Comment by fommil** [comment]
btw, we do not care about "quick installation" shortcuts. That leads to gaining lazy users who do not read the docs and contact me at all times of the day and night. We are volunteers who do not have time for that sort of user. Somebody needs to pay me a full salary to deal with that level of shit.

**Comment by frgomes** [comment]
Well, I do. I care about quick installation. Thanks a lot anyway.
