### ISSUE TITLE
Connection refused and setf method unknown error

### ISSUE THREAD

**Issue by Vadi** [ensime/ensime-server#227]
I am using Lion and Emacs 23. I installed ensime as mentioned but when i do M-x ensime-connect I get this error. The bin/server has executable permission. I cloned the ensime code instead of release download.

open-network-stream: make client process failed: Connection refused, :name, ENSIME Scala, :buffer, nil, :host, 127.0.0.1, :service, 9999

Also when I open the emacs, i get an error "setf method unknown" in line 27 of ensime-builder.el, however if i do force-recompile this error goes away and i can do M-x ensime

Any help ?

**Comment by mmlac** [comment]
**TL;DR** as this is Google's top result:
 delete the `port` and `http` file in the .ensime_cache folder of your project after you made sure that there is indeed no ensime running via `ps aux | grep ensime` (mac/linux)

**Comment by fommil** [comment]
Actually no, just follow the troubleshooting guide in this case :wink:
