### ISSUE TITLE
no need to store the local server process

### ISSUE THREAD

**Issue by reactormonk** [ensime/ensime-server#286]
Running the ensime server either locally or [remotely](http://stackoverflow.com/questions/13435687/connect-emacs-to-a-remote-ensime-server).

EDIT: (by @fommil) the underlying problem here is that when we spawn a new server process in emacs, we are retaining a reference to the process itself, and not just the buffer that the process is running in. This should not be necessary as we don't really use the process for anything... but it means that our emacs code is tied to only starting and connecting to servers. We cannot simply connect to an existing server.

**The acceptance criteria for this ticket is to refactor the elisp so that we no longer store a reference to the server process and that we no longer require a reference to a buffer containing the server. And then (simple once the other bit is done) to allow the user to specify defaults (and project overrides) for the host/port to connect to.**

**Comment by fommil** [comment]
@JulesGosnell the bounty has not been claimed, if you don't claim it then bounty source keeps it.
