### ISSUE TITLE
ENSIME cannot be used when lisp code is byte compiled [$40]

### ISSUE THREAD

**Issue by unix-junkie** [ensime/ensime-server#310]
I'm trying to compile a simplistic hello-world Scala project with Ensime,
and receive the following error message
when attempting to connect the Ensime server:

    Debugger entered: (("Error in timer" ensime-attempt-connection ((:project-name "test-scala" :project-package "com.example" :use-maven t :root-dir "/Users/ashcheglov/docs/programming/scala/test-scala/") #<process *inferior-ensime-server*> nil 2) (invalid-function ensime-with-connection-buffer)))
    byte-code("\303\304\305	\nF\"\207" [fun args data debug nil "Error in timer"] 6)
    ensime-timer-call(ensime-attempt-connection (:project-name "test-scala" :project-package "com.example" :use-maven t :root-dir "/Users/ashcheglov/docs/programming/scala/test-scala/") #<process *inferior-ensime-server*> nil 2)
    apply(ensime-timer-call (ensime-attempt-connection (:project-name "test-scala" :project-package "com.example" :use-maven t :root-dir "/Users/ashcheglov/docs/programming/scala/test-scala/") #<process *inferior-ensime-server*> nil 2))
    byte-code("r\301\302H\303H\"\210)\301\207" [timer apply 5 6] 4)
    timer-event-handler([t 20837 31909 591770 0.3 ensime-timer-call (ensime-attempt-connection (:project-name "test-scala" :project-package "com.example" :use-maven t :root-dir "/Users/ashcheglov/docs/programming/scala/test-scala/") #<process *inferior-ensime-server*> nil 2) nil 0])

The server starts just fine -- I see the java process in the process list and can connect to it using **JConsole**. Despite that, the mode string in Emacs shows: ``Ensime: wtf``

This happens only when using the byte-compiled version of Ensime. Once I remove all \*.elc files, the problem goes away.

I'm using Emacs 24.3.1 on Mac OS X 10.6.8:
``GNU Emacs 24.3.1 (x86_64-apple-darwin10.8.0, NS apple-appkit-1038.36)``

**Comment by fommil** [comment]
@JulesGosnell fancy taking a look and fixing our lisp macros?

**Comment by fommil** [comment]
@JulesGosnell Ping!

**Comment by fommil** [comment]
@edani  the bounty has not been claimed, if you don't claim it then bounty source keeps it.
