### ISSUE TITLE
ENJINE: java mode

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#345]
aka ENhanced Java INteraction mode for Emacs ;-P

Many of the features of ENSIME could be made available for Java source code editing. Specifically:

* jump to source of symbol at point
* method completion
* package navigation
* classname completion

On the emacs side, this would involve creating an `ensime-java-mode` (or `enjine-mode`) that enables the functions that are to be used, which sends requests to the server. Many of the `ensime-mode` features can be re-used, such as popup/autocomplete boxes and the SWANK protocol (which might not need to be changed).

On the server side would be significant changes, as we would need to use the java compiler in order to produce a [javac.tree](http://docs.oracle.com/javase/6/docs/jdk/api/javac/tree/) that would be used for queries related to `.java` files, instead of the presentation compiler (for `.scala` files).

This might not be as hard as it sounds, since the java compiler doesn't need to perform type inference it can treat each file in isolation and just parse it from fresh every time.

This would pave the way forwards for integration with static analysis tools that could offer hints or automated refactorings, and spring support.

**Comment by aemoncannon** [comment]
I just started working with a VeryLargeJavaCodeBase, so I might make some movements in this direction. My tentative plan is to make minimal adjustments to Ensime to support (probably in this order):
1 navigation
2 inspection
3 completion
As you say, 1,2,3 all require a typed java tree, so the big question is where to get that. I previously integrated with eclipse jdt for java error highlighting, but that has since been ripped out during various refactorings. Might try that direction again.
Other goals:
* don't muddy up the scala story too much
* support VeryLarge projects. will probably borrow from our scala approach here (don't eagerly load sources)

**Comment by rorygraves** [comment]
@fommil Wanted to work on this at some point incase he was made to go back to a VLJCB. 

I definitely think ti would be good to support scala/java mixed projects (and by extension java projects).
The protocol could be made either more agnostic or into language agnostic and language specific subsections quite easily.

I suspect @fommil  has a lot to say on this one - I know he has some ideas about the AST.  

Getting the basics up and working shouldn't be too silly and we support a lot of the infrastrure you will need.

**Comment by aemoncannon** [comment]
@rory Yep. Most of the UI in emacs will work fine. The debugger should
require zero work. I'm guessing the indexer will be easy as well.

**Comment by rorygraves** [comment]
btw, I know there has been some radio silence from me recently - I've actually been improving the tests of the debugger (found a couple of bugs/problems which I'm working on).  PR soon.

**Comment by aemoncannon** [comment]
@rory Cool yeah, I can barely get 5 mins a day lately. That's great about debugger coverage.

**Comment by fommil** [comment]
Awesome! I *strongly* recommend looking at NetBeans as the inspiration as they use the official java compile tree. I have contributed to NetBeans in the past and their hints framework (ie prompts to fix/tidy code) should be reasonably easy to port /include. 

The NetBeans completion code is tied up in their framework but is easy to understand and covers a lot of corner cases. 

I'd be happy to study my old NetBeans commits and point you at the key classes. The Java tree is fiddly but very easy: unlike the scala one! :-)

**Comment by fommil** [comment]
Indexer should already work out of the box now. We should really be looking at the depickler to populate scala specific info.

In the long term, having Spring support would also be essential (eg jump to definition/implementation taking xml wiring into account and working in the xml).

**Comment by fommil** [comment]
Btw for your sanity, check out Project Lombok and beware that I am probably the only Scala dev on the planet who loves Spring :-D

**Comment by aemoncannon** [comment]
: )

**Comment by aemoncannon** [comment]
@fommil Pointers on starting out with Netbeans would be great. Do they publish artifacts?

**Comment by aemoncannon** [comment]
@fommil Lombok looks sweet. If only such things were remotely permissible in my situation.

**Comment by fommil** [comment]
They were using mercurial when I was contributing: https://netbeans.org/community/sources/hg.html

Try grabbing the source and grepping for "halliday" in the commit author log and that'll bring up all the classes I knew well. Their completer was fully sync (which was a bit of a mess) but all the hints framework was beautifully async.

**Comment by aemoncannon** [comment]
It looks like timing is good for a good emacs java solution:
http://www.reddit.com/r/emacs/comments/2o4x49/emacs_for_java/

**Comment by rorygraves** [comment]
Sounds like it's your time to shine :)

**Comment by fommil** [comment]
I investigated a lot of these alternatives about 6 months ago and they were basically all dead projects

**Comment by adelarsq** [comment]
This project may be usefull https://github.com/artur-shaik/vim-javacomplete2

**Comment by fommil** [comment]
Interesting, but I think we'll use the java compile tree API. Same as netbeans. Thanks!

**Comment by aemoncannon** [comment]
Just an fyi i think i'll take a crack at this soon. My plan is to use the java compiler api to get type checking, then use the AST to power completion. Lookup the qualified type, query our indexer, return the results.

**Comment by fommil** [comment]
Awesome! It's on my roadmap too but goodness knows when I can get the it. Don't forget to look at netbeans for inspiration.

**Comment by fommil** [comment]
btw @aemoncannon my plan is

1. scala 2.10 support into the mainline, drop 2.9. I'm starting a new contract in 4 weeks and they use 2.10, I don't expect to ever use 2.9 again (woot!). This shouldn't be too hard but is sort of blocked on drone.io 0.4 being released for matrix builds. The emacs client tests might be tricky too, but maybe we just say that they only matter for 2.11.
2. loose ends in sexpress and implement SWANKY. My Scala Exchange talk (if it is accepted) is on this, so I really need to get it done. I'd really like to then start going through the client calls to the server and move them over to WebSockets one by one, I think it should reduce our line count. I'm assuming the emacs websocket support is stable, of course. If I get this done before you start working on the java stuff, it would be great if we just go straight to SWANKY for the Java calls.
3. close as many bugs in the 1.0 milestone as possible
4. ENJIME

so, let's see how long it takes for me to catch up, and what can distract me in the meantime :smile:

btw, did you see that I moved all the bounties into one big pile on bountysource? You have permissions to distribute the cash as you see fit, I was thinking we give $50 or so to new contributors to say thanks on their first PR.

**Comment by fommil** [comment]
actually, somewhat related... I was wondering if we should perhaps have two ensime minor modes in emacs:

* `ensime-project-mode` - for stuff like starting a REPL, search, opening the doc server
* `ensime-scala-mode` - for everything that requires the user to be in a scala file

and I guess, next, `ensime-java-mode`. What do you think?

The alternative is one big `ensime-mode` with lots of `(if (is-scala-file) foo bar)`.

**Comment by aemoncannon** [comment]
@fommil
Your roadmap looks good. I'm still a little apprehensive about performance
regressions with swank-over-websockets, but would love to see all our
network code go away...

I do think having a separate ensime-java-mode is a good idea. Having
separate keymap, documentation, etc would (I'm guessing) help to attract
java devs who don't want to think about scala.
That said, I may be lazy about it in the short term...

p.s. Long term I want to attract Android devs. I think there's huge
potential there if we incorporate tooling for viewing apks, decompiling dex
files, debugging, etc etc.

**Comment by aemoncannon** [comment]
@fommil

Your roadmap looks good.

I do think having a separate ensime-java-mode is a good idea. Having
separate keymap, documentation, etc would (I'm guessing) help to attract
java devs who don't want to think about scala.

That said, I may be lazy about it in the short term...

**Comment by fommil** [comment]
Tooling for Android would be really good. In Java land, Spring support is also a natural next stage.

**Comment by aemoncannon** [comment]
FYI little progress on this. Will have PR soon

**Comment by fommil** [comment]
Any progress at all is fantastic. I'm almost done with the Scala 2.10 stuff.

**Comment by fommil** [comment]
looks like dev has picked up on https://github.com/jdee-emacs/jdee so I wonder how much we can share. I think they use the Eclipse compile tree, which I'm very keen to avoid.

**Comment by aemoncannon** [comment]
cool cool

**Comment by aemoncannon** [comment]
Quick update: porting a few things over to the netbeans wrappers. That PR
still on the way...

**Comment by fommil** [comment]
:-)

**Comment by dakrone** [comment]
@aemoncannon looking forward to this! @fommil I'm confused about the bounty for this, it looks like there was a $250 bounty but it has already been paid out?

**Comment by fommil** [comment]
@dakrone yeah we removed the bounties and put them into a slush fund because it was the same people creating the bounties who were closing the tickets.

**Comment by aemoncannon** [comment]
Quick update: Typechecking and type-at-point working pretty well. Working
on rough support for doc-at-point then PR.

@fommil For completion, we're going to need a search query like "select all
public methods for this fqn (including inherited)"  -- do we have that?

**Comment by fommil** [comment]
We can relating create one, the inherited bit will require some SQL wizardry but the data should all be there.

**Comment by dakrone** [comment]
@aemoncannon anything I can do to help with testing this?

**Comment by fommil** [comment]
@dakrone yes! Aemon has a PR open which should work for you. Follow the instructions on the wiki for running from source builds and let us know how you get on with some projects, ideally on github. We might need to look at upgrading the maven plugin to make sure it all works well. Mixed Scala/Java projects with SBT will be easier to test. (Akka comes to mind)

**Comment by aemoncannon** [comment]
@dakrone
You'll want to grab my PRs for ensime-server and for ensime-emacs

**Comment by fommil** [comment]
I think we can close this one! :smile: it's not finished, but the game is afoot. Aemon, if you want any of the bounty TAKE ALL MY MONEY!

**Comment by aemoncannon** [comment]
I used Android Studio(idea) all day at a hackathon. I think the biggest
differentiator is automatic import handling. Need to think hard how to
streamline this in emacs. Maybe part of general suggestion framework. Could
feed compile errors into the 'suggester'  and then event the diffs to
client..

**Comment by fommil** [comment]
sounds good! definitely sounds part of the suggester stuff. There is a bunch of stuff in netbeans for this already. Going on memory, search for the code that suggests creating a `serialVersionID` or the code that suggests static imports (I think I might have written them, it's all a haze) and then find everything else that is in that framework.

**Comment by fommil** [comment]
:+1: for diffs to do this... if you wrote the emacs side for letting the user choose to apply the suggested refactoring (or just apply it regardless) it would make #996 a lot easier to implement!

**Comment by phdoerfler** [comment]
Might someone please take a minute to summarize the current state of Java support for ensime? What about mixed java / scala projects? Do I need to have eclim running? Or does ensime rely on jdee? Or is there simply no support for Java yet? Thanks!

**Comment by fommil** [comment]
@phdoerfler its too early. We'll announce when its out of alpha.

**Comment by phdoerfler** [comment]
@fommil  I'll keep my fingers crossed then :)

**Comment by fommil** [comment]
If you are really really keen, just turn on ENSIME mode when in Java mode.

**Comment by aemoncannon** [comment]
I've been yak shaving the last few weeks but hope to continue polishing
enjime soon

**Comment by fommil** [comment]
@aemoncannon **you** have been yak shaving? I'm supposed to be writing a talk, but I've ended up refactoring my `.emacs` file. :grimacing:

**Comment by aemoncannon** [comment]
Btw @phdoerfler and anyone else following along,
I could use some help with my PR for symbol-at-point (vs ensime-server). Specifically figuring out how to make those tests pass with java 6 : )

**Comment by myrjola** [comment]
Hi! Was all current work regarding ENJINE already merged? Is there any documentation related to the Java support? I could give it a shot and help out if I can.

**Comment by fommil** [comment]
@myrjola it's ongoing, you can try it out by just turning on `ensime-mode` when in a java file. Have a look in https://github.com/ensime/ensime-server/blob/master/core/src/main/scala/org/ensime/core/JavaAnalyzer.scala to see what is currently implemented.

**Comment by myrjola** [comment]
Thanks @fommil! I got autocompletion working, so ENJINE is already quite usable. Great work so far!

I noticed some problems. For example `ensime-show-all-errors-and-warnings` works, but `ensime-print-errors-at-point` hangs for me. Probably it is not implemented as there is no references to error or warning in `JavaAnalyzer`. Is it too early to start opening issues and PRs?

**Comment by aemoncannon** [comment]
Not too early. Go for it!

**Comment by fommil** [comment]
@myrjola the absolute best way to open a ticket is to submit a PR with a failing test. We can help with that, start by looking in the core/it folder for similar tests (look for tests with Java in their name). It should be reasonably obvious how to copy/paste the template.

**Comment by fommil** [comment]
BasicWorkflow could probably do with a java file added to it, it's a big generic integration test that everything is all wired up correctly.

**Comment by arichiardi** [comment]
Hello everybody, is there a way to build ensime server without having `sbt` installed? 

I would be keen of having a look at this, and I also wanted to point to some new cool idea or having the server become an `nrepl` and reuse `cider`'s code (not my idea, see [here](https://github.com/jdee-emacs/jdee/issues/51).

In particular there could be a nrepl middleware project called, for instance, `jdk-nrepl` which contains code useful for all of the Clojure/Scala/Java projects, then a specific `cider-nrepl` for cider, `ensime-nrepl`...`jdee-nrepl`...

**Comment by fommil** [comment]
@arichiardi hmm, hello. Why are you asking this on this old - and closed - ticket?

Please start at http://ensime.org and you'll eventually find yourself in the contributors page.

**Comment by arichiardi** [comment]
Oh ok sorry, some googling brought me here :smile:

I wanted to test `enjime` so I installed everything and it does works. But then I was trying to auto-complete interface methods for a Java class and came across this.

I checked [Contributing](http://ensime.github.io/contributing/) but could not find anything on how to contribute this Java feature. What do you suggest me to start with?

**Comment by fommil** [comment]
http://ensime.github.io/contributing/#implementing-a-feature-or-bugfix

**Comment by arichiardi** [comment]
Ok thank you, I will try to check that

**Comment by fommil** [comment]
It's best that we start a fresh discussion https://github.com/ensime/ensime-server/issues/1667
