### ISSUE TITLE
RFE: order ensime-search results by "closest" module/library

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#355]
e.g. hits in current module first, then deps, then non-dep modules, then libraries in the same order.

Also, exact hits of simple names should be preferred over prefixes (there is a trick in Lucene to do this that I once created, I'll have to remember how I did it).

**Comment by fommil** [comment]
this is the search brother of #126

**Comment by ChrisCoffey** [comment]
I'll take a stab at this in the next couple of days

**Comment by fommil** [comment]
https://github.com/ensime/ensime-server/blob/master/core/src/main/scala/org/ensime/indexer/IndexService.scala#L23F

add a boost to classes in your project. Not obvious how that bit of information is passed to the lucene analyser.

**Comment by fommil** [comment]
I think all you need to do is work out an importance score in IndexService.persist and then add a parameter to SimpleLucene.create that encodes it as an index-time boost. I'm a bit embarrassed about lack of unit test coverage of SimpleLucene, because we rely on the integration level testing of IndexService. It's designed to hide the mutable (and incredibly specialist) Java API from Scala. The reason I added the Blocked tag is because I'm refactoring SimpleLucene in the graphpocalypse, but I can resolve any conflicts. Just please try to minimise your changes in this code (i.e. don't refactor anything that isn't necessary)

**Comment by fommil** [comment]
oh I bet IndexService will need to take an `EnsimeConfig` or you'll need to add an extra parameter onto `persist` so that the caller can pass the bit of information.

**Comment by ChrisCoffey** [comment]
Turns out the boosting fix for this ticket actually exacerbates the issue in #1287. I'd like to close my current PR, port the general boosting concept over to a new branch, address the inner-class matching, then come back to this. Any objections to that approach?

**Comment by fommil** [comment]
@ChrisCoffey your PR is good enough to merge as-is, but just make the boost 1.1f :stuck_out_tongue:

**Comment by fommil** [comment]
by as-is, I mean when you implement the `isUser` method
