### ISSUE TITLE
share compiler with SBT

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#384]
This probably depends on a tonne of upstream changes, but it would be awesome if the compiler instance itself from SBT (or whatever) was doing both presentation and `.class` generation.

Currently, presentation and compilation happen in separate processes.

This would also allow presentation compiler "red squigglies" to be compared against what the final compiler **really** thinks. (Although, as a stopgap, perhaps we could speak to the other process in any case...)

**Comment by fommil** [comment]
@jsuereth @eed3si9n may have more to say. We have a small bounty on this if you'd like to send people our way :smile:

**Comment by fommil** [comment]
this doesn't appear possible.

**Comment by jvican** [comment]
@fommil Sorry, could you explain why it's not possible? I am really interested in this feature. My memory footprint doubles just because of this.
  
Anyway, from my understanding of the new Scala compiler `dotty`, I have a hunch that this could be possible. However, there is still a long way to go.

**Comment by fommil** [comment]
SBT doesn't expose the presentation compiler. ENSIME doesn't use the compiler. There is no benefit to be gained here.

**Comment by jvican** [comment]
Oh right, I miss that. So, basically, there is no way to share sbt? I have no idea, but could it be feasible to write a sbt plugin that is receiving commands sent by ensime, run them and return the result? (in case sbt is async, which I think so) Or perhaps that's too much overhead/complex?

**Comment by fommil** [comment]
I'm a bit confused what you're asking for. ENSIME doesn't use sbt, the developer uses sbt themselves (one instance) if that is their build tool. It's not everybody's build tool.

**Comment by jvican** [comment]
Ups, sorry, I took for granted that `ensime` is using `sbt`. I don't know why. Thanks!
