### ISSUE TITLE
refactor swank parser layer

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#390]
(possibly parboiled, possibly with Spray JSON or something in the middle)

minor breaking protocol changes may be tolerable for the sake of consistency (but releases need to be well timed with the backports branches and the emacs client)

**Comment by fommil** [comment]
Just a quick update on this, I think I'm ready to put in the first PR as the tests are green.

1. ~~rewrite SwankProtocolConversions to use S-Express~~
2. rewrite SwankProtocol to use S-Express (kill off old SExp/WireFormat code)
3. change the protocol to use the "natural" S-Express transformations (lots of emacs work)
4. use Shapeless-powered 

once that's all done, the entire Swank protocol layer will probably collapse to a couple of lines AND the wire format should be easily swappable with another implementation: e.g. JSON or XML.

**Comment by fommil** [comment]
@rorygraves had a good idea: release 1.0 sooner without any protocol changes at this point. I'm in favour of that, as it means we can change the protocol on the unstable branch, impacting less people, and not have to worry about backporting to scala 2.9.

**Comment by rorygraves** [comment]
More that if as part of 1.0 we were going to make a number of tweaks ot the protocol it might be worth release 0.9.1 stable (now) - 0.9.2 stable (+protocol tweaks) ... (1.0.0 stable) once we were 1.0 feature complete..

**Comment by fommil** [comment]
back on this after a hiatus into the land of DevOps...

**Comment by fommil** [comment]
I'm working on converting all the incoming messages to use S-Express

**Comment by fommil** [comment]
I'm also trying to generalise the marshalling so that we can plug in a JSON marshaller

**Comment by fommil** [comment]
WIP available at https://github.com/fommil/ensime-server/tree/sexp_input I feel like I'm making progress here. Swappable protocols is very nearly in sight!

**Comment by fommil** [comment]
@rorygraves one thing that really comes to mind here is that we seem to have two APIs: one is async and message based (what `SwankProtocol` is becoming) and the other is synchronous (`EnsimeApi`).

I'd really like us to just have **one** API --- the `Protocol` one --- but that will mean that programmatic callers will either have to be actor based or use the ask pattern when calling into ENSIME. I don't think it's really our place to add a trivial ask pattern layer in the off-change that someone wants to use the API that way, do you have a strong opinion one way or the other?

**Comment by rorygraves** [comment]
I agree - its the api should be inverted - pure async messages as the primary API.  But I believe it is critical to create a wrapper that is the equivalent of the ```EnsimeApi```.  It would become a wrapper (effectively another protocol on top of the core system).

**Comment by fommil** [comment]
damn, I didn't get this finished. I'll be out of action until Monday on this now... swank tests are passing but in reconciling the domain model I've managed to break the main source code. Also, two things:

1. need to get an `Undo`  from the id (left as `FIXME`)
2. `TypeCompletionsReq` isn't actually a public endpoint, it probably should be (and I think I confused it with public symbol search internally in a few places, which needs to be backed out)

**Comment by fommil** [comment]
this is done, forgot to close
