### ISSUE TITLE
find usages (reverse lookups)

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#425]
there is no real reason why we can't use lucene to do the "who references me" style questions... no need to re-type check anything. Every time a file is edited, we rebuild the index for that file.

**Comment by fommil** [comment]
this might be dropped from 1.0 unless it turns out to be easy to implement

**Comment by tpolecat** [comment]
(Adding myself to this since issue since I'm looking into the db stuff.)

**Comment by fommil** [comment]
w00t! I should imagine it will dramatically increase the DB size so any thoughts on optimising the storage would be well received (although I suspect having a good filter on which symbols we care about... i.e. not `java.lang.*` or any anonymous classes) would be good enough.

FYI when we call this method https://github.com/ensime/ensime-server/blob/master/core/src/main/scala/org/ensime/indexer/ClassfileIndexer.scala#L17 we get handed the FQNs of everything in that file.

**Comment by cvogt** [comment]
+1 :)

**Comment by fommil** [comment]
@cvogt you should know that @tpolecat is putting together a patch to move us to Doobie and he has threatened to look into this :smile: It's also on my personal hitlist soonish.

**Comment by cvogt** [comment]
@fommil @tpolecat no problem. I like what @tpolecat is doing. I am trying to excite people about type-safe composable queries :), but I also like doobie's free monad. Seems a bite more elaborate than slick's.

**Comment by tpolecat** [comment]
I should have more time to work on this next month.

**Comment by fommil** [comment]
I don't really like the scalaz functional style because I find it confuses more than helps, plus is a massive source of object creation / GC overhead. However, in this instance, the benefit is moving away from Slick (which I've now labeled as dirty until FreeSlick is ready) and getting back to raw SQL queries, which were causing compiler warnings in Slick. Hopefully @tpolecat can show us why free monads are useful, but I suspect we'll want all that to be contained to the DAO as implementation details.

**Comment by fommil** [comment]
although it is pretty awesome that we now have two of the Scala community's top DB contributors able to help on this :grinning: so whatever happens I'm sure we'll have a rock solid implementation.

Is there any chance of an NIO implementation of the JDBC driver for H2?

**Comment by t3chnoboy** [comment]
Was it implemented in https://github.com/ensime/ensime-server/pull/1602 ?

**Comment by fommil** [comment]
@t3chnoboy no, that's something else, but the graph branch now stores the necessary information.

**Comment by olkinn** [comment]
is this still WIP?

**Comment by yyadavalli** [comment]
@olkinn I think so, waiting on #1681

**Comment by fommil** [comment]
Heh, yeah it's taking us forever to get the graph branch merged... we've had bad CI reliability problems hopefully now fixed. We'll probably do Scala 2.12 first since it's easier

**Comment by sugakandrey** [comment]
It's coming... eventually :)

**Comment by olkinn** [comment]
@fommil why did this get closed?

**Comment by fommil** [comment]
Very nearly! Hopefully today

**Comment by olkinn** [comment]
oooooh, exciting!!
