### ISSUE TITLE
general improvement in scala coverage

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#447]
code coverage on the scala side really needs to get above 50% for me to feel comfortable accepting PRs

**Comment by fommil** [comment]
this report is particularly interesting from a coverage pov https://coveralls.io/files/430345582

**Comment by rorygraves** [comment]
yep - means there is a bunch of core functionality that the current tests are not covering.
The analyser has the same problem https://coveralls.io/files/430345560 (the calls are probably related.
And the debug manager isn't much bettter https://coveralls.io/files/430345602

**Comment by rorygraves** [comment]
Pretty much sums up why I don't trust our coverage yet - whilst we aer hitting 75% core components are not covered.

**Comment by aemoncannon** [comment]
Yeah that's weird..

**Comment by fommil** [comment]
since we broke the 70% barrier, I'm actually happy calling this a victory :smile: (however, the mission should not stop)
