### ISSUE TITLE
CI and coverage for emacs lisp [$50]

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#448]
Have a `Makefile` that runs our `ensime-emacs` tests on travis and generates a coverage report, ideally uploading a payload to coveralls.io

This necessitates writing tests that can be run in batch mode.

**Comment by edani** [comment]
I'm stuck with the coverage. We can instrument all source files with `edebug` and get stats on how many times each form was called. It works great when it works... but I hit a problem that I think is related to macros defined in ensime-emacs. Their execution fails in edebug but I can't pinpoint why.

**Comment by rorygraves** [comment]
Could the macro issue be related to issue that prevents the compilation on melpa? (https://github.com/ensime/ensime-server/issues/310)

**Comment by fommil** [comment]
was considering moving this to housekeeping, but it's still code because the macro thing needs to be resolved before we can get the coverage reports.

**Comment by fommil** [comment]
:+1: to possible connection with #310 ... sounds too similar

**Comment by edani** [comment]
It's possible, but "edebug" is kind of complicated, it reads a lisp definition and rewrites it laced with debug forms. It can't do that correctly with macros unless it's supplied with extra information. My problem is that I can't locate the exact point where the error happens (that is, what macro caused it)

**Comment by aemoncannon** [comment]
Hey Eric, does the 'testcover' library do the same rewriting?
http://www.gnu.org/software/emacs/manual/html_node/elisp/Test-Coverage.html

It's a shame there isn't built in coverage... the build in profiler is
Sweet.

**Comment by edani** [comment]
I did look at testcover, it uses edebug then rewrites the result one more time! This is what I tried first and I also had problems with it, but I don't remember the details. Maybe I can give it a second look (it might make it easier to locate the "edebug" problem)

**Comment by aemoncannon** [comment]
Bummer. Yeah, Emacs needs native support for this. The native profiler has
been a revelation.

**Comment by fommil** [comment]
http://sachachua.com/blog/2015/02/continuous-integration-code-coverage-emacs-packages-travis-coveralls

**Comment by sachac** [comment]
@edani: If you're referring to the code breakage related to Lisp error: (invalid-read-syntax "Failed matching" (&rest gv-place form)), I think it's because ensime-client.el has

    (setf (ensime-protocol-version process) nil
          (ensime-pid process) nil
          (ensime-server-implementation-name) nil
          (ensime-connection-name) nil
          (ensime-analyzer-ready nil))

The last form there (ensime-analyzer-ready) doesn't have a corresponding value for it, so edebug can't handle it. I tried changing it to (ensime-analyzer-ready nil) nil, but then I had problems with error: "check that sbt is on your PATH and that your config is compatible with http://github.com/ensime/ensime-server/wiki/Example-Configuration-File [(wrong-type-argument stringp nil)]". A temporary workaround that makes coverage reporting work is to skip ensime-startup.el and ensime-client.el, which you can see in the pull-request at https://github.com/ensime/ensime-emacs/pull/96

What's the proper fset for the analyzer status? =)

**Comment by aemoncannon** [comment]
@sachac  Thanks for looking into this! I believe it should read:
    (setf (ensime-protocol-version process) nil
          (ensime-pid process) nil
          (ensime-server-implementation-name process) nil
          (ensime-connection-name process) nil
          (ensime-analyzer-ready process) nil)

**Comment by fommil** [comment]
@sachac please claim your bounty on this

**Comment by edani** [comment]
Very nice!

**Comment by sachac** [comment]
@fommil The people who wrote the tests deserve so much more of the credit. =)

**Comment by fommil** [comment]
Oh that's OK, we're using the bounties to try and attract more contributors :-) if you don't want it, at least recycle it and put it on a ticket you'd like to raise awareness on.
