### ISSUE TITLE
auto-complete.el does not show results for method overloads. [$20]

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-server#460]
A regression. This was originally fixed in our hacked, bundled version of auto-complete.el: https://github.com/aemoncannon/ensime-server/commit/c65e355bfb90b577b992941a337d898133d46fc6

The problem is that auto-complete.el de-duplicates results based on their names (at least it did when I last looked).
https://github.com/auto-complete/auto-complete/blob/master/auto-complete.el#L1067

**Comment by fommil** [comment]
This issue was moved to ensime/ensime-emacs#180
