### ISSUE TITLE
Summarise file (aka Structure View)

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#471]
it would be great to be able to get a view that shows a summary of the current file and give the ability to quickly jump to classes, traits and members.

Effectively an emacs version of IntelliJ's "Structure View".

**Comment by edani** [comment]
@IvanMalison's PR was added to scala-mode2 a while ago. It does a pretty good job considering that it relies on scala-mode2's syntax parser. Here is a way to see how it looks   (make sure you update to the latest scala-mode2)

```elisp
(require 'scala-mode2)
(add-hook 'scala-mode-hook #'imenu-add-menubar-index)
(require 'speedbar)
(speedbar-add-supported-extension ".scala")
(setq scala-imenu:should-flatten-index nil)
(setq imenu-auto-rescan t)
(speedbar)
(menu-bar-mode 1)
```

It shows the scala file's structure in the "Index" menu a well as the speedbar. Speedbar has a few problems:

- it doesn't auto-refresh
- when refreshed manually, the structure is collapsed again.
- at the moment, trying to expand all descendants causes an infinite loop.

But these problems aren't exactly Ensime's

**Comment by IvanMalison** [comment]
I meant to try to get around to implementing this in ensime, but it never really happened. How difficult would it be to get source code location information from the compiler frontend.  If it's something that could be done relatively quickly, I'd be happy to take a stab at it. I did write a tiny bit of code to grab type information from ensime, but it probably isn't worth including in ensime:
https://github.com/IvanMalison/.emacs.d/blob/3fd9acd615b819fa8f7f34f0d768ba7898458fb6/lisp/ensime-imenu.el

> at the moment, trying to expand all descendants causes an infinite loop.

what do you mean by this?

I actually use the stuff in scala-mode2 with helm-imenu rather than speedbar.

**Comment by rorygraves** [comment]
@IvanMalison The source locations should not be hard to get from Ensime - I think the info might already be available via ``` inspect-type-by-name``` ,  ``` inspect-type-by-id ``` and ``` inspect-type-at-point ``` Ensime calls.

**Comment by edani** [comment]
I don't think it's hard,  SemanticHighlighting.scala already does something similar, maybe you could 
make small changes to it. You'd get the whole structure in one call.

Right now it takes the scala parse tree and returns information about specific leaf nodes but classes/methods/etc .definitions are in the same structure.

I guess the node types we care about for this are `ClassDef`, `ValDef` and `DefDef` but the whole list can be found in Trees.scala: http://www.scala-lang.org/api/2.10.4/index.html#scala.reflect.api.Trees

Semantic highlighting is performed very often (the call is swank:symbol-designations) so you could update imenu whenever that happens.

Right now swank:symbol-designations returns triples (type, start-pos, end-pos).  The protocol could be extended to include the class (or method, val, etc.) name.

As far as my infinite loop comment, it's an issue with speedbar and unrelated to your work. Place the cursor on a speedbar line and press `[` to reproduce.

**Comment by rorygraves** [comment]
Lol @IvanMalison - can you tell people are really keen on this feature? :smiley:

**Comment by IvanMalison** [comment]
@rorygraves I'm pretty keen on it too.

**Comment by fommil** [comment]
client side in emacs this would be best implemented as an `imenu` generator, but this ticket is for the server component.

**Comment by ancane** [comment]
:+1:

**Comment by ancane** [comment]
I'm working on this in my branch https://github.com/ancane/ensime-server

**Comment by rorygraves** [comment]
Very cool - looking forward to this one!

**Comment by fommil** [comment]
:+1: yup!

**Comment by fommil** [comment]
@ancane how are you getting on with this? Need any help?

BTW, have you released your popup-imenu browser yet?

**Comment by ancane** [comment]
@fommil Thanks, doing good. Close to finish with the traverser for structure view.
And I made the PR for popup-imenu https://github.com/milkypostman/melpa/pull/3405.

**Comment by fommil** [comment]
@ancane there was a long-standing bounty on this ticket. If you don't claim it, then the money sits in a bank account for eternity and nobody gets it. Please claim it at https://www.bountysource.com/issues/2916173-summarise-file-aka-structure-view

**Comment by fommil** [comment]
@ancane are you signed up for gitter.im ?

**Comment by ancane** [comment]
@fommil Thanks, I'm glad bounty waited for me ;)
Which room should I look for at gitter?

**Comment by fommil** [comment]
https://gitter.im/ensime/ensime-server
