### ISSUE TITLE
M-. sometimes can't identify the symbol

### ISSUE THREAD

**Issue by edani** [ensime/ensime-server#492]
This looks like a race condition. I see this problem intermittently, but here is how I can reproduce it on my machine. This assumes that the scala-compiler sources are available.

- Open RichPresentationCompiler.scala then start ENSIME
- Place the cursor on CompilerControl, line 17 then type M-. This should open CompilerControl.scala
- In CompilerControl, place the cursor on Global (line 46) and press M-. This opens Global.scala
- In Global.scala, M-. is very erratic, and fails most of the time (but not always). It seems that the first or second uses of M-. succeed, but after that they all fail. The server log says:

```
[info] [warning] symbolAt for class scala.reflect.internal.Trees$EmptyTree$: <empty>
```

That message is emitted at RichPresentationCompiler.scala line 378.

The problem isn't limited to Global.scala. In other cases, pressing M-. fails , then trying again succeeds.

**Comment by edani** [comment]
I don't know if this is fixed for good, but #1058 probably made this better.

**Comment by michalrus** [comment]
When trying to jump to the definition of `org.scalatest.prop.GeneratorDrivenPropertyChecks`, I’m getting “Sorry, no definition found.”. I’ll try to prepare a test for this, as suggested by @fommil in the gitter channel.

Sidenote: IntelliJ can’t find the source either. :smiley_cat:

**Comment by fommil** [comment]
I just got a missed hit on `Future.sequence` in `SearchService` in our `SearchService`. Hmm.

**Comment by VlachJosef** [comment]
I'm getting the same missed hit on `Future.sequence` but when I jump to `Future` definition and then try again, then it is working.

**Comment by fommil** [comment]
@VlachJosef that's usually a sign that the indexer is broken. Actually, I bet I know what that is and I think the Graphpocalypse might fix it (FQNs of methods must include their parameters and return type)

**Comment by soc** [comment]
I'm seeing this failure when trying to do a jump-to with a type, no method, parameter or return type involved: https://gist.github.com/soc/75c83e73019f7b012ab1

**Comment by fommil** [comment]
@soc have you got some code that exhibits the problem? Finding reproducible test cases is the first step in this annoying bug.

**Comment by greenrd** [comment]
I suggest we create separate issues for different variants of this problem.

**Comment by fommil** [comment]
we need a reproduction before we can do anything...

**Comment by soc** [comment]
I'm experiencing it in the autowire branch here: https://github.com/lihaoyi/workbench-example-app/tree/autowire

**Comment by fommil** [comment]
@soc ok cool, can you point me at some line of code / member where you experience the problem? Ideally create a fresh ticket as Robin suggests, and include as much info as you can for me to reproduce. Some examples of info here http://ensime.github.io/editors/emacs/troubleshooting/

**Comment by fommil** [comment]
We're going through the older bug reports that don't have a reproduction.

Nowadays, we close tickets that look like a known issue or don't provide the details requested by the template (which didn't exist when you reported this). The reason is to improve the quality of our issue tracker and to make it easier for contributors to help.

Can you please give a full reproduction, ideally in the form of a unit or integration test? A github repository with exact instructions for somebody to follow, like a script, is also good. We are happy to help you write an automated test exhibiting the bug, and discuss ideas on how to fix, read the http://ensime.org/contributing guide for more information.

We will leave this ticket open for a few weeks. If you can confirm it is a bug by giving us a **detailed** reproduction - or let us know that you're working on a fix - we will leave it open for longer.

Please read the http://ensime.org/getting_help guide to understand the steps that are now required prior to submitting a bug report. We recently rewrote almost all the documentation since this bug was initially reported and you might find some useful information in there.

**Comment by fommil** [comment]
I really think my branch will fix this.

**Comment by terrencehan** [comment]
@IvanMalison  Have you find any workaround of your issue? I still need to open relevant source file before finding definition now.

For example, if I wanna find the definition of a variable which is declared in supper class, I have to visit the super class first, then M+. works for me.

**Comment by syama666** [comment]
I encountered this event (failed to look up the definition).
I found such a message in the log.
`[2017-07-18 20:24:13,249] WARN org.ensime.core.RichPresentationCompiler - No definition found. Please report to https://github.com/ensime/ensime-server/issues/492 what you expected for class scala.reflect.internal.Trees$EmptyTree$: EmptyTree`

**Comment by amirkarimi** [comment]
I also get `21:36:43.975 WARN  None o.e.c.RichPresentationCompiler - No definition found. Please report to https://github.com/ensime/ensime-server/issues/492 what you expected for class scala.reflect.internal.Trees$EmptyTree$: EmptyTree` error but I can find the class defnition using `C-c C-v v`.

**Comment by Aaron2Ti** [comment]
Got same error with ensime 2.1

```
13:40:31.148 WARN  None o.e.c.RichPresentationCompiler - No definition found. Please report to https://github.com/ensime/ensime-server/issues/492 what you expected for class scala.reflect.internal.Trees$EmptyTree$: EmptyTree
```

**Comment by madper** [comment]
Howdy @fommil ,
The issue I met is:
1. When the first time I type M-. on a variable ensime can find the definition of it.
2. When I type M-. on `Ve[]ctor("x", "y","z")` the ensime reports `Sorry, ENSIME couldn’t find the definition.` (Lets assume the `[]` is the cursor ;-)
3. After step 2, M-. reports `Sorry, ENSIME couldn’t find the definition.`  when I type M-. again on the variable in step 1.

I'm using ensime2.1. Here is the code which always reproduces the same issue:
``` Scala
package mcats
object Main extends App {
  import cats.data.Writer
  import cats.instances.vector._
  import cats.syntax.applicative._
  import cats.syntax.writer._

  type Logged[A] = Writer[Vector[String], A]
  val writer1 = for {
    a <- 10.pure[Logged]
    _ <- Vector("a", "b", "c").tell     // Line 11
    b <- 32.writer(Vector("x", "y", "z"))
  } yield a + b

  val writer2 = writer1.mapWritten(_.map(_.toUpperCase))   // Line 15
  println(writer2.reset.run)
}
```
The `Vector` in Line 11 and/or `_.map` in line 15 trigger the bug often.
BTW, the scala version is 2.12.4. Cats-core is 1.0.0-RC2.
Please kindly do let me know if you need more information. Thanks a lot in advance.

**Comment by fommil** [comment]
@madper I'm not maintaining ensime anymore

**Comment by Soya-Onishi** [comment]
There are any updates?
I encountered a same problem in very simple project.

1. create sbt directory structure and build.sbt
2. run `ensimeConfig` in sbt console
3. write following two source files
4. restart emacs
5. try to jump to a user definition from identity like `add` (`add` method is defined in `Storage.scala`) in `Main.scala`
6. emacs says `Sorry, ENSIME couldn't find the definition.`

`Main.scala` is 
```
object Main extends App {
  val storage = new Storage("some one")

  storage.add("name")
  storage.show()
}
```

`Storage.scala` is 
```
import scala.collection.mutable.ListBuffer

class Storage(val name: String) {
  var list = new ListBuffer[String]()

  def add(str: String): Unit = {
    list += str
  }

  def show(): Unit = {
    list.toList.foreach {
      x => println(x)
    }
  }
}
```
I realized that if `Storage.scala` has already opened, 'M-.' works correctly(same as @IvanMalison)
In addition, 'M-.' works correctly if searching built in(i.e. not user defined) method like `println`.

I'm novice for ENSIME. please tell me if I have something wrong.
