### ISSUE TITLE
semantic highlight for implicit conversions

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#530]
@edani any ideas on this?

It would be great to see underlined (or similar) blocks of code that have been implicitly converted. e.g. pimp `string` and then see `<u>string</u>.myPimpedMethod`

**Comment by greenrd** [comment]
Has this been implemented? I don't see it in the recent commits.

**Comment by rorygraves** [comment]
@edani Has an open pull request and is making some tweaks before merging.

**Comment by rorygraves** [comment]
@fommil  is being a big eager with the closing of tickets.

**Comment by fommil** [comment]
yup, but you'll need to build from the associated PR which will be merged very soon.

**Comment by fommil** [comment]
You can use my `fommil/implicits` branch which rebases eric's work on top of master.

**Comment by greenrd** [comment]
Is there a way to show *which* conversion has been applied? I've tried `C-c C-v i` which just shows the original type pre-conversion and *all* the possible implicit conversions which could be applied to that type, and `M-.` which (of course) goes to the target type of the conversion, but neither of those necessarily answer the question.

**Comment by fommil** [comment]
`C-c C-v e` should do that

**Comment by greenrd** [comment]
Thanks! It has to be done with point on the method being called, I found.

It should probably be added to the ENSIME->Source menu.

**Comment by fommil** [comment]
what is this "mouse" of which you speak? :-P

**Comment by rorygraves** [comment]
@fommil If you decide to limit yourself to 1950's  you should probably ban yourself from git, the web and colour monitors as well.  + your shiny phone.

**Comment by fommil** [comment]
what's a phone?

**Comment by rorygraves** [comment]
Consider it a magic talky box.
