### ISSUE TITLE
semantic highlighting errors visible after correction

### ISSUE THREAD

**Issue by anildigital** [ensime/ensime-server#535]
I have sample scala program. When I make wrong syntax there. Ensime highlights error. But when I correct code, Ensime doesn't mark it correct and keeps showing red line.

It still keeps showing the line even I do 'Typecheck Project' C-c C-v a

```
[info] 22:28:42.852 [default-akka.actor.default-dispatcher-23] INFO  org.ensime.protocol.SwankProtocol - Writing: (:scala-notes (:is-full nil :notes ((:severity error :msg "')' expected but '}' found." :beg 102 :end 102 :line 7 :col 3 :file "/Users/anil/Code/scala/em_scala/src/main/Main.scala"))))
```

This is seen, even after code is corrected. I am using Mac and Java 7, Scala 2.10.

**Comment by fommil** [comment]
I'm afraid that's not enough information. Can you please give a full reproduction, ideally in the form of a unit or integration test? A github repository with exact instructions for somebody to follow, like a script, is also good. http://ensime.org/getting_help/

We have very good documentation at http://ensime.org/contributing/ to help you get started hacking on ENSIME.
