### ISSUE TITLE
no fork version of the ensime sbt server starter

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#552]
The current server starter uses an sbt start script that then forks the server.
This means creating two `java` instances before the compilers are started, which may be considered expensive on lower-end machines.

It would be good to pass the java options (prefixed with `-J`) to `sbt` (assuming paulp's script is used) or to instantiate sbt to create a start script, which is then called.

**Comment by fommil** [comment]
I was thinking about using https://github.com/sbt/sbt-start-script for this but it copies the dependencies.

A cleaner way to do it might be for the callout to sbt to simply write out the classpath to a file, then read that into emacs and call `exec` directly.

That approach will require attaching a second process to a `comint` after its first process terminates. @aemoncannon @edani is that possible?

**Comment by aemoncannon** [comment]
I have no idea! : ) but I bet its doable.

**Comment by fommil** [comment]
sweet, I'll look into the sbt side and share a branch with you both when my elisp foo runs out.

**Comment by edani** [comment]
I like that idea too. Also the great thing is that the classpath can be cached so e.g. in the emacs test suite there's no need to run stb more than once.

**Comment by fommil** [comment]
@edani @aemoncannon 

This should produce a file `classpath` which contains the OS-dependent string for the classpath part.

https://github.com/fommil/ensime-emacs/tree/one_process

**Comment by fommil** [comment]
sorry, missed a bit... pushing change now

**Comment by fommil** [comment]
actually that's missing the tools.jar, but I think I can fix that.

**Comment by aemoncannon** [comment]
Oh man that would be sweet.

**Comment by fommil** [comment]
@aemoncannon @edani have either of you had any time to look at my branch? I did some research on comint-mode and couldn't find any documentation on how to add a callback to the process for when it dies. Also, I noticed that we return the process from the function that starts the server, and that might be used elsewhere. However, there is no reason to do this because comint allows looking up the process associated to a buffer separately, so we could return the buffer instead.

**Comment by fommil** [comment]
If I could work out how to attach a callback to a process when it finishes, I could polish this off.

**Comment by aemoncannon** [comment]
@fommil look for set-process-sentinel

**Comment by fommil** [comment]
awesome! I can finish this off now. If anybody fancies taking it, please ping me. I'm moving house soon anyway, so likely AWOL for a few weeks.

**Comment by fommil** [comment]
@aemoncannon uuugh, this is going into territory in elisp that I'm not familiar with. The process is handed around to lots of places and I'd like it to be the buffer that is handed around instead. Is there any chance you could have a look at refactoring that code to be independent of a process, please? Then I can add the sbt magic.

**Comment by fommil** [comment]
a potential workaround to avoid a large refactor would be to launch a piece of elisp as a process (I'm not sure if this is even possible?) It would spawn the sbt job, then gather the parameters to exec into java. The real problem here is that sbt can't exec. I'm not fussed if this means spawning a second emacs process, just so long as it can properly exec into the java process entirely.

**Comment by aemoncannon** [comment]
I see. Because you want to swap the process. Doable. Maybe next day or two.

**Comment by fommil** [comment]
That'd be awesome thanks. I'll do a little bit of research on spawing off elisp as a separate process. That might serve as a good workaround. I'll ping you if I make any progress.

**Comment by aemoncannon** [comment]
Not sure about execing from elisp but godspeed ;)

**Comment by fommil** [comment]
Yeah, I did the research, and I learnt a lot of mad things about spawning other emacs servers and talking to them, but ultimately it is not possible to `exec` out of emacs.

I think it boils down to one of three options: a) refactor loads of code to pass buffer references instead of one process b) write different scripts for UNIX/Windows that run the logic under one process c) find out some magical way of starting up a "do nothing" process and then replace it when we have the work to do. I'm not even sure if c) is possible... it sounds insane.

This might help: http://stackoverflow.com/questions/3068929

**Comment by fommil** [comment]
there is a variant of `3`: return a mock process and then populate it later. e.g. via https://github.com/nicferrier/emacs-fakir

Then the job becomes making sure that the mock perfectly proxies the underlying ensime-server process (e.g. signals and sentinels)

**Comment by aemoncannon** [comment]
I think I prefer A, because it's cross platform and doesn't require magic.

Is there perhaps a D, where we introduce a new buffer/proc pair for the SBT
run, wait til its done, kill it, then start buffer/proc for server?

I don't think A,D are toooo heinous on the elisp side -- I wouldn't mind
working on it.

**Comment by edani** [comment]
I've been busy theses past few days but I'm back now... Aemon, if you want I can work on this after I'm done with #155.

**Comment by fommil** [comment]
@edani great!

@aemoncannon if you think you can do that without blocking the user on sbt, then it is definitely an option. I don't think we need to keep the process if we have the buffer though.

I'm wondering why we need to keep a reference to the process/buffer at all, because connecting remotely doesn't need this. Maybe option E can be just removing the need to store anything.

**Comment by aemoncannon** [comment]
Storing the server proc was a recent change I made, so we can say 'starting
up' in the period before we've connected -- it gives us a place to hang a
config object. I suppose you could just iterate buffers to find the server
buf, and store config as a buffer local var instead. So long as we don't
lose the messaging. (Looking at my PR might be helpful)

@edani Have at it!

**Comment by edani** [comment]
I'll be travelling in the next few days but I should have this finished by the end of next week.

**Comment by fommil** [comment]
:-)

**Comment by aemoncannon** [comment]
Awesome!
