### ISSUE TITLE
stacktrace filters

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#566]
it would be great to be able to collapse stackframes in the `stacktrace-mode` that are effectively scala noise (e.g. scala stdlib/scalatest/akka stuff)

**Comment by kleewho** [comment]
@fommil I created PR with changes doing what you requested. I'm open to suggestions how to improve my code

**Comment by fommil** [comment]
Sweet! I'll try to use this over the next few days and give some feedback
