### ISSUE TITLE
lazy vals semantically highlighted as vars

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#595]
I just noticed that references to lazy vals are being given the `scala-font-lock:var-face`. That is wrong, they should be getting the `scala-font-lock:val-face` (or is it just `font-lock-variable-name-face`)

Not sure if this is a bug in the client or the server yet: a test case in the server shouldn't be too hard to set up.

**Comment by noelmarkham** [comment]
Thanks to @fommil in helping get me started with `ensime-server` development today.

A few things about this bug:
* It's actually only `lazy val` _fields_ that are suffering from this issue:  <img width="264" alt="screen shot 2015-11-14 at 20 48 08" src="https://cloud.githubusercontent.com/assets/1492487/11165757/0c55733e-8b11-11e5-9990-becff4206e37.png">
* There's some odd behaviour in the presentation compiler which says that lazy val fields are actually variables. I can provide evidence if you want - just let me know how/where.

I have a fix for this, I'm just preparing the PR.

**Comment by rorygraves** [comment]
I would be interested in the evidence (mostly out of idle curiosity I accept).  Looking forward to the PR.
