### ISSUE TITLE
Travis build failures - possible approaches

### ISSUE THREAD

**Issue by rorygraves** [ensime/ensime-server#597]
I suspect we are seeing this - 
http://docs.travis-ci.com/user/common-build-problems/#My-build-script-is-killed-without-any-error

The search test (and the intg tests) will all trigger using higher threads (as intg tests effectively do the search test), and trigger the kill.

I can only see two ways of handling this:

1) Adding special flags to limit threads (akka dispatcher config?)

2) Setting up a build on a home/ VPN server to do the pr builds/ coveralls etc. (not sure if its possible to get github to report from them).   

I suspect this is going to get worse with things like the emacs based integration tests.

What do people think?

**Comment by fommil** [comment]
I'll take this and give travis one last go with its new docker support.

**Comment by fommil** [comment]
I'm looking at this now.

**Comment by aemoncannon** [comment]
Nice!
