### ISSUE TITLE
creating a repl should not depend on the scala binary [$100]

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#642]
there is no need to require the scala binary: we know the full classpath to use and the repl command line script only calls out to `scala.tools.nsc.MainGenericRunner` (I noticed that there is an `$EMACS_OPT` which we should probably investigate in the stock script).

**Comment by fommil** [comment]
Also, no need to ask the server about what the classpath is... it's all in the `.ensime` file.

**Comment by fommil** [comment]
I think my protocol non-change actually broke launching the REPL. Implementing this will fix that.

**Comment by aemoncannon** [comment]
Good candidate for rpc call to rip out before 'stable'

**Comment by fommil** [comment]
@dangerousben don't forget to claim your bounty (or it just sits in the aether with no owner)

**Comment by tonylotts** [comment]
:+1:
