### ISSUE TITLE
Debugging issues with server/emacs, follow on from #586

### ISSUE THREAD

**Issue by rorygraves** [ensime/ensime-server#662]
Following on from #586 there are a number of errors when doing debugging:

@wohanley  Reports
'But now I'm seeing the message "Wrong type argument: stringp, nil" in Emacs on invoking ensime-db-set-
break, and then "error in process filter: Wrong type argument: stringp, nil" when I run the debugger, after which the program being debugged hangs (but Emacs doesn't, and ensime-db-quit allows it to continue). I'm not sure whether that's a separate issue '

Needs investigation - its possible to turn the the stack traces of the errors in emacs to get more information about where in the emacs side it is blowing up.

**Comment by wohanley** [comment]
FYI, I'm not seeing this anymore with 20150315.737.
