### ISSUE TITLE
Javadoc/scaladoc support in ensime server ; browse local doc jars [$250]

### ISSUE THREAD

**Issue by edani** [ensime/ensime-server#675]
(updated from #487, with more details)
Javadoc/scaladoc browsing should be managed by the server. A new swank call should return the URL of a symbol's doc. In most cases the mapping of package names to external URLs can be done by the server, using a built-in map or one provided in .ensime.  The server should have the URLs of the Scala and Java standard libraries built-in (for all supported versions of Scala and Java)

In addition, the ensime server should read a list of locally-installed doc jars in the .ensime config , and serve them using a local HTTP server.

**Comment by aemoncannon** [comment]
A couple questions:
1) How do we handle docs for sources in progress? Like what if I've yet to generate docs for my current project, or the docs are just stale due to local changes? CompilerControl#askDocComment might help here.

2) How much do we want to be able to suck docs into Emacs? I think this would be quite cool, especially in situations like completion where looking aside to html docs would be annoying, but I don't know how hard it is to slice out the docs for a particular method/class/trait from a doc jar.

**Comment by fommil** [comment]
1. we don't do anything right now (they aren't even in `EnsimeConfig`), but `ensime-sbt` does download/resolve the jar file of the javadocs/scaladocs so getting hold of the files is trivial.
2. I would love to see two types of documentation. a) ensime-server actually serves the javadocs/scaladocs for all middleware as if it was a webhost statically serving those files. ensime-emacs simply points the browser at a localhost URL. b) when autocompleting a method, the selected method has its documentation shown inline.

If we need to parse javadocs we might be able to reuse some of my paranamer regexes/code https://github.com/paul-hammant/paranamer/blob/master/paranamer/src/java/com/thoughtworks/paranamer/JavadocParanamer.java

**Comment by aemoncannon** [comment]
FYI doing some work on this here: https://github.com/aemoncannon/ensime-server/blob/fiddling-with-doc-server/src/main/scala/org/ensime/core/DocServer.scala

Lots to be done, but mostly handles making urls for thing-at-point, extracting the jars (lazily), falling back to oracle, etc.

**Comment by aemoncannon** [comment]
TODO:
  * Inspect actual jar contents to determine scaladoc vs javadoc. Not enough to look at where the symbol was defined.
  * Add the ensime doc jar to the :doc-jars list in ensime-sbt.
  * Resolve ambiguity if/when two jars supply docs for the package -- need to check for the actual desired file.
  * Method types
  * Package types

**Comment by fommil** [comment]
is this done now? Wow, our first big bounty item possibly closed :smile:

**Comment by aemoncannon** [comment]
Yeah this is done, modulo a few bugs.

**Comment by fommil** [comment]
then please claim :smile:

The bounties have been a bit of a flop to be honest, but at least they make the project very approachable. Might have been better to put it on low hanging fruit instead of the bigger ticket items.
