### ISSUE TITLE
loose ends in S-Express

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#692]
* SexpData unapply should allow dupes, on a first key wins basis
* SexpList apply should have a tail recursive instead of recurse that could blow up the stack
* ensure that Either/Option have alternative handlers (be strict by default, but allow the lazier "common sense" form)

**Comment by fommil** [comment]
* move back into `org.ensime.sexp` (in prep for separation)
* option not to write out case class fields that are `nil` (@aemoncanon requested)

**Comment by fommil** [comment]
* upgrading scalacheck reveals lots of bugs

**Comment by fommil** [comment]
example of a transient failure https://travis-ci.org/ensime/ensime-server/builds/52514899

**Comment by aemoncannon** [comment]
Still seeing the recursion fails occasionally in sexplist apply

**Comment by fommil** [comment]
I might use shapless in sexpress in the same way its used in the JSON stuff... all the hard work has been done, this should be a much simpler task.

**Comment by fommil** [comment]
re the tail recursion failure. Yeah, I see this in really big files now. That's probably because we're trying to respond with a really big list of semantic information. Bugger.

**Comment by fommil** [comment]
another transient http://fommil.com/github.com/ensime/ensime-server/shapeless_upgrade/e31a41db3e97b28d2183c5b2b322b3138ff50c1e
