### ISSUE TITLE
ensime sbt failing in scala 2.11 and sbt 0.13.6

### ISSUE THREAD

**Issue by msackman** [ensime/ensime-server#698]
Apologies if this is something stupid on my part (it probably is). Despite a lot of googling around I can't make this work.
1. large existing scala/akka project
2. cat ~/.sbt/0.13/plugins.sbt 
   
   ```
   resolvers += Resolver.sonatypeRepo("snapshots")
   
   addSbtPlugin("org.ensime" % "ensime-sbt" % "0.1.5-SNAPSHOT")
   ```
3.  cat project/build.properties
   
   ```
   sbt.version=0.13.6
   ```
4. `sbt gen-ensime`
   
   ```
   [info] Resolving org.ensime#ensime-sbt;0.1.5-SNAPSHOT ...
   [warn]  module not found: org.ensime#ensime-sbt;0.1.5-SNAPSHOT
   [warn] ==== local: tried
   [warn]   /home/matthew/.ivy2/local/org.ensime/ensime-sbt/scala_2.11/sbt_0.13/0.1.5-SNAPSHOT/ivys/ivy.xml
   [warn] ==== public: tried
   [warn]   https://repo1.maven.org/maven2/org/ensime/ensime-sbt_2.11_0.13/0.1.5-SNAPSHOT/ensime-sbt-0.1.5-SNAPSHOT.pom
   ...
   [warn] ==== sonatype-snapshots: tried
   [warn]   https://oss.sonatype.org/content/repositories/snapshots/org/ensime/ensime-sbt_2.11_0.13/0.1.5-SNAPSHOT/ensime-sbt-0.1.5-SNAPSHOT.pom
   ```

and sure enough, that doesn't resolve. I tried asking in #scala but no responses.

**Comment by msackman** [comment]
Hello!

 

New message, please read <http://homemadefacialmasks.info/event.php?l2>

 

matthew@wellquite.org

**Comment by fommil** [comment]
@msackman your email account has been compromised, and whoever did it is sending spam to github tickets.

**Comment by msackman** [comment]
On Tue, Apr 19, 2016 at 08:18:45AM -0700, Sam Halliday wrote:
> @msackman your email account has been compromised, and whoever did it is sending spam to github tickets.

Hi Sam, thanks for the notification.

I believe my email was hacked sometime back in January. Whilst it is
secure again now, there is not much I can do to stop spammers who have
clearly harvested every valid email address out of my email folders.
Whilst I do have SPF DNS records published, it would appears github does
not pay attention to them. I'm sorry for spam polluting your project.

Matthew

**Comment by fommil** [comment]
no problem, glad you've got it cleared up.

**Comment by msackman** [comment]
Hello!

 

You have a new message, please read <http://dragonballdownload.info/confrontation.php?k3t>

 

matthew@wellquite.org

**Comment by msackman** [comment]
Hello!

 

You have a new message, please read <http://dierenplek.nl/accomplishment.php?i8831>

 

matthew@wellquite.org

**Comment by msackman** [comment]
Hey,
Did you hear the latest news? You should definetely read more info here <http://gejoratri.cuchia.com/lnmrq>

matthew@wellquite.org

**Comment by fommil** [comment]
locking to stop the spam
