### ISSUE TITLE
Can't use std emacs auto-complete with ensime

### ISSUE THREAD

**Issue by 4lex1v** [ensime/ensime-server#700]
For some reason when i turn on ensime mode for scala, auto-complete mode stops working, i.e i've defined custom dictionary, but it doesn't complete if something matches from the dictionary, even if i have something in the buffer... If i turn ensime off, reload emacs auto-complete works. I guess it happens because of some ensile-auto-complete settings, is there any way to combine ensime-ac with std behavior? Btw, i don't have any specific settings:

```elisp
(add-to-list 'ac-dictionary-directories (concat configs-dir "dict"))
(ac-config-default)
```

That's all

**Comment by fommil** [comment]
This issue was moved to ensime/ensime-emacs#176
