### ISSUE TITLE
Can't see "breakpoint set" and "current line" indications during debugging in text mode (emacs -nw)

### ISSUE THREAD

**Issue by ttsiodras** [ensime/ensime-server#702]
If I try debugging in a text-mode Emacs (emacs -nw), then I can't see the "current line" and "breakpoint set here" indications... in fact there is no visual indications whatsover after `C-c C-d b` or `C-c C-d n`.

Is there any workaround? I am used to working under `screen` sessions, reattach to them remotely, etc.

**Comment by Hiroyuki-Nagata** [comment]
I'm also inconvenienced from this issue.

**Comment by fommil** [comment]
This issue was moved to ensime/ensime-emacs#175
