### ISSUE TITLE
semantic highlighting incompatible with whitespace-mode [$50]

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#703]
```
(setq 
  whitespace-style '(lines-tail)
  whitespace-line-column 80)
```

will highlight characters over 80 characters (even non-whitespace), but ensime semantic highlighting will then apply additional faces. I don't know how faces work, but the "whitespace" face should win here.

**Comment by ahanwadi** [comment]
Seeing the same issue.

**Comment by fommil** [comment]
yeah, this one sucks. I think to properly fix it we'd have to use font-locks instead of overlays.

**Comment by fommil** [comment]
This issue was moved to ensime/ensime-emacs#174
