### ISSUE TITLE
feature: implement/override method

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#706]
when in a class/trait allow users to ask to implement/override a method, then provide a list of methods from parents, and insert the boilerplate.

**Comment by tbje** [comment]
For reference: https://github.com/scala-ide/scala-ide/pull/672

**Comment by fommil** [comment]
Sweet! We can also look at Netbeans for the Java side of things, since we're planning on using the javac API also

**Comment by aemoncannon** [comment]
Should this be handled via completion? Start typing "override..." and it
lists the method signature as candidate?

**Comment by fommil** [comment]
Possibly part of the passive fixes framework?

**Comment by fommil** [comment]
@aemoncannon actually, on typing partial `override` would work really well for this too.

**Comment by fommil** [comment]
needs passive fixes
