### ISSUE TITLE
Wrong resolution of objects with the same name within multi-projects

### ISSUE THREAD

**Issue by theefer** [ensime/ensime-server#716]
When several multi-projects of a project directory have classes or objects with the same name (e.g. `lib.Config`), ensime doesn't seem to correctly resolve the link to the instance within the same project (as the compiler does via sbt); often it resolves to an instance in another project.

**Comment by theefer** [comment]
I believe this is still an issue, as classes seem to be resolved globally in a multi-project, rather than in the local sub-project, which is an issue if sub-projects declare the same class (e.g. `lib.Config`).

How much work would it be to address this issue? Has there been any progress toward a fix?

As this is the main blocker for me to use ensime for various projects, I'd really love to see it resolved, and possibly try and give a hand if it's not too hardcore... Any guidance welcome!

**Comment by fommil** [comment]
can you give an example of what you want to achieve? there are two things that can be done, independently, each solving different problems.

**Comment by theefer** [comment]
Sure. For example I'm working on the [grid](https://github.com/guardian/grid) project which uses a [multi-project sbt structure](https://github.com/guardian/grid/blob/master/project/Build.scala). Each of these sub-projects has its own different `lib.Config` class (e.g. [kahuna's](https://github.com/guardian/grid/blob/master/kahuna/app/lib/Config.scala) and [media-api's](https://github.com/guardian/grid/blob/master/media-api/app/lib/Config.scala)).

Now when I open [kahuna's Config.scala](https://github.com/guardian/grid/blob/master/kahuna/app/lib/Config.scala) in Emacs with ensime, I get the following error after `object Config`: `constructor Config is defined twice   conflicting symbols both originated in file ’/home/seb/work/grid/image-loader/app/lib/Config.scala’`. It seems that ensime isn't able to tell them apart, even though they live in different sub-projects, which then seems to prevent ensime to correctly pick up the correct `lib.Config` object local to each sub-project in other files.

The same applies to say the `controllers.Application` objects in the various subprojects.

Let me know if that makes sense or if you need more details, or some reduced case.

Thanks!

**Comment by aemoncannon** [comment]
We used to support this by launching multiple ensime instances. You'd pick the desired subproject on launch, and that, coupled with the config, was enough to build the proper deps list (all subproject dependency info was (still is?) encoded in the monolithic .ensime.

This got thrown out at some point. Options as far as I can tell:
* old-school: multiple ensime launches. needs server support. monolithic .ensime
* old-school++: multiple ensime launches. plugin support to generate separate .ensimes for subs
* hydra-mode: one ensime launch, multiple pres-compilers

I kinda like old-school++, as it requires fewer shenanigans in the server.

**Comment by theefer** [comment]
One use case I forgot to mention, in case it's relevant, is that all the sub-projects are independent, but [they all depend on the `common-lib` sub-project](https://github.com/guardian/grid/blob/master/project/Build.scala#L107), so they need to be able to [resolve its definitions](https://github.com/guardian/grid/blob/master/media-api/app/controllers/MediaApi.scala#L30-L36) too.

**Comment by fommil** [comment]
I think we can support this new in the server quite easily. More thoughts in #1152 hoof to help you implement this before one of us gets around to it!

**Comment by fommil** [comment]
Autocorrect hates me.

**Comment by fommil** [comment]
Also, to support the kind of workflow aemon is talking about on the client side, follow https://github.com/ensime/ensime-sbt/issues/116

That is something that may be relevant for me so I may be looking into it in a few months

**Comment by fommil** [comment]
Hydra mode is probably better long term, especially if the indexer is updated the understand module dependencies. Old school++ may be needed to tame large projects.

**Comment by fommil** [comment]
I've implemented subproject restrictions when generating `.ensime` files in https://github.com/ensime/ensime-sbt/issues/116

It should make it into ensime-sbt 0.3.0, which I plan to release today/tomorrow.

**Comment by theefer** [comment]
Amazing, thanks, looking forward to giving it a go!

Sorry if this is a silly question, but what do you mean by subproject restrictions, and how is it going to help with the subproject object resolution issue? I assume it's the Old school++ route? Will the idea be to run `gen-ensime NAME` for each sub-project?

Happy New Year!

**Comment by fommil** [comment]
old school++, although I would tend to only do one at a time... it's more for managing an extremely large mono repo.
