### ISSUE TITLE
When completing higher-order functions, offer a choice of expansion styles.

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-server#723]
Currently, for company-mode completion, we have a post-completion hook that yas-expands a (dynamically constructed)template for the parameter list. This works well, but is a little awkward for methods like map, where while sometimes you want to do foos.map(bar), many times you'd prefer foos.map { c => println('yo!'); bar(c) }

One option would be to include 'map' twice in the candidate list, one for each style, but this would add a lot of noise.

Another idea is to offer the choice to the user after they've selected 'map'. I've played with using company to select between two snippets, but for some reason I can't make company start completing from inside a post-completion handler.

@dgutov @capitaomorte Any advice? Perhaps there is already a good way of doing this in either company-mode or yasnippet?

**Comment by aemoncannon** [comment]
@fommil How's this working for you?

**Comment by fommil** [comment]
This is really funky! I had a double take the first time it asked and now I am used to it and have only myself to blame if I pick the wrong braces :-)
