### ISSUE TITLE
Add other refactoring supported by scala-refactoring

### ISSUE THREAD

**Issue by rorygraves** [ensime/ensime-server#725]
The scala-refactoring library supports more refactorings than we currently support:
http://scala-ide.org/docs/current-user-doc/features/typingviewing/refactoring/index.html
Although many of the missing features may require significant emacs side support as they are often very interactive (e.g. merging parameter lists etc)..

**Comment by fommil** [comment]
we decided at scalasphere that only a few refactorings are really supported, so we should be reducing rather than adding.
