### ISSUE TITLE
completion debugging stacktraces when no ensime server connected

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#730]
the new completer doesn't like it at all when there is no ensime server connected. Sometimes (e.g. during rebases or when working in badly broken codebases) I like to work without the ensime server and it makes it pretty difficult to do so. Can we have a graceful no-op when there is no server connected?

**Comment by fommil** [comment]
I did notice a weirdness about this. 

Start with a new file and try typing the first "package"  definition line. I get stack traces. 

I turned off debug-on-error so I don't see it anymore but it would be nice to handle it.

**Comment by fommil** [comment]
Actually that's a totally different issue, but it has the same effect.

**Comment by aemoncannon** [comment]
https://github.com/ensime/ensime-emacs/pull/77
