### ISSUE TITLE
Ensime-20141225.1206 ensime no longer functions void function -find

### ISSUE THREAD

**Issue by metatron-the-chronicler** [ensime/ensime-server#733]
I managed to fix this by upgrading my installation of dash.  Is there a way that ensime can be made to pull  in updated packages from melpa?

**Comment by zph** [comment]
On my setup, it seems that the ensime version requirement for Dash wasn't being loaded. So emacs was using an outdated `dash`. The version in `ensime-pkg.el` seems correct.

Manually upgrading dash via `package-list-packages` resolved the issue.
