### ISSUE TITLE
Automatically mark unused imports

### ISSUE THREAD

**Issue by eallik** [ensime/ensime-server#748]
Most IDEs of any language I've seen automatically mark unused imports with e.g. a yellow underline; is there a way to get Ensime to do that? If not, could it be implemented? `ensime-refactor-organize-imports` is way too agressive for this and besides does more than just remove unused imports (e.g. it regroups and flattens the imports, which I'd like to manage manually).

**Comment by rorygraves** [comment]
+1

**Comment by aemoncannon** [comment]
It looks like the OrganizeImports refactoring supports removing unneeded
without re-organizing.

    /**
     * Recomputes the imports and removes all existing
     * imports not in the computed set. This mode preserves
     * the user's formatting of imports, and is used for
     * refactorings that modify imports but don't want
     * to fully reorganize them.
     */
    val RecomputeAndModify = Value


So if you wanted to do underlining, you could run OrganizeImports  with
above option (not currently supported in ensime) and then highlight the
lines removed in the client.

**Comment by fommil** [comment]
this now works in 2.11.
