### ISSUE TITLE
Weird issue when writing test for public symbol search 

### ISSUE THREAD

**Issue by rorygraves** [ensime/ensime-server#749]
Was trying to add a test for the public symbol search If I add these two extra test calls I get inconsistent results.
If I run it as part of a full test run it failes with empty results, if I run the BasicWorkflow test as a single test the below code passes.
also the results for java.io.File look odd to me - @fommil / anybody got any idea whats going on?

```scala
       //-----------------------------------------------------------------------------------------------
        // public symbol search - java.io.File

        val javaSearchSymbol = project.rpcPublicSymbolSearch(List("java", "io", "File"), 2)
        javaSearchSymbol match {
          case SymbolSearchResults(List(
            TypeSearchResult("java.awt.image.ImageObserver", "ImageObserver", 'class,
              Some(_)),
            TypeSearchResult("java.io.File", "File", 'class,
              Some(_)),
            TypeSearchResult("org.ensime.util.FileUtilSpec", "FileUtilSpec", 'class, None))) =>

          case _ =>
            fail("Public symbol search does not match expectations, got: " + javaSearchSymbol)
        }

        //-----------------------------------------------------------------------------------------------
        // public symbol search - scala.util.Random
        val scalaSearchSymbol = project.rpcPublicSymbolSearch(List("scala", "util", "Random"), 2)
        scalaSearchSymbol match {
          case SymbolSearchResults(List(
            TypeSearchResult("scala.util.Random", "Random", 'class, None),
            TypeSearchResult("scala.util.Random$", "Random$", 'class, None))) =>
          case _ =>
            fail("Public symbol search does not match expectations, got: " + scalaSearchSymbol)
        }
```

**Comment by fommil** [comment]
are you waiting for the index to be finished?

**Comment by edani** [comment]
One thing I noticed with the emacs integration test, is that the indexer isn't really ready when the `:indexer-ready` message is sent, I've been meaning to look into it. In the meantime I've been adding a 5-second delay.

**Comment by rorygraves** [comment]
Lol - that hint spurred a thought and a code dive and I think I may have spotted the problem:


```scala
    indexed onComplete { _ =>
      // delayed commits speedup initial indexing time
      log.debug("committing index to disk...")
      index.commit()
      log.debug("...done committing index")
    }
```

The index commit is async to the indexed count - which is what we are waiting on.
Just testing a PR, but hopefully this means we can remove random waits :)

**Comment by rorygraves** [comment]
I'm guessing the bad reads occur before the commit completes and see the empty index

**Comment by fommil** [comment]
oh yeah, we should make the added/removed `Future` really only finish when this has finished. I knew there was something dodgy going on in here...

**Comment by rorygraves** [comment]
Cool - I believe I have a fix and its playing nicely with my test - PR shortly.

**Comment by fommil** [comment]
I've been meaning to refactor the `SearchService` for a while, I was never 100% happy with it during the rewrite of the DB layer.
