### ISSUE TITLE
Synthesized field setters do not appear in completion results.

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-server#750]
// e.g.
object Hello {
 var color:String = "red"
 def main() {
   this.co<TAB>
   // should list color_= as a completion option
 }
}
// Note that explicitly defined setters *do* appear in completion results.

**Comment by ale64bit** [comment]
These symbols require some analysis of the existing completions? Because I don't get them with `askTypeCompletion` or `askScopeCompletion` whatsoever. Any hints?

**Comment by rumoku** [comment]
Intellij IDEA does not list *color*_  ,  but instead *color* only.

**Comment by fommil** [comment]
not sure we want to encourage mutable style of coding :stuck_out_tongue:
