### ISSUE TITLE
Should be able to invoke parameter list expansion at will (even if there's only one completion candidate).

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-server#753]
company-mode will not initialize completion if there's only a single candidate, and therefore will not run the post-completion action, which in our case is necessary to expand the parameter list.

@dgutov Do you have a suggested workaround?

**Comment by dgutov** [comment]
Is this the same as https://github.com/company-mode/company-mode/issues/205?

IOW, the problem isn't "only one completion candidate", but that the method name is already complete. I don't have a good workaround, though, aside from wrapping the command, like it was suggested in that issue.

**Comment by aemoncannon** [comment]
Yep, it is the same. And I think the solution in that thread is good enough
for us.

Thank you for your time.
