### ISSUE TITLE
company-mode menu sometimes jumps around the screen

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-server#754]
This doesn't always happen, but when it does it's fairly annoying.
Any ideas @dgutov ?   We're using an async candidate function.
https://drive.google.com/file/d/0B-vtUjWF36KRcEtxUUFERzFxMTg/view?usp=sharing

**Comment by dgutov** [comment]
This is bad. Do you have a step-by-step reproduction scenario?

I would very much like to look at it.

**Comment by aemoncannon** [comment]
I will see if I can whittle it down to something reasonable.

**Comment by aemoncannon** [comment]
No small repro case yet (unless you feel like installing ensime), but I
think I see what's going on. We request max-results at a time from our
server. Currently max-results is set low, 30, and it's quite possible that
the first 30 will not contain the eventual match.

As the prefix lengthens, so long as the last batch had max-results
candidates, we request a fresh batch. Each time a new batch is received,
I'm guessing company recomputes the menu size and position. Moreover, it
appears that company is trying to avoid the previous menu when placing the
next menu. That's why you see the crazy jumping behavior.

So I think there's a couple issues here:

  1) Given that we're using :async, max-results of 30 might be too
conservative. The purpose of max-results is to prevent the lookup from
timing out, but I wonder if that's still a valid concern.

  2) Company might want to ignore the previous menu when computing the next
position. I have no idea how much of a PITA that would be ; )

**Comment by dgutov** [comment]
Erm, are you calling the async callback several times? I didn't expect anyone to do that. :)

I guess I should add a check. But meanwhile, change the code to buffer the results and only pass them to the `candidates` callback when the list is complete. Or just fetch them all together.

> Company might want to ignore the previous menu when computing the next position. I have no idea how much of a PITA that would be ; )

If we allowed the callback to be called several times, this would probably be a non-issue, but other things become harder (both to design and implement). For instance, what would we do if an asynchronous backend returns `nil` to `sorted` and then invokes the callback multiple times? Re-sort the items in the popup every time?

> The purpose of max-results is to prevent the lookup from timing out, but I wonder if that's still a valid concern.

If that problem has no better solution, I could add some sort of "keep-alive" calling convention to the callback. But please test and see if it's really necessary. A higher timeout value could also work well enough.

**Comment by aemoncannon** [comment]
> I didn't expect anyone to do that.
Well, for the record it worked pretty well : )

> But please test and see if it's really necessary.
Initial tests are looking good for removing the limit altogether. Fingers
crossed.

Thanks again.
