### ISSUE TITLE
Add support for wartremover

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-server#755]
Seems like there'd be value in having wartremover warnings show up in Emacs.

**Comment by aemoncannon** [comment]
We'd want to respect wartremover configuration as it appears in sbt.

**Comment by rorygraves** [comment]
I love the idea of integration of these kind of tools into emacs.  A couple of thoughts:

1) Would we need to mandate the version of wartremover (as it becomes a presentation compiler dependency?
2) You would need some kind of wartremover overview view in emacs (i.e. show all errors and jump to source).

The other option for running such integrations is to have a secondary process (basically running sbt wartremover on a loop) - possibly on a snapshot copy of the code under edit.  And then feeding those results back.  My original thinking on the subject was how to show live test coverage information (effective continuous test and highlighting update).  The downside of this approach is that it will use a lot of cpu.

**Comment by aemoncannon** [comment]
Good points. The version thing is tricky. I *really* don't want to run sbt
in the background - it's just too huge and slow.

**Comment by edani** [comment]
Looking at this: https://github.com/puffnfresh/wartremover/blob/master/sbt-plugin/src/main/scala/wartremover/package.scala , wartremover is a compiler plugin so it should be possible to not make it a dependency of ENSIME, and rather add it to the scala (pres or full?) compiler instance at runtime.

**Comment by aemoncannon** [comment]
Last time I checked pres-compiler didn't play well with compiler plugins.
But that may have changed.

**Comment by fommil** [comment]
I think pres compiler "just works" now for this sort of thing.
