### ISSUE TITLE
Control+D does not work with continuous build and test in ensime-sbt buffer

### ISSUE THREAD

**Issue by peterbecich** [ensime/ensime-server#756]
In the `ensime-sbt` buffer, I can't seem to return to the sbt prompt after entering `~run`.  With just `run`, `Control+d` works fine.

`Control+q Control+c` or `Control+q Control+d` do not work, either: http://stackoverflow.com/a/8948621/1007926

From the `inferior-ensime-server` buffer:

```
[info]   OS : Mac OS X
[info]   Java : Java HotSpot(TM) 64-Bit Server VM 25.5-b02, Java(TM) SE Runtime Environment 1.8.0_05-b13
[info]   Scala : version 2.11.4
[info]   Ensime : 0.9.10-SNAPSHOT
```

**Comment by fommil** [comment]
I don't believe we have an sbt mode anymore, we're outsourcing to sbt-mode and just adding a few hooks around it. If you're used to the old mode, it might be worth reading the updated docs as this was a fairly recent change. 

Reopen if you still believe this is an issue.

**Comment by edani** [comment]
@peterbecich To be more specific, this is probably a question to ask on https://github.com/hvesalai/sbt-mode/issues/  . There seems to be a similar issue open over there.
