### ISSUE TITLE
Running multiple instances of Ensime used to work

### ISSUE THREAD

**Issue by photex** [ensime/ensime-server#759]
Seems, that up until recently (within the last couple of weeks, I've been on vacaction), I was able to run ensime for multiple projects (using emacs). After updating this morning and eventually sitting down to do some work, the first project started up and worked fine, but now the second bails with "an exception in main" which I'm pretty sure is because this second project is trying to use the same port as the first (53315).
Is this an issue with my configuration or has ensime stopped using random port numbers?

**Comment by photex** [comment]
Oh, well, just a moment... it seems that this has more to do with Gradle. I think multiple sbt projects work fine.

**Comment by fommil** [comment]
Best kind of bug report :smile:

**Comment by mrmechko** [comment]
Trying to hack multi-project support for sbt projects in ensime-atom:

Does this mean you need a separate ensime-server instance for each project or can a single ensime-server instance deal with multiple projects on different ports?

**Comment by fommil** [comment]
One server per project. Used to be one server per submodule but we fixed that.
