### ISSUE TITLE
can see ENSIME-server classpath in completion options

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#769]
start a new project with no dependecies, you can still complete (e.g. importing packages) on ENSIME classfiles and dependencies.

**Comment by alpeb** [comment]
For some reason `.ensime_cache/build.sbt` is being created with `-Dscala.usejavacp=true`. Even though in `Analyzer` the presentation compiler settings are set to override this to `false`, some weird logic here ignores that:
https://github.com/scala/scala/blob/2.11.x/src/compiler/scala/tools/util/PathResolver.scala#L239
The result being that the presentation compiler ends up having the ensime jar in its classpath.

Changing that flag in `ensime_cache/build.sbt` avoids this issue.

**Comment by rorygraves** [comment]
@alpeb Good spot.  That is pretty weird logic within PathResolver - I'm guessing ```Defaults.useJavaClassPath``` must pick it up from the ```-D``` variable.  The build.sbt is generated on the emacs side https://github.com/ensime/ensime-emacs/blob/master/ensime-startup.el#L218
@fommil @aemoncannon Am I missing something in thinking this can simply be removed?

**Comment by fommil** [comment]
this isn't as simple as it sounds. The presentation compiler behaves differently on scala 2.9, 2.10 and 2.11 so we'd need some testing around this to confirm the cause/solution.

Incidentally, `.ensime_cache/build.sbt` is no longer used so this may be a relic of the old launcher. The flags are now added by the elisp code.

**Comment by alpeb** [comment]
I tried issuing a PR in in scala for this, but they're arguing the command-line option should take precedence:

https://github.com/scala/scala/pull/4342#issuecomment-74977198
https://issues.scala-lang.org/browse/SI-9159

**Comment by fommil** [comment]
@alpeb if we don't pass the CLI argument and **just** set it in code, do you think that would work for 2.9, 2.10 and 2.11?

**Comment by alpeb** [comment]
I've commented out `-Dscala.usejavacp=true` in `ensime-startup.el` and attempted using Ensime in a minimal project with scala 2.9.3, 2.10.4 and 2.11.5. Ensime symbols are not there and completion seems to be working fine. Not sure if this is enough of a test though.

**Comment by fommil** [comment]
@alpeb did you start up the server every time you changed the version of scala?

If so, then it sounds like this flag was completely superfluous, so please submit a PR to remove it.

**Comment by alpeb** [comment]
Yea, before each test I changed the scala version in my sample project's `build.sbt` and killed the `.ensime` file and `.ensime_cache` dir, and then ran `sbt gen-ensime` before launching Emacs. I'll submit the PR tonight.

**Comment by fommil** [comment]
cool. No need to delete the cache, but it's certainly safe to do so.

You can now create one-liner PRs directly in github, they added the feature a few weeks ago. Just click edit on the file in the ensime repo.

**Comment by adriaanm** [comment]
Glad you were able to workaround the finicky flag. Classpath handling in scalac (especially the usejavacp and usebootcp flags) are in desparate need for a rewrite (probably going to happen when we work on Java 9/jigsaw support), but many tools depend on their existence, so this is going to take some time on our end.
