### ISSUE TITLE
completion blacklist

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#770]
A bunch of the standard completions, e.g. `ensuring`, are just noise to me. I'd like to exclude them from completions with user config.

**Comment by aemoncannon** [comment]
What if we just gave them a very low ranking?

**Comment by fommil** [comment]
I'd prefer to just exclude some stuff

**Comment by fommil** [comment]
this is the completion brother of #354

**Comment by fommil** [comment]
the user config would be best implemented as a user-specific `~/.ensime.conf` file using the typesafe config format. We could actually have the fallback behaviour of Project, User, Default and it would be very useful for putting other stuff as well.
