### ISSUE TITLE
don't auto complete in comments / documentation

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#772]
@aemoncannon I'm not sure how easy/hard this would be to fix. If we're passing the cursor location along with the object to complete, we should be able to ask the presentation compiler if we're in a comment block or not.

**Comment by aemoncannon** [comment]
Hmmm, this depends a lot on what compiler does with the docs. Will look
into it.

@aemoncannon <https://github.com/aemoncannon> I'm not sure how easy/hard
this would be to fix. If we're passing the cursor location along with the
object to complete, we should be able to ask the presentation compiler if
we're in a comment block or not.

—
Reply to this email directly or view it on GitHub
<https://github.com/ensime/ensime-server/issues/772>.

**Comment by fommil** [comment]
we might also be able to leverage the `scala-mode2` comment detection

**Comment by fommil** [comment]
it would be pretty sweet if we could turnon flyspell completion in comments.

**Comment by fommil** [comment]
also, when  completing in strings it would be good if it was restricted to the interpolated scala bits only

**Comment by aemoncannon** [comment]
@fommil Working well for you?

**Comment by fommil** [comment]
Yes it is, thank you!
