### ISSUE TITLE
M-. fails when used on a case class .apply

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#775]
when working on the 1.0, I'm going to try to add examples of failing M-. use within the ensime-server source code here, so that we can interactively debug what is failing and catch the lions share of the failures.

**Comment by aemoncannon** [comment]
Great

**Comment by fommil** [comment]
Got one. Not in our codebase, but should be easily reproducible.

I `M-.`d on a `spray.can.Http$Connect.apply`. The exact source for the target is at https://github.com/spray/spray/blob/v1.3.2/spray-can/src/main/scala/spray/can/Http.scala#L43

maybe there is something special about case classes and companions that we need to support.


```
15:42:23.289 [default-akka.actor.default-dispatcher-3] INFO  o.e.s.protocol.swank.SwankProtocol - Received msg: (:swank-rpc (swank:symbol-at-point "OBFUSCATED" 3431) 12)
15:42:23.362 [Scala Presentation Compiler []] DEBUG o.e.core.RichPresentationCompiler - search: spray.can.Http$Connect.apply = None
15:42:23.374 [default-akka.actor.default-dispatcher-3] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:return (:ok (:name "apply" :local-name "apply" :decl-pos nil :type (:arrow-type t :name "(host: String, port: Int, sslEncryption: Boolean, localAddress: Option[java.net.InetSocketAddress], options: scala.collection.immutable.Traversable[akka.io.Inet.SocketOption], settings: Option[spray.can.client.ClientConnectionSettings])(implicit sslEngineProvider: spray.io.ClientSSLEngineProvider)spray.can.Http.Connect" :type-id 15 :result-type (:arrow-type nil :name "Connect" :type-id 16 :decl-as class :full-name "spray.can.Http$$Connect" :type-args nil :members nil :pos nil :outer-type-id 13) :param-sections ((:params (("host" (:arrow-type nil :name "String" :type-id 1 :decl-as class :full-name "java.lang.String" :type-args nil :members nil :pos nil :outer-type-id nil)) ("port" (:arrow-type nil :name "Int" :type-id 2 :decl-as class :full-name "scala.Int" :type-args nil :members nil :pos nil :outer-type-id nil)) ("sslEncryption" (:arrow-type nil :name "Boolean" :type-id 3 :decl-as class :full-name "scala.Boolean" :type-args nil :members nil :pos nil :outer-type-id nil)) ("localAddress" (:arrow-type nil :name "Option" :type-id 4 :decl-as class :full-name "scala.Option" :type-args ((:arrow-type nil :name "InetSocketAddress" :type-id 5 :decl-as class :full-name "java.net.InetSocketAddress" :type-args nil :members nil :pos nil :outer-type-id nil)) :members nil :pos nil :outer-type-id nil)) ("options" (:arrow-type nil :name "Traversable" :type-id 6 :decl-as trait :full-name "scala.collection.immutable.Traversable" :type-args ((:arrow-type nil :name "SocketOption" :type-id 8 :decl-as trait :full-name "akka.io.Inet$$SocketOption" :type-args nil :members nil :pos nil :outer-type-id 7)) :members nil :pos nil :outer-type-id nil)) ("settings" (:arrow-type nil :name "Option" :type-id 9 :decl-as class :full-name "scala.Option" :type-args ((:arrow-type nil :name "ClientConnectionSettings" :type-id 10 :decl-as class :full-name "spray.can.client.ClientConnectionSettings" :type-args nil :members nil :pos nil :outer-type-id nil)) :members nil :pos nil :outer-type-id nil))) :is-implicit nil) (:params (("sslEngineProvider" (:arrow-type nil :name "ClientSSLEngineProvider" :type-id 11 :decl-as trait :full-name "spray.io.ClientSSLEngineProvider" :type-args nil :members nil :pos nil :outer-type-id nil))) :is-implicit t))) :is-callable t :owner-type-id 17)) 12)
```

**Comment by aemoncannon** [comment]
I hit a very similar thing on the doc branch. The problem is that the
symbol at point is the 'apply' method of a synthetic Object which doesn't
exist in sources. In both cases we need to do a little dance to find the
intended target.

**Comment by fommil** [comment]
interesting. Also note it doesn't work even if the source code is open in another window (I navigated there using the search)

I'm renaming this ticket. If anymore are encountered we can create new tickets.

**Comment by fommil** [comment]
@aemoncannon I've been using my branch for the last few days to check I don't get exceptions on normal ops. I'm not happy with that, so will move over to your branch to enjoy the docs :smile:

**Comment by aemoncannon** [comment]
@fommil Cool. I bet it would work if you explicitly declared an object Bla for the case class with a custom apply method.

**Comment by fommil** [comment]
@aemoncannon actually in this case I'm using a custom apply. Curiouser and curiouser.

**Comment by aemoncannon** [comment]
@fommil :-)   Don't forget to grab that elisp I posted on my PR. I found it
was necessary to explicit escape the urls.

**Comment by aemoncannon** [comment]
@fommil Huh.

**Comment by fommil** [comment]
funnily enough, now that you've added spray-can we **do** see this in the ensime source as well :smile:

**Comment by 4lex1v** [comment]
Good afternoon guys. I also have issues with this problem, so tried to look why it might not work. This might not be related, but i think it's not only about generated `.apply` method, i see this issue in other cases as well, e.g scala [Async/await](https://github.com/scala/async/blob/master/src/main/scala/scala/async/Async.scala) lib:

```
12:50:45.187 [Scala Presentation Compiler []] DEBUG o.e.core.RichPresentationCompiler - search: scala.async.Async.async = None
12:50:45.192 [default-akka.actor.default-dispatcher-12] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:return (:ok (:name "async" :local-name "async" :decl-pos nil :type (:arrow-type t :name "[T](body: T)(implicit execContext: scala.concurrent.ExecutionContext)scala.concurrent.Future[T]" :type-id 37 :result-type (:arrow-type nil :name "Future" :type-id 38 :decl-as trait :full-name "scala.concurrent.Future" :type-args ((:arrow-type nil :name "T" :type-id 35 :decl-as nil :full-name "scala.async.T" :type-args nil :members nil :pos nil :outer-type-id nil)) :members nil :pos nil :outer-type-id nil) :param-secti...
```

**Comment by fommil** [comment]
@4lex1v cool, can you raise a separate ticket for that please? Project, file and position would be good.

**Comment by aemoncannon** [comment]
This is a known issue (I think there's a ticket for it, but w.r.t
completion). Anyway won't hurt to file it.

**Comment by fommil** [comment]
@4lex1v say hi to Ani and Jan :smile:

**Comment by fommil** [comment]
I can't reproduce this one anymore. Seems to be working for me.
