### ISSUE TITLE
Jenkins/Travis ensime-server builders to run the elisp tests

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#777]
as discussed offline, will need changes to the emacs sbt launcher to support a temporary ivy cache, into which we will publish the build.

**Comment by fommil** [comment]
This is the emacs test that rory set up on Jenkins. If we install emacs24 on Travis, we can include this as part of the server tests.

```
export JAVA_HOME=/usr/lib/jvm/java-6-oracle
export PATH=$JAVA_HOME/bin:$PATH
export JDK_HOME=$JAVA_HOME
export ENSIME_RUN_AND_EXIT=1
export EMACS=emacs24

cd test

emacs24 --version
emacs24 -d $DISPLAY --no-init-file --load dotemacs_test.el --eval "(ensime-run-all-tests)"
```

**Comment by fommil** [comment]
But we need a way to set the scala version that is being tested by the emacs test... @edani or @aemoncannon is that parameterisable?

**Comment by fommil** [comment]
emacs24 is not available on Ubuntu LTS 12.04 (precise) without using a custom build http://ubuntuhandbook.org/index.php/2013/09/install-upgrade-to-emacs-24-3-in-ubuntu-13-04-12-10-12-04/

Do we want to only support emacs24, or should the tests run on emacs23 ? http://packages.ubuntu.com/precise/emacs23-nox

**Comment by fommil** [comment]
aemon's travis runs on the old infrastructure give hints about which packages need to be installed. I guess we could just grab the .deb files, extract them into $HOME and set PATH/LD_LIBRARY_PATH and hope... https://travis-ci.org/aemoncannon/ensime-emacs/builds/44688907

**Comment by fommil** [comment]
aah, cool! I just spotted this, so looks like you have indeed thought about the version of scala to test.

```
export ENSIME_TEST_SERVER_VERSION=2.10.4
```

Then all we need to do is set `ENSIME_TEST_SERVER_VERSION=$TRAVIS_SCALA_VERSION`

**Comment by fommil** [comment]
reminder: set the `SBT_OPTS` so that sbt runs in offline mode when starting ensime-server. That way we will be sure to use the version we just built.

**Comment by aemoncannon** [comment]
Recommend testing vs emacs 24.

23 also maybe, if its not a pain.

That env var is not currently threaded through ensime-test.. I don't think.
We'll need to fix that and a couple hard coded instances of "2.11"

**Comment by aemoncannon** [comment]
https://github.com/ensime/ensime-emacs/pull/79

**Comment by fommil** [comment]
@aemoncannon FYI https://github.com/rolandwalker/emacs-travis/issues/4

Also, I've had some twitter interaction with @travis-ci about emacs support on docker. The problem might go away.

**Comment by aemoncannon** [comment]
@fommil Merged changes to read env var.

**Comment by fommil** [comment]
https://github.com/travis-ci/travis-build/pull/372

**Comment by fommil** [comment]
boring, I know, but I'm pouring myself a good whisky and getting this one sorted tonight once and for all. It's **far** too useful.

**Comment by fommil** [comment]
the dreaded

```
Error in init file: File error: "Cannot open load file", "package".
```

I think I know how to fix it.

**Comment by fommil** [comment]
@aemoncannon I'm getting somewhere on my master ensime-server branch. `emacs23` is installed by default (but `package.el` isn't, so I download it) but the output on travis incomprehensible:

https://travis-ci.org/fommil/ensime-server/builds/51148569

It looks like it's starting up a console emacs in the dumb terminal instead of doing it all in the background. Any ideas? Maybe `xvfb` isn't kicking in or something.

**Comment by fommil** [comment]
aah, maybe they haven't installed an X capable `emacs`

**Comment by aemoncannon** [comment]
Possible to manually install an emacs in the mean time, as we do in travis.yml?

**Comment by fommil** [comment]
Yup I'll do that

**Comment by fommil** [comment]
I tried to compile this locally but the sheer number of dependencies for the GTK+ build is rather big and it's not possible to build a fully statically linked emacs. Bugger, I think we're really blocked on https://github.com/travis-ci/travis-ci/issues/3244

**Comment by fommil** [comment]
unblocked! :smile:

**Comment by aemoncannon** [comment]
Hate to be a debbie downer, but what about emacs 24? Technically some
packages we use require it (company-mode)

**Comment by fommil** [comment]
@aemoncannon this actually helps. Now that they install emacs-gtk that means all the dependencies for emacs24 will be available so we can potentially build our own and dist to travis for the build matrix.

**Comment by fommil** [comment]
btw, I'm thinking for post 1.0 we should think about making the minimum requirements be:

* scala 2.10
* java 7 (async file system messaging)
* emacs24

**Comment by aemoncannon** [comment]
+1

**Comment by fommil** [comment]
right. I'm going to destroy this one today.

**Comment by fommil** [comment]
damnit, the ppa .deb uses gtk3 which isn't on `precise` by default. Building my own emacs24 with gtk2 support...

**Comment by aemoncannon** [comment]
God speed!

**Comment by fommil** [comment]
I've got a build of 24.4 (should we be using 24.1 for testing?)

```
./configure --prefix=$HOME/emacs24 --program-suffix=24
```

and going to dist it to dropbox now.

**Comment by aemoncannon** [comment]
Eh, maybe ideally? But this is fine.

**Comment by fommil** [comment]
emacs 24.1 fails immediately...
```
Required package `cl-lib-0.5' is unavailable
```

**Comment by fommil** [comment]
wtf, `Finished suite with status 0.` yet `The command "sbt ++$TRAVIS_SCALA_VERSION publishLocal && cd $HOME/ensime-emacs && test/run_emacs_tests.sh" exited with 1.`
