### ISSUE TITLE
make ENSIME look nice in visualvm

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#778]
Easily done, and makes us look classy: http://stackoverflow.com/questions/1334907/

**Comment by aemoncannon** [comment]
Reminds me that ensime does not have an official icon.

**Comment by fommil** [comment]
what about ![this](https://avatars0.githubusercontent.com/u/5089042?v=3&s=200)

**Comment by aemoncannon** [comment]
Where's that come from??

**Comment by fommil** [comment]
ensime organisation. I thought you made it!

**Comment by aemoncannon** [comment]
Nope. @rajish Maybe you know who made the icon?

**Comment by rorygraves** [comment]
Am I missing something from the link - you can't do it from ensime - you need to add an extension in jvisualvm to update the icon - that doesn't seem worth the effort.

**Comment by rajish** [comment]
@aemoncannon, yep,  that was me. Do you need inkscape file?

**Comment by fommil** [comment]
I think you just drop in a classfile that matches the API. In any case, Scala does it so we can look into how they do it.

@rajish that'd be great, thanks!

**Comment by rorygraves** [comment]
http://stackoverflow.com/questions/4433979/how-do-i-give-a-name-to-a-visualvm-unknown-application might lead to some hints, sbt definately has an iconm as does scala.

**Comment by rorygraves** [comment]
Now this file is just depressing
https://sourcecodebrowser.com/visualvm/1.3/_main_class_application_type_factory_8java_source.html

Look at line 108

**Comment by fommil** [comment]
*sigh*

**Comment by rorygraves** [comment]
So about 10 minutes of code, 3 years of getting the PR accepted for it to in Java 9 which nobody is going to run for after 5 years.

**Comment by fommil** [comment]
I think it's possible client side

**Comment by fommil** [comment]
Heh, the old logo i posted has now been replaced with the new one because of the url.

**Comment by rorygraves** [comment]
Moved ticket out from 1.0 - its a nice to have, but it involved a pull against jvisualvm rather than ensime.

**Comment by fommil** [comment]
did you send one? if we can't do it on our end then just close this.
