### ISSUE TITLE
organise (not optimise) imports

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#779]
related to #748 it would be really nice to have rules that reorganise imports. Ideally we could allow users to define this but as a first stab we could use something non-offensive such as:

1. java imports
2. scala library imports
3. middleware imports
4. project imports

followed by a space and then repeat (in the same order) for imports that provide some implicit (we could play it safe and lump underscore imports here until we can work out which symbols are imported).

I like this approach because it means I can ignore the first block as boilerplate/informational, but look at the second block to understand how implicits might be impacting my file.

**Comment by aemoncannon** [comment]
Yeah I like this. I wonder how we can tell between java and scala imports..

**Comment by fommil** [comment]
Oh I mean J2SE vs Scala Stdlib. It would be great if we could also split up the middleware into java/scala! (We could potentially do this by looking at the source resolver)

**Comment by aemoncannon** [comment]
Ah I see. So the first cut would only require textual sorting.

**Comment by fommil** [comment]
@aarondav do you think you'd be able to help out here? I just noticed that you wrote https://github.com/aarondav/scala-imports-organizer

How tied is your code to the IntelliJ codebase?

**Comment by aemoncannon** [comment]
Not sure if you already considered, but scala-refactoring contains *almost*
supports this already. Take a look at the OrganizeImports refactoring.
Mirko Stocker writes pretty code : )

**Comment by fommil** [comment]
is that the stuff when we type `C-c C-r o`? It is nice, but it doesn't allow customisation AFAIK

**Comment by aarondav** [comment]
Unfortunately, the majority of the complexity of scala-imports-organizer is dealing with and manipulating the IntelliJ AST. There are still a few interesting pieces about the ordering in [bucketImports()](https://github.com/aarondav/scala-imports-organizer/blob/master/src/com/scalaImportsOrganizer/ScalaImportsOrganizerAction.scala#L202), [makeImportStatement()](https://github.com/aarondav/scala-imports-organizer/blob/master/src/com/scalaImportsOrganizer/ScalaImportsOrganizerAction.scala#L262), and [Import#compareTo()](https://github.com/aarondav/scala-imports-organizer/blob/master/src/com/scalaImportsOrganizer/ScalaImportsOrganizerAction.scala#L338) which deal with some of the edge cases of Scala imports. Perhaps the comments on those methods are even more useful to ensure one is aware of the edge cases.

**Comment by fommil** [comment]
Thanks for your thoughts on the matter:-)
