### ISSUE TITLE
optimise imports drops inner classes

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#780]
possibly an upstream bug with scala-refactoring, if one has imports like

```
...
import foo.Bar.Bloo
...
```

then a `C-c C-r o` will drop the `Bloo`

**Comment by alpeb** [comment]
I was gonna tackle this one but I can no longer reproduce it. Can you?

**Comment by fommil** [comment]
@aemoncannon put a $50 bounty on this and I think @mlangc solved it upstream :smile: go here to claim it or the money just sits in a bank account somewhere https://www.bountysource.com/issues/7616033-optimise-imports-drops-inner-classes

**Comment by mlangc** [comment]
Well, I don't remember solving a bug like this in particular, but I did a lot of changes to `Organize Imports` over the last year, so I might have fixed this unknowingly ;-). Other candidates are @wpopielarski and @sschaef.
