### ISSUE TITLE
Generated protocol assertions for elisp.

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-server#784]
Would be neat if we could generate a series of elisp assertions like:

(assert-completion x)
(assert-position x)
(assert-note x)
...

These would act as a poor man's type checking / documentation in elisp, and would be easy to maintain because they'd be gleaned directly from the case classes in Model.scala.

**Comment by fommil** [comment]
This issue was moved to ensime/ensime-emacs#171
