### ISSUE TITLE
Noisy presentation compiler can cause emacs to crash

### ISSUE THREAD

**Issue by photex** [ensime/ensime-server#785]
... and I'm not sure how to debug this in order to give you  more information.

I started a new job on Monday and it's one of the largest codebases I've personally worked with. Ensime can start fine for the most part, but if I do something like start sbt it'll crash emacs. SBT has to be set to use 4gb heap just to work with this project.

This is OSX using the latest Emacs.app from emacsforosx.com.

How can I help?

**Comment by fommil** [comment]
I wouldn't call that gigantic. My project at work needs a **lot** more than 4gb :wink:

Sounds like ENSIME just needs more heap. If you increase the heap size for sbt even further, the `gen-ensime` task will automatically pick up on it and create an appropriate `.ensime` config for you. Alternatively, you can manually edit the `.ensime` to pass more heap to the java process that starts the ensime server.

**Comment by photex** [comment]
It doesn't change the fact that this is crashing *emacs*, sbt is fine. The
project breadth is large enough that interacting with ensime in the emacs
process is literally causing emacs to crash for some reason. Not a simple
"darn, the ensime server bailed", no the actual emacs instance goes down.
That's the bug I'm reporting here.

**Comment by aemoncannon** [comment]
Could you specify the sequence of events that leads to the crash? How are
you starting SBT? When exactly does it crash?

**Comment by photex** [comment]
It hasn't been the same thing each time... it's more like, after a certain
amount of time. If I watch the ensime server process buffer there is a lot
of output with a relatively high frequency of exceptions raised by
something in the presentation compiler.

It's happened when opening a file, it's happened when starting sbt (C-c C-b
s), and it's happened while just scrolling through the project files list
in helm. I would really like to figure out how to provide some more
substantial information about this.

There are 8k files in this project separated over multiple subprojects,
which is what I meant by gigantic. The majority of these are generated from
IDLs.

**Comment by fommil** [comment]
that sounds weird. Are you definitely using the latest version of ensime?

**Comment by rorygraves** [comment]
@photex Can you give me a couple of examples of the errors from the presentation compiler?

**Comment by rorygraves** [comment]
@fommil Do we truncate the ensime buffer in emacs at all?  Could it be something stupid like running out of memory within emacs because of the number of errors?

**Comment by photex** [comment]
@rorygrave Here is one of the exceptions from the presentation compiler: http://hastebin.com/dafotapuhe.log

and here is an error that makes up most of the rest of the buffer (with the symbol being different):
http://hastebin.com/mepumenupi.m

So I just updated from MELPA to make sure I had the latest, and I compiled the project from my shell before starting ensime and I don't have any of these errors so far. The ensime server buffer is only at 93 lines.

**Comment by fommil** [comment]
what version of scala is your project? And can you confirm that this is in the `.ensime`?

**Comment by photex** [comment]
Scala 2.10.4

This is also listed correctly in .ensime

**Comment by fommil** [comment]
does the problem arise if you do an `sbt clean` then restart ENSIME then look at a file? What then happens if you do a `sbt compile`?

I think Rory's instinct is correct here: sounds like the number of messages coming from the ensime server are enough to cause emacs to OOM. We should probably filter stack traces to reduce the noise.

**Comment by rorygraves** [comment]
If that is the issue we should also look at size limiting the buffer (dropping the head when the buffer goes over a certain size)  (and reducing the noise obviously).

**Comment by aemoncannon** [comment]
Could be Emacs is freaking out trying to create all the overlays for a
massive number of notes. One quick check you could do is to redefine the
note creation function to a no-op. Evaluate the following:

(defun ensime-add-notes (lang result))

And then try.

**Comment by photex** [comment]
Ok, if I run clean, then yes the ensime buffer grows by thousands of lines
per file opened, and every file I open after that starts adding on. The
line count went to ?? after 20k or so.

I'll repeat all of this again after setting ensime-add-notes as suggested.

**Comment by fommil** [comment]
Two things we can do:

1. don't log so much when the presentation compiler borks (or send it to a file)
2. emacs don't hold onto the whole log file

**Comment by fommil** [comment]
BTW, I wouldn't expect the presentation compiler to actually work after you run clean. It needs the classes of your file's dependencies to be compiled before it can infer anything. The problem here seems to be that the presentation compiler is very noisy when it goes wrong.

**Comment by aemoncannon** [comment]
@photex Any luck?

**Comment by photex** [comment]
@aemoncannon it definitely made things snappier. 

I haven't had a crash since making sure I run compile first thing.

**Comment by fommil** [comment]
@photex this is something we'd like to fix before releasing the 1.0 Stable. It could take some time before any of us get around to it, would you be interested in fixing it and providing a Pull Request? It should be simple to fix and we can point you at the suspicious code in the server (plus if you have any experience with logback config files, that would be useful)

**Comment by photex** [comment]
@fommil I'd be happy to contribute. Sounds like it's two parts, keeping the process buffer truncated and logging externally?

**Comment by fommil** [comment]
1. that will probably be when we create the buffer https://github.com/ensime/ensime-emacs/blob/master/ensime-mode.el#L553

2. we might not need to log externally, if we can make the messages more terse. If we could get logback to filter the stacktraces to exclude presentation compiler internal packages, that would be good. Alternatively me might just not include the stacktrace/cause in the log message. It looks like the exception is being raised here https://github.com/ensime/ensime-server/blob/master/src/main/scala/org/ensime/core/SemanticHighlighting.scala#L150 (maybe there is even a bug in our use of the API)

**Comment by fommil** [comment]
another noisy stacktrace I've been seeing

```
[info] 	at scala.tools.nsc.interactive.CompilerControl$AskTypeAtItem.apply(CompilerControl.scala:354) [scala-compiler.jar:na]
[info] 	at org.ensime.server.RichPresentationCompiler$$anonfun$wrapTypedTreeAt$1.apply(RichPresentationCompiler.scala:476) [ensime_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
[info] 	at org.ensime.server.RichPresentationCompiler$$anonfun$wrapTypedTreeAt$1.apply(RichPresentationCompiler.scala:476) [ensime_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
[info] 	at org.ensime.server.RichPresentationCompiler.wrap(RichPresentationCompiler.scala:450) [ensime_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
[info] 	at org.ensime.server.RichPresentationCompiler.wrapTypedTreeAt(RichPresentationCompiler.scala:476) [ensime_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
[info] 	at org.ensime.server.RichPresentationCompiler.typeAt(RichPresentationCompiler.scala:313) [ensime_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
[info] 	at org.ensime.server.RichCompilerControl$$anonfun$askTypeInfoAt$1.apply(RichPresentationCompiler.scala:49) [ensime_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
[info] 	at org.ensime.server.RichCompilerControl$$anonfun$askTypeInfoAt$1.apply(RichPresentationCompiler.scala:49) [ensime_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
```

**Comment by photex** [comment]
Hi folks!

Is there a guide about getting started hacking with ensime? As mentioned in my first post I literally just started at my current job so have been primarily focused on getting into the swing of things, but I'd really like to take a stab at this now.

**Comment by fommil** [comment]
@photex https://github.com/ensime/ensime-server/wiki

**Comment by fommil** [comment]
or do you mean hacking **on** ensime?

**Comment by photex** [comment]
Both actually.

**Comment by fommil** [comment]
not really, just dive in to the code. This should get you set up from a practical perspective https://github.com/ensime/ensime-server/wiki/Quick-Start-Guide#installing-the-server-from-source

**Comment by fommil** [comment]
a lot of the actor refactorings should deal with this. We'd need a recent reproduction to be able to say anything.
