### ISSUE TITLE
support scalajs crossbuild projects

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#786]
Problem: ENSIME will double count source directories that are referenced in more than one module. Previously, we thought this would never happen, but it turns out that this is exactly how ScalaJS advises setting up a cross-compiled project (i.e. code that is compiled to both scala and javascript, running tests in both the JVM and Rhino).

This might not be such a big deal, because there is only one set of `.class` files generated. I'll play around for a few days and see if any problems arise.

@lihaoyi does scalajs have any plans to change this recommended structure? (btw, I don't think you need to define a `lazy val root` module anymore with sbt... in fact this causes a problem with ENSIME because it depends on scala 2.10 and that will be pulled in as a library dependency in the IDE. I suspect gen-idea will suffer the same problem because we basically copied their code for our plugin)

**Comment by fommil** [comment]
I think I was worrying about nothing, we seem to be coping just fine... it feels weird though, like something **should** have broken.

**Comment by lihaoyi** [comment]
@fommil want to ask on the mailing list? People there can point you at existing discussion and the path forward.

**Comment by lihaoyi** [comment]
or on the gitter channel https://gitter.im/scala-js/scala-js#
