### ISSUE TITLE
Disconnected immediately, and then on reconnect, Symbol's value as variable is void: ensime-default-server-port

### ISSUE THREAD

**Issue by eallik** [ensime/ensime-server#790]
I've just set up a fresh project using Ensime 20150117.107; as soon as I do `M-x ensime`, it immediately displays "Disconnected" in the mode bar, without even waiting for the first `RET`. When I then attempt to `ensime-connect`, it says:

    Symbol's value as variable is void: ensime-default-server-port

`build.sbt`:

```scala
scalaVersion in ThisBuild := "2.11.5"
```

SBT version 0.13.7

`project/plugins.sbt`:

```scala
resolvers += Resolver.sonatypeRepo("snapshots")

addSbtPlugin("org.ensime" % "ensime-sbt" % "0.1.5-SNAPSHOT")
```

**Comment by eallik** [comment]
OK, turns out the issue was solved by moving my `.scala` file from under the project root to under `src/main/scala` — is that intended behavior? I thought SBT projects could have `.scala` files directly under the project root.

**Comment by fommil** [comment]
yes, that is intended behaviour. We don't support "script" style projects although there is a ticket to do so in #668
