### ISSUE TITLE
resolve the scalariform classpath/version mess

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#792]
Scalariform used to be maintained at https://github.com/mdr/scalariform by @mdr and is pulled in by https://github.com/sbt/sbt-scalariform

Scalariform is most actively maintained at https://github.com/daniel-trinh/scalariform by @daniel-trinh with a corresponding https://github.com/daniel-trinh/sbt-scalariform

Unfortunately, daniel kept the same FQNs when he published his artifacts under a different name, so users can end up with multiple versions of scalariform on their classpath as transitive dependency resolvers cannot detect the collision.

There are a couple of bugs that daniel has partially addressed, e.g. preserving/forcing dangling newlines, which result in changes to source code formatting that is not backwards compatible to the mdr branch (there doesn't appear to be a way to choose the old behaviour https://github.com/daniel-trinh/scalariform/issues/29 ). (Note, it is unclear if these fixes have been backported to scala 2.10, as they don't seem to work under sbt https://github.com/mdr/scalariform/issues/75 .)

Unfortunately, this has consequences for us at ENSIME because we depend on daniel's build (primarily because mdr didn't publish a scala-2.11 build) in our server and we depend on mdr's builds in our sbt-plugin so that we can correctly export the settings.

I raised this on the scala-ide mailing list, as they are also impacted https://groups.google.com/d/msg/scala-ide-dev/65JHMO6Kkao/blIfevBtmW0J but nothing has come of it except an acknowledgement that there is a problem.

Here are some solutions

1. mdr picks up dev again and pumps out all the fixes on the mainline :smile:
2. mdr gives daniel-trinh / rep at scala-ide the right to publish under the `org.scalariform` groupid
3. ensime creates a fork of daniel's master with all the FQNs renamed so that we can depend on scalariform in our plugin, and the fork in ensime-server

I have been unable to contact mdr so, unfortunately, the latter is looking to be the best way forward.

In any solution, we will have to get daniel to release a version of his scalariform and sbt plugin with all the FQNs moved to a new location, so that transitive resolvers to both (or all three!!) versions do not conflict with each other.

@mdr @daniel-trinh can either of you please comment?

**Comment by daniel-trinh** [comment]
When you say "FQNs moved to a new location", does this mean renaming all of the packages from using `org.scalariform` in the source files to `another.fqn`, in `scalariform` and `sbt-scalariform`??

**Comment by fommil** [comment]
@daniel-trinh good to hear from you :smile: yes, that is exactly what I mean

**Comment by fommil** [comment]
@daniel-trinh probably the best fqn to rename to would be `org.scalariform` => `danieltrinh.scalariform` as that will involve two `git mv`s (one for main, one for src) and then a global search/replace in `package org.scalariform` and `import org.scalariform`.

**Comment by fommil** [comment]
daniel has PRs on this to both his projects, action on me to check that everything works.

**Comment by fommil** [comment]
@daniel-trinh I made contact with @mdr on twitter, he says he can give you the right to publish to the main artefact out sonatype (you'll need to get in contact for this I should imagine)

**Comment by fommil** [comment]
@daniel-trinh @mdr any updates on this?

**Comment by fommil** [comment]
@daniel-trinh have you applied for publishing rights on sonatype yet? I think that's probably the next step and Matt could approve you being added to the list.

**Comment by fommil** [comment]
@daniel-trinh any joy with sonatype publishing? http://central.sonatype.org/pages/ossrh-guide.html

**Comment by fommil** [comment]
daniel trinh released the update! yay! I'll look at this in the coming days. Unfortunately he wasn't able to work out how to release empty packages under his own namespace, but that's a different problem.

**Comment by fommil** [comment]
I released `ensime-sbt` with the updates, which should fix the issue for the majority of people.

Upstream still need to reconcile the https://github.com/sbt/sbt-scalariform/issues/20 but it sounds like there will be movement soon.

**Comment by andrebeat** [comment]
Because of https://github.com/sbt/sbt-scalariform/issues/20 I'm unable to update to a more recent version of `ensime-sbt` (I'm stuck on 0.1.5) on most of my projects since they rely on `sbt-scalariform` (specifically we rely on the integration test support).

I actually merged @daniel-trinh's fork with the upstream changes. Aside from sbt build code (which I didn't bother merging) the only changes are support for integration tests. If @daniel-trinh is interested I can create a PR.

**Comment by fommil** [comment]
@andrebeat are you saying that the current version of `sbt-scalariform`, i.e. 

```scala
addSbtPlugin("org.scalariform" % "sbt-scalariform" % "1.4.0")
```

has introduced a regression? Probably best to raise that with Daniel.

Also, prompt people at the linked ticket to decide who the one true source is.

**Comment by andrebeat** [comment]
Yes, since it is a newer version sbt evicts my current dependency (`"com.typesafe.sbt" % "sbt-scalariform" % "1.3.0"`). The new version `"org.scalariform" % "sbt-scalariform" % "1.4.0"` doesn't provide the following methods `scalariformSettingsWithIt` and `defaultScalariformSettingsWithIt`. 

I agree with you, I'll move this discussion somewhere else as it is more appropriate.

**Comment by fommil** [comment]
It's probably trivial to port those methods into your codebase.

**Comment by andrebeat** [comment]
For reference, I've updated @daniel-trinh's `sbt-scalariform` fork to be feature par with the "upstream" version (https://github.com/daniel-trinh/sbt-scalariform/pull/8).
