### ISSUE TITLE
Explain use of swank:call-completion

### ISSUE THREAD

**Issue by rorygraves** [ensime/ensime-server#799]
I was looking at uncovered code and worked back to swank:call-completion trying to work out what 'id' was.
The comment says 
```
'Int:A type id, as returned by swank:scope-completion or swank:type-completion.'
```
but neither of these methods exist - I can however see it called by ```ensime-client.el``` which is called from ```ensime-auto-complete.el``` but my lisp-foo is not strong enough to decypher the magic.
Can somebody ( @aemoncannon / @edani  ?) explain which call the id comes from so I can write a test?

**Comment by edani** [comment]
The type id is returned by swank:completions  (which I gather replaced both swank:scope-completion and swank:type-completion at some point).   It's also returned by several other calls such as swank:inspect-type-at-point or any other call that returns a TypeInspectInfo, if that makes the test easier to write.

Also type IDs are generated in org.ensime.model.ModelBuilders.cacheType  so you can also call that directly if you have a Type instance.

**Comment by aemoncannon** [comment]
Yep

**Comment by aemoncannon** [comment]
The purpose of call-completion is to retrieve detailed types for parameters
and return type, after a completion is chosen. It accepts a type id because
type id is the abbreviated form that is included with each completion.

**Comment by rorygraves** [comment]
I knew we employed you guys for a reason :smiley: 
Thanks for the info - will update the comment and add some test coverage.
