### ISSUE TITLE
elisp tests should use versions defined by ensime-pkg

### ISSUE THREAD

**Issue by tjweir** [ensime/ensime-server#804]
Hello,

I just recently upgraded my ENSIME to the latest in ELPA, Version: 20150119.1350 and any attempt to use auto-complete leads to the error of:
"Symbol's function definition is void: -find"

My sbt plugin is 0.1.5-SNAPSHOT

*inferior-ensime-server* buffer says:
Ensime : 0.9.10-SNAPSHOT

*Messages* Buffer says:
Connected to ENSIME speaking protocol 0.8.10, please wait while the project is loaded.
Error running ensime-source-buffer-saved-hook: (void-function -find)
Error running timer `tooltip-timeout': (void-function -find)
Company: An error occurred in auto-begin
Company: Back-end ensime-company error "Symbol's function definition is void: -find" with args (candidates ca)
Company: An error occurred in auto-begin
Company: Back-end ensime-company error "Symbol's function definition is void: -find" with args (candidates cal)
Company: An error occurred in auto-begin
Company: Back-end ensime-company error "Symbol's function definition is void: -find" with args (candidates cale)
Company: An error occurred in auto-begin
Company: Back-end ensime-company error "Symbol's function definition is void: -find" with args (candidates calen)
ensime-owning-connection-for-source-file: Symbol's function definition is void: -find

Am I doing something goofy?

Thanks!

**Comment by aemoncannon** [comment]
-find should be an alias for -first in dash.el. I'm guessing ensime-pkg.el
needs to be updated with the latest version. That said, this should have
been caught by a test..

**Comment by aemoncannon** [comment]
Dotemacs_test.el should be using the versions from ensime-pkg.el, but it
isn't. I'm guessing that's why this slipped through.

**Comment by tjweir** [comment]
Ok, based on Aemon's comments, I looked at what version of dash.el I had installed.
It was: dash-20140121.427
When I upgraded to: dash-20141220.1452
and now everything is working as expected.

Thank you for your help.

Shall I close this, or do you want to leave it open to improve the tests?

**Comment by aemoncannon** [comment]
Leave open, please. The package is broken until we fix the version, and we
should fix the tests as well.

**Comment by tjweir** [comment]
Ok, thanks again for the help.

ENSIME is what made me switch from Vim to Emacs!  :)

**Comment by aemoncannon** [comment]
Glad to be of service. If you enjoy elisp we welcome pull requests : )

**Comment by tjweir** [comment]
I do tend to need a reason to learn a new language. :)

**Comment by rorygraves** [comment]
We welcome Scala PRs too ;)

**Comment by fommil** [comment]
@aemoncannon did you get the elisp tests using the package file?

**Comment by aemoncannon** [comment]
@fommil yeah. See dot-emacs.el. though still not pinned to specific
versions : \
