### ISSUE TITLE
modularise

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#813]
break into:

* sexp
* api
* server

which will probably necessitate moving to a project/Build.scala style project. Easily done, but it'll be a PITA for merge conflicts moving everything around.

This allows us to use the sexp/api layers in the sbt-plugin (but remember that it'll be taking them from the 2.10 branch) and potentially other build plugins.

**Comment by fommil** [comment]
I'm working on this as a follow up to 

Having #669 would be incredibly useful...

**Comment by fommil** [comment]
I'm hoping to get this done today. It's turning into a refactor of the testing because now we can really just define actual projects for the test projects and pull them in.

It should be relatively easy to add tests for `git submodules` if we really want to, which should make recreating user bugs really easy.

**Comment by fommil** [comment]
@rorygraves  almost done. I have a whole new set of integration test fixtures now that make integration testing really easy. Just polishing the debug/workflow tests (which can now be split up with no performance penalty)

**Comment by rorygraves** [comment]
@fommil Awesome, looking forward to reviewing it all.
