### ISSUE TITLE
Public symbol search failing with swank protocol exception

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-server#814]
- Received msg: (:swank-rpc (swank:public-symbol-search ("getFromFil") 50) 207)
[info] 17:44:12.828 [default-akka.swank-dispatcher-198] ERROR o.e.s.protocol.swank.SwankProtocol - Exception whilst handling rpc org/ensime/server/protocol/swank/SwankProtocol$StringListExtractor$
[info] java.lang.NoClassDefFoundError: org/ensime/server/protocol/swank/SwankProtocol$StringListExtractor$
[info] 	at org.ensime.server.protocol.swank.SwankProtocol.StringListExtractor$lzycompute(SwankProtocol.scala:1742) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
[info] 	at org.ensime.server.protocol.swank.SwankProtocol.StringListExtractor(SwankProtocol.scala:1742) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
[info] 	at org.ensime.server.protocol.swank.SwankProtocol.org$ensime$server$protocol$swank$SwankProtocol$$handleRPCRequest(SwankProtocol.scala:807) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
[info] 	at org.ensime.server.protocol.swank.SwankProtocol$$anonfun$handleEmacsRex$1.apply$mcV$sp(SwankProtocol.scala:122) [ensime_2.11.jar:0.9.10-SNAPSHOT]
[info] 	at org.ensime.server.protocol.swank.SwankProtocol$$anonfun$handleEmacsRex$1.apply(SwankProtocol.scala:119) [ensime_2.11.jar:0.9.10-SNAPSHOT]
[info] 	at org.ensime.server.protocol.swank.SwankProtocol$$anonfun$handleEmacsRex$1.apply(SwankProtocol.scala:119) [ensime_2.11.jar:0.9.10-SNAPSHOT]
[info] 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library-2.11.4.jar:na]
[info] 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [scala-library-2.11.4.jar:na]
[info] 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [akka-actor_2.11-2.3.8.jar:na]
[info] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_05]
[info] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_05]
[info] 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]
[info] 17:44:12.828 [default-akka.actor.default-dispatcher-173] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:return (:abort 201 "org/ensime/server/protocol/swank/SwankProtocol$StringListExtractor$") 207)

**Comment by fommil** [comment]
I've also noticed that search has been a bit temperamental lately.

**Comment by aemoncannon** [comment]
Saw this again just now when doing an import-type-at-point

**Comment by fommil** [comment]
if this is a problem with the protocol, then maybe my branch will fix it (and introduce it's own set of problems!)

**Comment by edani** [comment]
Hash this been happening lately? I'm having trouble reproducing it.

**Comment by fommil** [comment]
I seen something like this in https://github.com/ensime/ensime-emacs/issues/275

I'm pretty sure its a client side bug. I think we decided it was best to bail the server connection if there is a parse error.
