### ISSUE TITLE
IncompatibleClassChangeError on C-c C-d r

### ISSUE THREAD

**Issue by eallik** [ensime/ensime-server#816]
When running one of my app entry points, I get:

```
Press q to quit, use n,s,o,c to control debugger.
----------------------------------------

Instance of java.lang.IncompatibleClassChangeError
serialVersionUID: long = -3042686055658047285
detailMessage: String = "Implementing class"
UNASSIGNED_STACK: StackTraceElement[] = Array[]
cause: Throwable = Instance of IncompatibleClassChangeError
stackTrace: StackTraceElement[] = Array[]
SUPPRESSED_SENTINEL: List = Instance of Collections$UnmodifiableRandomAccessList
suppressedExceptions: List = Instance of Collections$UnmodifiableRandomAccessList
NULL_CAUSE_MESSAGE: String = "Cannot suppress a null exception."
SELF_SUPPRESSION_MESSAGE: String = "Self-suppression not permitted"
CAUSE_CAPTION: String = "Caused by: "
SUPPRESSED_CAPTION: String = "Suppressed: "
EMPTY_THROWABLE_ARRAY: Throwable[] = Array[]
$assertionsDisabled: boolean = true
serialVersionUID: long = 4980196508277280342
serialVersionUID: long = 3579600108157160122
serialVersionUID: long = -4914975503642802119
```

The entry point under question is a simple object with a `main` method.

**Comment by aemoncannon** [comment]
Is it possible your app is being run with a funny configuration (hitting a
stale library..)? Ensime talks to the process under debug through a thin
IPC channel. We can't do much about what happens over there.

**Comment by fommil** [comment]
I'm afraid that's not enough information. Can you please give a full reproduction, ideally in the form of a unit or integration test? A github repository with exact instructions for somebody to follow, like a script, is also good. http://ensime.org/getting_help/

We have very good documentation at http://ensime.org/contributing/ to help you get started hacking on ENSIME.

**Comment by eallik** [comment]
I'm afraid 1 year later is a bit too late to give a full reproduction ;)
