### ISSUE TITLE
Trying to 'sbt publish-local' the plugin and getting crazy errors

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-server#817]
Am I doing something dumb?

sbt --version
sbt launcher version 0.13.5

sbt publish-local
[info] Loading global plugins from /Users/aemon/.sbt/0.13/plugins
[info] Loading project definition from /Users/aemon/projects/ensime-sbt-cmd/project
[info] Set current project to ensime-sbt (in build file:/Users/aemon/projects/ensime-sbt-cmd/)
[info] :: delivering :: org.ensime#ensime-sbt;0.1.5-SNAPSHOT :: 0.1.5-SNAPSHOT :: integration :: Thu Feb 05 14:25:10 GMT 2015
[info] Main Scala API documentation to /Users/aemon/projects/ensime-sbt-cmd/target/scala-2.10/sbt-0.13/api...
[info] 	delivering ivy file to /Users/aemon/projects/ensime-sbt-cmd/target/scala-2.10/sbt-0.13/ivy-0.1.5-SNAPSHOT.xml
[info] Compiling 4 Scala sources to /Users/aemon/projects/ensime-sbt-cmd/target/scala-2.10/sbt-0.13/classes...
[error] /Users/aemon/projects/ensime-sbt-cmd/src/main/scala/CommandSupport.scala:4: not found: object IO
[error] import IO._
[error]        ^
[error] /Users/aemon/projects/ensime-sbt-cmd/src/main/scala/CommandSupport.scala:7: not found: type AutoPlugin
[error]   this: AutoPlugin =>
[error]         ^
[error] /Users/aemon/projects/ensime-sbt-cmd/src/main/scala/CommandSupport.scala:9: not found: type State
[error]   protected def fail(errorMessage: String)(implicit state: State): Nothing = {
[error]                                                            ^
[error] /Users/aemon/projects/ensime-sbt-cmd/src/main/scala/CommandSupport.scala:24: not found: type TaskKey
[error]   protected implicit class RichTaskKey[A](key: TaskKey[A]) {
etc
etc
etc

**Comment by fommil** [comment]
try cleaning out all the caches: the project, ~/.ivy2 and potentially ~/.sbt

**Comment by aemoncannon** [comment]
Thanks. I think it was confused because I had a global ensime-sbt plugin?
Anyway after reinstalling all the things it worked. There goes an hour!
