### ISSUE TITLE
Update comms to use spray.io/akka.io

### ISSUE THREAD

**Issue by rorygraves** [ensime/ensime-server#820]
Apparently this was all ported to 2.9 by spray, so there is no reason not to move to akka.io on the server.

**Comment by fommil** [comment]
@rorygraves are you ever going to get round to this or should I pick it up?

**Comment by rorygraves** [comment]
Please pick it up - you are 90% of the way there.

**Comment by fommil** [comment]
more important stuff, let's unassign it and put it back into the 1.0 backlog

**Comment by fommil** [comment]
the waffle fairy is assigning this to rory (because I know he's almost finished it :smile:)
