### ISSUE TITLE
Initial Semantic highlighting of open buffer list takes too long

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-server#821]
This can sometimes take 25-30s as the jvm + pres compiler both need to warm up. We should do this lazily, when the buffer is viewed the first time (i believe there's a recently introduced hook for this...)

**Comment by aemoncannon** [comment]
(obviously this is only a problem if you're booting ensime when you already have several scala files open)

**Comment by fommil** [comment]
This issue was moved to ensime/ensime-emacs#167
