### ISSUE TITLE
sbt-scalariform dependency non-existent

### ISSUE THREAD

**Issue by wiegraffolles** [ensime/ensime-server#824]
When installing ensime-sbt, the package sbt-scalariform is required by ensime-sbt, and it requests that sbt pull down this package from the following url: 

https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/sbt/sbt-scalariform_2.10_0.13/1.3.0/sbt-scalariform-1.3.0.pom

However this file does not actually exist on the Sonatype server *for any file version* and this causes the installation to fail.  The sbt-scalariform package is now available at https://github.com/daniel-trinh/sbt-scalariform, so please update the ensime-sbt dependencies accordingly.

**Comment by fommil** [comment]
it does exist at the releases repo, not the snapshot one. It sounds like something weird is going on with your sbt resolution. Moving to daniel-trinh's branch is not trivial and is being resolved elsewhere #792 and when that is fixed (upstream blockage) this will fix itself.
