### ISSUE TITLE
Bad source jar kills the server

### ISSUE THREAD

**Issue by oneself** [ensime/ensime-server#825]
Hi,

I have a bad source jar in my dependency graph.  When ensime loads up, it tries to access the jar, get's an exception, and dies.  I think that this should not kill the server.  The specific jar source should just not be available.

I was able to solve this temporarily by removing the offending jar from :reference-source-roots in .ensime.

Here's the stack trace I get when I M-x ensime.  Note that all sbt commands (package, test, etc.) run fine, including gen-ensime.

    [error] Exception in thread "main" org.apache.commons.vfs2.FileSystemException: Could not open Jar file "/home/me/.ivy2/cache/cascading.avro/avro-scheme/srcs/avro-scheme-2.2-SNAPSHOT-sources.jar".
    [error]         at org.apache.commons.vfs2.provider.jar.JarFileSystem.createZipFile(JarFileSystem.java:62)
    [error]         at org.apache.commons.vfs2.provider.zip.ZipFileSystem.getZipFile(ZipFileSystem.java:136)
    [error]         at org.apache.commons.vfs2.provider.jar.JarFileSystem.getZipFile(JarFileSystem.java:214)
    [error]         at org.apache.commons.vfs2.provider.zip.ZipFileSystem.init(ZipFileSystem.java:83)
    [error]         at org.apache.commons.vfs2.provider.AbstractVfsContainer.addComponent(AbstractVfsContainer.java:52)
    [error]         at org.apache.commons.vfs2.provider.AbstractFileProvider.addFileSystem(AbstractFileProvider.java:101)
    [error]         at org.apache.commons.vfs2.provider.AbstractLayeredFileProvider.createFileSystem(AbstractLayeredFileProvider.java:90)
    [error]         at org.apache.commons.vfs2.provider.AbstractLayeredFileProvider.findFile(AbstractLayeredFileProvider.java:63)
    [error]         at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:693)
    [error]         at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:649)
    [error]         at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:605)
    [error]         at org.ensime.indexer.package$.vjar(package.scala:14)
    [error]         at org.ensime.indexer.SourceResolver$$anonfun$4.apply(SourceResolver.scala:52)
    [error]         at org.ensime.indexer.SourceResolver$$anonfun$4.apply(SourceResolver.scala:50)
    [error]         at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    [error]         at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    [error]         at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:153)
    [error]         at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:306)
    [error]         at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:306)
    [error]         at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    [error]         at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
    [error]         at scala.collection.SetLike$class.map(SetLike.scala:93)
    [error]         at scala.collection.AbstractSet.map(Set.scala:47)
    [error]         at org.ensime.indexer.SourceResolver.<init>(SourceResolver.scala:50)
    [error]         at org.ensime.core.Project.<init>(Project.scala:69)
    [error]         at org.ensime.server.Server.<init>(Server.scala:70)
    [error]         at org.ensime.server.Server$.initialiseServer(Server.scala:42)
    [error]         at org.ensime.server.Server$.main(Server.scala:38)
    [error]         at org.ensime.server.Server.main(Server.scala)
    [error] Caused by: java.util.zip.ZipException: error in opening zip file
    [error]         at java.util.zip.ZipFile.open(Native Method)
    [error]         at java.util.zip.ZipFile.<init>(ZipFile.java:132)
    [error]         at java.util.jar.JarFile.<init>(JarFile.java:153)
    [error]         at java.util.jar.JarFile.<init>(JarFile.java:117)
    [error]         at org.apache.commons.vfs2.provider.jar.JarFileSystem.createZipFile(JarFileSystem.java:58)
    [error]         ... 28 more

**Comment by fommil** [comment]
As discussed on email, I don't believe we should handle dodgy jars. We could, perhaps, have a more explicit error message await how to resolve the problem. It is, ultimately, a an environment problem.

**Comment by rorygraves** [comment]
We should probably alert on the failure and continue.  It should definitely be a soft failure rather than killing the server.  Obviously a better error message would help too :)

**Comment by fommil** [comment]
I don't think so, because then we'll have to handle the dodgyness everywhere that we touch the jar or its entries, that's a lot of error handling. If the jar is dodgy, I believe we should just fail fast with an error. The reality is that the jar **is** dodgy and should be deleted/replaced by the user.

**Comment by andreasjansson** [comment]
I'm seeing the same issue, and I "fixed" it by just removing the dodgy jars from my .ensime. Like the OP, the jars broken for me are source jars, and ensime runs just fine without them. Could we emit a warning and ignore broken jars, as long as they're source jars?

**Comment by fommil** [comment]
@andreasjansson if that helps, then sure. Have a look in `SourceResolver` and we'd be happy to take a PR on this.

**Comment by fommil** [comment]
(if you could find a dodgy jar on maven central that we can use for integration testing, then add it to the relevant `testing` project in `project/Build.scala`)

**Comment by caoilte** [comment]
I have a dodgy jar, but it's not on Maven central any more. Presumably it got removed at some point because it was corrupted - but not before getting mirrored.

https://repository.cloudera.com/cloudera/repo/org/json/json/20090211/json-20090211-sources.jar

My feeling is that if ensime can't be given the smarts to ignore the corrupt jar then gen-ensime shouldn't put it in the .ensime file in the first place.

The current behaviour is to hang until Ensime-server is killed which is really really nasty.

**Comment by fommil** [comment]
workaround is to delete your local copy and add the jar to the list of excluded classifiers in ivy. Ask an sbt expert about how to do that. That entirely sidesteps the issue. If you could report back here about the commands, I'll update the original report for others to apply the same workaround.

**Comment by caoilte** [comment]
> add the jar to the list of excluded classifiers in ivy

Is that even possible? I don't have the source jars as dependencies so I wouldn't be excluding them from my build. I assume gen-ensime adds them dynamically. Wouldn't I need to run an exclude rule over the output of that?

**Comment by fommil** [comment]
@caoilte I think you deleted a comment. It's an ivy-wide exclusion rule you'll add to the file I noted above. I don't actually know how to do it, but if you find out and report here that would be appreciated.
