### ISSUE TITLE
.ensime and :java-home

### ISSUE THREAD

**Issue by Gastove** [ensime/ensime-server#826]
As of the latest release I've hit the following: the `:java-home` ensime config is listed as optional, claiming it overrides `ensime-default-java-home`. However, that variable never seems to get defined. And the error that ensime throws is the ever-maddening `Ensure that SBT is on yoru Path and that your config matches etc`, which claims `:java-home` is optional.  As soon as I set `:java-home`, everything lit right back up and I was back in action.

Sooooo. Something is hinky somewhere, but I'm not sure which problem precisely is the culprit.

**Comment by fommil** [comment]
it's not optional, it's required. I'll update the docs.

**Comment by fommil** [comment]
How did you generate your `.ensime`?

**Comment by Gastove** [comment]
Heh. Python script -- the project I'm work on is all maven all the time. The script is handy -- and I can use ensime at all -- but it's not exactly reference-grade, shall we say.

**Comment by fommil** [comment]
hehe. I think somebody made a maven plugin, it would be good if you could consolidate your efforts.

**Comment by Gastove** [comment]
Oh my lord. I started hacking on one last week, but it's not exactly top-of-mind at the moment -- but if the repo for that winds up linked or posted somewhere around here, I'd be happy to try and pitch in. Sounds a heck of a lot better than, uh, what I've got now.

**Comment by fommil** [comment]
hmm, I can't seem to find a link to it on the wiki! We must have forgotten to document it... but I know one exists.

**Comment by aemoncannon** [comment]
https://github.com/parsnips/ensime-maven-plugin
