### ISSUE TITLE
When selecting a completion from classpath (provided by indexer), don't insert fully qualified name.

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-server#830]
I feel like a more useful behavior would be to insert unqualified while at the same time inserting the import. Thoughts?

**Comment by fommil** [comment]
yes, agreed! I think this is a regression as it didn't always do this.

**Comment by ploddi** [comment]
👍

**Comment by tonylotts** [comment]
:+1:

**Comment by tbje** [comment]
+1

**Comment by fommil** [comment]
This issue was moved to ensime/ensime-emacs#166
