### ISSUE TITLE
remove blobs from the history

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#833]
Would anybody object if we ran this script on the server/emacs repos?

  https://github.com/rtyley/bfg-repo-cleaner

Perhaps just the emacs one initially. Looking into the emacs travis testing has made me realise how big these repos actually are because they used to ship jars with them and that's all in there forever.

**Comment by aemoncannon** [comment]
Fine by me. But for the purposes of testing, is it possible to do a
'shallow' clone or something?

**Comment by fommil** [comment]
possibly, that might be useful

**Comment by fommil** [comment]
@edani @aemoncannon @rorygraves I've run this on `ensime-emacs` (I've got a backup) and it seems to have really trimmed down the repo size.

```
git clone --mirror git@github.com:ensime/ensime-emacs.git
java -jar Downloads/bfg-1.12.3.jar --delete-files '*.zip' ensime-emacs.git
java -jar Downloads/bfg-1.12.3.jar --delete-files '*.zip' ensime-emacs.git
cd ensime-emacs.git && git reflog expire --expire=now --all && git gc --prune=now --aggressive
git push
```

However, it means that the history of your outstanding PRs look really funky. There is a fancy way to rebase from a rewrite of history, but I find it too complicated. I recommend simply noting the hashcode of the commits from your PR and then just cherry pick them on top of a fresh branch cut from master.

**Comment by fommil** [comment]
hah, this was totally futile. Turns out that it's not possible to do anything about the existing pull request branches, which are read-only: https://github.com/rtyley/bfg-repo-cleaner/issues/36

so a clone of the full repo is still really big. At least pulling just master is a lot smaller now. http://stackoverflow.com/questions/1911109

e.g.
```
 git clone -b master git@github.com:ensime/ensime-emacs.git
```

**Comment by fommil** [comment]
oh, no, ignore me... you don't need to request just the `master` branch

```
git clone git@github.com:ensime/ensime-emacs.git
```

works as expected and is only 2MB :smile:

**Comment by fommil** [comment]
similar thing done to `ensime-server`, it's now only 5.2MB instead of 60MB+

Apologies for the inconvenience of making everybody's PR's look all weird!

Make sure you also force push the new master onto your master, or your own origin will still be really big.

**Comment by aemoncannon** [comment]
what do you recommend doing with our github forks?

**Comment by aemoncannon** [comment]
nm. my PRs should be ready to go.
