### ISSUE TITLE
support symbolic methods (those that are renamed in bytecode)

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#835]
which is a bit annoying for scalaz and akka tell/ask

**Comment by aemoncannon** [comment]
Looks like indexer is returning no hits for !:
23:46:11.567 [Scala Presentation Compiler []] DEBUG o.e.core.RichPresentationCompiler - search: akka.actor.ScalaActorRef.! = None

**Comment by fommil** [comment]
I've probably put a minimum character limit. Doh!

**Comment by edani** [comment]
Doesn't scalac translate punctuation into alphanumeric strings? In that case the indexed name would be $bang$ or something.

**Comment by hedefalk** [comment]
@edani Funny. Apparently I never took your comment in, but that's exactly what I realized here: https://github.com/ensime/ensime-server/issues/1020#issuecomment-132981113. These are most definitely dups and I'd suggest closing this one since that other ticket has a better title. I can't seem to find anything about character limit.

**Comment by fommil** [comment]
related to #635 ?

**Comment by hedefalk** [comment]
Question: would it be ok to find the mappings of  $hash, $greater, $bang etc. and just translate them before searching db or do we want a greater scope of a fix?

**Comment by fommil** [comment]
@hedefalk that sounds like a sensible approach. I'm pretty sure I've written this code before.... https://github.com/fommil/lions-share/blob/master/analysis/src/main/scala/com/github/fommil/lion/alloc/domain.scala#L38

**Comment by fommil** [comment]
btw, this is on the 1.0 milestone which means its on my short-term hitlist. But that's not to say we wouldn't accept a PR on it.

**Comment by hedefalk** [comment]
Awesome! Still feel a bit intimidated of the server code so I would need some holding hands anyways…

**Comment by hedefalk** [comment]
Here's the latest NameTransformer from scala: https://github.com/scala/scala/blob/2.11.x/src/library/scala/reflect/NameTransformer.scala

**Comment by edani** [comment]
I think the right place to do the translation should be here: https://github.com/ensime/ensime-server/blob/ea19d572e94e83a4518713bdb69d75c8b399735e/core/src/main/scala/org/ensime/model/Helpers.scala#L93  for consistency.

As far as doing the translation, going through scala.reflect.internal.Names:  https://github.com/scala/scala/blob/0b47dc2f28c997aed86d6f615da00f48913dd46c/src/reflect/scala/reflect/internal/Names.scala#L431  might be more future-proof.
