### ISSUE TITLE
search not showing results, but working

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#837]
I can do an `ensime-search` followed by the name of a class I'm interested in, but nothing appears in the search list, but pressing enter will bring me to exactly where I wanted to go. Looks like a rendering bug.

**Comment by aemoncannon** [comment]
Pretty sure we actually scrape the ui text in a lisp integration -- pretty
funny that we can still be thwarted by rendering of invisible text. Abandon
all hope, ye who enter here.

https://github.com/ensime/ensime-emacs/blob/master/ensime-test.el#L1702

**Comment by fommil** [comment]
something funny was going on. I wonder if the result had been cached or something.

**Comment by fommil** [comment]
This issue was moved to ensime/ensime-emacs#165
