### ISSUE TITLE
gen-ensime for submodules only

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#839]
It would be really useful for our test harness if we could generate a `.ensime` just for specific submodules.

That way we could compile all the sources, generate a `.ensime`, and in the server integration tests have everything we need handed to us without the need to pass any parameters to the java process.

**Comment by fommil** [comment]
an alternative would be to depend on the .ensime for ensime itself and then filter submodules. Hmm, I might do that (either solution puts a dependency on ensime-sbt from the server, which might result in weird dependency cycles).

**Comment by fommil** [comment]
hmm, that means the integration tests would depend on `gen-ensime` but not the project build. That's a possible workable solution.

**Comment by raboof** [comment]
Hmm, could this explain some compiler errors I see in a project (that uses submodules) that builds fine in sbt? Any workarounds?

I see some errors I can't directly relate though (e.g. 'ERROR: spray.routing.Route.type does not take parameters')

**Comment by fommil** [comment]
Sounds like you're experiencing #673 although it's not usually that bad these days.

**Comment by fommil** [comment]
this is now redundant.
