### ISSUE TITLE
Refactor API to combine *byName *atPoint calls

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-server#845]
Is this worth doing? The proliferation of public calls is a little annoying, but maybe this is actually simpler and more understandable. Thoughts?

A quick survey yields:

  def rpcInspectTypeAtPoint(f: String, range: OffsetRange): Option[TypeInspectInfo]
  def rpcInspectTypeById(id: Int): Option[TypeInspectInfo]
  def rpcInspectTypeByName(name: String): Option[TypeInspectInfo]

  def rpcSymbolAtPoint(f: String, point: Int): Option[SymbolInfo]
  def rpcMemberByName(typeFullName: String, memberName: String, memberIsType: Boolean): Option[SymbolInfo]

  def rpcTypeById(id: Int): Option[TypeInfo]
  def rpcTypeByName(name: String): Option[TypeInfo]
  def rpcTypeByNameAtPoint(name: String, f: String, range: OffsetRange): Option[TypeInfo]
  def rpcTypeAtPoint(f: String, range: OffsetRange): Option[TypeInfo]

  def rpcDocUriAtPoint(f: String, point: OffsetRange): Option[String]
  def rpcDocUriForSymbol(typeFullName: String, memberName: Option[String], memberTypeId: Option[Int]): Option[String]

**Comment by fommil** [comment]
:+1: should we leave this until post 1.0 when we can go crazy and refactor a whole bunch of protocol stuff?

**Comment by aemoncannon** [comment]
Cool

**Comment by fommil** [comment]
we could go further and consider a more consistent approach about File/SourceFileInfo and generally removing redundant calls that can have the same effect through several smaller (more atomic calls). I don't really see there being a performance overhead in talking to ENSIME. All the overhead is in the presentation compiler.

**Comment by fommil** [comment]
going through the API again today I see this one again.

I wonder if we should perhaps have a sealed trait that captures the concept of `AtPoint` vs `ByName` and use that in place of everything. Internally the server could just turn both into the same query and return the same response regardless.

As noted above, we should do the same for `File` vs `SourceFileInfo`. There is no reason to have `File` in the api anymore since we introduced `SourceFileInfo`.

**Comment by fommil** [comment]
will probably be addressed by #1787 ... the One Analyzer Per Project epic is flagging up that we should really just rewrite a lot of this functionality to use the graph instead of the analyzer.
