### ISSUE TITLE
Framework for passive fixups

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-server#848]
Two aspects to this:
- A backend system for subscribing to interesting events, changes to particular AST fragments, looking at a certain type of file, etc, and then computing fixups.
  - A gui that gives a non-intrusive notification when fixups are available.
  - A gui for applying said fixups.

**Comment by fommil** [comment]
:+1: certainly important for Java... but even in Scala there are some obvious cases (like "implement this missing method").

For Java, I strongly recommend just re-using/borrowing the NetBeans API and implementations. Extremely useful stuff in there (I know, I wrote some of them :stuck_out_tongue: )

**Comment by fommil** [comment]
I'm actually keen for Java stuff to be a focus for post 1.0, so moving to that milestone so it doesn't get lost.

For post 1.0 my personal priorities are:

1. refactor protocol messages, marshalling and use WebSockets: will make it **really** easy to extend in the future and lowers the barrier to entry for new contributors.
2. really spend some time in the model/search layers to ensure we're passing around the correct Java and Scala names for everything (this affects Shapeless users a lot)
3. (unless it makes it into 1.0) type hierarchy browsing: "show me the implementations of this trait" stuff.
4. Java!
5. Spring! (ok, maybe that's pushing it...)

**Comment by aemoncannon** [comment]
+1 this will be a big quality of life improvement for me at work ;-)

**Comment by fommil** [comment]
@rorygraves this would work well for the "add type to public member" stuff we always want to implement

**Comment by rorygraves** [comment]
Sounds good to me!

**Comment by fommil** [comment]
relevant discussion in the emacs mailing list (for elisp passive cleanups) https://groups.google.com/d/msg/gnu.emacs.help/Oza4k-YpZk4/jazksyvgqmkJ

**Comment by VyacheslavMik** [comment]
IMHO, an override suggestions would be useful feature.
