### ISSUE TITLE
integrate with sbt-server

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#849]
@jsuereth @eed3si9n may have more to say. Initial thoughts are:

1. tighter feedback from the compiler (perhaps even better incremental compile)
2. notifications when the build definition has been reloaded ... recreate the .ensime and bounce the server transparently to the user.

**Comment by edani** [comment]
This would be nice. I miss C-c C-c e` showing actual compiler errors, the links from sbt-mode just aren't the same.

**Comment by fommil** [comment]
dupe of #384 (which was once an OMG Ponies and has a reasonable bounty on it!)
