### ISSUE TITLE
current snapshot doesn't work

### ISSUE THREAD

**Issue by codeck** [ensime/ensime-server#850]
ensime update fails always because lack of "testingempty" "testingsimple"  "testingdebug".
my env: scala 2.11.5 sbt 0.13.7 ensime 0.9.10-SNAPSHOT

**Comment by fommil** [comment]
Oh crap, I'll fix that asap.

**Comment by fommil** [comment]
This was an upstream bug in sbt https://github.com/sbt/sbt/issues/1888

I've worked around it, and pushed a new snapshot. Thanks for reporting!
