### ISSUE TITLE
Build stability 

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#856]
Still not using non parallel, but I found out how to do this. 

I get transients, even locally, in the emacs debugging test and this seems to hang the build a lot. 

A timeout out the emacs expectations would also be good.

**Comment by fommil** [comment]
```
JDK_HOME=/usr/lib/jvm/jdk-6-oracle-x64 JAVA_HOME=/usr/lib/jvm/jdk-6-oracle-x64/jre  TRAVIS=true test/run_emacs_tests.sh debug
```

results in

```
Received test event: :debug-event with value (:type output :body Exception in thread "main" java.lang.NoClassDefFoundError: scala/Predef$
	at test.Test$.main(Test.scala:7)
	at test.Test.main(Test.scala)
Caused by: java.lang.ClassNotFoundException: scala.Predef$
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at ja)
ENSIME: Asynchronous return could not find originating buffer.
Received test event: :return-value with value (:ok (:file /tmp/ensime_test_proj_27529EDo/src/main/scala/test/Test.scala :syms ((package 8 12) (param 38 42) (class 44 57) (val 69 70) (val 87 88) (val 105 106) (functionCall 120 127) (operator 134 135) (operator 130 131) (val 128 129) (val 132 133) (val 136 137))))
Server connection closed unexpectedly: connection broken by remote peer
```

**Comment by fommil** [comment]
(note, this is transient, and happens if I use the JAVA_HOME to be the jre or the jdk)

**Comment by fommil** [comment]
I tested a homebrew version of ensime-server with logging-to-file enabled and seen this:

```
Debugger VM args:  -classpath "/tmp/ensime_test_proj_20585Kmu/target/scala-2.11/classes:/tmp/ensime_test_proj_20585Kmu/test-target"
```

And I'm now amazed that this ever worked :smile: looks like a genuine bug (possibly in the emacs test) because the `.ensime` doesn't have the scala-library on its dependency list.

```elisp
(:root-dir "/tmp/ensime_test_proj_20585Kmu/" :cache-dir "/tmp/ensime_test_proj_20585Kmu/cache/" :name "test" :scala-version "2.11.5" :java-home "/usr/lib/jvm/jdk-6-oracle-x64" :subprojects ((:name "test" :module-name "test" :source-roots ("/tmp/ensime_test_proj_20585Kmu/src/main/scala/") :depends-on-modules nil :target "/tmp/ensime_test_proj_20585Kmu/target/scala-2.11/classes/" :test-target "/tmp/ensime_test_proj_20585Kmu/test-target/")))
```

btw, this is the same thing in ensime/ensime-emacs#97

**Comment by fommil** [comment]
I'm have a PR in to ensime-emacs to fix this, but we are getting exit 1, despite the tests returning 0.

I wonder if `Xvfb` is somehow getting in the way.

**Comment by fommil** [comment]
t'was a bug in emacs-24.4 by the looks of it. I'll use 24.3 on the ensime-server and a matrix of 24.{1,2,3} on ensime-emacs.

**Comment by fommil** [comment]
ha! And after all that, seems we're using an emacs-24.3 function `display-buffer-at-bottom` @edani any way of using something else in its place so we can only require 24.1 at a minimum?

**Comment by edani** [comment]
@fommil   OK I'll look into it.
