### ISSUE TITLE
Support emacs-24.1

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#861]
This upstream commit introduced `display-buffer-at-bottom` to emacs-24.3

https://github.com/emacs-mirror/emacs/commit/5938d5196d09aff887aa74603c102b1f303a613a

We're using that function, so it means that our minimum requirement is 24.3. It would be good to require at least 24.1, for some older machines (bear in mind that Ubuntu LTS is still on emacs23, which I doubt we can realistically support).

@edani @aemoncannon is this something we care about for 1.0, or should we close it it as `WontFix`?

**Comment by aemoncannon** [comment]
If this is the only thing blocking, then yeah, I think it's worth it.

**Comment by edani** [comment]
I'm trying to wade through the emacs 24 changes to see what's available... We could simply replace it with `display-buffer`
