### ISSUE TITLE
support emacs-24.4 in our tests

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#862]
Looks like emacs-24.4 `kill-emacs` doesn't actually work properly. It either hangs, or doesn't exit 0 as requested.

@aemoncannon any chance you could have a look at alternative ways of exiting from the tests?

**Comment by fommil** [comment]
I was originally suspicious of this upstream commit https://github.com/emacs-mirror/emacs/commit/7932d062cf85c2c37bd15b22be30a65c034001fc but actually I'm seeing quite a lot of hanging on travis when we try to exit. https://travis-ci.org/ensime/ensime-emacs/builds/52804848

I wonder if perhaps we have a race condition to exit the tests.

**Comment by fommil** [comment]
e.g. https://travis-ci.org/ensime/ensime-emacs/jobs/52804849 has "Finished suite with status 0" about halfway down.

**Comment by fommil** [comment]
`kill-emacs` might be a wild goose chase. A bigger problems seems to be that our tests just hang at the end.

@aemoncannon would it be hard to put a timeout limit on the async emacs tests? And do you have any ideas why the logic to exit might not be kicking in?

**Comment by fommil** [comment]
another build where it exits 1: https://travis-ci.org/ensime/ensime-emacs/jobs/52813805

so maybe there was a regression in kill-emacs that we have to workaround. Maybe we have to bleed stdin before exiting?

**Comment by aemoncannon** [comment]
hmm.. i wonder if our kill-emacs hook (recently introduced) could be
causing issues.

**Comment by fommil** [comment]
ooh, that sounds suspicious indeed

**Comment by fommil** [comment]
nope, that didn't seem to help emacs24 https://travis-ci.org/ensime/ensime-emacs/builds/52856527

**Comment by aemoncannon** [comment]
assuming you didn't mean to close?

**Comment by fommil** [comment]
I did, but then it started failing again, so it is right to open again.

**Comment by fommil** [comment]
I narrowed this down to the `ensime-update` function. Patch the tests so they run quicker with this:

```
diff --git a/ensime-test.el b/ensime-test.el
index a2671a7..9061a49 100644
--- a/ensime-test.el
+++ b/ensime-test.el
@@ -1974,8 +1974,8 @@
    (lambda() 
      (ensime-run-suite ensime-fast-suite)
      (setq ensime--test-exit-on-finish ensime--test-exit-on-finish--old)
-     (when (and ensime--test-had-failures ensime--test-exit-on-finish)
-       (kill-emacs 1))
+;;     (when (and ensime--test-had-failures ensime--test-exit-on-finish)
+       (kill-emacs 1);)
      (ensime-run-suite ensime-slow-suite))))
 
 (defun ensime-run-one-test (key)
```

I've had trouble with the bisecting, doing another run.

**Comment by fommil** [comment]
FYI this is the bisect script, might be useful again

```bash
#!/bin/bash

# assumes running in emacs git repo

EMACS_DIR=$PWD/../ensime-emacs/emacs

rm -rf $EMACS_DIR

git clean -xfd

./autogen.sh
./configure --prefix=$EMACS_DIR
make || exit 125 
make install

if [ ! -f "$EMACS_DIR/bin/emacs" ] ; then
    echo "HACK: emacs build was borked"
    exit 125
fi

cd $EMACS_DIR/..

TRAVIS=true EMACS=$EMACS_DIR/bin/emacs test/run_emacs_tests.sh

RET=$?

killall Xvfb

exit $RET
```

git bisect start emacs-24.4 emacs-24.3
git bisect run ../ensime-emacs/bisect-script.sh

**Comment by fommil** [comment]
this seems to have been solved when running on shippable. I have no idea why.
