### ISSUE TITLE
RFC: inspector interface changes

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-server#865]
Currently we have a 'doc' link for types, where docs are available. And members themselves are linked to docs. This is inconsistent, and doesn't leave much room in the UI for source-code links. Proposal:

* Don't put any explicit links to docs or sources in the inspector. All hyperlinks are intra-links.
* Bind M-. to go to source, and C-c C-v d for docs.
* Display a (message ..) on entering inspector that explains the bindings.

Thoughts? It's a little more hidden, but consistent with general usage, and there will be less visual noise.

**Comment by edani** [comment]
That would work I think. Note, the current behavior on methods is for <RET> to link to the source code and fall back on doc if there's no source. It looks like the source code availability broke within the past few weeks so it always links to the docs.

**Comment by aemoncannon** [comment]
Done.
