### ISSUE TITLE
emacs tests matrix on scala 2.9/2.10

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#866]
I just tried running the tests on scala 2.10 and (after fixing a typo) they run but exit 1. Needs some TLC.

We should really get this pipeline in place for 1.0.

**Comment by aemoncannon** [comment]
Agreed

**Comment by fommil** [comment]
I think 2.10 is failing because of a problem in the server, not the emacs tests, so I'll try and address this when next rebasing.

**Comment by fommil** [comment]
This issue was moved to ensime/ensime-emacs#163
