### ISSUE TITLE
Add a variant of rpcGetMemberByName that accepts fqn, member name, member type

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-server#868]
As it exists, the rpcGetMemberByName call is not capable of uniquely identifying an overloaded member. Follow the example of rpcGetDocUriByName and accept fqn, member name, member type id. This will allow us to pinpoint the right sourcecode in the inspector.

Related: make this call package-aware. This will fix the package browsing in inspector.

Also: refactor rpcGetDocuriByName to use the new rpcGetMemberByName internally : )

**Comment by edani** [comment]
When I added rpcGetMemberByName, my goal was to rely less on type IDs, because it's now easier to restart the presentation compiler which blows the type IDs away.  What would you think of passing the type's string representation, the one that's used in doc URLs ?

**Comment by aemoncannon** [comment]
@edani Hmm, yeah I think that would work. We'd have to return 'signatureString' for each member when inspecting, so we'd have it on hand. Could adapt rpcDocUriForSymbol, and perhaps rpcCallCompletionInfo as well, to use this approach.

**Comment by aemoncannon** [comment]
I wonder if there's a more succinct way of identifying an overload. Is there a natural ordering on overloads? If so, we could just return the index.

**Comment by fommil** [comment]
I'm looking into similar matters in #1153

**Comment by jozi-k** [comment]
I wanted briefly to look at code in this issue but could not find `rpcGetMemberByName` method. Can you please update the issue description?

**Comment by fommil** [comment]
Drop the rpc, have a look in the incoming.scala file. Btw if you're looking for ideas, the 2.0 milestone might be better
