### ISSUE TITLE
Failure in launching Scala REPL for a Play project

### ISSUE THREAD

**Issue by kindoblue** [ensime/ensime-server#870]
On Mac Yosemite 10.10.2, Emacs 24.4.1, after a successful launch of Ensime (from Elpa ensime-20150305.651)

I tried to run the scala REPL (C-c C-v z). I got an error message back:

    Wrong type argument: stringp, ("/Users/ice/.ivy2/cache/com.google.code.findbugs/jsr305/jars/jsr305-2.0.3.jar" "/Users/ice/.ivy2/cache/com.typesafe.play/build-link/jars/build-link-2.3.8.jar" "/Users/ice/.ivy2/cache/com.typesafe.play/play-ws_2.11/jars/play-ws_2.11-2.3.8.jar" <<a lot of jars>>...) 

This is happening in `start-file-process`, at the line

    (apply 'start-process name buffer program program-args)

With arguments from edebug listed as

    Result: "ensime-inferior-scala"
    Result: #<buffer *ensime-inferior-scala*>
    Result: "scala"
    Result: ("-classpath" ("/Users/ice/.ivy2/cache/com.google.code.findbugs/jsr305/jars/jsr305-2.0.3.jar" "/Users/ice/.ivy2/cache/com.typesafe.play/build-link/jars/build-link-2.3.8.jar" "/Users/ice/.ivy2/cache/com.typesafe.play/play-ws_2.11/jars/play-ws_2.11-2" <<A LOT OF JARS>>))

scala is in the path and it seems to me `start-process` fail because the program-args is very long (around 9500 chars) but I don't think that is the problem.

**Comment by fommil** [comment]
yeah, this is known #642 . Just use the `console` from `sbt-mode`

**Comment by tonylotts** [comment]
I get this error also, in a non-play scala project.

**Comment by tonylotts** [comment]
My error was related to the .ensime file as generated by sbt-ensime 1.5.  
:source-roots contained "/src/main/java", removal fixed the issue.

I'm not sure why that was added, there's no java in the project. :smile:
I'm using scala 2.11.6 if that helps.

**Comment by fommil** [comment]
Directories get created when ensime starts, you must have deleted it
