### ISSUE TITLE
Audit performance

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-server#872]
I've started to notice the compiler getting backed up with calls to semantic highlighting. Wondering if there's any low-hanging perf. fruit here.

**Comment by fommil** [comment]
yeah, I'm seeing that as well sometimes. I wonder if we get caught in a spin loop or something.

I have a YourKit license at work, I might investigate starting up with the profiling agent attached when I'm noticing this sort of thing.

**Comment by aemoncannon** [comment]
Two things I can rule out:
  * it's not reading the file over the socket (we actually don't do that for this call)
  * it's not a problem with slow serialization (i truncated the symbol list before serialization)


I just saw it tick through 15 out of 20 highlighting items rather slowly, then stall for several seconds, then finish a couple more, then time out the rest. Something funky going on.

**Comment by aemoncannon** [comment]
More learnings:
* the call to askLoadedTyped is by far the biggest time sink. times vary wildly from 4ms to 17,000ms
* seems to be strong correlation between particular source files and time to load type tree.
* SwankProtocolConversions is an offender (15, 16 seconds for initial type)

Working theory: fancy type shenanigans make pres compiler sad.

**Comment by fommil** [comment]
`SwankProtocolConversions`? wow, maybe we're serialising something humongous?

The new marshalling should be super fast --- if we could capture an entire user session I'd really like to use that data for profiling. If there is anything slowing it down, I'm sure it can be improved.

**Comment by aemoncannon** [comment]
I didn't explain clearly: just *typing* the file takes the 15 secs. All
time spent in pres comp

**Comment by aemoncannon** [comment]
Maybe all the implicits?

**Comment by aemoncannon** [comment]
My working theory:  the sluggishness I've noticed lately is actually a
function of the project I'm editing.. ensime itself. We have a lot of
requests (background typechecks, background semantic highlighting) that are
fighting with foreground requests (completion) for limited Analyzer
bandwidth -- and recently the Analyzer got a lot more busy : )

**Comment by aemoncannon** [comment]
Related: would it be crazy to have multiple compiler instances?

**Comment by edani** [comment]
I was thinking the other day: for completion, we should only have to re-typecheck when the user starts a new word, not after every keystroke in the middle of a word.

**Comment by aemoncannon** [comment]
not sure what the on-idle type checking is doing. company should only make
one request at the beginning of the word for completions (unless you
backtrack)

**Comment by edani** [comment]
So much for my theory then.

the idle type checking should normally reload the current buffer and re-typechecks it. It shouldn't fire more than once every 2 seconds (user configurable).

Also, the semantic highlighting runs just after the idle typechecking and shouldn't cause the pres-compiler to re-typecheck the file, it should piggyback on the result of the previous typecheck. But I now realize that I never verified this.

**Comment by aemoncannon** [comment]
hmmm, the typechecking is passing source over the socket right? and correct
me if im wrong but i don't think sem-high is, so would that mean that
sem-high is loading stale source and force a re-type?

**Comment by aemoncannon** [comment]
or does sem-high write the buffer...

**Comment by edani** [comment]
sem-high, the way the emacs client calls it, calls createSourceFile(File)  which shouldn't cause anything to be re-typechecked... unless I'm mistaken.  Actually if it did re-typecheck the source file from disk we'd see plenty of sem-highlighting weirdness so now I'm 90% sure that it does the right thing...

**Comment by fommil** [comment]
multiple presentation compilers is not so crazy... we'd need it for true multi-module support

**Comment by fommil** [comment]
what's the cost of using overlays vs using faces?

**Comment by aemoncannon** [comment]
Probably no prob to use faces.. But can we hide that from font lock is
another question...

**Comment by aemoncannon** [comment]
This turns out to be a broader issue than just semantic highlighting. Interactivity goes completely out the window for SwankProtocolConversions.scala. Completion is impossible. Semantic highlighting takes forever and blocks everything else.

I've been scratching my head about this, because it seems a real shame that ensime chokes on ensime, but I don't see a good solution. The best I can think of is to maybe track 'problem' sources and disable all passive RPCs for these units.

Thoughts?

p.s. The real problem here is that any unit could take multiple seconds to typecheck. Seriously, wtf Scala?

**Comment by rorygraves** [comment]
I've come across this before  - implicits esp can trigger terrible compiler performance (and it varies wildly).
Yeah its really mot clear how to address this - I like the idea of the tracking.  I'm also going to put together a test case using the analyser stuff I've been working on, and then maybe I can revisit some of the profiling I was doing with @milessabin and see if we can get some direct speedups.

**Comment by aemoncannon** [comment]
@rorygraves Cool. At the least I'd be fascinated to know what the compiler is doing during all those seconds.

In the short term, what do you think of using a file-local variable to suspend passive operations for a particular file? http://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html#Specifying-File-Variables

E.g.
If ensime-suspend-all-passive-rpcs is set, disable semantic highlighting, typechecking, and completion-as -you-type for that file.

**Comment by rorygraves** [comment]
That makes sense to me.

**Comment by rorygraves** [comment]
I as about to spend add a ticket to analyse this, and then found this one.
So we are fundamentally a veneer on top of the presentation compiler.  A couple of evenings sessions highlighted some items (pretty much all within the presentation compiler), that could provide significant improvements in highlighting and general performance. (6.5 seconds to generate symbols for a file with lots of implicits)

E.g. (Really an aide-memoir for later)
* ```scala.collection.mutable.ArrayOps$ofRef.<init>(Object[]) ArrayOps.scala``` called from ```scala.reflect.internal.util.WeakHashSet.tableLoop$1(int, WeakHashSet$Entry[]) WeakHashSet.scala``` to lift an array to an ArrayOps to call an implicit ```.size``` instead of calling ```.length``` (created 52,000 times in my short sample)

* ```scala.reflect.internal.Types  - lubDepthAdjust - Depth``` (created 114,000 instances in my trace) - this is a boxing issue.

* The frightening ```scala.reflect.internal.Symbols$Symbol.nameString()``` which generates classnames by walking the heirarchy generating StringBuffers at each level to build fragments. My favourite bit is the fun comment ``` /** TODO - find some efficiency. */``` in Names.scala.  

The list goes on.  I'm going to assign this to myself and part it until after ScalaDays.  I think there are some huge wins here within the compiler which benefits everybody

**Comment by aemoncannon** [comment]
Go, Rory!

**Comment by fommil** [comment]
I used the `(profiler-start)` and `(profiler-report)` stuff yesterday for the first time, it's pretty impressive. You could easily add the start to the test dotfile and an `quit-emacs-hook` to dump out the report. Would be interesting!

**Comment by aemoncannon** [comment]
It really is nice. Root-causing editing lag used to a real challenge -- now
trivial.

**Comment by fommil** [comment]
some specific memory problems raised as tickets in the last few weeks (TL;DR it's all VFS's fault!)
