### ISSUE TITLE
include ensime-startup.el in coverage

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#875]
We are currently excluding `ensime-startup.el` from the coverage runs (see `dotemacs_test.el`). If we include it, the tests just hang with 

```elisp
Using ensime-test-dev-home of /home/travis/build/ensime/ensime-emacs/
Wrong type argument: stringp, nil
```

@sviridov (apologies for pulling you in if you'd rather not be) do you have any advice on how we could find the problem and fix it in our code? Our repo is https://github.com/ensime/ensime-emacs

**Comment by sviridov** [comment]
@fommil Ok, I will fork it and make some experiments.

**Comment by fommil** [comment]
:smile: actually our coverage is kinda broken anyway in master. I have a fix ready in my branch, should be merged in the next few minutes.

**Comment by fommil** [comment]
@sviridov  apologies in advance because this involves a lot of automatic downloading of Java  / Scala jars that will probably be completely irrelevant to you other than this bug report. But I'll explain to you what is happening and how to clean up afterwards.

If you clone our repository

git clone --depth 1 https://github.com/ensime/ensime-emacs

you can run the tests with

  test/run_emacs_tests.sh

That will create a clean-room emacs.d just for the tests and contact MELPA to download our dependencies.

HOWEVER, you will also need to have a working JDK and the `sbt` script in your PATH. 1) Use your package manager to install something like `openjdk-6-jdk` 2) obtain https://github.com/paulp/sbt-extras/blob/master/sbt and place it on your PATH.

To explain: ENSIME is a bit like SLIME. There is a server component
which runs a Scala compiler in-process. Scala runs on the JVM and we
piggy-back off the SBT build tool for dependency management. Lots of
files are being downloaded and being placed into your `~/.ivy` and
`~/.sbt` folders as a result. For the typical Scala developer, this will
already have been populated because its part of their dev environment.

**Comment by fommil** [comment]
@sviridov master is good again, please rebase

**Comment by sviridov** [comment]
@fommil I found a problem. 

`undercover.el` is heavily based on `edebug`. And `edebug` has some problems with `ensime--select-server-version` function ([here](https://github.com/ensime/ensime-emacs/blob/master/ensime-startup.el#L252)). `edebug` replacing function declaration with his own. Most of the time it's ok but not in this case.  `edebug` considers "0.9.10-SNAPSHOT" as docstring and not as returning value. So, after replacing, `ensime--select-server-version` will return `nil`.

**Comment by fommil** [comment]
Cool! Great find. We can replace that function with a defcustom
