### ISSUE TITLE
Generated .ensime does not contain "provided" jars

### ISSUE THREAD

**Issue by sutram** [ensime/ensime-server#877]
I am getting errors from Ensime and narrowed it down to two jars and their associated dependencies. I assume, these jars don't show up in the generated .ensime because I am using "provided" to keep them out of the final assembly jar.

Part of my build.sbt. The .ensime file does not contain the first two or their associated dependencies.

libraryDependencies ++= Seq(
  "org.apache.spark" % "spark-core_2.10" % "1.2.1" % "provided",
  "org.apache.spark" % "spark-streaming_2.10" % "1.2.1" % "provided",
  "org.apache.spark" % "spark-streaming-kafka_2.10" % "1.2.1",
  "io.druid" % "druid-indexing-service" % "0.6.164" exclude("org.slf4j", "slf4j-log4j12") exclude("log4j", "log4j") exclude("org.hyperic", "sigar") exclude("net.java.dev.jets3t", "jets3t") force(),
  "io.druid.extensions" % "druid-histogram" % "0.6.164" exclude("org.slf4j", "slf4j-log4j12") exclude("log4j", "log4j") exclude("org.hyperic", "sigar") exclude("net.java.dev.jets3t", "jets3t") force(),
    "io.druid.extensions" % "druid-kafka-eight" % "0.6.164" exclude("org.slf4j", "slf4j-log4j12") exclude("log4j", "log4j") exclude("org.hyperic", "sigar") exclude("net.java.dev.jets3t", "jets3t") exclude("org.apache.kafka", "kafka_2.9.2") force(),
  "com.metamx" % "tranquility_2.10" % "0.3.2" exclude("net.java.dev.jets3t", "jets3t"),
  "com.yammer.metrics" % "metrics-core" % "2.2.0",
  "org.apache.avro" % "avro" % "1.7.7" force()
)

**Comment by fommil** [comment]
if you have a look in the `ensime-sbt` repo you'll probably be able to fix this quite easily.

As a workaround, I recommend using exclusion rules in your `assembly` packager to decide what is/isn't relevant for bundling. And if you're using `assembly`, make sure that you're obliging the open source licenses of everything you're bundling because not all OSS licenses allow this.

**Comment by sutram** [comment]
So changing https://github.com/ensime/ensime-sbt/blob/bf43c9cf04b4618058ab329632b213fd00998b30/src/main/scala/EnsimePlugin.scala#L148 to:

val filter = ""

should do the trick?

I am not sure why "provided" should exclude the jar from .ensime since those jars are still needed for compilation.

Thanks

**Comment by fommil** [comment]
I don't think that's relevant for you. This filter is only for projects that are sbt plugins. You need to add the provided phase to the calculation of `mainJars`

**Comment by fommil** [comment]
uuugh, I had a look and I have no idea how to do this because sbt basically has the most insanely ~~complicated~~ obfuscated API on the planet. Your best chance of getting this to work is to ask on the sbt mailing list and then send us a PR with a fix, because I usually prefer to be poked in the eye with a laser than to have to touch the SBT code.

**Comment by fommil** [comment]
although maybe you're right... maybe `provided` should always be included. Can you try with a `publishLocal` removing the `filter` and replacing all references to it with the string `provided`?

**Comment by sutram** [comment]
@fommil I changed that line to val filter = "provided" and it worked.

Thanks

**Comment by sutram** [comment]
Though I assume that changing

val mainJars = jarsFor(Compile) ++ unmanagedJarsFor(Compile)
to
val mainJars = jarsFor(Compile) ++ unmanagedJarsFor(Compile) ++ jarsFor(Provided)

is a better approach and this works too.

**Comment by fommil** [comment]
Oh cool, I didn't know that Provided (with a capital) was a thing. 

Would you like to have a think about this and send us a PR? It feels dirty the have the filter AND a different phase, so it would be good to pick one only.

**Comment by sutram** [comment]
Please review this pull request:

https://github.com/ensime/ensime-sbt/pull/83
