### ISSUE TITLE
Lots of CPU being spent on reading from socket ( dominates server cpu usage )

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-server#879]
Profile captured while doing a few completions.

I don't notice anything suspicious about the read loop. The stream is buffered. My guess is that I'm seeing the cost of reading the file multiple times.

![image](https://cloud.githubusercontent.com/assets/7484/6549973/4aaf3cf0-c5eb-11e4-85a3-fe8362ff659f.png)

**Comment by fommil** [comment]
This might be an artefact. When doing profile runs I often ignore socket reads and folk join internals because it seems the confuse the profiler.

**Comment by aemoncannon** [comment]
@fommil Fair. But *something* is making things noticeably more sluggish.
I'm seeing a lot more completion timeouts than I have in the past. I'm
going to do some experimentation.

**Comment by fommil** [comment]
hmm, if there is no log in the server side then maybe hunt for work in `Future`s... they swallow exceptions.

**Comment by aemoncannon** [comment]
Duplicat eof #872
