### ISSUE TITLE
C-c C-c is undefined

### ISSUE THREAD

**Issue by raboof** [ensime/ensime-server#880]
Since this morning's `M-x ensime-update`, `C-c C-c` no longer seems to work.

`M-x ensime` does lead to a 'welcome message'. Doing it again leads to a 'Connected to ENSIME, please wait until the project is loaded'.

**Comment by fommil** [comment]
`C-c C-c` isn't one of ours... https://github.com/ensime/ensime-server/wiki/Emacs-Command-Reference#presentation-compiler what are you expecting it to do?

**Comment by raboof** [comment]
Ah, found it at https://github.com/ensime/ensime-server/wiki/Quick-Start-Guide#starting , didn't realize it's more general than ensime.

While not strictly an ensime issue, any clue why it's not available? I know it worked before (and provided me with the scala errors)

**Comment by fommil** [comment]
I have this bound, which sounds like it's what you're looking for to jump to sbt compile errors

https://github.com/fommil/unix/blob/master/.emacs#L381

Maybe we bound `C-c C-c` in a really old version of ENSIME, I don't know. If you bind `C-c C-c` you'll lose all the prefix commands and you'll have to rebind them.

**Comment by raboof** [comment]
PEBKAC: you have to be in a buffer that contains a .scala file for `C-c C-c a` to work, I missed that. Sorry about the noise :)

**Comment by fommil** [comment]
you can add the mode to any buffer you want, but yes it's not on by default :smile:
