### ISSUE TITLE
Example .ensime file references ensime-default-java-home

### ISSUE THREAD

**Issue by rolandtritsch** [ensime/ensime-server#885]
Hi all,

the example .ensime file references ensime-default-java-home and says you can use :java-home to override it.

Just grep-ed the code and can't find ensime-default-java-home.

Means either the variable is missing or the doc is wrong.

Ideas?

Regards ...
    Roland

**Comment by rolandtritsch** [comment]
This is a duplicate of #826 and the doc says that :java-home is required. But it also seems to suggest that you can either use :java-home or ensime-default-java-home (which is clearly not the case). Means ... the doc should probably read ...

;; :java-home (required ; emacs) specifies the JAVA_HOME environment when launching ENSIME or a sbt session.

**Comment by fommil** [comment]
which docs talk about the emacs setting? I thought that was all removed.

**Comment by rolandtritsch** [comment]
https://github.com/ensime/ensime-server/wiki/Example-Configuration-File

**Comment by fommil** [comment]
@rolandtritsch cool, thanks for catching that. I've updated the docs.

Thanks for the gradle plugin! I'd recommend that you watch the `ensime-sbt` repo for changes and, more importantly, this file https://github.com/ensime/ensime-server/blob/master/api/src/main/scala/org/ensime/config/EnsimeConfig.scala

If anything breaks, check the history of that file first of all. The case class structure defines the S-Exp format that we accept. I'll try to remember to cc you in PRs if we change it. It is unlikely to change in until after 1.0. The most recent change was probably the addition of `doc-jars`.

**Comment by rolandtritsch** [comment]
Hi Sam, thanks. Got it. - RT

On 14 March 2015 at 13:20, Sam Halliday <notifications@github.com> wrote:

> @rolandtritsch <https://github.com/rolandtritsch> cool, thanks for
> catching that. I've updated the docs.
>
> Thanks for the gradle plugin! I'd recommend that you watch the ensime-sbt
> repo for changes and, more importantly, this file
> https://github.com/ensime/ensime-server/blob/master/api/src/main/scala/org/ensime/config/EnsimeConfig.scala
>
> If anything breaks, check the history of that file first of all. The case
> class structure defines the S-Exp format that we accept. I'll try to
> remember to cc you in PRs if we change it. It is unlikely to change in
> until after 1.0. The most recent change was probably the addition of
> doc-jars.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ensime/ensime-server/issues/885#issuecomment-80460541>
> .
>



-- 
e: roland@tritsch.org
m: +353-86-8563975
s: rolandtritsch
---
http://trits.ch/rt-qr-code
http://trits.ch/rt-linked-in
http://www.tritsch.org
