### ISSUE TITLE
investigate hanging emacs tests

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#886]
it seems to be that when travis boxes are under strain, our emacs tests hang.

I don't think it's coincidence that they always hang following a server shutdown:

```
...
Server connection closed unexpectedly: connection broken by remote peer
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
```

I wonder if we perhaps have a race condition in our tests

**Comment by fommil** [comment]
hmm, looks like the connection to the server dies before we get the `:indexer-ready` event.

As a quick hack, I'm going to reduce the work needed in the tests by optionally indexing the `rt.jar` file. That should mean that `indexer-ready` arrives a lot quicker in the emacs integration tests.

**Comment by aemoncannon** [comment]
I used to just disable indexing entirely for most tests (there was config
flag for it). Seemed to help.

**Comment by fommil** [comment]
@aemoncannon we need the scala indexing for some of the tests, e.g. search/importing. But we're now just using a minimal scala-library config so it shouldn't be too onerous.

**Comment by edani** [comment]
Would it be a good idea to cache the index in the first test and reuse it in subsequent one?

**Comment by fommil** [comment]
@edani yes, it would be ridiculously sensible to do that. doh!

In fact, it would have been infinitely easier to do that than the crappy hack I came up with.

**Comment by fommil** [comment]
these seem to have gone away when moving to shippable
