### ISSUE TITLE
popup docs

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#888]
it would be awesome if the docs for a method (or, I suppose class) popped up when the user has a completion choice.

Similarly, being able to do this statically on a class or method would be amazing. I must admit, when I used IntelliJ I didn't tend to use this in Scala, but when I was using Java it was an absolute must. With the Java goal in mind, I'm adding this to the TNG milestone.

**Comment by aemoncannon** [comment]
We just need an rpc that:
* looks up doc uri for symbol
* downloads that html
* scrapes the text
* maybe strip, or interpret, html tags
* return the chunk

Then I can hook that up to company's help system.

**Comment by fommil** [comment]
cool, who added the bounty? (it says me, but that's just the bountysource plugin being crap)

**Comment by aemoncannon** [comment]
Twas i

**Comment by fommil** [comment]
btw, in Emacs this would be best implemented with `company-quickhelp-mode` https://github.com/expez/company-quickhelp

**Comment by ancane** [comment]
:+1:

**Comment by noelmarkham** [comment]
I'm hoping to take a look at this over the Christmas break and into the New Year. Just checking I'm not treading on any toes here?

**Comment by fommil** [comment]
Awesome! Not sure what my response time is going to be like over Xmas but I'll try to answer any questions you ask... eventually.

**Comment by noelmarkham** [comment]
Same :)

**Comment by fommil** [comment]
I wrote a regex in paranamer (javadocs implementation) that might be useful for you on the server side.

**Comment by noelmarkham** [comment]
Sounds good - any work/help welcomed!
