### ISSUE TITLE
Travis => Shippable

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#889]
It very nearly worked https://github.com/Shippable/support/issues/1159

The awesome thing is that they allow custom Docker images! I'm not sure of the machine specs: a Travis container is 4GB RAM with a CPU made out twigs, shippable is ???.

**Comment by fommil** [comment]
right now, I'm wondering why the hell we ever used travis in the first place... shippable is amazing!

**Comment by fommil** [comment]
and docker is just amazeballs, I'd only ever heard of it before https://docs.docker.com/installation/debian/

**Comment by fommil** [comment]
oh: ```Custom images may only be used with dedicated hosts. No initialized dedicated host was found for subscription ensime.```. That's dead then.

**Comment by fommil** [comment]
OMG OMG OMG, $12/year.... ![shut up and take my money](http://i3.kym-cdn.com/photos/images/newsfeed/000/264/241/9e9.gif)

**Comment by aemoncannon** [comment]
nice!

**Comment by fommil** [comment]
@aemoncannon @rorygraves @edani I just bought us a year with these guys, I'll try to get it all setup today and be done with private jenkins/travis for good.

```
5 build minions!
999 private projects.
5GB of server storage.
90 minute build timeout.
5 foreign hosts
Use custom docker images for builds.
Customize build timeout durations.
```

**Comment by aemoncannon** [comment]
so cool! I owe you a beer

**Comment by fommil** [comment]
haha, definitely. Are either you or eric ever in London? I think we owe **you** the beer.

**Comment by aemoncannon** [comment]
Occasionally for work. Will ping you next time : )

**Comment by edani** [comment]
@fommil  I'm afraid not... but thanks a bunch for setting this up!

**Comment by ttrahan** [comment]
@fommil super excited that you've found the wonders of Shippable.  let us know if you'd like any assistance evaluating what it takes to set up a dedicated host in order to use our Docker Build feature.  Happy shipping!

**Comment by fommil** [comment]
thanks @ttrahan !

I'm trying to use `debian:jessie` but seeing this:

```
HTTPConnectionPool(host='127.0.0.1', port=4243): Max retries exceeded with url: /v1.15/images/create?tag=jessie&fromImage=debian (Caused by <class 'socket.error'>: [Errno 111] Connection refused): Traceback (most recent call last):
  File "/home/shippable/dpd/step_listener.py", line 99, in handle_message_callback
    self.execute_step(build_plan, current_step, False)
  File "/home/shippable/dpd/step_listener.py", line 165, in execute_step
    raise e
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4243): Max retries exceeded with url: /v1.15/images/create?tag=jessie&fromImage=debian (Caused by <class 'socket.error'>: [Errno 111] Connection refused)
```

am I asking for the wrong image or is there something wrong with our dedicated host(s)?

**Comment by fommil** [comment]
also @ttrahan is it normal for a deploy job to take 45 mins+?

**Comment by ttrahan** [comment]
hi @fommil - that sounds too long.  There are likely some adjustments needed.  I'm going to ask one of our engineers to review your situation, including the issue you're having above with the ConnectionError.  If you don't mind, I'll also move these two issues over to our support repo to get it connected with our engineers.  More to come soon.

**Comment by fommil** [comment]
@ttrahan that's fine, just make sure you reference me so I can track it.

I killed the hung deploy job and it finished fine the second time, most likely an environmental transient.

**Comment by fommil** [comment]
all 4 cross builds of emacs running on Rory's machine at the same time right now, muahahaha! If everything is looking good, I'll merge later.

I've taken my machine off the dedicated network as I'm not entirely sure if it can be run on two accounts at the same time: https://github.com/Shippable/support/issues/1195

**Comment by fommil** [comment]
it is done! Thank Stallman for that, now I can start to write some actual code instead of being a devops :monkey:

Coverage reports are still waiting on a few upstream bugs. @rorygraves is looking into that.
