### ISSUE TITLE
typelevel CoC

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#890]
There was recently some discussion about how the existence of a Code of Conduct has been a differentiator for people wanting to choose a project to contribute to. Perhaps we should make the necessary documentation updates to use the TypeLevel one http://typelevel.org/conduct.html

**Comment by aemoncannon** [comment]
+1

**Comment by fommil** [comment]
https://github.com/ensime/ensime-server/wiki/Code-of-Conduct I'll link from README shortly.

**Comment by rorygraves** [comment]
Cool.
