### ISSUE TITLE
Questions regarding Ensime Debugger

### ISSUE THREAD

**Issue by rcsenkbeil** [ensime/ensime-server#898]
So, I found this old video demonstrating the early debugger support in Ensime: https://www.youtube.com/watch?v=v7-G6vD42z8

I was hoping to get a few questions answered before diving into Ensime. :)

First, from scanning your code, did you guys move from using `jdb` to the Java-based `JDI` interface?

Second, from what the video showed, does this mean that Ensime's debugging support can transform the compiled JVM code back into Scala so you can analyze the stack correctly (as you do in the video) and step through breakpoints? In other words, if Scala generates multiple lines of Java, does the Ensime debugger handle that? Doesn't Scala also generate methods for `val` declarations instead of fields as well? Do things like _traits_ in Scala get translated correctly back in the debugger?

Third and last, does the Ensime debugger support stepping into and analyzing the stack frames of closures such as inline anonymous functions?

These kinds of powerful features come bundled with much more heavyweight IDEs like IntelliJ and the Eclipse-based ScalaIDE. So, I was wondering what kind of support Ensime (in its current state) has.

**Comment by aemoncannon** [comment]
Responses inline

On Fri, Mar 20, 2015 at 5:48 PM Chip Senkbeil <notifications@github.com>
wrote:

> So, I found this old video demonstrating the early debugger support in
> Ensime: https://www.youtube.com/watch?v=v7-G6vD42z8
>
> I was hoping to get a few questions answered before diving into Ensime. :)
>
> First, from scanning your code, did you guys move from using jdb to the
> Java-based JDI interface?
>
Yes.

> Second, from what the video showed, does this mean that Ensime's debugging
> support can transform the compiled JVM code back into Scala so you can
> analyze the stack correctly (as you do in the video) and step through
> breakpoints? In other words, if Scala generates multiple lines of Java,
> does the Ensime debugger handle that? Doesn't Scala also generate methods
> for val declarations instead of fields as well?
>
We just use the line numbers as they appear in the .class files. We don't
do any fancy footwork to make Scala debugging more friendly. Though, IMO,
it works well.

> Third and last, does the Ensime debugger support stepping into and
> analyzing the stack frames of closures such as inline anonymous functions?
>
Yes. As far as the JVM is concerned these are just methods of synthetic
classes, so it should work fine.

> These kinds of powerful features come bundled with much more heavyweight
> IDEs like IntelliJ and the Eclipse-based ScalaIDE. So, I was wondering what
> kind of support Ensime (in its current state) has.
>
We just need a motivated contributor to take the reigns ;- )

**Comment by fommil** [comment]
(closing as a question, but please continue discussion here!)
