### ISSUE TITLE
Inspecting object when debugging

### ISSUE THREAD

**Issue by muhmud** [ensime/ensime-server#905]
Hi,

When using ensime to debug and inspect an object variable, I only get "Instance of XXX", without being able to drill in any further. If I step into a method of the object, I can then inspect it.

It is possible to inspect such a variable further without actually stepping into it's code?

Thanks, and fantastic project!

Muhmud.

**Comment by fommil** [comment]
`C-c C-d i` inspect value.

**Comment by muhmud** [comment]
Sweet! Will try it out so as I can :) 


Sent from my Samsung device

-------- Original message --------
