### ISSUE TITLE
Getting a 'Malformed ....' error when requesting debug value at array index

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-server#907]
(try inspecting argv)

00:05:46.051 [default-akka.actor.default-dispatcher-62] INFO  o.e.s.protocol.swank.SwankProtocol - Received msg: (:swank-rpc (swank:debug-value (:type element :object-id 1134 :index 0)) 52)
00:05:46.051 [default-akka.actor.default-dispatcher-62] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:return (:abort 202 "Malformed swank:debug-value call: (swank:debug-value (:type element :object-id 1134 :index 0))") 52)

**Comment by rorygraves** [comment]
This is probably my changes to the debugger parsing code and extraction.
Its expecting a quoted object id:
```
(:swank-rpc (swank:debug-value (:type element :object-id 1134 :index 0)) 52)
```
vs (the working): 
```
: (:swank-rpc (swank:debug-value (:type element :object-id "1134" :index 0)) 52)
```

All of the debug location extractors look like they are expecting the same thing.
I propose we update the lisp to match (as its an identifier rather than a long value).
Need to check all the other uses of ```:object-id```

**Comment by aemoncannon** [comment]
Hmm, I'd be surprised if we actually do any interpretation of this value in lisp; it should just round-trip it. I wonder if the server is passing out longs somewhere.

I'm guessing this is also the root cause of #905

**Comment by rorygraves** [comment]
Thats easily possible (that we pass it back out as a long) - going to take a look.

**Comment by rorygraves** [comment]
Yep - you are right: https://github.com/ensime/ensime-server/blob/master/server/src/test/scala/org/ensime/server/protocol/swank/SwankProtocolConversionsSpec.scala#L51

Will rebase by DebugThreadId changes later on and add  a DebugObjectId to address this.

**Comment by aemoncannon** [comment]
Radical

**Comment by fommil** [comment]
is this still happening?

**Comment by fommil** [comment]
oh, I think we caught all these.
