### ISSUE TITLE
ensime-default-server-port is not defined

### ISSUE THREAD

**Issue by adamfaulkner** [ensime/ensime-server#910]
Line 322 of ensime-client.el refers to a `ensime-default-server-port` variable. it is not defined. This makes it impossible to do `M-x ensime-connect`

**Comment by fommil** [comment]
That's for you to define. Default is dynamic

**Comment by adamfaulkner** [comment]
In that case, you might want to use defcustom to declare it so that the user is aware of this variable.
At any rate, in its current state the user cannot execute M-x ensime-connect without defining this variable. This is unexpected, since ensime-connect prompts the user for a port. It would be better if it just didn't specify a default if the default is not defined.

I guess since ensime-connect isn't really documented, it doesn't really matter if you just want to ignore this.

**Comment by fommil** [comment]
It's only really for debugging ensime itself. I mean, you'd have to start your own server with custom options to fix the port number beforehand. Somebody once wanted it for TRAMP but I don't think it's actively used. Rory uses it because he uses IntelliJ to hack on ENSIME :-P

**Comment by adamfaulkner** [comment]
Sounds good. I was just using it to debug another problem I had, sorry for bothering you about it.

**Comment by rorygraves** [comment]
We should document it or improve the error messages - I don't use it at the mo - mostly focused on the api directly.
