### ISSUE TITLE
Ensime doesn't connect after M-x ensime or M-x ensime-connect

### ISSUE THREAD

**Issue by adamfaulkner** [ensime/ensime-server#911]
This looks similar to #714 and #781 , but neither of the fixes mentioned fixed the problem for me.

This project has nothing interesting in it, I've obtained it by following the quick start guide exactly.

I was able to get ensime to work by adding to the ensime-setup-connection function in ensime-client.el:

```elisp
(defun ensime-setup-connection (process)
  "Make a connection out of PROCESS."
  (let ((ensime-dispatching-connection process))

    (setf (ensime-protocol-version process) nil
          (ensime-pid process) nil
          (ensime-server-implementation-name process) nil
          (ensime-connection-name process) nil
          (ensime-analyzer-ready process) nil)

    ;; Initialize connection state in the process-buffer of PROC."

    ;; To make life simpler for the user: if this is the only open
    ;; connection then reset the connection counter.
    (when (equal ensime-net-processes (list process))
      (setq ensime-connection-counter 0))

    (ensime-with-connection-buffer
     () (setq ensime-buffer-connection process))
    (setq ensime-buffer-connection process)

    (setf (ensime-connection-number process)
      (incf ensime-connection-counter))

    process))
```

(note the additional (setq ensime-buffer-connection process) after ensime-with-connection-buffer). This makes me think that the ensime-with-connection-buffer macro might be broken.

Of course, I don't have much context for this, I'm just trying scala out.

**Comment by fommil** [comment]
Hmm. That's odd. We are seeing something similar in a PR at the moment, we might have done a dodgy merge. 

Which version of scala is your project using?

**Comment by fommil** [comment]
works for me in scala 2.11. I can't see what extra you've added to the connection code, can you raise a PR please?

**Comment by adamfaulkner** [comment]
Thanks for the response.

I don't want to make a PR because I'm pretty sure what I did was a hacky workaround. I just added a `(setq ensime-buffer-connection process)` outside the `ensime-with-connection-buffer` macro. I assume the `ensime-with-connection-buffer` macro is important.

I'm using scala 2.11.6.

Thanks again.

**Comment by fommil** [comment]
Can you go back to canonical ensime and try to come up with a reproducible script for us?

**Comment by adamfaulkner** [comment]
I went back and repeated everything systematically, and it appears to be working. It doesn't look like you've landed any changes that could have fixed this issue since I experienced it, so I guess I must have missed something the first time. Super weird...
Anyway, thank you for your help.
