### ISSUE TITLE
ensime-sbt-command getting set to nil

### ISSUE THREAD

**Issue by MrBones118** [ensime/ensime-server#912]
With the latest ensime in melpa, a clean ivy-cache, and sbt definitely in path, running M-x ensime was giving me
condition-case: check that sbt is on your PATH and that your config is compatible with http://github.com/ensime/ensime-server/wiki/Example-Configuration-File [(wrong-type-argument stringp nil)]

After some digging, the backtrace was telling me that ensime-sbt-command was nil, and hence an error was being caused by (locate-file nil) on my path looking for sbt.

I've no idea why this could be happening. That variable isn't set anywhere, either by me or ensime.

In the end, I ran (setq ensime-sbt- command "PATH-TO-SBT/sbt"), and everything worked fine, so I'm pretty certain the issue.

I've not yet tried reproducing this with emacs -Q - more details to come if I can.

**Comment by fommil** [comment]
check https://github.com/ensime/ensime-server/issues/670
