### ISSUE TITLE
Completion on dot

### ISSUE THREAD

**Issue by muhmud** [ensime/ensime-server#913]
Is it possible to configure ensime to perform auto completion straight after typing a dot? 

This is useful when you just want to browse an interface or you're not 100% sure what you're looking for.

**Comment by fommil** [comment]
you mean without typing TAB?

**Comment by muhmud** [comment]
Hmm, tab would be fine, except it doesn't work for me. I have to type the first two letters to trigger completion

**Comment by aemoncannon** [comment]
Your configuration may bind something else to TAB. Try manually running M-x
ensime-company-complete-or-indent

**Comment by eklavya** [comment]
I used to have a .emacs snippet that enables completion on tab without having to write first two characters. I lost it. Can someone please tell me how to set that up again?
