### ISSUE TITLE
random freezing

### ISSUE THREAD

**Issue by BrianHicks** [ensime/ensime-server#914]
I'm writing some scalatest tests and Ensime's completion (using company here) will randomly freeze emacs. I'd love to provide you with logs, but even when I have the inferior buffer open the output freezes so I can't see any errors. Killing the Java process doesn't unfreeze Emacs either, unfortunately, so I'm not sure how I can get you more debugging info.

I'm using the latest version from MELPA, Emacs 24.4.1, and OSX 10.10. Any ideas?

**Comment by aemoncannon** [comment]
Interesting. We have a pretty long rpc timeout: 30 secs. Have you tried
waiting that long? Company's timeout should kick in before that though.
Possible you have a stale company mode?
Otherwise I'd say:
A) hack the server output filter to flush output to a file. at least then
we can see the log.
B) hook a debugger / profiler to the server to see if it's doing anything

**Comment by fommil** [comment]
I'm tempted to say that this isn't ensime, given that killing the server doesn't stop the hang.

I've seen random emacs hangs due to UTF-8 characters, can you please eliminate that as a possibility?

**Comment by rorygraves** [comment]
@fommil  - further discussion going on in the gitter channel - the screenshot shows that the server was complete and the display is blocked partway through logging the response

**Comment by BrianHicks** [comment]
As an update:

Here's a [screenshot of `*inferior-ensime-server-` when frozen](http://i.imgur.com/elx4oax.png), and a [coredump from Java](https://gist.github.com/BrianHicks/c96bf25c92bb1ca33de1).

Based on those, @rorygraves has determined that it is a problem with emacs. We're not sure how to go further, though!

To answer questions:

 - @aemoncannon: I've waited for long periods of time before killing emacs, it doesn't help
 - @fommil: the information I'm working with would all fit in ASCII, or maybe Latin-1. I'm not sure how it's *actually* encoded, however. I know that at least there are no double-width characters.

**Comment by BrianHicks** [comment]
And thanks to @rorygraves we have a little progress. After using the advice in [this SO question on debugging a frozen emacs](http://emacs.stackexchange.com/questions/506/debugging-a-frozen-emacs) (specifically `toggle-debug-on-quit`) I have a [gist with the errors](https://gist.github.com/BrianHicks/44f8ec48dda1f6202ac5) to share. Looks like there's a lot to do with company-mode here.

**Comment by fommil** [comment]
can you try upgrading company mode to the latest melpa version?

**Comment by BrianHicks** [comment]
all my packages are at the latest versions already. In fact, I've removed my elpa directory and reinstalled everything to see if that was the cause of the issue.

**Comment by fommil** [comment]
dang. Is there a "script" on a github project that you could write for us, for us to reproduce locally? That'd make it a lot easier to reproduce.

BTW, as a workaround, I think it's possible to switch to another autocompletion backend (aemon only recently added company mode support, until then we used autocomplete and I think it's still around). I have never looked back since we upgraded.

I blame Apple :stuck_out_tongue:

**Comment by BrianHicks** [comment]
I'm not sure what you mean by a script. It's a sporadic issue. It happens most often trying to do period completion. If you're looking for emacs config, I'm using [spacemacs](https://github.com/syl20bnr/spacemacs) though that seems to be working for other users. [Here's the scala/ensime configuration section](https://github.com/syl20bnr/spacemacs/tree/master/contrib/lang/scala). I'm using syl20bnr/spacemacs@766625558b6b67901eae78da26b223b9eb336ff8 at the moment.

**Comment by fommil** [comment]
script = a list of instructions for us to walk through on a (preferably) small project

**Comment by fommil** [comment]
oh, actually, trying this with a minimal emacs config would probably be good as well. it might be some weird interaction of plugins.

**Comment by BrianHicks** [comment]
I'll get a small project together tomorrow and put it up to try and reproduce.

In the meantime, I'm using a kit as you can see, I'm not sure how to do a minimal config. What are some guidelines you'd recommend for that?

**Comment by aemoncannon** [comment]
The stacktrace contains the smoking gun, I think. Try evaluating this:
(string-match (concat scala-syntax:plainid-re "\\'")
"/collect/tag=impression&guid=f367bb93950dec44bb3efa375f331bb1035a6589&r")

**Comment by BrianHicks** [comment]
@aemoncannon yep, that freezes it in exactly the same way. Just in case it's useful, here's the stacktrace:

```
﻿Debugger entered--Lisp error: (quit)
  string-match("\\(\\([[:lower:]_[:upper:]\\$]\\([_]??[[:lower:][:upper:]\\$0-9]+\\)*\\(_+[#:<=>@!%&*+/?\\\\^|~-]+\\|_\\)?\\)\\|[#:<=>@!%&*+/?\\\\^|~-]+\\)\\'" "/collect/tag=impression&guid=f367bb93950dec44bb3efa375f331bb1035a6589&r")
  eval((string-match (concat scala-syntax:plainid-re "\\'") "/collect/tag=impression&guid=f367bb93950dec44bb3efa375f331bb1035a6589&r") nil)
  eval-expression((string-match (concat scala-syntax:plainid-re "\\'") "/collect/tag=impression&guid=f367bb93950dec44bb3efa375f331bb1035a6589&r") nil)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

**Comment by aemoncannon** [comment]
Yeah, we're hitting an especially bad case for the regexp engine. Looks
like the "...&r" at the end of the string is triggering continual
backtracking. I still don't understand why that'd cause the time to explode
so badly....

**Comment by aemoncannon** [comment]
One may rightly ask: why are we attempting completion within strings at
all? The answer is that we want to support completing interpolated
expressions in s"..." strings, so we postpone the check until the server
(in all its wisdom) can take a look.

**Comment by aemoncannon** [comment]
I think the 'right' answer is that we should have a custom state machine for determining the prefix identifier. This would require careful adherence to scala's identifier syntax.

@BrianHicks If you want a quick fix, you could modify ensime-completion-util.el#46 to use ensime-in-string-or-comment-p
