### ISSUE TITLE
Missing plugins and their dependencies

### ISSUE THREAD

**Issue by rajish** [ensime/ensime-server#918]
I've tried to compile from scratch current master of `ensime-server` and found out that there's missing entry for the `sbt-graph` plugin and there are couple of `scoverage`-related errors when starting `sbt`:

```
ensime-server/build.sbt:5: error: value instrumentSettings is not a member of object scoverage.ScoverageSbtPlugin
import scoverage.ScoverageSbtPlugin.instrumentSettings
       ^
```

```
ensime-server/build.sbt:6: error: value coverallsSettings is not a member of object org.scoverage.coveralls.CoverallsPlugin
import org.scoverage.coveralls.CoverallsPlugin.coverallsSettings
       ^
```

The `scoverage` plugins versions look OK, so I suspect there's some additional plugin missing?

**Comment by fommil** [comment]
You're branch has some stale files. Try a git clean

**Comment by fommil** [comment]
Good to see you back :-) are you planning on working on anything?

**Comment by rajish** [comment]
Thanks, I came up with the same solution. Damn, you're fast! I wanted to close the bug myself. 
WRT to work on something I forgot what a free weekend means but I'm still here. So occasionally you can hear from me.

**Comment by rorygraves** [comment]
What are these 'free weekends' you talk of?

**Comment by rajish** [comment]
Exactly
