### ISSUE TITLE
swank:debug-stop Does not actually stop the VM

### ISSUE THREAD

**Issue by rorygraves** [ensime/ensime-server#919]
From Google groups message.

swank:debug-stop disposes the vm mirror (calls ```vm.dispose()```) it should probably call ```vm.exit(0)``` otherwise we are leaking processes.

See jdi documentation at https://docs.oracle.com/javase/7/docs/jdk/api/jpda/jdi/com/sun/jdi/VirtualMachine.html 

This needs an integration test and a fix.

**Comment by fommil** [comment]
I guess it's unlikely that somebody would want to keep the JVM running after stopping a debugging session. Would this explain why our debug tests used to grind to a halt?

**Comment by rorygraves** [comment]
Yep - that would be my guess.  It may well explain that test failure.
