### ISSUE TITLE
Windows CI tests

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#920]
just throwing it out there. It has been a lot of pain, but I have virtualbox running Windows XP in another project as part of the Shippable CI.

If it were possible to script virtualbox images to run a command, we could do the same in ensime. Although, I think the docker images have to be private. Instructions here https://github.com/fommil/freeslick/tree/docker-base

**Comment by fommil** [comment]
as I discovered in FreeSlick, this requires a hardware donation, because rory/my VPS machines can't nest virtual machines.

**Comment by fommil** [comment]
windows builds are possible via http://www.appveyor.com/

not necessarily the emacs tests, but we should be able to do the server integration tests.

**Comment by fommil** [comment]
example build definition https://github.com/sbt/sbt-native-packager/blob/master/appveyor.yml

**Comment by fommil** [comment]
Travis seems to allow OS X these days ... but I guess we'll have the same problems as before (unless rory's test refactoring made it easier to run) http://docs.travis-ci.com/user/osx-ci-environment/

**Comment by fommil** [comment]
We now have a Windows build!

It's just doing the unit tests, but it doesn't seem too hard to get the integration tests working as well. @edani any chance you could have a look at those please? It's just the BasicWorkflow one that is failing. When you think you've got them fixed, just move the `it:test` line onto the `test_script` line and AppVeyor should run it every time. If you're feeling **really** brave, try editing the AppVeyor script to download (and cache) Emacs 24.4 and run the client integration tests.

**Comment by edani** [comment]
@fommil I've been offline for the past week. I'll look at this some time this week Thanks fro getting AppVeyor to work!
