### ISSUE TITLE
sbt address already in use

### ISSUE THREAD

**Issue by arigoldx** [ensime/ensime-server#921]
I'm guessing that this is due to our sbt setup, specifically the ports we use, but while Ensime seems to work A OK, I get this when I try a `C-c C-v s`:

```bash
Running sbt
ERROR: transport error 202: bind failed: Address already in use
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [../../../src/share/back/debugInit.c:750]
FATAL ERROR in native method: JDWP No transports initialized, jvmtiError=AGENT_ERROR_TRANSPORT_INIT(197)
/usr/local/Cellar/sbt/0.13.7/libexec/sbt-launch-lib.bash: line 41: 91643 Abort trap: 6 
```

I'm able to start up Ensime and do things like `C-c C-v i` but I'd love to be able to build our project (which I currently do with one of our commands, `portal-run` at the sbt prompt). For now I have to kill the current sbt process and then start my own in a shell. Man oh man, this smells like a port thing.

I'm not new to emacs but I'm still pretty new to `sbt` and `ensime`. That being said I'm more than happy to document or help out in any other way.

**Comment by fommil** [comment]
huh, that is really weird. In ENSIME we only assign one port and its ephemeral, so this is more likely to be an sbt problem.

There is talk of an agent... are you running with any special java flags that would be attaching an agent? (e.g. YourKit or something)

**Comment by fommil** [comment]
oh hold on, `C-c C-v s`, that's trying to talk to the (deprecated) ScalaX online API isn't it? I'm guessing this support is just so broken that we should remove it. https://github.com/ensime/ensime-server/wiki/Emacs-Command-Reference

**Comment by arigoldx** [comment]
hmm.. if it helps, this is essentially my `/usr/local/etc/sbtopts`:
```
-sbt-create

-J-XX:+CMSClassUnloadingEnabled
-J-Xmx2048M
-J-XX:MaxPermSize=1024M
-J-Xdebug
-J-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
```
no "YourKit" that I could find..

I tried some of the other commands but always see `ERROR: transport error 202: bind failed: Address already in use`. also `ps aux | grep sbt` shows an `sbt` running which is the one started from `ensime` (I triple checked).

any docs you might suggest I read? I've gotta plane flight tomorrow and would be psyched to help out with this..

and thanks!

**Comment by arigoldx** [comment]
interestingly enough, I read through https://github.com/ensime/ensime-server/wiki/Emacs-Command-Reference#sbt and saw that "Much of this is a wrapper over `sbt-mode`" so I tried just a simple `sbt-start` and that came up fine.

of course `ensime` failed 'cause the ports now already in use..

**Comment by rorygraves** [comment]
@arigoldx You actually beat me to it - was about to reply - ensime uses sbt to generate the launch scripts for ensime - and port 5005 will obviously be in use.

**Comment by arigoldx** [comment]
say, @rorygraves, any idea why can't I connect to the sbt that ensime itself created?

**Comment by rorygraves** [comment]
Ensime spins one up only long enough to generate the classpath etc - it used to hang around, but I don't think it does any more @fommil Please correct me/add more info

**Comment by arigoldx** [comment]
I think it does hang around 'cause `ps aux | grep sbt` shows one.. hmm.

**Comment by fommil** [comment]
if you have an `sbt` open in a terminal and then you do any commands in ENSIME that would start up an `sbt` shell (e.g. building the project) then it's going to fail because you start sbt itself up with the debugger turned on and fixed to a specific port.

If you want to debug from sbt, I recommend having a read of the various suggestions linked from https://github.com/ensime/ensime-server/issues/801 and simply removing this from your .sbtopts

ok to close?

**Comment by fommil** [comment]
(btw, you might not be the only person trying to bind to port 5005. Use netstat to find out if another process has opened the port)

**Comment by arigoldx** [comment]
thanks @fommil - I'll look at the sbtopts and ports and that link you posted.

fwiw, I'm most definitely *not* starting any sbts in any terminals. the only one started was from ENSIME.

**Comment by dalegaspi** [comment]
FYI for anyone using ensime in a [multi-module sbt project](http://www.scala-sbt.org/0.13/docs/Multi-Project.html): you will need to specify the sub-project where the main class is or you get this similar error above...

i.e., if the main class `YourMainClass` is in package `com.your.pkg` is in a sub-module `module-web` you will have to run (in the sbt console):

```sbt
> module-web/ensimeRunDebug com.your.pkg.YourMainClass
```
