### ISSUE TITLE
Compile errors for files that are not open

### ISSUE THREAD

**Issue by muhmud** [ensime/ensime-server#922]
Hi,

I get spurious compile errors, I think mostly related to package scope, which disappear when I open the related files in emacs.

E.g. I am editing package1.subpackage1.Class1 which references package1.subpackage1.subpackage2.Class2 as subpackage2.Class2. This gives me an error until I open the file for Class2. I think I also get this when both classes are in the same package.

Is there something I can do about this? Apart from opening lots of files?

Thanks very much!

Muhmud.

**Comment by fommil** [comment]
https://github.com/ensime/ensime-server/wiki/Edit-Compile-Workflow

**Comment by muhmud** [comment]
Thanks
