### ISSUE TITLE
server update failed on addMavenResolverPlugin

### ISSUE THREAD

**Issue by fspeech** [ensime/ensime-server#924]
I am following the Wiki's instructions on installing ensime. After ```M-x ensime``` for the first time the process failed at:
```...\AppData\Local\Temp\ensime_update_3440Ylu\project\plugins.sbt:1: error: not found: value addMavenResolverPlugin
addMavenResolverPlugin
^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore```

**Comment by fommil** [comment]
hmm, are you using paulp's `sbt` script?

**Comment by fommil** [comment]
i.e. `sbt` == https://github.com/paulp/sbt-extras/blob/master/sbt

**Comment by fspeech** [comment]
I am running Emacs native on Windows. The script you pointed to is a bash script so I am pretty sure that is not what is called by my Emacs.

**Comment by fspeech** [comment]
I did a bit of research this command seems a fairly recent addition to sbt:
https://github.com/sbt/sbt/pull/1808#issuecomment-70700677

So maybe somewhere things are out of sync.

**Comment by fommil** [comment]
in sbt, you set the version of sbt in `project/build.properties` no matter the version of the launcher. I suspect you've got a really ancient version of the launcher.

**Comment by fommil** [comment]
the script is indeed `sbt`, use it instead of whatever sbt script you currently have.

**Comment by fspeech** [comment]
My launcher is 0.13.7 downloaded on 2/7/2015. I can try installing the latest 0.13.8.

**Comment by fspeech** [comment]
Updating to 0.13.8 did not make a difference.

>the script is indeed sbt, use it instead of whatever sbt script you currently have.

Hmm. It is possible to coax Emacs to run a bash script from  within Windows but it will take some effort. However I am afraid that may be just a wild goose chase here. My sbt seems to work fine for all practical purposes, even within ensime update:
```...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
```
The only problem is this new command ```addMavenResolverPlugin``` that is not recognized by the current version of sbt.

**Comment by fspeech** [comment]
As a test I added  ```addMavenResolverPlugin``` to a test build.sbt and ran from a MSYS2 terminal window (which has a bash shell) the script you pointed to and I got the exact same failure. The only observable difference is that the script you pointed to downloaded a copy of the launcher and put it in ```.sbt/launchers```, but as far as I can tell it is the same launcher that I downloaded from scala-sbt.org website.

**Comment by fspeech** [comment]
I have opened an issue on sbt https://github.com/sbt/sbt/issues/1952

Meanwhile how can I get rid of this dependency on ensime? Where does ensime store the plugin.sbt file on my computer?

**Comment by fspeech** [comment]
I built ensime-server manually from the git repo, which was fairly smooth after I first removed reference to ```addMavenResolverPlugin``` in plugins.sbt. In Emacs I also temporarily overloaded the server update function to remove the above reference. After struggling with scala versioning quite a bit to get the local ivy2 build recognized, now ensime-server is running and the swank interface is working:
```
...
22:01:18.315 [default-akka.actor.default-dispatcher-4] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:indexer-ready)
22:01:18.315 [default-akka.actor.default-dispatcher-4] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:background-message 105 "Initializing Analyzer. Please wait...")
22:01:18.316 [default-akka.actor.default-dispatcher-4] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:compiler-ready)
22:01:18.316 [default-akka.actor.default-dispatcher-4] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:full-typecheck-finished)
```
but Emacs still displays ensime status as disconnected. If I attempt to tab in the buffer it asks me to try connecting to the server again. ```M-x ensime``` does not help. I am stymied here. Is ensime known to not work on Windows? Don't see why that would be the case though.

**Comment by fspeech** [comment]
Okay after poking through the various ensime-*.el files I finally realized that ensime expects source files layout to be just like what is specified in the .ensime file. Since I was running on a test file with no directory structure whatsoever it does not recognize that process started from that file buffer to be a related process. I moved the file to an expected subdir location and now ensime server status is correct. I will test out other features as well.

This exercise shows that my setup does work. The issue I reported at the beginning is real though it looks like a bug in sbt itself. Until the sbt bug is fixed it seems to me the right thing to do is to roll back the dependency on ```addMavenResolverPlugin```.

**Comment by fspeech** [comment]
I have to say once it is working it is pretty impressive. I could even easily navigate to the source of println!

**Comment by fommil** [comment]
Bloody sbt again. 

Roll back all your hacks and remove the two lines recently added to ensime-start.el referencing plugins.sbt

I'll revert this on the server and client site later today if it turns out to be sbt.

**Comment by fommil** [comment]
ok, I've rolled back all our use of this maven resolver feature (which I'm pretty sure didn't have any performance improvement anyway) so in an hour or so the stock install should Just Work.

Having an automated Windows integration test would be awesome to catch all this stuff.
