### ISSUE TITLE
SexpFormat[Boolean] cannot produce SexpFalse values

### ISSUE THREAD

**Issue by mattly** [ensime/ensime-server#926]
I am attempting to setup ensime with an existing project that uses a locally modified copy of sbt. The project has its own Scalariform rules that seem to be at odds with what I can coax out of ensime. I would rather turn off ensime's formatting if possible, but there doesn't seem to be an option for doing so. Is this possible?

**Comment by mattly** [comment]
FYI I have a failing test around the ScalariForm preference that's not working, and am looking into fixing it, though I'm still somewhat new to Scala:

``` failing_test.diff
diff --git a/swank/src/test/scala/org/ensime/config/ScalariformFormatSpec.scala b/swank/src/test/scala/org/ensime/config/ScalariformFormatSpec.scala
index db5aff2..07cb018 100644
--- a/swank/src/test/scala/org/ensime/config/ScalariformFormatSpec.scala
+++ b/swank/src/test/scala/org/ensime/config/ScalariformFormatSpec.scala
@@ -12,10 +12,12 @@ class ScalariformFormatSpec extends FormatSpec {
 
   val prefs = FormattingPreferences().
     setPreference(DoubleIndentClassDeclaration, true).
+    setPreference(SpacesAroundMultiImports, false).
     setPreference(IndentSpaces, 13)
 
   it("should parse some example config") {
     val text = """(:doubleIndentClassDeclaration t
+                     :spacesAroundMultiImports f
                      :indentSpaces 13)"""
     val recover = text.parseSexp.convertTo[FormattingPreferences]
     assert(recover.preferencesMap == prefs.preferencesMap)
@@ -24,6 +26,7 @@ class ScalariformFormatSpec extends FormatSpec {
   it("should create valid output") {
     assert(prefs.toSexp === SexpList(
       SexpSymbol(":doubleIndentClassDeclaration"), SexpSymbol("t"),
+      SexpSymbol(":spacesAroundMultiImports"), SexpSymbol("f"),
       SexpSymbol(":indentSpaces"), SexpNumber(13)
     ))
   }
```

**Comment by mattly** [comment]
Here's what I've figured out:

1) This project is using daniel-trinh/scalariform instead of mdr/scalariform
2) this version of scalariform has an option `SpacesAroundMultiImports` that defaults to `true`.
3) this project's ScalariForm rules set this to `false`, because (and I quote) "IntelliJ is always right"
4) `BooleanFormat` in the sexp `BasicFormats.scala` will turn values into either `true` or `nil` – since, and I quote, 'all non-nil Sexps are technically "true"'
5) `nil` values are left to defaults, in this case `true`
6) Ensime gives me no way to specify a `false` for this value.

Philosophical issues about truthiness and non-existence aside, if I am going to use Ensime and therefore continue to resist the project's insistence I adopt IntelliJ, I pragmatically need a way to set a false value. I'll set about adding this to `BasicFormats.scala`, though some guidance would be useful.

**Comment by rorygraves** [comment]
I believe you can use the keyword ```nil``` to specify a false value - if that doesn't work then it is definitely a bug.

**Comment by rorygraves** [comment]
P.s. I've had the joy of working in places where 'X is the one true way'.  They are clearly wrong and Ensime/Emacs is the one true path. :smiley:

**Comment by fommil** [comment]
Scalariform is a mess right now, we're working with them to fix it but they are being very slow to release anything. Ensime doesn't format anything automatically just just don't ask ensime to format your files.

**Comment by fommil** [comment]
closing as a dupe of #792

**Comment by fommil** [comment]
oh, yes, of course `f` is lisp is true. This is because `nil` is false and everything else is true.

**Comment by mattly** [comment]
Well, I'm not sure what else to say other than:

1) I've setup ENSIME as suggested with the config in `~/.sbt/0.13/plugins/plugins.sbt`, and even if I haven't done a `sbt gen-ensime` for this project, when I go to launch the project it ignores the project's scalariform rules and uses defaults. This alone means I can't use ENSIME on the same development machine on another project that with this project, unless I specify it per-project and not per-environment as suggested.

2) I've tried doing the `./sbt gen-ensime` in this project (using the local sbt, which should pick up on the multi-project config ruels), editing the `.ensime` file, and then manually adding `:formatting-prefs` as so:
```
  :formatting-prefs (:spacesAroundMultiImports nil)
```
and when running `./sbt` it will still reformat every scala file in the project with SpacesAroundMultiImports[^] despite the Scaraiform settings in the project itself. It sounds like this is the problem in #792 whereby thanks to the ensime hook in my ~/.sbt config, it's loading the wrong version of Scalariform which doesn't have this option, but I'm really not sure how to tell if that's the case or if it's simply ignoring my setting.

^ example:
```
-import scala.concurrent.{ExecutionContext, Future}
+import scala.concurrent.{ ExecutionContext, Future }
```

3) What would circumvent the entire problem to begin with is a way to tell ENSIME to simply not attempt setting up Scalariform to begin with and let whatever else is in the project handle the formatting.

I'm not sure what the right solution is here, and while the situation with Scalariform sounds tragic, I think the pragmatic solution would be no. 3 – for me to have a way to tell ENSIME not to load Scalariform at all.

I'm relatively new to Scala, I came onto this project through helping out with a different facet of it, but as I'm getting more involved in the Scala portions, I'm finding the interactive tools useful in learning Scala. So if that means using IntelliJ like everyone else on the project because it's not making bad assumptions about how the project is setup, and then subsequently using IntelliJ for any other Scala work I want to do, then that's what it means. It  I'd rather work in Emacs, but then I'd also rather work in Clojure as well.

**Comment by rorygraves** [comment]
@mattly  That is very weird - Ensime has nothing to auto-format code, and at the point you are running normal sbt stuff is simply not running (until you start it from emacs).

If the code is being reformatted as part of an sbt action it must be something within your build file.  
I'm guessing that you are picking up daniel-trinh/scalariform instead of mdr/scalariform as sbt-ensime depends on it (i.e. it is an dependency order thing).

I believe the current one actually share namespaces @fommil  was trying to get the daniel-trinh republished in its own namespace I believe.

you could try force setting the pref in your build config temporarily - 

```

**Comment by fommil** [comment]
Use gen-ensime, then turn off the ensime plugin, or do some sbt exclusion rule magic. Upstream bug, probably worth filing a regression with Daniel.

**Comment by mattly** [comment]
thanks @fommil, turning off the ensime plugin in ~/.sbt/0.13/plugins/plugins.sbt after running gen-ensime did the trick.
