### ISSUE TITLE
Warn if scala 2.11.4 or lower used

### ISSUE THREAD

**Issue by timcharper** [ensime/ensime-server#929]
Latest version of ensime-server refers to the trait `scala.tools.nsc.util.ClassFileLookup`, which does not exist in 2.11.4 or lower.

**Comment by timcharper** [comment]
Evidence:

Not found:

http://www.scala-lang.org/api/2.11.4/scala-compiler/index.html#scala.tools.nsc.util.ClassFileLookup

Found:

http://www.scala-lang.org/api/2.11.5/scala-compiler/index.html#scala.tools.nsc.util.ClassFileLookup

**Comment by fommil** [comment]
Rather than warn, we should avoid using it.

**Comment by fommil** [comment]
Workaround is to run gen-ensime with Scala version override. It'll use a slightly newer version of scala for emacs but for project will still use the older scala.
