### ISSUE TITLE
disable placeholders on completion

### ISSUE THREAD

**Issue by wedens** [ensime/ensime-server#934]
Is it possible to disable completion placeholders? (function arguments) If not it will be useful feature to toggle in config.
I use company-mode for completion.

**Comment by wedens** [comment]
as a workaround it will not put placeholders if yasnippet minor mode is disabled

**Comment by aemoncannon** [comment]
Yeah that'll do it : )   This is a good issue -- wanna do a PR to add a var
to disable?

**Comment by wedens** [comment]
I use emacs for about 4 days and I don't know elisp enough :)

**Comment by fommil** [comment]
Great way to learn elisp :-D

**Comment by fommil** [comment]
This issue was moved to ensime/ensime-emacs#159
