### ISSUE TITLE
ensime-sbt does not include optional dependencies in compile-deps

### ISSUE THREAD

**Issue by wookietreiber** [ensime/ensime-server#935]
The ensime-sbt plugin does not include optional dependencies in the generated `.ensime` files `compile-dep` setting. While these are optional for the user of the library, I still need them to compile the library, so they should be included.

These are my dependencies (each on their on line for better readability):

```
> show libraryDependencies
[info] List(
  org.scala-lang:scala-library:2.11.6,
  org.jfree:jfreechart:1.0.19,
  org.scala-lang.modules:scala-swing:1.0.1,
  org.specs2:specs2-core:3.4:test,
  com.lowagie:itext:4.2.1:optional,
  org.jfree:jfreesvg:2.1:optional
)
```

Notice the optional dependencies are missing (while specs2 and its deps are correctly in `test-deps`):

```
$ grep compile-deps .ensime
   :compile-deps (
  "/home/wookietreiber/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar"
  "/home/wookietreiber/.ivy2/cache/org.jfree/jfreechart/jars/jfreechart-1.0.19.jar"
  "/home/wookietreiber/.ivy2/cache/org.jfree/jcommon/jars/jcommon-1.0.23.jar"
  "/home/wookietreiber/.ivy2/cache/org.scala-lang.modules/scala-swing_2.11/bundles/scala-swing_2.11-1.0.1.jar"
)
```

**Comment by fommil** [comment]
it should be relatively easy to fix this in the plugin, fancy having a look and submitting a PR? :smile:

https://github.com/ensime/ensime-sbt/blob/master/src/main/scala/EnsimePlugin.scala

**Comment by jsuereth** [comment]
You'll want to grab the "compile-internal" classpath from ivy.  This is how mavens notion of optional and ivy's notion of configurations manifest in sbt.  Should be a quick-ish fix

**Comment by fommil** [comment]
I thought that optional dependencies were ones that the user had to explicitly add to their project anyway. In that case, I'd suggest just adding the deps to your build dependencies and then we can close this ticket. I don't think your library should be declaring libraries as `optional` if you actually them to compile.

**Comment by fommil** [comment]
oh hold on, you mean **you** have marked them `optional`. Never mind me.
