### ISSUE TITLE
If ensime-gen-config process asks user a question, user cannot answer it

### ISSUE THREAD

**Issue by greenrd** [ensime/ensime-server#936]
I saw this in my *ensime-gen-config* buffer:

```
[info] Loading global plugins from /home/user/.sbt/0.13/plugins
[info] Loading project definition from /home/user/git/foo/project
[error] [/home/user/git/foo/build.sbt]:27: illegal start of simple expression
[error] [/home/user/git/foo/build.sbt]:33: ')' expected but eof found.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

I fixed the problem and tried to press `r` and then enter, but of course nothing happened.

I guess this is a general possibility for any command that invokes `sbt`.

**Comment by fommil** [comment]
just close the buffer and tidy up your sbt config. There is no way to recover.

**Comment by greenrd** [comment]
Actually the process needs to be killed as well.

I don't think this should be a fundamental buffer. There are other buffer modes which allow interaction with a process, termination of the process by sending a signal (which would also be useful if sbt hangs), etc. Fundamental-mode does none of that.

**Comment by fommil** [comment]
Are you sure that the process isn't killed when the buffer is closed?

We'd accept a PR that simply sends `gen-ensime` to the sbt buffer. That's simpler. It would be massive overkill to do anything fancy for this function.

**Comment by fommil** [comment]
https://github.com/ensime/ensime-emacs/blob/2acb64dae5ae0ed3d0bac4a5f43eae01c3ac82f8/ensime-config.el#L152 as far as I am aware, killing buffers like this should always kill the process.

**Comment by edani** [comment]
This seems to be a common complaint with sbt. One solution besides killing the buffer is to redirect stdin. It doesn't seem trivial to do it with emacs' `start-process` though.

**Comment by fommil** [comment]
uuugh, then we end up writing another `sbt-mode`. Why didn't we just use `sbt-command` in the first place?

**Comment by fommil** [comment]
or is there a way to run sbt in batch mode so it doesn't ask questions? Maybe we should do that in this case. There is no reason for it to be interactive.

**Comment by greenrd** [comment]
It could be useful to be able to press `l` for `last`, to see the stack trace.

**Comment by fommil** [comment]
out of interest, why would you want to see that? The only thing that can go wrong is that you have a syntax error in your file, and it tells you which lines its on.

If people are wanting full interaction with sbt when running this batch command, then doing it via `sbt-command` (i.e. `sbt-mode`) is the only real option. We'd accept a PR for that.

**Comment by greenrd** [comment]
> out of interest, why would you want to see that? The only thing that can go wrong is that you have a syntax error in your file, and it tells you which lines its on.

I think plugins can go wrong as well, so in that case it would be useful to see the stack trace.

> If people are wanting full interaction with sbt when running this batch command, then doing it via sbt-command (i.e. sbt-mode) is the only real option. We'd accept a PR for that.

OK, I'll look into that.

**Comment by fommil** [comment]
This issue was moved to ensime/ensime-emacs#158
