### ISSUE TITLE
ensime-gen-config knows where the ensime config file is but asks anyway

### ISSUE THREAD

**Issue by greenrd** [ensime/ensime-server#937]
If you have enabled regenerating the ensime config file using `sbt gen-ensime`, ensime presumably already knows where the config file is, but still asks anyway. It would not make sense to regenerate the config file and then... use a different config file, so it shouldn't waste the user's time by asking.

**Comment by fommil** [comment]
would you like to work on this and send a PR? :smile:

**Comment by fommil** [comment]
This issue was moved to ensime/ensime-emacs#157
