### ISSUE TITLE
Error when using ensime-sbt-perform-on-save and saving buffer

### ISSUE THREAD

**Issue by danmilon** [ensime/ensime-server#938]
The following error is written when I have `ensime-sbt-perform-on-save` set and try to save a buffer.

    Error running ensime-source-buffer-saved-hook: (wrong-type-argument sequencep t)

Any idea what might be wrong here?

**Comment by danmilon** [comment]
BTW I did `(setq debug-on-error t)` but no stack trace was given.

**Comment by fommil** [comment]
what's your action set to? Do you have an example project you can share?

**Comment by danmilon** [comment]
Excuse me, I'm not really fluent with elisp terminology and just started setting up ensime. Uhm, I did `(setq ensime-sbt-perform-on-save t)`. The docs mention it should be a non-nil value, so I guess what I did should be enough, right?

BTW I did this `(add-hook 'after-save-hook 'ensime-sbt-do-compile)` and it works fine.

**Comment by fommil** [comment]
it needs a string value for the command you want to perform, so that's why it failed. https://github.com/ensime/ensime-emacs/blob/22a878749b8a7ee2d4e6fa6e76c1df7c8180ade7/ensime-sbt.el#L49

**Comment by danmilon** [comment]
Right, I confused two different properties. I was reading [the docs](https://ensime.github.io), where it says:

```
Compile-on-Save:
```
```
If the value of the Emacs-Lisp variablt ensime-sbt-compile-on-save is non-nil ENSIME will invoke the
'compile' task in the inferior sbt process(presuming you have one running) whenever you save a
Scala buffer. This option is enabled by default.
```

**Comment by fommil** [comment]
those docs are **soooo** old, I wouldn't trust them.

**Comment by fommil** [comment]
trust the emacs generated help, or the wiki. They are all kept up to date.
