### ISSUE TITLE
M-. (ensime-edit-definition) fails to lookup the definition.

### ISSUE THREAD

**Issue by 4lex1v** [ensime/ensime-server#946]
Also [#775](https://github.com/ensime/ensime-server/issues/774) and [#492](https://github.com/ensime/ensime-server/issues/492)

It occurs intermittently When i try to lookup the definition for values/functions defined in objects. If the definition is local, in most cases it's fixed by running full typecheck, if it's from some library it fails to find the definition. 

Can't share my working project, will try to reproduce on some open-source project and will add details with logs here.

**Comment by fommil** [comment]
thanks but to keep the ticket open we'll need some details. We already know it fails in certain situations and we're trying to aggregate examples because we don't think they all have the same cause. We'll reopen if you could please create a shareable situation where this fails.
