### ISSUE TITLE
Jump back to the previous point after M-. (ensime-edit-defintion)

### ISSUE THREAD

**Issue by 4lex1v** [ensime/ensime-server#947]
I think it would be nice to push current location to the ring before jumping to definition, so that it would be possible to return to previous location using `C-u C-Space`. Maybe this is done differently, i didn't find

**Comment by fommil** [comment]
`M-,` :wink:

**Comment by fommil** [comment]
(although maybe you're suggesting a more canonical way to do it, in which case we can reopen)
