### ISSUE TITLE
Kill command in Signals menu in *sbt* buffer does not work

### ISSUE THREAD

**Issue by greenrd** [ensime/ensime-server#948]
The minibuffer says "Text is read-only" and the sbt process does not get killed. This is on Linux.

**Comment by fommil** [comment]
is this an `sbt-mode` buffer? If so, it's provided by https://github.com/hvesalai/sbt-mode

**Comment by fommil** [comment]
btw, if you're trying to kill the forked command that sbt is running, I use `C-c l` then `C-c C-c`. I keep meaning to bind it to something easy to remember.

**Comment by greenrd** [comment]
Yes I am, but `C-c l` says `C-c l is undefined`.

**Comment by fommil** [comment]
Maybe I forgot the correct command. I think I linked to it from the ensime-sbt README
