### ISSUE TITLE
conflict between AutoComplete and YASnippet minor modes?

### ISSUE THREAD

**Issue by peterbecich** [ensime/ensime-server#949]
This may well not belong here.
The relevant minor modes I have enabled are yas, AC, and Ensime.

If I type in the full name of a method, ```this.flatMap```, and press Tab, I'm prompted ```Choose '{' or '('```.  Either choice of parenthesis gives me error ````yas-expand-snippet' needs properly setup `yas-minor-mode'```.  This could also happen if I ignore any auto-completed suggestion and type the full method name.

If I accept the auto-completion suggestion with a Tab or Enter half way through the method name, I'm prompted again for a choice of parenthesis type, and this time yasnippet fills in the arguments correctly with no error:

```this.flatMap(fa: F[A])(f: Function1[A, F[B]])```

Another possible effect of this (potential?) conflict are duplicitous auto-complete suggestions.  The only characters I've actually typed here are ```this.flat```.  This isn't even a nuisance; I just thought it may be indicative of something.
![screen shot 2015-04-23 at 6 12 34 pm](https://cloud.githubusercontent.com/assets/6315338/7310645/88f69d88-e9e4-11e4-893d-54eb779ea6d2.png)

Why do you think YASnippet works some of the time?

Thanks for your time!

**Comment by fommil** [comment]
I've seen something similar. I think I turned off yas in Scala mode because I didn't feel it was adding any value, but you're right they don't play well together. Check why dotfiles project to confirm what I did.

**Comment by peterbecich** [comment]
I learned something from this configuration, thanks.
https://github.com/fommil/dotfiles/blob/master/.emacs

Disabling the AutoComplete minor mode and keeping yas enabled fixes the duplicitous auto-complete suggestions.  Disabling yas just stops any filling of arguments, though.

**Comment by gregnwosu** [comment]
I have dont have yas enabled for dropdown completion, however I have set my cursor to change colour when a snippet can fire, this works best for me.

**Comment by fommil** [comment]
@gregnwosu oh, that sounds nice! How did you do that? I think dropdown is automatic... it'd prefer it not to do that.

**Comment by gregnwosu** [comment]
alas not my own work

from: 
http://pages.sachachua.com/.emacs.d/Sacha.html
https://github.com/pcmantz/elisp/blob/master/my-bindings.el
``` lisp (setq default-cursor-color "gray")
(setq yasnippet-can-fire-cursor-color "purple")

;; It will test whether it can expand, if yes, cursor color -> green.
(defun yasnippet-can-fire-p (&optional field)
  (interactive)
  (setq yas--condition-cache-timestamp (current-time))
  (let (templates-and-pos)
    (unless (and yas-expand-only-for-last-commands
                 (not (member last-command yas-expand-only-for-last-commands)))
      (setq templates-and-pos (if field
                                  (save-restriction
                                    (narrow-to-region (yas--field-start field)
                                                      (yas--field-end field))
                                    (yas--templates-for-key-at-point))
                                (yas--templates-for-key-at-point))))
    (and templates-and-pos (first templates-and-pos))))

(defun my/change-cursor-color-when-can-expand (&optional field)
  (interactive)
  (when (eq last-command 'self-insert-command)
    (set-cursor-color (if (my/can-expand)
                          yasnippet-can-fire-cursor-color
                        default-cursor-color))))

(defun my/can-expand ()
  "Return true if right after an expandable thing."
  (or (abbrev--before-point) (yasnippet-can-fire-p)))

                                        ; As pointed out by Dmitri, this will make sure it will update color when needed.
(add-hook 'post-command-hook 'my/change-cursor-color-when-can-expand)

(defun my/insert-space-or-expand ()
  "For binding to the SPC SPC keychord."
  (interactive)
  (condition-case nil (or (my/hippie-expand-maybe nil) (insert "  ")))) ```

**Comment by fommil** [comment]
I've also seen similar things. tracking over at https://github.com/ensime/ensime-emacs/issues/217
