### ISSUE TITLE
do not periodically re-typecheck sources extracted from jars, and do not show the notes.

### ISSUE THREAD

**Issue by greenrd** [ensime/ensime-server#950]
In my emacs *ENSIME-Compilation-Result* buffer I have a bunch of warnings for `scalaz/BijectionT.scala`, which is in the ensime cache (it was extracted from inside a source jar). But it should not even be wasting time compiling those read-only buffers, let alone displaying the warnings from them.

**Comment by fommil** [comment]
you've misinterpreted what is happening.

1) those files are extracted so that you can navigate to them
2) the presentation compiler "compiles" the files so that you can get type information when browsing the files.

**Comment by fommil** [comment]
btw, if you have any questions about how the internals of ENSIME work, we're always happy to talk about it on the gitter channel :smile:

**Comment by greenrd** [comment]
Well sorry I got the terminology wrong, I thought that a presentation compiler "compiles" things, but obviously I was wrong. But what I was trying to say is that it creates clutter in the error/warning buffer.

**Comment by fommil** [comment]
Then don't ever navigate to files that you consider clutter

**Comment by fommil** [comment]
On do you mean that it shouldn't try to recompile / typecheck the files?

**Comment by greenrd** [comment]
Yes, exactly. Or at least, if that's necessary, it shouldn't display the warnings.

**Comment by fommil** [comment]
You mean you want to hide the squigglies in the read-only buffer, or hide them from the log?

I think we extract these two sensible refinements from this ticket, so I'll reopen under a new name:

1. don't automatically re-typecheck readonly buffers (i.e. those which have been extracted from source jars).
2. don't display the compiler notes for readonly buffers.

The latter is purely cosmetic, there is no way to get any ENSIME functionality in the buffer without typechecking it (i.e. passing it through the presentation compiler).

**Comment by fommil** [comment]
@greenrd how's your elisp? If you'd like to work on this and send in a PR we would be happy to help you out. I suspect it might only be one or two extra lines of surgical code to do an `(unless (buffer-read-only) ... )` or something like that.

**Comment by edani** [comment]
@fommil I would still typecheck all buffers, just not show warnings for the read-only ones. For one thing, a typecheck can't be avoided if we want the semantic highlighting and navigation.

**Comment by fommil** [comment]
@edani is there no way to exclude it after the first pass, or is that just awkward?

:+1: to cosmetic fix here.

**Comment by edani** [comment]
@fommil I'm not sure what that would entail so I would just go with the easy fix.

**Comment by fommil** [comment]
This issue was moved to ensime/ensime-emacs#156
