### ISSUE TITLE
java.lang.NoClassDefFoundError: shapeless/DefaultSymbolicLabelling

### ISSUE THREAD

**Issue by codygman** [ensime/ensime-server#953]
my .ensime:

    (
     :root-dir "/home/cody/programming/scala/df-test"
     :cache-dir "/home/cody/programming/scala/df-test/.ensime_cache"
     :name "df-test"
     :java-home "/usr/lib/jvm/java-8-openjdk-amd64"
     :java-flags ("-Xms1024m" "-Xmx1024m" "-XX:ReservedCodeCacheSize=128m")
     :reference-source-roots ("/usr/lib/jvm/java-8-openjdk-amd64/src.zip")
     :scala-version "2.11.0"
     :compiler-args nil
     
     :subprojects ((
       :name "df-test"
       :module-name "df-test"
       :source-roots ("/home/cody/programming/scala/df-test/src/main/scala" "/home/cody/programming/scala/df-test/src/main/java" "/home/cody/programming/scala/df-test/src/test/scala" "/home/cody/programming/scala/df-test/src/test/java")
       :target "/home/cody/programming/scala/df-test/target/scala-2.11/classes"
       :test-targets ("/home/cody/programming/scala/df-test/target/scala-2.11/test-classes")
       :depends-on-modules nil
       :compile-deps ("/home/cody/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.0.jar")
       :runtime-deps nil
       :test-deps nil
       :doc-jars ("/home/cody/.ivy2/cache/org.scala-lang/scala-library/docs/scala-library-2.11.0-javadoc.jar" "/home/cody/programming/scala/df-test/target/scala-2.11/df-test_2.11-0.1-SNAPSHOT-javadoc.jar")
       :reference-source-roots ("/home/cody/.ivy2/cache/org.scala-lang/scala-library/srcs/scala-library-2.11.0-sources.jar")))
 
)

full *inferior-ensime-server-df-test*:

    Starting ENSIME server: /usr/lib/jvm/java-8-openjdk-amd64/bin/java -classpath /usr/lib/jvm/java-8-openjdk-amd64/lib/tools.jar:/home/cody/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.0.jar:/home/cody/.ivy2/cache/org.ensime/ensime_2.11/jars/ensime_2.11-0.9.10-SNAPSHOT.jar:/home/cody/.ivy2/cache/org.ensime/server_2.11/jars/server_2.11-0.9.10-SNAPSHOT.jar:/home/cody/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.0.jar:/home/cody/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.0.jar:/home/cody/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.1.jar:/home/cody/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.1.jar:/home/cody/.ivy2/cache/org.ensime/api_2.11/jars/api_2.11-0.9.10-SNAPSHOT.jar:/home/cody/.ivy2/cache/com.github.stacycurl/pimpathon-core_2.11/jars/pimpathon-core_2.11-1.4.0.jar:/home/cody/.ivy2/cache/com.danieltrinh/scalariform_2.11/jars/scalariform_2.11-0.1.5.jar:/home/cody/.ivy2/cache/org.ensime/swank_2.11/jars/swank_2.11-0.9.10-SNAPSHOT.jar:/home/cody/.ivy2/cache/org.ensime/sexpress_2.11/jars/sexpress_2.11-0.9.10-SNAPSHOT.jar:/home/cody/.ivy2/cache/com.chuusai/shapeless_2.11/bundles/shapeless_2.11-2.0.0.jar:/home/cody/.ivy2/cache/org.parboiled/parboiled-scala_2.11/jars/parboiled-scala_2.11-1.1.7.jar:/home/cody/.ivy2/cache/org.parboiled/parboiled-core/jars/parboiled-core-1.1.7.jar:/home/cody/.ivy2/cache/com.typesafe.akka/akka-slf4j_2.11/jars/akka-slf4j_2.11-2.3.9.jar:/home/cody/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/jars/akka-actor_2.11-2.3.9.jar:/home/cody/.ivy2/cache/com.typesafe/config/bundles/config-1.2.1.jar:/home/cody/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.3.jar:/home/cody/.ivy2/cache/ch.qos.logback/logback-core/jars/logback-core-1.1.3.jar:/home/cody/.ivy2/cache/org.slf4j/jul-to-slf4j/jars/jul-to-slf4j-1.7.12.jar:/home/cody/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.12.jar:/home/cody/.ivy2/cache/org.slf4j/jcl-over-slf4j/jars/jcl-over-slf4j-1.7.12.jar:/home/cody/.ivy2/cache/com.h2database/h2/jars/h2-1.4.182.jar:/home/cody/.ivy2/cache/com.typesafe.slick/slick_2.11/bundles/slick_2.11-2.1.0.jar:/home/cody/.ivy2/cache/com.jolbox/bonecp/bundles/bonecp-0.8.0.RELEASE.jar:/home/cody/.ivy2/cache/com.google.guava/guava/bundles/guava-15.0.jar:/home/cody/.ivy2/cache/org.apache.commons/commons-vfs2/jars/commons-vfs2-2.0.jar:/home/cody/.ivy2/cache/commons-logging/commons-logging/jars/commons-logging-1.1.1.jar:/home/cody/.ivy2/cache/org.apache.maven.scm/maven-scm-api/jars/maven-scm-api-1.4.jar:/home/cody/.ivy2/cache/org.codehaus.plexus/plexus-utils/jars/plexus-utils-1.5.6.jar:/home/cody/.ivy2/cache/org.apache.maven.scm/maven-scm-provider-svnexe/jars/maven-scm-provider-svnexe-1.4.jar:/home/cody/.ivy2/cache/org.apache.maven.scm/maven-scm-provider-svn-commons/jars/maven-scm-provider-svn-commons-1.4.jar:/home/cody/.ivy2/cache/regexp/regexp/jars/regexp-1.3.jar:/home/cody/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-4.7.2.jar:/home/cody/.ivy2/cache/org.apache.lucene/lucene-analyzers-common/jars/lucene-analyzers-common-4.7.2.jar:/home/cody/.ivy2/cache/org.ow2.asm/asm-commons/jars/asm-commons-5.0.3.jar:/home/cody/.ivy2/cache/org.ow2.asm/asm-tree/jars/asm-tree-5.0.3.jar:/home/cody/.ivy2/cache/org.ow2.asm/asm/jars/asm-5.0.3.jar:/home/cody/.ivy2/cache/org.ow2.asm/asm-util/jars/asm-util-5.0.3.jar:/home/cody/.ivy2/cache/org.scala-lang/scalap/jars/scalap-2.11.6.jar:/home/cody/.ivy2/cache/org.scala-refactoring/org.scala-refactoring.library_2.11/jars/org.scala-refactoring.library_2.11-0.6.2.jar:/home/cody/.ivy2/cache/commons-lang/commons-lang/jars/commons-lang-2.6.jar:/home/cody/.ivy2/cache/io.spray/spray-can_2.11/bundles/spray-can_2.11-1.3.3.jar:/home/cody/.ivy2/cache/io.spray/spray-io_2.11/bundles/spray-io_2.11-1.3.3.jar:/home/cody/.ivy2/cache/io.spray/spray-util_2.11/bundles/spray-util_2.11-1.3.3.jar:/home/cody/.ivy2/cache/io.spray/spray-http_2.11/bundles/spray-http_2.11-1.3.3.jar -Xms1024m -Xmx1024m -XX:ReservedCodeCacheSize=128m -Densime.config=/home/cody/programming/scala/df-test/.ensime org.ensime.server.Server
    17:48:53.984 [main] ERROR org.ensime.server.Server - There was a problem parsing /home/cody/programming/scala/df-test/.ensime
    java.lang.NoClassDefFoundError: shapeless/DefaultSymbolicLabelling
    	at org.ensime.server.Server$.main(Server.scala:41) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
    	at org.ensime.server.Server.main(Server.scala) [server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
    Caused by: java.lang.ClassNotFoundException: shapeless.DefaultSymbolicLabelling
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[na:1.8.0_01-internal]
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.8.0_01-internal]
    	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_01-internal]
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[na:1.8.0_01-internal]
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_01-internal]
    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.8.0_01-internal]
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_01-internal]
    	... 2 common frames omitted
    Exception in thread "main" java.lang.NoClassDefFoundError: shapeless/DefaultSymbolicLabelling
    	at org.ensime.server.Server$.main(Server.scala:41)
    	at org.ensime.server.Server.main(Server.scala)
    Caused by: java.lang.ClassNotFoundException: shapeless.DefaultSymbolicLabelling
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    	... 2 more
    
    Process *inferior-ensime-server-df-test* exited abnormally with code 1

**Comment by codygman** [comment]
I somehow fixed this by basically deleting .sbt and .ivy.

**Comment by fommil** [comment]
That's item 1 in the contributing guidelines :-P
