### ISSUE TITLE
Package object members not imported correctly

### ISSUE THREAD

**Issue by greenrd** [ensime/ensime-server#959]
When I do `C-c C-r t` and select a completion that is inside a package object, it gets imported as

    import com.example.foo.package.Bar

instead of

    import com.example.foo.Bar

**Comment by fommil** [comment]
damn, I thought that was fixed recently in #832 

Which version of scala is your project using?

**Comment by greenrd** [comment]
> Which version of scala is your project using?

2.11.6

**Comment by fommil** [comment]
ok, definitely a regression then, or a corner case. Any chance you could set up a failing test case?

**Comment by DanielJoyce** [comment]
This bug has existed FOREVER in scala ide. Never worked right.
