### ISSUE TITLE
Add versioning to .ensime files

### ISSUE THREAD

**Issue by jschlather** [ensime/ensime-server#965]
I recently generated a new .ensime file for a project after upgrading the scala version. I spent a hour or two troubleshooting an issue where I was getting malformed swank call errors on the init-project call. I finally realized it might be because my emacs ensime version wasn't as up to date as what I used to generate the plugin file.

I think it would be helpful if we added a version parameter to the .ensime files so that if the current version of ensime needs a later .ensime file or if the version of ensime currently running needs a newer .ensime file, the message to update and what to update could be displayed transparently to the user.

**Comment by fommil** [comment]
being pragmatic about this, it might be better just to send people to the schema when it fails, and then they can work out from the commit message which fields have changed. It's an incredible amount of work to add this sort of versioning support (the server already does validation, btw, and will feed back exactly what is missing).

Given that all users are going to be reasonably well acquainted with S-Expressions and definitely acquainted with Scala, this would seem a reasonable approach. https://github.com/ensime/ensime-server/blob/master/api/src/main/scala/org/ensime/config/EnsimeConfig.scala

Would you like to submit a patch to add this message on error?

**Comment by fommil** [comment]
"I finally realized it might be because my emacs ensime version wasn't as up to date as what I used to generate the plugin file."

This confuses me, how did you generate your ensime config?

**Comment by jschlather** [comment]
I generated my ensime config using the ensime-sbt plugin. But I hadn't updated my emacs ensime plugin in several months.

I think your approach is reasonable. I'll look at changing the error message when I get a chance.

**Comment by fommil** [comment]
I think we only need `:scala-version` and `:java-home` from the `.ensime` file so that's all you need to look for on the client side (we might even have appropriate errors for this).

It actually sounds like your client and server got out of sync with each other. I thought we were completely backwards compatible on that, but we do check the protocol version.

I'm not entirely sure if this is a `.ensime` file config issue. What was the server side error you seen?

**Comment by jschlather** [comment]
I got a malformed swank exception on init-project and the contents of the exception was my .ensime config. I didn't see any issues in formatting manually examining it.

**Comment by fommil** [comment]
Wow, your ensime plugin must have been ancient! We've not done it that way in several months.

**Comment by fommil** [comment]
Try playing around by breaking your config file and see what the errors look like now. You might not need to do anything anymore to better understand errors in the config file.

**Comment by jschlather** [comment]
It probably hadn't been updated since January. The config errors are sort of hit or miss. Removing name gives a very informative error that name is missing, removing scala-version gives an error about byte code but does say to check your config file, if the config file is mis-formatted then there's a deserialization exception.

It seems like my case was likely very rare, so I'm okay closing this.

**Comment by fommil** [comment]
Scala version and java home are read by the emacs side. They could do with useful messages. Everything else will be checked server side.
