### ISSUE TITLE
Symbol's function definition is void: ensime-db-list-locals

### ISSUE THREAD

**Issue by Schwarzschild** [ensime/ensime-server#967]
I have emacs/ensime set up pretty well though I have one problem.  I get the following error when examining local variables in the ensime debugger.

   Symbol's function definition is void: ensime-db-list-locals

I use C-c C-d b to set a break point; then C-c C-d r to run up to the break point.  Finally, I try C-c C-d l to list local vars and get that error.

  Emacs version 24.3.1 
  OS: Ubuntu 14
  ENSIME-ReferenceServer version "0.8.3"
  Scala 2.11.4
  java version "1.8.0_45"

Please advise.

Thank you.

**Comment by rorygraves** [comment]
Hi Marc,  The ensime-debugger is a bit under loved - can you show the contents of the inferior ensime buffer when you do this?  I suspect it is a bug.  I think the local variable handling is more complex due to the closure support (i.e. what we consider local may actually be in a higher stack frame.

If you look in the buffer you can see the call and response (and any errors) for you call.

Attacking the debugger is definately on my personal hit list, but right now its behind my ScalaDays talk and some performance analysis I have been putting off.

**Comment by Schwarzschild** [comment]
Thank you for the quick reply.  I wouldn't expect you to shuffle priorities for this although it is comforting to know that it is on your "personal hit list" and may get attention sooner than later.

The ensime-db-output looks fine.  Here is the tail snippit from the inferior-ensime-server buffer:

    ...
    [JDI: Event: BreakpointEvent@Hello$:34 in thread main]Writing: (:debug-event (:type output :body "Hello World"))
    [JDI: Event: BreakpointEvent@Hello$:34 in thread main]
    Writing: (:debug-event (:type output :body "Hello Marc"))
    Writing: (:debug-event (:type breakpoint :thread-id "1" :thread-name "main" :file "/home/ms/s/myproject/src/main/scala/Main.scala" :line 34))
    Writing: (:debug-event (:type breakpoint :thread-id "1" :thread-name "main" :file "/home/ms/s/myproject/src/main/scala/Main.scala" :line 34))
    ...

And this is a snippit from *Messages*

    ...
    Resolved breakpoint at: /home/ms/s/myproject/src/main/scala/Main.scala : 34
    Installing breakpoint at locations: Set(Hello$:34)
    Thread 'main' hit breakpoint at Main.scala : 34 [2 times]
    Symbol's function definition is void: ensime-db-list-locals
    ...

Is there an alternative emacs scala debugger to ensime-debugger?  Is there a way to use sbt/gdb without ensime?

Thank you,
Marc

**Comment by fommil** [comment]
I'm afraid that's not enough information. Can you please give a full reproduction, ideally in the form of a unit or integration test? A github repository with exact instructions for somebody to follow, like a script, is also good. http://ensime.org/getting_help/

We have very good documentation at http://ensime.org/contributing/ to help you get started hacking on ENSIME.
