### ISSUE TITLE
Custom REPL

### ISSUE THREAD

**Issue by rishihahs** [ensime/ensime-server#972]
Is there a good way we can specify a custom REPL?

For example, I want to use `spark-shell`, so I just redefined `ensime-inf-default-cmd-line`:

    (defcustom ensime-inf-default-cmd-line '("spark-shell")
        "Default command to launch the repl, used when not connected to an ENSIME server."
        :type 'string
        :group 'ensime-inf)

Is there a better way to do this? Maybe on a per project basis?

**Comment by fommil** [comment]
That  parameter should have been removed because it's not used anymore. 

What does the spark repl do?

**Comment by rishihahs** [comment]
It's a repl for [Apache Spark](https://spark.apache.org), which is built on top of the scala repl.

Also, the snippet I posted above works for me (it loads the spark repl instead). Since the parameter has been removed, will this "hack" stop working in the future?

**Comment by fommil** [comment]
@rishihahs I mean, what does the script do. Can you link us to the source?

You have an old version of ensime if this is working.

We could easily customise the main class that gets started by the REPL, or pass a parameter to it.

**Comment by rishihahs** [comment]
The source of `spark-shell` is [here](https://github.com/apache/spark/blob/master/bin/spark-shell), which essentially uses [this Scala class](https://github.com/apache/spark/blob/master/repl/scala-2.11/src/main/scala/org/apache/spark/repl/Main.scala) for the repl.

**Comment by fommil** [comment]
Ok, looks like we could customise the class to start, and you'd use org.apache.spark.repl.Main

Would you'd like to submit a PR for this? It should be relatively straightforward and all the work in this area is in a very recent commit.

**Comment by fommil** [comment]
Probably best to implement it as a function that takes the class name, that way you could write a little spark-repl interactive function. Drop the user variable.

**Comment by rishihahs** [comment]
I think what's happening is that I was running `M-x ensime-inf-switch` *before* launching ensime (`M-x ensime`), so it used `ensime-inf-default-cmd-line`. Like you said, this no longer works when launching ensime first.

Also, after running ensime, `M-x ensime-inf-switch` gives me a "Error: Could not find or load main class scala.tools.nsc.MainGenericRunner". When I print out `ensime-inf-get-repl-cmd-line`, it says the class path is "< homedir >/.sbt/boot/scala-2.10.4/lib/scala-library.jar". Shouldn't it be "< homedir >/.sbt/boot/scala-2.10.4/lib/*" instead (since what would include scala-compiler.jar, and scala-reflect.jar)?

I'd love to submit a PR for this; could you tell me which file to edit? I understand that instead of `scala.tools.nsc.MainGenericRunner`, I should pass a user-supplied class, and also a custom classpath.

**Comment by fommil** [comment]
You'll need to get the standard prompt working first. Sounds like there is a problem. Waxed sure you're using the latest version from MELPA. What OS?

**Comment by rishihahs** [comment]
OS X 10.9, and I have the latest version from MELPA.

**Comment by fommil** [comment]
then I'm flagging this as a bug, because it should work. @dangerousben any ideas on why this might fail under OS X? (also don't forget to claim your bounty)

**Comment by dangerousben** [comment]
ensime-inf-default-cmd-line *is* still used when there's no server connection.  I'm not sure that's easily avoidable because at that stage the ensime classpath file doesn't necessarily  exist (I suppose we could look for one and fall back to the scala binary as a last resort).

When there is a server connection, the classpath should include scala-compiler and scala-reflect at the start (with scala-library probably being the first dependency of your project).

@rishihahs could you post the contents of your ensime classpath file?  This is located at ~/.emacs.d/ensime/classpath_<scala version>_<ensime_version> on my machine but if it's different on OS X you can find it for evaluating (ensime--user-directory).

As for the alternative REPL (once we've fixed the above), you should just be able to modify ensime-inf-cmd-template (maybe even just changing the main class if the above class is already on your project classpath).

**Comment by fommil** [comment]
@dangerousben ok, that's confusing. I recommend that when there is no server, it asks for the `.ensime` file and then tries to find the classpath file... failing to launch with no fallback. That, or don't allow the behaviour if the ENSIME server isn't up and running. `sbt` can be used to launch a REPL if the user doesn't want to interact with the ensime server. I'm a big advocate of failing fast and KISS :smile:

Hopefully this customisation could fit well with the idea we knocked around of allowing the user to specify the subproject that they want to launch into.

**Comment by dangerousben** [comment]
Is the general philosophy that ensime-emacs doesn't really work without a server connection then?  I can see it being useful to be able to open a scala repl within emacs to mess around with without having to define a project.

**Comment by fommil** [comment]
yeah, general philosophy is that the server needs to be up and running. The REPL is a bit of a corner case, it's piggy-backing off the existence of the `.ensime` file. For this particular case I'd be happy if it worked without the server, but only if the `.ensime` and classpath files are present. I don't think we should be going to the extra effort of handling the case where the `.ensime` file is not present or there is no classpath file. Anyone wanting a REPL without running `ensime-update` can use `sbt-mode`.

**Comment by fommil** [comment]
Actually, I think in general the "repl mode" itself should probably be shared code that lives in `scala-mode2`. Then maybe `scala-mode2` could offer the option of a scala binary REPL, `sbt-mode` use it when the user types `console`, and ensime would start the REPL straight from the project's classpath.

**Comment by rishihahs** [comment]
@dangerousben The contents of my ensime classpath file are: [here](https://gist.github.com/rishihahs/4101390df7c99ede387f)

Like you said, modifying `ensime-inf-cmd-template` by adding to the classpath and changing the main class, indeed worked for me:

      (defcustom ensime-inf-cmd-template
        '(:java :java-flags "-classpath" (concat :classpath ":<path to spark jars>") "-Dscala.usejavacp=true" "org.apache.spark.repl.Main" "-Xnojline")
        "The command to launch the scala interpreter. Keywords will be replaced with data loaded from server."
        :type 'string
        :group 'ensime-inf)

The changes are: `(concat :classpath ":<path to spark jars>")` and `org.apache.spark.repl.Main`

**Comment by tninja** [comment]
This one might work with spark-shell: https://github.com/tninja/scala-tool-support
