### ISSUE TITLE
Provide virtual parenthesis instead of dedicated reduce/increase scope

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#973]
Unless I'm missing something, navigation of scala files is pretty well supported by scala-mode2 and emacs built in sexp navigation controls (M-C-n and their kin). Therefore we could remove this feature altogether and simplify or codebase.

**Comment by fommil** [comment]
This may be best implemented as an integration with https://github.com/Fuco1/smartparens/issues/470 because the blocks are often inferred by the compiler.

**Comment by fommil** [comment]
This is something that maybe @lihaoyi's scala language parser could help with... although I can't find it anymore https://groups.google.com/forum/#!searchin/scala-internals/parser/scala-internals/q-pJ4aMNgmo/N13L76DBHeoJ

**Comment by lihaoyi** [comment]
My scala language parser has been folded in the https://github.com/lihaoyi/fastparse repo.

I have no idea what scala-mode2 or sexp-navigation-controls are, but you could probably easily find the "size" of a code node by using `instrument` without needing to modify the parser.

**Comment by fommil** [comment]
@lihaoyi I'd be looking at finding the start and end of anything that is considered a code block. Does size contain the start?

**Comment by edani** [comment]
I've been thinking about this. At the moment I'm pretty happy with the emacs sexp navigation that relies on matching `{}` and `()`. For anything else I just move forward/back by words (`C-M-f`, `C-M-b`).

While this would be cool technically, I'm not sure if I would actually use real-scala-block navigation because the blocks wouldn't be visually explicit.  So I would agree with your original comment and just remove the reduce/increase scope feature  (or just leave it alone).  What's everyone else's opinion?

**Comment by fommil** [comment]
I think it depends on the style of the code being navigated. If there is lots of desugaring going on, basic parenthesis navigation is pretty useless.

**Comment by fommil** [comment]
btw @edani how do you setup sexp navigation? I use smartparens with this https://github.com/fommil/dotfiles/blob/master/.emacs.d/init.el#L414 but it always feels long-winded to have to go and remap each keybinding... I've often felt that the sexp navigation should be brackets by default.

**Comment by edani** [comment]
@fommil   I just use the default not-so-smart parens `C-M-u`, `C-M-d`, `C-M-f`, `C-M-b`  which, as far as I can tell, just scans for balanced `{[( )]}`.

**Comment by fommil** [comment]
heh, this might actually go very well with the AST GSoC idea.
