### ISSUE TITLE
consider ditching shippable and using drone

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#974]
Shippable has growing pains that are not being addressed.

A FOSS alternative appears to have come out of the woodwork: https://github.com/drone/drone

We could host it, and use https://github.com/travis-ci/travis-build to generate the build scripts.

**Comment by fommil** [comment]
I'm bumping the priority of this because shippable is just getting ridiculous.

Initial tests of drone are showing it to be absolutely amazing, but our emacs tests are blocked on https://github.com/drone/drone/issues/1048 our coverage testing in blocked on #980 anyway but will benefit from https://github.com/drone/drone/issues/1045 and parallel builds are expected in v0.4 of drone (a week from release).

**Comment by markschaake** [comment]
@fommil We ([Allen Institute for Artificial Intelligence](https://github.com/allenai)) had terrible issues with Shippable and decided to transition to [SemaphoreCI](https://semaphoreci.com/). So far we love it. Reliable builds, faster builds, and a much better UI. I suggest you give them a look. don't have any affiliation with them, FYI.

**Comment by fommil** [comment]
@markschaake cool, thanks for the pointer. I'm really happy with drone after using it for a few days actually.

**Comment by fommil** [comment]
This seems to allow Emacs to work without a tty:

https://github.com/fommil/drone-tests/blob/master/.drone.yml
