### ISSUE TITLE
Support source jars that have sources in a subdirectory.

### ISSUE THREAD

**Issue by pschorf** [ensime/ensime-server#977]
It would be nice to support loading reference sources from files where the zip file is not directly laid out like com/mycompany/Class.java, but instead has some prefix like src/com/mycompany/Class.java. The jar:// url supports adding a path after the filename, which we use for our intellij project file generator.

I'd be happy to work on adding support for this, but wanted to run it by you before I started on it.

**Comment by edani** [comment]
Yes it would :-) Actually we have #761 open to support this.   I think the bulk of the work would be in finding all the places in the emacs code that assume that the current buffer is a real file, and fix them.

**Comment by fommil** [comment]
that would indeed be fantastic. One of my bugbears! The expansion of the source files actually slows things down, can eventually lead to large cache directories, and stops emacs from being able to browse a jar in archive mode.

Erik is correct about finding all the usages on the client side, the best thing to do from a protocol perspective is to look at my latest PR and inside the `outgoing.scala` / `common.scala` files, looking for parameters in the messages called either `file` or typed `File`. Then you'd want to come up with a new container type, like

```scala
case class EnsimeFile(path: String)
```

preferably using Apache VFS notation for the files.

On the client side, you'd need to support raw `File` paths as well for backwards compatibility with the 2.9 and 2.10 branches, but I think that should be fairly trivial... just have a wrapper that appends the `file://` prefix.

Let's move it to the #761 so as to avoid dupes. Ask away!

**Comment by fommil** [comment]
actually maybe we could be smart with the container type:

```
sealed trait SourceFileRef 
case class FileRef(file: File) extends SourceFileRef
case class JarEntryRef(jar: File, entry: String) extends SourceFileRef
```

etc

**Comment by fommil** [comment]
I'd be happy to do the painful `SwankProtocolConversion` piece if you can get it working internally.

**Comment by pschorf** [comment]
Does it make sense to keep this as a separate issue? It seems like you could implement this while still unpacking files, as long as you gave the client the correct path in the unpacked jar.

**Comment by fommil** [comment]
Nah, unpacking was always a workaround because we weren't sure how to handle the archive references on the client side.

**Comment by fommil** [comment]
I misunderstood this, reopening and renaming.

**Comment by fommil** [comment]
(classic case of proposed solution clouding the problem statement)

**Comment by pschorf** [comment]
I'll see what I can do about working around it internally tomorrow, but I
think this is still worth keeping open since other tools support it.

If I can't get a workaround, I'll start on a PR :)

**Comment by fommil** [comment]
our philosophy is to fix problems at their core, instead of working around. If it is not possible to fix at the core, then document heavily why you've written something crazy that complicates things here, and even then, only do it if it actually impacts somebody (not an imaginary weird scenario).

**Comment by pschorf** [comment]
I got some traction on making a change internally, so I'll close this out. Thanks for the help!

**Comment by fommil** [comment]
:smile: best way to fix it
