### ISSUE TITLE
Emacs hangs on completion

### ISSUE THREAD

**Issue by sellout** [ensime/ensime-server#982]
I’m not sure what’s going on here. I don’t see any output in the `*inferior-ensime-…*` buffer or elsewhere, but when I start to type an identifier lately (currently using version 20150607.437 from Melpa, but have seen it before I upgraded to that, too), Emacs just hangs indefinitely. It seems like it’s maybe doing completion, but I have to lean on C-g (like, for tens of seconds) for it to slowly output each letter of the identifier I typed and then finally give me back control of Emacs.

**Comment by rorygraves** [comment]
Hi @sellout  - Thats a really odd behaviour.  Whats the last thing in the inferior buffer? (trying to determine which side the error is on).  I think you can also turn on debug stack traces so you can see what it is you are interrupting with C-g.  Thanks

**Comment by fommil** [comment]
I'm almost certain this is a symptom of #970

Does it tend to happen after your build tool compiled some stuff?

Reopen if it doesn't sound like the regression the you.

**Comment by sellout** [comment]
Yeah, I’ll try to add more to this as I narrow it down. The last line of the inferior buffer is 
```
00:12:03.942 [default-akka.actor.default-dispatcher-452] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:full-typecheck-finished)
```
but that is a few minutes before I encountered the problem, and the message is not always the same.

I have debug-on-error enabled globally, but there is no `*Backtrace*` buffer.

Also, this problem usually doesn’t exhibit right off the bat. I get normal completion (company) for some period before it stops responding.

**Comment by sellout** [comment]
@fommil – You’re probably right. I mean, there’s a lot of saving files, running sbt commands, etc. so I’m sure some stuff was compiled. I’ll keep an eye on that issue. Thanks.

**Comment by fommil** [comment]
This one is killing me too, see it get fixed in the coming weeks. I've been distracted preparing for the talk at scala days.

It's horrible, but as a workaround you can kill the inferior buffer and start ensime again when your build tool has stabilised. I do that a lot.
