### ISSUE TITLE
organising the Teams

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#989]
@sviridov and @marcsaegesser sorry I was rearranging the teamings because we seem to be getting a more complex ecosystem following a successful scaladays. I removed you guys from the old "Developer" team (which no longer exists) but when I added you back in again you weren't added but were sent an invite instead. Sorry about that, let me know if you'd like the write privileges back (although I really wish it was merge permissions, not write permissions, because none of us should be pushing directly to the repo).

**Comment by sviridov** [comment]
@fommil Not a problem. I don't need any `ensime` related privileges while `undercover.el` works fine for you.
