### ISSUE TITLE
Support for Jerk over HTTP

### ISSUE THREAD

**Issue by propensive** [ensime/ensime-server#990]
Having the JSON API available as a REST service over HTTP would practically minimize any barriers to writing external tools which talk to Ensime, without learning anything new or proprietary.

**Comment by fommil** [comment]
this'll be easy to do for the sync messages as part of the websockets API but all the async messages will go to dev null (such as the semantic highlighting and notes).

**Comment by propensive** [comment]
Great. I guess there will need to be some sort of configuration for which port the HTTP server runs on (and whether it runs at all)...

**Comment by fommil** [comment]
@propensive nope, it self assigns. Currently a `portfile` (might be just `port`) appears in the cache dir when the server is running. There will be a similar `websockets` file with the port number.

**Comment by propensive** [comment]
Oh, that works even better.

**Comment by aemoncannon** [comment]
may be useful to know that we already spin up one http server for serving
docs.
not suggesting we re-use that one, but might be a model to follow

**Comment by propensive** [comment]
Is there any reason *not* to reuse the doc server?

**Comment by fommil** [comment]
I'm planning on reusing it yes. Just needs a little refactor.

**Comment by edani** [comment]
So would the long-term plan be to swich to json/websockets in the emacs client as well? It would be good to not have to worry about two protocols.

**Comment by rorygraves** [comment]
@fommil  were chatting about this a while ago - if we can use the same generators to produce them from a single definition (effectively the case classes) it is less important to retire one.  The plus side of keeping s-expression messages is that emacs is good at handling them.

**Comment by rorygraves** [comment]
So open question - but less stressful than actively maintaining two full protocol stacks.

**Comment by aemoncannon** [comment]
My 2 cents: switching to json in emacs would be a bad idea. The emacs side
of the protocol (which we inherited from slime) is designed to spend as
much time in native code as possible (see 'read' function). We've never had
to stress about client-side parsing speed and I suspect this is why.

**Comment by fommil** [comment]
I think a long term goal could be moving to S-Expressions over websockets in Emacs. It's a 2 phase thing: 1. Use natural form (ie shapeless magic) for s-expressions over current sockets, then swap to websockets and find and Emacs lib that does it well.

**Comment by fommil** [comment]
I guess we could do it the other way round.
