### ISSUE TITLE
load all files in module

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#993]
We can either have "load all in project" or "load just the open files".

When working on projects with a broken build, it would be useful to be able to "load all files in this module" as an alternative workflow.

**Comment by fommil** [comment]
This would involve creating a new API endpoint for the feature (taking in the name of a module), handled by the Analyser, which would then load all the source files in the current module. Perhaps also the inverse (unload all files from a module).

**Comment by ChrisCoffey** [comment]
This is good to close now that #1413 has landed.

**Comment by fommil** [comment]
oh, yeah. The PR needs the comment "closes #xxx" before github can do it automatically.
