### ISSUE TITLE
Errors hovering on some imports…

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#997]
_From @hedefalk on June 16, 2015 9:7_

```
10:45:38.121 [Thread-10] INFO  o.e.s.protocol.swank.SwankProtocol - Received msg: (:swank-rpc (swank:type-at-point "/Users/viktor/dev/projects/ensime-server/server/src/it/scala/org/ensime/fixture/EnsimeConfigFixture.scala" 46) 60)
10:45:38.122 [ENSIME-akka.actor.default-dispatcher-12] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:return (:ok nil) 60)
```

error in callback: TypeError: Cannot read property ':arrow-type' of null

I get just (:ok nil) on java.util.File

_Copied from original issue: ensime/ensime-atom#18_

**Comment by fommil** [comment]
this is all sounding very odd --- it works in emacs. Can you maybe post your server log to gist?

Is this all after receiving the "typecheck ready" message, etc.

**Comment by fommil** [comment]
oh, this is a bug! Well spotted.

Looks like `type-at-point` doesn't work over import statements.

**Comment by hedefalk** [comment]
@fommil you're on fire!
